#ifndef POKEHEARTGOLD_BATTLE_SYSTEM_H
#define POKEHEARTGOLD_BATTLE_SYSTEM_H

#include "battle/battle.h"
#include "battle/battle_setup.h"

#include "bag.h"
#include "pokemon.h"
#include "text.h"

BgConfig *BattleSystem_GetBgConfig(BattleSystem *battleSystem);
Window *BattleSystem_GetWindow(BattleSystem *battleSystem, int index);
u32 BattleSystem_GetBattleType(BattleSystem *battleSystem);
BattleContext *BattleSystem_GetBattleContext(BattleSystem *battleSystem);
OpponentData *BattleSystem_GetOpponentData(BattleSystem *battleSystem, int battlerId);
int BattleSystem_GetMaxBattlers(BattleSystem *battleSystem);
Party *BattleSystem_GetParty(BattleSystem *battleSystem, int battlerId);
int BattleSystem_GetPartySize(BattleSystem *battleSystem, int battlerId);
Pokemon *BattleSystem_GetPartyMon(BattleSystem *battleSystem, int battlerId, int index);
u32 *ov12_0223A8D4(BattleSystem *battleSystem);
u32 *ov12_0223A8DC(BattleSystem *battleSystem);
SpriteSystem *BattleSystem_GetSpriteSystem(BattleSystem *battleSystem);
SpriteManager *BattleSystem_GetSpriteManager(BattleSystem *battleSystem);
UnkBattleSystemSub17C *ov12_0223A8F4(BattleSystem *battleSystem, int index);
BattleInput *BattleSystem_GetBattleInput(BattleSystem *battleSystem);
u32 *ov12_0223A908(BattleSystem *battleSystem, int index);
void ov12_0223A914(BattleSystem *battleSystem, int index, u32 *a2);
BattleNumberPrinter *BattleSystem_GetHpNumPrinter(BattleSystem *battleSystem);
BattleNumberPrinter *BattleSystem_GetLevelNumPrinter(BattleSystem *battleSystem);
MsgData *BattleSystem_GetMessageLoader(BattleSystem *battleSystem);
u32 *ov12_0223A934(BattleSystem *battleSystem);
PaletteData *BattleSystem_GetPaletteData(BattleSystem *battleSystem);
Pokedex *BattleSystem_GetPokedex(BattleSystem *battleSystem);
u8 *BattleSystem_GetSendBufferPtr(BattleSystem *battleSystem);
u8 *BattleSystem_GetRecvBufferPtr(BattleSystem *battleSystem);
u16 *ov12_0223A954(BattleSystem *battleSystem);
u16 *ov12_0223A960(BattleSystem *battleSystem);
u16 *ov12_0223A96C(BattleSystem *battleSystem);
u16 *ov12_0223A978(BattleSystem *battleSystem);
u16 *ov12_0223A984(BattleSystem *battleSystem);
u16 *ov12_0223A990(BattleSystem *battleSystem);
UnkBattleSystemSub1D0 *ov12_0223A99C(BattleSystem *battleSystem);
MessageFormat *BattleSystem_GetMessageFormat(BattleSystem *battleSystem);
String *BattleSystem_GetMessageBuffer(BattleSystem *battleSystem);
u16 BattleSystem_GetTrainerIndex(BattleSystem *battleSystem, int battlerId);
Trainer *BattleSystem_GetTrainer(BattleSystem *battleSystem, int battlerId);
PlayerProfile *BattleSystem_GetPlayerProfile(BattleSystem *battleSystem, int a1);
Bag *BattleSystem_GetBag(BattleSystem *battleSystem);
BagCursor *BattleSystem_GetBagCursor(BattleSystem *battleSystem);
u16 BattleSystem_GetMonBall(BattleSystem *battleSystem, Pokemon *mon);
u32 ov12_0223AAB8(BattleSystem *battleSystem);
u32 BattleSystem_GetTrainerGender(BattleSystem *battleSystem, int battlerId);
int BattleSystem_GetBattlerFromBattlerType(BattleSystem *battleSystem, int a1);
u8 ov12_0223AB0C(BattleSystem *battleSystem, int battlerId);
u8 BattleSystem_GetFieldSide(BattleSystem *battleSystem, int battlerId);
void *BattleSystem_GetMessageIcon(BattleSystem *battleSystem);
PCStorage *BattleSystem_GetPcStorage(BattleSystem *battleSystem);
Terrain BattleSystem_GetTerrainId(BattleSystem *battleSystem);
int BattleSystem_GetBackgroundId(BattleSystem *battleSystem);
int BattleSystem_GetLocation(BattleSystem *battleSystem);
int BattleSystem_GetBattlerIdPartner(BattleSystem *battleSystem, int battlerId);
int ov12_0223ABB8(BattleSystem *battleSystem, int battlerId, int side);
BOOL BattleSystem_RecoverStatus(BattleSystem *battleSystem, int battlerId, int selectedMonIndex, int movePos, int item);
u32 BattleSystem_GetBattleSpecial(BattleSystem *battleSystem);
int BattleSystem_GetTimezone(BattleSystem *battleSystem);
int ov12_0223B52C(BattleSystem *battleSystem);
u8 ov12_0223B580(BattleSystem *battleSystem, int battlerId, u8 a2);
u16 BattleSystem_CheckEvolution(BattleSetup *setup, int *selectedMonIndex, int *evolutionCondition);
u8 ov12_0223B688(BattleSystem *battleSystem);
u8 ov12_0223B694(BattleSystem *battleSystem);
int BattleSystem_GetSafariBallCount(BattleSystem *battleSystem);
void BattleSystem_SetSafariBallCount(BattleSystem *battleSystem, int item);
Options *BattleSystem_GetOptions(BattleSystem *battleSystem);
BOOL BattleSystem_AreBattleAnimationsOn(BattleSystem *battleSystem);
u32 BattleSystem_GetFrame(BattleSystem *battleSystem);
u8 BattleSystem_GetTextFrameDelay(BattleSystem *battleSystem);
u32 BattleSystem_GetBattleStyle(BattleSystem *battleSystem);
void *ov12_0223B750(BattleSystem *battleSystem);
SOUND_CHATOT *BattleSystem_GetChatotVoice(BattleSystem *battleSystem, int battlerId);
void BattleSystem_TryChangeForm(BattleSystem *battleSystem);
void ov12_0223B854(BattleSystem *battleSystem, int battlerId, int selectedMonIndex);
void ov12_0223B870();
void BattleSystem_SetBackground(BattleSystem *battleSystem);
u8 *ov12_0223BAD0(BattleSystem *battleSystem);
u16 *ov12_0223BAD8(BattleSystem *battleSystem);
u16 *ov12_0223BAE0(BattleSystem *battleSystem);
u16 *ov12_0223BAEC(BattleSystem *battleSystem);
int BattleSystem_GetWeather(BattleSystem *battleSystem);
u8 ov12_0223BB04(BattleSystem *battleSystem);
void ov12_0223BB10(BattleSystem *battleSystem, u8 a1);
int ov12_0223BB1C(BattleSystem *battleSystem);
void BattleSystem_GameStatIncrement(BattleSystem *battleSystem, int id);
void ov12_0223BB44(BattleSystem *battleSystem);
void ov12_0223BB64(BattleSystem *battleSystem, int a1);
void ov12_0223BB6C(BattleSystem *battleSystem, u8 a1);
void *ov12_0223BB78(BattleSystem *battleSystem);
void ov12_0223BB80(BattleSystem *battleSystem, void *a1);
UnkBattleSystemSub1D0 *ov12_0223BB88(BattleSystem *battleSystem, int index);
u8 *ov12_0223BB94(UnkBattleSystemSub1D0 *ptr, int index);
void ov12_0223BBA8(UnkBattleSystemSub1D0 *ptr, int index, int a2);
void ov12_0223BBC0(UnkBattleSystemSub1D0 *ptr, int index, int a2);
void ov12_0223BBD8(UnkBattleSystemSub1D0 *ptr, int index, int a2);
void ov12_0223BBF0(BattleSystem *battleSystem, u8 a1);
void ov12_0223BBFC(BattleSystem *battleSystem, u8 *a1);
void ov12_0223BC08(BattleSystem *battleSystem, u8 *a1);
void ov12_0223BC14(BattleSystem *battleSystem, u8 a1);
void ov12_0223BC20(BattleSystem *battleSystem, u8 a1);
void ov12_0223BC2C(BattleSystem *battleSystem, u8 a1);
BattleHpBar *BattleSystem_GetHpBar(BattleSystem *battleSystem, int battlerId);
void BattleSystem_HpBar_Init(BattleSystem *battleSystem);
void BattleSystem_SetHpBarEnabled(BattleSystem *battleSystem);
void BattleSystem_SetHpBarDisabled(BattleSystem *battleSystem);
void BattleSystem_HpBar_Delete(BattleSystem *battleSystem);
u8 BattleSystem_GetBattleOutcomeFlags(BattleSystem *battleSystem);
void BattleSystem_SetBattleOutcomeFlags(BattleSystem *battleSystem, u8 battleOutcomeFlag);
u8 BattleSystem_GetCriticalHpMusicFlag(BattleSystem *battleSystem);
void BattleSystem_SetCriticalHpMusicFlag(BattleSystem *battleSystem, u8 flag);
u8 BattleSystem_GetCriticalHpMusicDelay(BattleSystem *battleSystem);
void BattleSystem_SetCriticalHpMusicDelay(BattleSystem *battleSystem, u8 delay);
void ov12_0223BD8C(BattleSystem *battleSystem, int a1);
u16 BattleSystem_Random(BattleSystem *battleSystem);
u32 BattleSystem_GetRandTemp(BattleSystem *battleSystem);
void BattleSystem_SetRandTemp(BattleSystem *battleSystem, u32 temp);
void ov12_0223BDDC(BattleSystem *battleSystem, int battlerId, u8 data);
BOOL ov12_0223BE0C(BattleSystem *battleSystem, int battlerId, u8 *data);
u8 ov12_0223BE68(BattleSystem *battleSystem, u8 *buffer);
void ov12_0223BF14(BattleSystem *battleSystem, u16 size, u8 *buffer);
u16 ov12_0223BFC0(BattleSystem *battleSystem);
int ov12_0223BFCC(BattleSystem *battleSystem, u16 battlerId);
u16 BattleSystem_GetTrainerItem(BattleSystem *battleSystem, int battlerId, int index);
BOOL BattleSystem_IsRecordingPaused(BattleSystem *battleSystem);
void ov12_0223BFFC(BattleSystem *battleSystem, u32 flag);
BOOL ov12_0223C080(BattleSystem *battleSystem);
void ov12_0223C0C4(BattleSystem *battleSystem);
u8 BattleSystem_GetChatotVoiceParam(BattleSystem *battleSystem, int battlerId);
Pokemon *BattleSystem_GetBugContestCaughtMon(BattleSystem *battleSystem);
u8 ov12_0223C140(BattleSystem *battleSystem, u32 battlerId);
void ov12_0223C1A0(BattleSystem *battleSystem, u8 *buffer);
void ov12_0223C1C4(BattleSystem *battleSystem, u8 *buffer);
void ov12_0223C1F4(BattleSystem *battleSystem, void **a1);
void ov12_0223C224(BattleSystem *battleSystem, int a1);
u32 CalcMoneyLoss(Party *party, PlayerProfile *profile);
void BattleSystem_SetPokedexSeen(BattleSystem *battleSystem, int battlerId);
void BattleSystem_SetPokedexCaught(BattleSystem *battleSystem, int battlerId);
BOOL BattleSystem_CheckMonCaught(BattleSystem *battleSystem, int battlerId);
void BattleSystem_SetDefaultBlend(void);
u8 BattleSystem_PrintTrainerMessage(BattleSystem *battleSystem, int trainerId, int battlerId, int a2, int delay);
u32 BattleSystem_PrintBattleMessage(BattleSystem *battleSystem, MsgData *data, BattleMessage *msg, u8 delay);
u32 ov12_0223C4E8(BattleSystem *battleSystem, Window *window, MsgData *data, BattleMessage *msg, int x, int y, int flag, int width, int delay);

#endif
