
#TODO: Make this not hard coded, possibly when the species enums get seperated from the c code
subdir('arceus')
subdir('burmy')
subdir('castform')
subdir('cherrim')
subdir('deoxys')
subdir('egg')
subdir('gastrodon')
subdir('giratina')
subdir('pichu')
subdir('rotom')
subdir('shaymin')
subdir('shellos')
subdir('substitute')
subdir('unown')
subdir('wormadam')

otherpoke_index_ncgr += {
    '259' : files('shadow.png'),
}

otherpoke_index_nclr += {
    '260' : files('shadow.png'),
}
