bag_graphics_ncgr = copy_gen.process(files(
    'bag_graphics_00002.NCGR',
    'bag_graphics_00006.NCGR',
    'bag_graphics_00007.NCGR',
    'bag_graphics_00010.NCGR',
    'bag_graphics_00014.NCGR',
    'bag_graphics_00016.NCGR',
    'bag_graphics_00020.NCGR',
    'bag_graphics_00023.NCGR',
    'bag_graphics_00026.NCGR',
    'bag_graphics_00029.NCGR',
    'bag_graphics_00033.NCGR',
    'bag_graphics_00036.NCGR',
    'bag_graphics_00037.NCGR',
    'bag_graphics_00046.NCGR',
    'bag_graphics_00051.NCGR',
))
bag_graphics_nclr = copy_gen.process(files(
    'bag_graphics_00003.NCLR',
    'bag_graphics_00008.NCLR',
    'bag_graphics_00011.NCLR',
    'bag_graphics_00013.NCLR',
    'bag_graphics_00015.NCLR',
    'bag_graphics_00017.NCLR',
    'bag_graphics_00030.NCLR',
    'bag_graphics_00034.NCLR',
    'bag_graphics_00038.NCLR',
    'bag_graphics_00040.NCLR',
    'bag_graphics_00041.NCLR',
    'bag_graphics_00047.NCLR',
    'bag_graphics_00048.NCLR',
))
bag_graphics_ncer = copy_gen.process(files(
    'bag_graphics_00001.NCER',
    'bag_graphics_00005.NCER',
    'bag_graphics_00019.NCER',
    'bag_graphics_00022.NCER',
    'bag_graphics_00025.NCER',
    'bag_graphics_00028.NCER',
    'bag_graphics_00032.NCER',
    'bag_graphics_00049.NCER',
))
bag_graphics_nanr = copy_gen.process(files(
    'bag_graphics_00000.NANR',
    'bag_graphics_00004.NANR',
    'bag_graphics_00018.NANR',
    'bag_graphics_00021.NANR',
    'bag_graphics_00024.NANR',
    'bag_graphics_00027.NANR',
    'bag_graphics_00031.NANR',
    'bag_graphics_00050.NANR',
))
bag_graphics_nscr = copy_gen.process(files(
    'bag_graphics_00009.NSCR',
    'bag_graphics_00012.NSCR',
    'bag_graphics_00035.NSCR',
    'bag_graphics_00039.NSCR',
    'bag_graphics_00042.NSCR',
    'bag_graphics_00043.NSCR',
    'bag_graphics_00044.NSCR',
    'bag_graphics_00045.NSCR',
    'bag_graphics_00052.NSCR',
    'bag_graphics_00053.NSCR',
    'bag_graphics_00054.NSCR',
    'bag_graphics_00093.NSCR',
    'bag_graphics_00094.NSCR',
))
bag_graphics_nsbmd = copy_gen.process(files(
    'bag_graphics_00055.NSBMD',
    'bag_graphics_00074.NSBMD',
))
bag_graphics_nsbca = copy_gen.process(files(
    'bag_graphics_00065.NSBCA',
    'bag_graphics_00066.NSBCA',
    'bag_graphics_00067.NSBCA',
    'bag_graphics_00068.NSBCA',
    'bag_graphics_00069.NSBCA',
    'bag_graphics_00070.NSBCA',
    'bag_graphics_00071.NSBCA',
    'bag_graphics_00072.NSBCA',
    'bag_graphics_00084.NSBCA',
    'bag_graphics_00085.NSBCA',
    'bag_graphics_00086.NSBCA',
    'bag_graphics_00087.NSBCA',
    'bag_graphics_00088.NSBCA',
    'bag_graphics_00089.NSBCA',
    'bag_graphics_00090.NSBCA',
    'bag_graphics_00091.NSBCA',
))
bag_graphics_nsbtp = copy_gen.process(files(
    'bag_graphics_00056.NSBTP',
    'bag_graphics_00057.NSBTP',
    'bag_graphics_00058.NSBTP',
    'bag_graphics_00059.NSBTP',
    'bag_graphics_00060.NSBTP',
    'bag_graphics_00061.NSBTP',
    'bag_graphics_00062.NSBTP',
    'bag_graphics_00063.NSBTP',
    'bag_graphics_00064.NSBTP',
    'bag_graphics_00075.NSBTP',
    'bag_graphics_00076.NSBTP',
    'bag_graphics_00077.NSBTP',
    'bag_graphics_00078.NSBTP',
    'bag_graphics_00079.NSBTP',
    'bag_graphics_00080.NSBTP',
    'bag_graphics_00081.NSBTP',
    'bag_graphics_00082.NSBTP',
    'bag_graphics_00083.NSBTP',
))
bag_graphics_nsbta = copy_gen.process(files(
    'bag_graphics_00073.NSBTA',
    'bag_graphics_00092.NSBTA',
))
