otherpoke_index_ncgr += {
    '0096' : files('normal/back.png'),
    '0097' : files('normal/front.png'),
    '0098' : files('fighting/back.png'),
    '0099' : files('fighting/front.png'),
    '0100' : files('flying/back.png'),
    '0101' : files('flying/front.png'),
    '0102' : files('poison/back.png'),
    '0103' : files('poison/front.png'),
    '0104' : files('ground/back.png'),
    '0105' : files('ground/front.png'),
    '0106' : files('rock/back.png'),
    '0107' : files('rock/front.png'),
    '0108' : files('bug/back.png'),
    '0109' : files('bug/front.png'),
    '0110' : files('ghost/back.png'),
    '0111' : files('ghost/front.png'),
    '0112' : files('steel/back.png'),
    '0113' : files('steel/front.png'),
    '0114' : files('mystery/back.png'),
    '0115' : files('mystery/front.png'),
    '0116' : files('fire/back.png'),
    '0117' : files('fire/front.png'),
    '0118' : files('water/back.png'),
    '0119' : files('water/front.png'),
    '0120' : files('grass/back.png'),
    '0121' : files('grass/front.png'),
    '0122' : files('electric/back.png'),
    '0123' : files('electric/front.png'),
    '0124' : files('psychic/back.png'),
    '0125' : files('psychic/front.png'),
    '0126' : files('ice/back.png'),
    '0127' : files('ice/front.png'),
    '0128' : files('dragon/back.png'),
    '0129' : files('dragon/front.png'),
    '0130' : files('dark/back.png'),
    '0131' : files('dark/front.png'),
}

otherpoke_index_nclr += {
    '194' : files('normal/front.png'),
    '195' : files('normal/back.png'),
    '196' : files('fighting/front.png'),
    '197' : files('fighting/back.png'),
    '198' : files('flying/front.png'),
    '199' : files('flying/back.png'),
    '200' : files('poison/front.png'),
    '201' : files('poison/back.png'),
    '202' : files('ground/front.png'),
    '203' : files('ground/back.png'),
    '204' : files('rock/front.png'),
    '205' : files('rock/back.png'),
    '206' : files('bug/front.png'),
    '207' : files('bug/back.png'),
    '208' : files('ghost/front.png'),
    '209' : files('ghost/back.png'),
    '210' : files('steel/front.png'),
    '211' : files('steel/back.png'),
    '212' : files('mystery/front.png'),
    '213' : files('mystery/back.png'),
    '214' : files('fire/front.png'),
    '215' : files('fire/back.png'),
    '216' : files('water/front.png'),
    '217' : files('water/back.png'),
    '218' : files('grass/front.png'),
    '219' : files('grass/back.png'),
    '220' : files('electric/front.png'),
    '221' : files('electric/back.png'),
    '222' : files('psychic/front.png'),
    '223' : files('psychic/back.png'),
    '224' : files('ice/front.png'),
    '225' : files('ice/back.png'),
    '226' : files('dragon/front.png'),
    '227' : files('dragon/back.png'),
    '228' : files('dark/front.png'),
    '229' : files('dark/back.png'),
}