otherpoke_index_ncgr += {
    '0000' : files('normal/back.png'),
    '0001' : files('normal/front.png'),
    '0002' : files('attack/back.png'),
    '0003' : files('attack/front.png'),
    '0004' : files('defense/back.png'),
    '0005' : files('defense/front.png'),
    '0006' : files('speed/back.png'),
    '0007' : files('speed/front.png'),
}

otherpoke_index_nclr += {
    '158' : files('normal/front.png'),
    '159' : files('normal/back.png'),
}