APPLICATION_RECORD_DIR  := files/application/record/record
APPLICATION_RECORD_NARC := $(APPLICATION_RECORD_DIR).narc

# APPLICATION_RECORD_PAL  := $(wildcard $(APPLICATION_RECORD_DIR)/*.pal)
# APPLICATION_RECORD_NCLR := $(APPLICATION_RECORD_PAL:%.pal=%.NCLR)
APPLICATION_RECORD_NCLR := $(wildcard $(APPLICATION_RECORD_DIR)/*.NCLR)
APPLICATION_RECORD_BIN  := $(wildcard $(APPLICATION_RECORD_DIR)/*.bin)

# APPLICATION_RECORD_NCLR_FLAGS := -bitdepth 8 -nopad -comp 10
# $(APPLICATION_RECORD_DIR)/record_00000011.NCLR: APPLICATION_RECORD_NCLR_FLAGS = -bitdepth 4

# $(APPLICATION_RECORD_NCLR): %.NCLR: %.pal
# 	$(GFX) $< $@ $(APPLICATION_RECORD_NCLR_FLAGS)

$(APPLICATION_RECORD_NARC): $(APPLICATION_RECORD_BIN) $(APPLICATION_RECORD_NCLR)
	$(KNARC) -p $@ -d $(APPLICATION_RECORD_DIR) -i

FS_CLEAN_TARGETS += $(APPLICATION_RECORD_NARC)
