# Collect ROM inputs and SHA-sums
icon_png_hg = files('icon.png')

rom_header_template_hg = files('rom_header_template.sbin')

main_sha1_hg = files('main.sha1')
filesystem_sha1_hg = files('filesystem.sha1')
rom_sha1_hg = files('rom.sha1')

rom_ini_hg = files('rom.ini')
filesys_csv_hg = files('filesystem.csv')
