[header]
template   = ${HEADER_TEMPLATE}
title      = POKEMON HG
serial     = IPKE
maker      = 01
secure-crc = 0xA0FF

[rom]
# Do *NOT* change the following line!
storage-type = PROM
fill-tail    = true
fill-with    = 0xFF

[banner]
version   = 1
icon      = ${ICON_PNG}
title     = Pokémon HeartGold
developer = Nintendo

[arm9]
static-binary = main.sbin_LZ
definitions   = main_defs.sbin_LZ
overlay-table = main_table.sbin_LZ

[arm7]
nef = ${ARM7_NEF}
