otherpoke_index_ncgr += {
    '0072' : files('plant/back.png'),
    '0073' : files('plant/front.png'),
    '0074' : files('sandy/back.png'),
    '0075' : files('sandy/front.png'),
    '0076' : files('trash/back.png'),
    '0077' : files('trash/front.png'),
}

otherpoke_index_nclr += {
    '170' : files('plant/front.png'),
    '171' : files('plant/back.png'),
    '172' : files('sandy/front.png'),
    '173' : files('sandy/back.png'),
    '174' : files('trash/front.png'),
    '175' : files('trash/back.png'),
}