otherpoke_index_ncgr += {
    '0008' : files('a/back.png'),
    '0009' : files('a/front.png'),
    '0010' : files('b/back.png'),
    '0011' : files('b/front.png'),
    '0012' : files('c/back.png'),
    '0013' : files('c/front.png'),
    '0014' : files('d/back.png'),
    '0015' : files('d/front.png'),
    '0016' : files('e/back.png'),
    '0017' : files('e/front.png'),
    '0018' : files('f/back.png'),
    '0019' : files('f/front.png'),
    '0020' : files('g/back.png'),
    '0021' : files('g/front.png'),
    '0022' : files('h/back.png'),
    '0023' : files('h/front.png'),
    '0024' : files('i/back.png'),
    '0025' : files('i/front.png'),
    '0026' : files('j/back.png'),
    '0027' : files('j/front.png'),
    '0028' : files('k/back.png'),
    '0029' : files('k/front.png'),
    '0030' : files('l/back.png'),
    '0031' : files('l/front.png'),
    '0032' : files('m/back.png'),
    '0033' : files('m/front.png'),
    '0034' : files('n/back.png'),
    '0035' : files('n/front.png'),
    '0036' : files('o/back.png'),
    '0037' : files('o/front.png'),
    '0038' : files('p/back.png'),
    '0039' : files('p/front.png'),
    '0040' : files('q/back.png'),
    '0041' : files('q/front.png'),
    '0042' : files('r/back.png'),
    '0043' : files('r/front.png'),
    '0044' : files('s/back.png'),
    '0045' : files('s/front.png'),
    '0046' : files('t/back.png'),
    '0047' : files('t/front.png'),
    '0048' : files('u/back.png'),
    '0049' : files('u/front.png'),
    '0050' : files('v/back.png'),
    '0051' : files('v/front.png'),
    '0052' : files('w/back.png'),
    '0053' : files('w/front.png'),
    '0054' : files('x/back.png'),
    '0055' : files('x/front.png'),
    '0056' : files('y/back.png'),
    '0057' : files('y/front.png'),
    '0058' : files('z/back.png'),
    '0059' : files('z/front.png'),
    '0060' : files('exclamation_mark/back.png'),
    '0061' : files('exclamation_mark/front.png'),
    '0062' : files('question_mark/back.png'),
    '0063' : files('question_mark/front.png'),
}

otherpoke_index_nclr += {
    '160' : files('a/front.png'),
    '161' : files('a/back.png'),
}