############################################################
### Linker spec file for Pokemon HeartGold/SoulSilver US ###
###      Pass this to the SDK's makelcf.exe utility      ###
###           along with the ARM9-TS template.           ###
###                        WIP                           ###
############################################################

Static main
{
    Address 0x02000000
    StackSize 0 2048
    Library libdwcaccount.a (.version)
    Library libsoc.a (.version)
	Library libcps.a (.version)
	Library libssl.a (.version)
    Library libvct.a (.version)
    Library libcard.a (.version)
    Library libdwcppwlobby.a (.version)
    Object main.nef.p/src_pm_version.c.o
    Object main.nef.p/src_main.c.o
    Object main.nef.p/src_list_menu.c.o
    Object main.nef.p/src_list_menu_2d.c.o
    Object main.nef.p/src_string_util.c.o
    Object main.nef.p/src_render_text.c.o
    Object main.nef.p/src_font.c.o
    Object main.nef.p/src_palette.c.o
    Object main.nef.p/src_sound.c.o
    Object main.nef.p/src_sound_radio_sys.c.o
    Object main.nef.p/asm_unk_02004A44.s.o
    Object main.nef.p/asm_unk_02005D10.s.o
    Object main.nef.p/src_sound_chatot.c.o
    Object main.nef.p/src_poke_overlay.c.o
    Object main.nef.p/src_systask_environment.c.o
    Object main.nef.p/src_overlay_manager.c.o
    Object main.nef.p/src_filesystem.c.o
    Object main.nef.p/src_gf_gfx_loader.c.o
    Object main.nef.p/src_pokepic.c.o
    Object main.nef.p/src_unk_02009D48.c.o
    Object main.nef.p/src_unk_0200A090.c.o
    Object main.nef.p/src_unk_0200ACF0.c.o
    Object main.nef.p/asm_unk_0200B150.s.o
    Object main.nef.p/src_brightness.c.o
    Object main.nef.p/src_msgdata.c.o
    Object main.nef.p/src_message_format.c.o
    Object main.nef.p/src_message_printer.c.o
    Object main.nef.p/src_unk_0200CE7C.c.o
    Object main.nef.p/src_sprite_system.c.o
    Object main.nef.p/src_sys_task_api.c.o
    Object main.nef.p/asm_render_window.s.o
    Object main.nef.p/asm_unk_0200FA24.s.o
    Object main.nef.p/asm_unk_0201010C.s.o
    Object main.nef.p/asm_unk_02012DD8.s.o
    Object main.nef.p/asm_unk_02013534.s.o
    Object main.nef.p/src_unk_02013FDC.c.o
    Object main.nef.p/src_gf_rtc.c.o
    Object main.nef.p/src_list_menu_items.c.o
    Object main.nef.p/asm_unk_02014A08.s.o
    Object main.nef.p/asm_unk_02014DA0.s.o
    Object main.nef.p/src_mail_message.c.o
    Object main.nef.p/src_easy_chat.c.o
    Object main.nef.p/asm_unk_02015DD8.s.o
    Object main.nef.p/asm_unk_020163E0.s.o
    Object main.nef.p/src_yes_no_prompt.c.o
    Object main.nef.p/asm_unk_02016EDC.s.o
    Object main.nef.p/asm_unk_02017FAC.s.o
    Object main.nef.p/asm_unk_02018000.s.o
    Object main.nef.p/src_unk_02018380.c.o
    Object main.nef.p/src_menu_input_state.c.o
    Object main.nef.p/src_touchscreen_list_menu.c.o
    Object main.nef.p/src_camera_translation.c.o
    Object main.nef.p/asm_unk_020192D0.s.o
    Object main.nef.p/asm_unk_0201956C.s.o
    Object main.nef.p/src_unk_02019BA4.c.o
    Object main.nef.p/src_system.c.o
    Object main.nef.p/src_heap.c.o
    Object main.nef.p/src_bg_window.c.o
    Object main.nef.p/src_gf_3d_render.c.o
    Object main.nef.p/src_sys_task.c.o
    Object main.nef.p/asm_unk_0201F990.s.o
    Object main.nef.p/src_string_control_code.c.o
    Object main.nef.p/src_math_util.c.o
    Object main.nef.p/src_text.c.o
    Object main.nef.p/src_vram_transfer_manager.c.o
    Object main.nef.p/asm_unk_0202068C.s.o
    Object main.nef.p/src_unk_02020A0C.c.o
    Object main.nef.p/src_ascii_util.c.o
    Object main.nef.p/asm_unk_02020B8C.s.o
    Object main.nef.p/asm_unk_020210A0.s.o
    Object main.nef.p/src_obj_char_transfer.c.o
    Object main.nef.p/src_obj_pltt_transfer.c.o
    Object main.nef.p/src_gf_gfx_planes.c.o
    Object main.nef.p/src_camera.c.o
    Object main.nef.p/asm_unk_02023694.s.o
    Object main.nef.p/src_sprite.c.o
    Object main.nef.p/src_touchscreen.c.o
    Object main.nef.p/src_timer3.c.o
    Object main.nef.p/src_error_handling.c.o
    Object main.nef.p/src_unk_02025534.c.o
    Object main.nef.p/asm_unk_02025C44.s.o
    Object main.nef.p/src_font_data.c.o
    Object main.nef.p/src_pm_string.c.o
    Object main.nef.p/src_touch_hitbox_controller.c.o
    Object main.nef.p/asm_unk_02026DE0.s.o
    Object main.nef.p/src_unk_02026E30.c.o
    Object main.nef.p/src_unk_02026E84.c.o
    Object main.nef.p/src_gf_3d_vramman.c.o
    Object main.nef.p/asm_unk_02027010.s.o
    Object main.nef.p/src_save_arrays.c.o
    Object main.nef.p/src_save.c.o
    Object main.nef.p/src_sav_system_info.c.o
    Object main.nef.p/src_player_data.c.o
    Object main.nef.p/src_save_link_ruleset.c.o
    Object main.nef.p/src_link_ruleset_data.c.o
    Object main.nef.p/src_daycare.c.o
    Object main.nef.p/src_pokedex.c.o
    Object main.nef.p/src_save_misc.c.o
    Object main.nef.p/src_options.c.o
    Object main.nef.p/src_apricorn_tree_sys.c.o
    Object main.nef.p/src_save_gymmick.c.o
    Object main.nef.p/src_save_palpad.c.o
    Object main.nef.p/src_mail.c.o
    Object main.nef.p/asm_unk_0202B614.s.o
    Object main.nef.p/asm_unk_0202C034.s.o
    Object main.nef.p/asm_unk_0202C730.s.o
    Object main.nef.p/src_coins.c.o
    Object main.nef.p/src_save_trainer_card.c.o
    Object main.nef.p/src_save_wifi_history.c.o
    Object main.nef.p/src_seal_case.c.o
    Object main.nef.p/src_igt.c.o
    Object main.nef.p/src_sav_chatot.c.o
    Object main.nef.p/src_game_stats.c.o
    Object main.nef.p/asm_unk_0202D230.s.o
    Object main.nef.p/src_save_special_ribbons.c.o
    Object main.nef.p/src_roamer.c.o
    Object main.nef.p/asm_unk_0202DB34.s.o
    Object main.nef.p/src_mystery_gift.c.o
    Object main.nef.p/src_hall_of_fame.c.o
    Object main.nef.p/asm_unk_0202E41C.s.o
    Object main.nef.p/src_save_rankings.c.o
    Object main.nef.p/src_palPark_migration.c.o
    Object main.nef.p/src_update_dex_received.c.o
    Object main.nef.p/src_save_follow_mon.c.o
    Object main.nef.p/src_save_pokegear.c.o
    Object main.nef.p/src_unk_0202F370.c.o
    Object main.nef.p/src_safari_zone.c.o
    Object main.nef.p/src_photo_album.c.o
    Object main.nef.p/asm_unk_0202FBCC.s.o
    Object main.nef.p/asm_unk_02030A98.s.o
    Object main.nef.p/src_unk_0203170C.c.o
    Object main.nef.p/asm_unk_020318C8.s.o
    Object main.nef.p/asm_unk_02031904.s.o
    Object main.nef.p/src_unk_02031AF0.c.o
    Object main.nef.p/asm_unk_02031B0C.s.o
    Object main.nef.p/src_pokewalker.c.o
    Object main.nef.p/src_save_trainer_house.c.o
    Object main.nef.p/asm_unk_02032844.s.o
    Object main.nef.p/asm_unk_02033AE0.s.o
    Object main.nef.p/asm_unk_02034354.s.o
    Object main.nef.p/asm_unk_02034B0C.s.o
    Object main.nef.p/asm_unk_02035900.s.o
    Object main.nef.p/asm_unk_020379A0.s.o
    Object main.nef.p/asm_unk_02037C94.s.o
    Object main.nef.p/asm_unk_0203A3B0.s.o
    Object main.nef.p/src_communication_error.c.o
    Object main.nef.p/src_unk_0203AC88.c.o
    Object main.nef.p/src_wfc_user_info_warning.c.o
    Object main.nef.p/src_map_matrix.c.o
    Object main.nef.p/src_map_header.c.o
    Object main.nef.p/src_map_events.c.o
    Object main.nef.p/src_save_local_field_data.c.o
    Object main.nef.p/asm_unk_0203BA5C.s.o
    Object main.nef.p/src_field_system_rtc_weather.c.o
    Object main.nef.p/src_start_menu.c.o
    Object main.nef.p/asm_unk_0203DB6C.s.o
    Object main.nef.p/src_field_system.c.o
    Object main.nef.p/src_location_backup.c.o
    Object main.nef.p/src_launch_application.c.o
    Object main.nef.p/src_script.c.o
    Object main.nef.p/src_fieldmap.c.o
    Object main.nef.p/src_scrcmd_c.c.o
    Object main.nef.p/src_scrcmd_mart.c.o
    Object main.nef.p/src_scrcmd_strbuf.c.o
    Object main.nef.p/src_scrcmd_lottery.c.o
    Object main.nef.p/src_scrcmd_sound.c.o
    Object main.nef.p/src_scrcmd_battle.c.o
    Object main.nef.p/src_scrcmd_8.c.o
    Object main.nef.p/src_scrcmd_9.c.o
    Object main.nef.p/src_unk_0204A3F4.c.o
    Object main.nef.p/src_unk_0204B538.c.o
    Object main.nef.p/src_scrcmd_apricorn.c.o
    Object main.nef.p/src_scrcmd_mystery_gift.c.o
    Object main.nef.p/src_scrcmd_12.c.o
    Object main.nef.p/src_scrcmd_money.c.o
    Object main.nef.p/src_scrcmd_daycare.c.o
    Object main.nef.p/src_scrcmd_party.c.o
    Object main.nef.p/src_scrcmd_dppl_prizes.c.o
    Object main.nef.p/src_scrcmd_17.c.o
    Object main.nef.p/src_scrcmd_items.c.o
    Object main.nef.p/src_scrcmd_move_relearner.c.o
    Object main.nef.p/src_scrcmd_20.c.o
    Object main.nef.p/src_scrcmd_battle_castle.c.o
    Object main.nef.p/src_scrcmd_battle_arcade.c.o
    Object main.nef.p/src_save_vars_flags.c.o
    Object main.nef.p/src_task.c.o
    Object main.nef.p/src_encounter.c.o
    Object main.nef.p/asm_unk_020517A4.s.o
    Object main.nef.p/src_battle_battle_setup.c.o
    Object main.nef.p/src_blackout.c.o
    Object main.nef.p/src_game_clear.c.o
    Object main.nef.p/src_field_warp_tasks.c.o
    Object main.nef.p/src_script_pokemon_util.c.o
    Object main.nef.p/asm_unk_02054514.s.o
    Object main.nef.p/asm_unk_02054648.s.o
    Object main.nef.p/asm_unk_02054E00.s.o
    Object main.nef.p/asm_unk_020551B8.s.o
    Object main.nef.p/asm_unk_02055244.s.o
    Object main.nef.p/src_unk_02055418.c.o
    Object main.nef.p/src_catching_show.c.o
    Object main.nef.p/asm_unk_02055BF0_data.s.o
    Object main.nef.p/src_unk_02055BF0.c.o
    Object main.nef.p/asm_unk_02056680.s.o
    Object main.nef.p/asm_unk_02056D7C.s.o
    Object main.nef.p/asm_unk_02058034.s.o
    Object main.nef.p/asm_unk_02058AEC.s.o
    Object main.nef.p/asm_unk_0205A44C.s.o
    Object main.nef.p/asm_unk_0205AC88.s.o
    Object main.nef.p/src_unk_0205B3DC.c.o
    Object main.nef.p/asm_text_0205B4EC.s.o
    Object main.nef.p/src_metatile_behavior.c.o
    Object main.nef.p/asm_unk_0205BB1C.s.o
    Object main.nef.p/asm_unk_0205BFF0.s.o
    Object main.nef.p/src_player_avatar.c.o
    Object main.nef.p/asm_unk_0205CB48.s.o
    Object main.nef.p/src_map_object.c.o
    Object main.nef.p/asm_unk_data_020FCBD8.s.o
    Object main.nef.p/asm_unk_0205FD20.s.o
    Object main.nef.p/asm_unk_02061284.s.o
    Object main.nef.p/asm_unk_data_020FD978.s.o
    Object main.nef.p/asm_unk_02062108.s.o
    Object main.nef.p/asm_unk_data_020FDB44.s.o
    Object main.nef.p/asm_unk_020632B0.s.o
    Object main.nef.p/src_unk_020648EC.c.o
    Object main.nef.p/src_field_use_item.c.o
    Object main.nef.p/asm_unk_020658D4.s.o
    Object main.nef.p/src_sys_flags.c.o
    Object main.nef.p/src_sys_vars.c.o
    Object main.nef.p/asm_unk_02066EDC.s.o
    Object main.nef.p/src_field_roamer.c.o
    Object main.nef.p/asm_unk_0206793C.s.o
    Object main.nef.p/asm_unk_02067A60.s.o
    Object main.nef.p/src_field_move.c.o
    Object main.nef.p/src_field_move_environment.c.o
    Object main.nef.p/asm_unk_020689C8.s.o
    Object main.nef.p/src_gymmick_init.c.o
    Object main.nef.p/src_unk_02068F84.c.o
    Object main.nef.p/asm_unk_02068FC8.s.o
    Object main.nef.p/src_unk_02069528.c.o
    Object main.nef.p/asm_unk_02069660.s.o
    Object main.nef.p/asm_unk_0206979C.s.o
    Object main.nef.p/src_follow_mon.c.o
    Object main.nef.p/src_map_preview_graphic.c.o
    Object main.nef.p/src_field_take_photo.c.o
    Object main.nef.p/src_unk_0206B910.c.o
    Object main.nef.p/src_alph_checks.c.o
    Object main.nef.p/src_get_egg.c.o
    Object main.nef.p/src_unk_0206D494.c.o
    Object main.nef.p/src_pokemon.c.o
    Object main.nef.p/src_move.c.o
    Object main.nef.p/src_trainer_data.c.o
    Object main.nef.p/src_pokemon_storage_system.c.o
    Object main.nef.p/src_pokemon_icon_idx.c.o
    Object main.nef.p/src_party.c.o
    Object main.nef.p/src_pokedex_util.c.o
    Object main.nef.p/src_battle_regulation.c.o
    Object main.nef.p/asm_unk_02074E5C.s.o
    Object main.nef.p/asm_unk_020755E8.s.o
    Object main.nef.p/asm_unk_020773AC.s.o
    Object main.nef.p/asm_unk_02077678.s.o
    Object main.nef.p/src_bag_view.c.o
    Object main.nef.p/src_item.c.o
    Object main.nef.p/src_bag.c.o
    Object main.nef.p/asm_unk_02078834.s.o
    Object main.nef.p/asm_unk_02078DD8.s.o
    Object main.nef.p/src_party_menu.c.o
    Object main.nef.p/src_party_context_menu.c.o
    Object main.nef.p/src_party_menu_sprites.c.o
    Object main.nef.p/src_party_menu_list_items.c.o
    Object main.nef.p/src_party_menu_items.c.o
    Object main.nef.p/src_naming_screen.c.o
    Object main.nef.p/asm_unk_020850F4.s.o
    Object main.nef.p/asm_unk_02085604.s.o
    Object main.nef.p/asm_unk_020863F4.s.o
    Object main.nef.p/asm_unk_02087284.s.o
    Object main.nef.p/asm_unk_02087A78.s.o
    Object main.nef.p/asm_unk_02087E70.s.o
    Object main.nef.p/asm_unk_02087FD4.s.o
    Object main.nef.p/src_unk_0208805C.c.o
    Object main.nef.p/asm_unk_02088288.s.o
    Object main.nef.p/asm_unk_0208B1AC.s.o
    Object main.nef.p/asm_unk_0208C3E4.s.o
    Object main.nef.p/asm_unk_0208DE40.s.o
    Object main.nef.p/src_ribbon.c.o
    Object main.nef.p/src_trainer_memo.c.o
    Object main.nef.p/asm_unk_0208F658.s.o
    Object main.nef.p/asm_unk_0208F814.s.o
    Object main.nef.p/asm_unk_0208FB64.s.o
    Object main.nef.p/src_use_item_on_mon.c.o
    Object main.nef.p/src_mail_misc.c.o
    Object main.nef.p/src_unk_02091054.c.o
    Object main.nef.p/src_hatch_egg_task.c.o
    Object main.nef.p/src_unk_02091278.c.o
    Object main.nef.p/src_unk_020912AC.c.o
    Object main.nef.p/src_dex_mon_measures.c.o
    Object main.nef.p/src_unk_02091564.c.o
    Object main.nef.p/asm_unk_020915B0.s.o
    Object main.nef.p/src_location_gmm_dat.c.o
    Object main.nef.p/src_move_relearner.c.o
    Object main.nef.p/asm_unk_02091880.s.o
    Object main.nef.p/src_application_delete_savedata.c.o
    Object main.nef.p/src_application_check_savedata.c.o
    Object main.nef.p/src_save_data_read_error.c.o
    Object main.nef.p/src_save_data_write_error.c.o
    Object main.nef.p/asm_unk_02092B04.s.o
    Object main.nef.p/asm_unk_02092BB8.s.o
    Object main.nef.p/src_unk_02092BE8.c.o
    Object main.nef.p/src_mom_gift.c.o
    Object main.nef.p/src_unk_020932A4.c.o
    Object main.nef.p/asm_unk_020932E0.s.o
    Object main.nef.p/asm_unk_020957B0.s.o
    Object main.nef.p/asm_unk_02095DF4.s.o
    Object main.nef.p/src_phonebook_dat.c.o
    Object main.nef.p/src_choose_starter.c.o
    Object main.nef.p/asm_unk_020961D8.s.o
    Object main.nef.p/src_error_message_reset.c.o
    Object main.nef.p/src_sin_vcount.c.o
    Object main.nef.p/asm_frontier.s.o
	Object main.nef.p/src_unk_020968B0.c.o
    Object main.nef.p/asm_unk_02096910.s.o
    Object main.nef.p/asm_unk_02096C88.s.o
    Object main.nef.p/asm_unk_02097024.s.o
    Object main.nef.p/asm_unk_020971F8.s.o
    Object main.nef.p/asm_unk_02097268.s.o
    Object main.nef.p/src_unk_02097720.c.o
    Object main.nef.p/asm_unk_020977CC.s.o
    Object main.nef.p/asm_unk_020979A8.s.o
    Object main.nef.p/asm_unk_02097B78.s.o
    Object main.nef.p/asm_unk_02097BE0.s.o
    Object main.nef.p/src_unk_02097D3C.c.o
    Object main.nef.p/src_pokemon_mood.c.o
    Object main.nef.p/src_unk_02097F6C.c.o

    ### Vendor libraries ###
    Library libspl.a
    Library libwvr.a
    Library libdwcbm.a
    Library libdwcaccount.a
    Library libcrypto_static.a
    Library libsoc.a
    Library libcps.a
    Library libssl.a
    Library libwcm.a
    Library libstubsmd5.a
    Library libvct.a
    Library libnnsfnd.a
	Library libnnsgfd.a
	Library libnnsg2d.a
	Library libnnsg3d.a
	Library libnnssnd.a

    ### NitroSDK ###
    Library libfx.a
    Library libgx.a
    Library libos.a
    Library libmi.a
    Library libsnd.a
	Library libpxi.a
	Library libfs.a
	Library libdgt.a
	Library libcp.a
	Library libspi.a
	Library librtc.a
	Library libcard.a
    Library libirc.a #this one is weird
	Library libwm.a
	Library libctrdg.a
	Library libmath.a
	Library libstd.a
    Library MSL_C_NITRO_Ai_LE.a
	Library MSL_Extras_NITRO_Ai_LE.a
	Library MSL_CPP_NITRO_Ai_LE.a
	Library FP_fastI_v5t_LE.a
	Library NITRO_Runtime_Ai_LE.a
}

Autoload ITCM
{
    Address 0x01FF8000
    Library libos.a (.itcm)
    Library libmi.a (.itcm)
}

Autoload DTCM
{
    Address 0x027E0000
    Library libos.a (.dtcm.bss)
}
Overlay OVY_0
{
    After main
    Object main.nef.p/asm_overlay_00_thumb.s.o
    Library libdwcauth.a
    Library libdwcbase.a
    Library libdwcac.a
    Library libdwcgscommon.a
    Library libdwcgsgp.a
    Library libdwcgsgstats.a
    Library libdwcgsgt2.a
    Library libdwcgsnatneg.a
    Library libdwcgsqr2.a
    Library libdwcgsserverbrowsing.a
}
Overlay field
{
    After main
    Object main.nef.p/asm_overlay_01_021E5900.s.o
    Object main.nef.p/src_field_overlay_01_021E66E4.c.o
    Object main.nef.p/asm_overlay_01_021E6880.s.o
    Object main.nef.p/asm_overlay_01_021E7FDC.s.o
    Object main.nef.p/asm_overlay_01_021E8744.s.o
    Object main.nef.p/asm_overlay_01_021E90C0.s.o
    Object main.nef.p/asm_overlay_01_021EA6C4.s.o
    Object main.nef.p/src_overlay_01_021EA824.c.o
    Object main.nef.p/asm_overlay_01_021EA8E0.s.o
    Object main.nef.p/asm_overlay_01_021EABA8.s.o
    Object main.nef.p/asm_overlay_01_021EAF00.s.o
    Object main.nef.p/asm_overlay_01_021EAFD4.s.o
    Object main.nef.p/asm_overlay_01_021EB1E8.s.o
    Object main.nef.p/asm_overlay_01_021EDAFC.s.o
    Object main.nef.p/src_field_scrcmd_message.c.o
    Object main.nef.p/src_field_draw_map_name.c.o
    Object main.nef.p/asm_overlay_01_021EFB38.s.o
    Object main.nef.p/asm_overlay_01_021F1348.s.o
    Object main.nef.p/asm_overlay_01_021F1AFC.s.o
    Object main.nef.p/asm_overlay_01_021F3114.s.o
    Object main.nef.p/asm_overlay_01_021F3378.s.o
    Object main.nef.p/asm_overlay_01_021F3610.s.o
    Object main.nef.p/asm_overlay_01_021F3D38.s.o
    Object main.nef.p/asm_overlay_01_021F3F50.s.o
    Object main.nef.p/asm_overlay_01_021F4464.s.o
    Object main.nef.p/asm_overlay_01_021F467C.s.o
    Object main.nef.p/asm_overlay_01_021F4704.s.o
    Object main.nef.p/asm_overlay_01_021F6830.s.o
    Object main.nef.p/asm_overlay_01_021F6CFC.s.o
    Object main.nef.p/asm_overlay_01_sprite_data.s.o
    Object main.nef.p/asm_overlay_01_021F72DC.s.o
    Object main.nef.p/asm_overlay_01_021F8D80.s.o
    Object main.nef.p/asm_overlay_01_021F944C.s.o
    Object main.nef.p/asm_overlay_01_021FAC44.s.o
    Object main.nef.p/asm_overlay_01_021FAD1C.s.o
    Object main.nef.p/asm_overlay_01_021FB04C.s.o
    Object main.nef.p/asm_overlay_01_021FB368.s.o
    Object main.nef.p/asm_overlay_01_021FB4C0.s.o
    Object main.nef.p/asm_overlay_01_021FB5D4.s.o
    Object main.nef.p/asm_overlay_01_021FB878.s.o
    Object main.nef.p/asm_overlay_01_021FC05C.s.o
    Object main.nef.p/asm_overlay_01_021FC4C4.s.o
    Object main.nef.p/asm_overlay_01_data_02208BFC.s.o
    Object main.nef.p/asm_overlay_01_021FC66C.s.o
    Object main.nef.p/asm_overlay_01_021FCD2C.s.o
    Object main.nef.p/asm_overlay_01_021FCE98.s.o
    Object main.nef.p/asm_overlay_01_021FD1B8.s.o
    Object main.nef.p/asm_overlay_01_021FD41C.s.o
    Object main.nef.p/asm_overlay_01_021FDA14.s.o
    Object main.nef.p/asm_overlay_01_021FE200.s.o
    Object main.nef.p/asm_overlay_01_021FE590.s.o
    Object main.nef.p/asm_overlay_01_021FE780.s.o
    Object main.nef.p/asm_overlay_01_021FEA0C.s.o
    Object main.nef.p/asm_overlay_01_021FEC38.s.o
    Object main.nef.p/asm_overlay_01_021FED9C.s.o
    Object main.nef.p/asm_overlay_01_021FEEEC.s.o
    Object main.nef.p/asm_overlay_01_021FF464.s.o
    Object main.nef.p/asm_overlay_01_021FF6B0.s.o
    Object main.nef.p/asm_overlay_01_021FF854.s.o
    Object main.nef.p/asm_overlay_01_021FFC0C.s.o
    Object main.nef.p/src_field_overlay_01_021FFECC.c.o
    Object main.nef.p/asm_overlay_01_02200040.s.o
    Object main.nef.p/asm_overlay_01_022001E4.s.o
    Object main.nef.p/asm_overlay_01_022006A8.s.o
    Object main.nef.p/asm_overlay_01_02200858.s.o
    Object main.nef.p/src_field_scrcmd_pokemon_misc.c.o
    Object main.nef.p/src_scrcmd_move_tutor.c.o
    Object main.nef.p/src_field_scrcmd_moneybox.c.o
    Object main.nef.p/asm_overlay_01_022031C0.s.o
    Object main.nef.p/asm_overlay_01_02203A18.s.o
    Object main.nef.p/asm_overlay_01_02203E40.s.o
    Object main.nef.p/asm_overlay_01_02204004.s.o
    Object main.nef.p/src_field_overlay_01_apricorn_tree_anim.c.o
    Object main.nef.p/src_field_overlay_01_rock_smash_item.c.o
    Object main.nef.p/src_field_headbutt.c.o
    Object main.nef.p/asm_overlay_01_022051EC.s.o
    Object main.nef.p/asm_overlay_01_022053EC.s.o
}
Overlay OVY_2
{
    After field
    Object main.nef.p/asm_overlay_02_02245B80.s.o
    Object main.nef.p/src_field_legend_cutscene_camera.c.o
    Object main.nef.p/src_field_overlay_2_gear_phone.c.o
    Object main.nef.p/src_field_event_cutscene_shaymin.c.o
    Object main.nef.p/src_field_event_cutscene_celebi.c.o
    Object main.nef.p/src_field_event_cutscene_sinjoh.c.o
    Object main.nef.p/src_overlay_02_02251E74.c.o
}
Overlay OVY_3
{
    After OVY_2
    Object main.nef.p/asm_overlay_03.s.o
}
Overlay OVY_4
{
    After OVY_2
    Object main.nef.p/asm_overlay_04.s.o
}
Overlay OVY_5
{
    After OVY_0
    Object main.nef.p/asm_overlay_05.s.o
}
Overlay OVY_6
{
    After OVY_0
    Object main.nef.p/src_overlay_06.c.o
}
Overlay OVY_7
{
    After OVY_6
    Object main.nef.p/asm_overlay_07.s.o
}
Overlay OVY_8
{
    After OVY_6
    Object main.nef.p/asm_overlay_08.s.o
}
Overlay OVY_9
{
    After OVY_6
}
Overlay OVY_10
{
    After OVY_6
    Object main.nef.p/src_battle_trainer_ai.c.o
    Object main.nef.p/asm_overlay_10_trainer_ai.s.o
}
Overlay OVY_11
{
    After main
}
Overlay OVY_12
{
    After OVY_7
    Object main.nef.p/src_battle_battle_022378C0.c.o
    Object main.nef.p/asm_overlay_12_022378C0.s.o
    Object main.nef.p/src_battle_battle_system.c.o
    Object main.nef.p/src_battle_battle_command.c.o
    Object main.nef.p/asm_overlay_12_battle_command.s.o
    Object main.nef.p/src_battle_battle_controller_player.c.o
    Object main.nef.p/src_battle_overlay_12_0224E4FC.c.o
    Object main.nef.p/asm_overlay_12_battle_controller_opponent.s.o
    Object main.nef.p/src_battle_battle_02261FD4.c.o
    Object main.nef.p/asm_overlay_12_battle_controller.s.o
    Object main.nef.p/src_battle_battle_hp_bar.c.o
    Object main.nef.p/asm_overlay_12_02265E28.s.o
    Object main.nef.p/src_battle_battle_input.c.o
    Object main.nef.p/asm_overlay_12_0226ADE0.s.o
    Object main.nef.p/src_battle_battle_cursor.c.o
    Object main.nef.p/src_battle_battle_finger.c.o
    Object main.nef.p/src_battle_overlay_12_0226BEC4.c.o
}
Overlay OVY_13
{
    After OVY_0
    Object main.nef.p/asm_overlay_13_thumb_1.s.o
    Library libmb.a
    Object main.nef.p/asm_overlay_13_thumb_2.s.o
    Object main.nef.p/lib_NitroDWC_asm_overlay_13_arm_2.s.o
}
Overlay OVY_14
{
    After main
    Object main.nef.p/asm_overlay_14.s.o
}
Overlay OVY_15
{
    After OVY_14
    Object main.nef.p/asm_overlay_15.s.o
}
Overlay OVY_16
{
    After OVY_15
    Object main.nef.p/src_overlay_16_022014A0.c.o
    Object main.nef.p/src_overlay_16_02201948.c.o
}
Overlay OVY_17
{
    After OVY_16
    Object main.nef.p/src_berry_pots_app.c.o
    Object main.nef.p/src_berry_pots_app_tasks.c.o
}
Overlay OVY_18
{
    After main
    Object main.nef.p/src_poketool_pokefoot.c.o
    Object main.nef.p/src_application_pokedex_ov18_021E590C.c.o
    Object main.nef.p/src_application_pokedex_ov18_021E5AA0.c.o
    Object main.nef.p/src_application_pokedex_ov18_021E5C40.c.o
    Object main.nef.p/src_application_pokedex_ov18_021E8BF4.c.o
    Object main.nef.p/asm_overlay_18.s.o
}
Overlay OVY_19
{
    After OVY_3
    Object main.nef.p/src_application_view_photo.c.o
}
Overlay OVY_20
{
    After OVY_3
    Object main.nef.p/src_scrcmd_size_record.c.o
}
Overlay OVY_21
{
    After OVY_3
    Object main.nef.p/src_scrcmd_fossils.c.o
}
Overlay OVY_22
{
    After OVY_3
    Object main.nef.p/src_overlay_22.c.o
}
Overlay npc_trade
{
    After OVY_3
    Object main.nef.p/src_npc_trade.c.o
}
Overlay bug_contest
{
    After OVY_3
    Object main.nef.p/src_overlay_bug_contest.c.o
}
Overlay OVY_25
{
    After OVY_3
    Object main.nef.p/src_overlay_25.c.o
}
Overlay OVY_26
{
    After OVY_3
    Object main.nef.p/src_overlay_26_022598C0.c.o
    Object main.nef.p/src_overlay_26_022599D0.c.o
}
Overlay OVY_27
{
    After bug_contest
    Object main.nef.p/asm_overlay_27.s.o
}
Overlay OVY_28
{
    After OVY_27
    Object main.nef.p/asm_overlay_28.s.o
}
Overlay OVY_29
{
    After OVY_27
    Object main.nef.p/asm_overlay_29.s.o
}
Overlay touch_save_app
{
    After OVY_27
    Object main.nef.p/src_touch_save_app.c.o
}
Overlay OVY_31
{
    After OVY_27
    Object main.nef.p/asm_overlay_31.s.o
}
Overlay OVY_32
{
    After OVY_27
    Object main.nef.p/asm_overlay_32.s.o
}
Overlay OVY_33
{
    After OVY_27
    Object main.nef.p/asm_overlay_33.s.o
}
Overlay OVY_34
{
    After OVY_27
    Object main.nef.p/asm_overlay_34.s.o
}
Overlay OVY_35
{
    After npc_trade
    Object main.nef.p/asm_overlay_35.s.o
}
Overlay OVY_36
{
    After main
    Object main.nef.p/src_overlay_36.c.o
}
Overlay OVY_37
{
    After main
    Object main.nef.p/asm_overlay_37.s.o
}
Overlay OVY_38
{
    After OVY_0
    Object main.nef.p/asm_overlay_38_thumb.s.o
    Object main.nef.p/lib_NitroDWC_asm_overlay_38_arm.s.o
}
Overlay OVY_39
{
    After OVY_38
    Object main.nef.p/asm_overlay_39_thumb.s.o
    Object main.nef.p/lib_NitroDWC_asm_overlay_39_arm.s.o
}
Overlay OVY_40
{
    After OVY_39
    Object main.nef.p/asm_overlay_40.s.o
}
Overlay OVY_41
{
    After OVY_40
    Object main.nef.p/asm_overlay_41.s.o
}
Overlay OVY_42
{
    After OVY_38
    Object main.nef.p/asm_overlay_42.s.o
}
Overlay OVY_43
{
    After OVY_42
    Object main.nef.p/asm_overlay_43.s.o
}
Overlay OVY_44
{
    After OVY_42
    Object main.nef.p/asm_overlay_44.s.o
}
Overlay OVY_45
{
    After OVY_42
    Object main.nef.p/asm_overlay_45_thumb.s.o
    Library libdwcppwlobby.a
}
Overlay OVY_46
{
    After OVY_45
    Object main.nef.p/asm_overlay_46.s.o
}
Overlay OVY_47
{
    After OVY_45
    Object main.nef.p/asm_overlay_47.s.o
}
Overlay OVY_48
{
    After OVY_45
    Object main.nef.p/asm_overlay_48.s.o
}
Overlay OVY_49
{
    After OVY_45
    Object main.nef.p/asm_overlay_49.s.o
}
Overlay trainer_card
{
    After main
    Object main.nef.p/src_overlay_trainer_card.c.o
}
Overlay trainer_card_main
{
    After trainer_card
    Object main.nef.p/asm_overlay_trainer_card_main.s.o
}
Overlay trainer_card_signature
{
    After trainer_card_main
    Object main.nef.p/asm_overlay_trainer_card_signature.s.o
}
Overlay OVY_53
{
    After main
    Object main.nef.p/src_oaks_speech.c.o
    Object main.nef.p/src_oaks_speech_obj.c.o
    Object main.nef.p/src_oaks_speech_yesnomenu.c.o
}
Overlay options_app
{
    After main
    Object main.nef.p/src_options_app.c.o
}
Overlay OVY_55
{
    After main
    Object main.nef.p/src_overlay_55.c.o
}
Overlay OVY_56
{
    After OVY_55
    Object main.nef.p/asm_overlay_56.s.o
}
Overlay OVY_57
{
    After OVY_7
    Object main.nef.p/asm_overlay_57.s.o
}
Overlay OVY_58
{
    After OVY_7
    Object main.nef.p/asm_overlay_58.s.o
}
Overlay OVY_59
{
    After OVY_58
    Object main.nef.p/asm_overlay_59.s.o
}
Overlay intro_title
{
    After main
    Object main.nef.p/src_title_screen.c.o
    Object main.nef.p/src_intro_movie.c.o
    Object main.nef.p/src_intro_movie_scenes_lib.c.o
    Object main.nef.p/src_intro_movie_scene_1.c.o
    Object main.nef.p/src_intro_movie_scene_2.c.o
    Object main.nef.p/src_intro_movie_scene_3.c.o
    Object main.nef.p/src_intro_movie_scene_4.c.o
    Object main.nef.p/src_intro_movie_scene_5.c.o
}
Overlay OVY_61
{
    After main
    Object main.nef.p/src_choose_starter_app.c.o
}
Overlay OVY_62
{
    After main
    Object main.nef.p/src_overlay_mic_test.c.o
}
Overlay OVY_63
{
    After OVY_6
    Object main.nef.p/src_register_hall_of_fame.c.o
}
Overlay OVY_64
{
    After main
    Object main.nef.p/asm_overlay_64.s.o
}
Overlay OVY_65
{
    After OVY_6
    Object main.nef.p/asm_overlay_65.s.o
}
Overlay OVY_66
{
    After main
}
Overlay OVY_67
{
    After main
    Object main.nef.p/asm_overlay_67.s.o
}
Overlay OVY_68
{
    After main
    Object main.nef.p/asm_overlay_68.s.o
}
Overlay OVY_69
{
    After main
    Object main.nef.p/asm_overlay_69.s.o
}
Overlay OVY_70
{
    After OVY_7
    Object main.nef.p/asm_overlay_70.s.o
}
Overlay OVY_71
{
    After OVY_70
    Object main.nef.p/asm_overlay_71.s.o
}
Overlay OVY_72
{
    After OVY_7
    Object main.nef.p/asm_overlay_72.s.o
}
Overlay OVY_73
{
    After main
    Object main.nef.p/asm_overlay_73.s.o
}
Overlay OVY_74
{
    After OVY_38
    Object main.nef.p/src_application_main_menu_main_menu.c.o
    Object main.nef.p/asm_overlay_74_thumb.s.o
    Object main.nef.p/asm_nitrocrypto.s.o
}
Overlay OVY_75
{
    After OVY_70
    Object main.nef.p/asm_overlay_75.s.o
}
Overlay credits
{
    After main
    Object main.nef.p/src_credits_data1.c.o
    Object main.nef.p/src_credits_credits.c.o
    Object main.nef.p/src_credits_data2.c.o
}
Overlay OVY_77
{
    After main
}
Overlay certificates_app
{
    After main
    Object main.nef.p/src_certificates_app.c.o
}
Overlay OVY_79
{
    After OVY_42
}
Overlay OVY_80
{
    After OVY_42
    Object main.nef.p/asm_overlay_80_02229EE0.s.o
    Object main.nef.p/asm_frontier_system.s.o
    Object main.nef.p/src_frontier_frontier_script_context.c.o
    Object main.nef.p/asm_overlay_80_0222ACA0.s.o
    Object main.nef.p/asm_overlay_80_0222AEF8.s.o
    Object main.nef.p/asm_overlay_80_0222BDF4.s.o
    Object main.nef.p/asm_overlay_80_0222F608.s.o
    Object main.nef.p/asm_overlay_80_0222FD08.s.o
    Object main.nef.p/asm_overlay_80_02230B8C.s.o
    Object main.nef.p/asm_overlay_80_022310C4.s.o
    Object main.nef.p/asm_overlay_80_02231BF8.s.o
    Object main.nef.p/asm_overlay_80_022324C4.s.o
    Object main.nef.p/src_frontier_frontier_cmd_arcade.c.o
    Object main.nef.p/asm_overlay_80_022340E8.s.o
    Object main.nef.p/asm_overlay_80_02235390.s.o
    Object main.nef.p/asm_overlay_80_02235438.s.o
    Object main.nef.p/asm_overlay_80_022357B4.s.o
    Object main.nef.p/asm_overlay_80_02235900.s.o
    Object main.nef.p/asm_overlay_80_02235FC8.s.o
    Object main.nef.p/asm_overlay_80_02236450.s.o
    Object main.nef.p/asm_overlay_80_02236B78.s.o
    Object main.nef.p/asm_overlay_80_022372D8.s.o
    Object main.nef.p/asm_overlay_80_02237A70.s.o
    Object main.nef.p/asm_overlay_80_02238034.s.o
    Object main.nef.p/asm_overlay_80_022384D8.s.o
    Object main.nef.p/asm_frontier_map.s.o
    Object main.nef.p/asm_overlay_80_02239960.s.o
    Object main.nef.p/asm_overlay_80_02239AF8.s.o
    Object main.nef.p/asm_overlay_80_02239BF0.s.o
    Object main.nef.p/asm_overlay_80_02239D74.s.o
    Object main.nef.p/asm_overlay_80_0223A00C.s.o
    Object main.nef.p/asm_overlay_80_0223AC24.s.o
}
Overlay OVY_81
{
    After OVY_80
    Object main.nef.p/asm_overlay_81.s.o
}
Overlay OVY_82
{
    After OVY_80
    Object main.nef.p/asm_overlay_82.s.o
}
Overlay OVY_83
{
    After OVY_80
    Object main.nef.p/asm_overlay_83.s.o
}
Overlay OVY_84
{
    After OVY_80
    Object main.nef.p/src_battle_arcade_game_board.c.o
    Object main.nef.p/asm_battle_arcade_game_board_data.s.o
}
Overlay OVY_85
{
    After main
    Object main.nef.p/asm_overlay_85.s.o
}
Overlay OVY_86
{
    After main
    Object main.nef.p/asm_overlay_86.s.o
}
Overlay OVY_87
{
    After main
    Object main.nef.p/asm_overlay_87.s.o
}
Overlay OVY_88
{
    After OVY_45
    Object main.nef.p/asm_overlay_88.s.o
}
Overlay OVY_89
{
    After OVY_45
    Object main.nef.p/asm_overlay_89.s.o
}
Overlay OVY_90
{
    After OVY_45
    Object main.nef.p/asm_overlay_90.s.o
}
Overlay OVY_91
{
    After OVY_90
    Object main.nef.p/asm_overlay_91.s.o
}
Overlay OVY_92
{
    After OVY_90
    Object main.nef.p/asm_overlay_92.s.o
}
Overlay OVY_93
{
    After OVY_90
    Object main.nef.p/asm_overlay_93_thumb_1.s.o
    Object main.nef.p/asm_overlay_93_arm.s.o
    Object main.nef.p/asm_overlay_93_thumb_2.s.o
}
Overlay OVY_94
{
    After main
    Object main.nef.p/src_overlay_94.c.o
}
Overlay OVY_95
{
    After main
    Object main.nef.p/asm_overlay_95.s.o
}
Overlay OVY_96
{
    After main
    Object main.nef.p/src_pokeathlon_pokeathlon_course.c.o
    Object main.nef.p/asm_overlay_96.s.o
}
Overlay OVY_97
{
    After OVY_96
    Object main.nef.p/asm_overlay_97.s.o
}
Overlay OVY_98
{
    After OVY_96
    Object main.nef.p/asm_overlay_98.s.o
}
Overlay OVY_99
{
    After main
    Object main.nef.p/asm_overlay_99.s.o
}
Overlay pokegear
{
    After main
    Object main.nef.p/src_application_pokegear_main_overlay_100_021E5900.c.o
    Object main.nef.p/src_application_pokegear_main_pokegear_main.c.o
    Object main.nef.p/src_application_pokegear_main_overlay_100_021E6914.c.o
    Object main.nef.p/src_application_pokegear_main_pokegear_cursor.c.o
}
Overlay pokegear_app
{
    After pokegear
    Object main.nef.p/src_application_pokegear_map_pokegear_map.c.o
    Object main.nef.p/src_application_pokegear_map_overlay_101_021F79B4.c.o
    Object main.nef.p/src_application_pokegear_map_overlay_101_021E7FF4.c.o
    Object main.nef.p/src_application_pokegear_map_overlay_101_021E9270.c.o
    Object main.nef.p/src_application_pokegear_map_overlay_101_021EB568.c.o
    Object main.nef.p/src_application_pokegear_map_overlay_101_021ED498.c.o
    Object main.nef.p/src_application_pokegear_map_fly_map.c.o
    Object main.nef.p/src_application_pokegear_map_overlay_101_021EDCE0.c.o
    Object main.nef.p/src_application_pokegear_configure_pokegear_configure.c.o
    Object main.nef.p/src_application_pokegear_configure_overlay_101_021EED44.c.o
    Object main.nef.p/src_application_pokegear_configure_overlay_101_021EF1D8.c.o
    Object main.nef.p/src_application_pokegear_configure_overlay_101_021EF6D0.c.o
    Object main.nef.p/src_application_pokegear_phone_pokegear_phone.c.o
    Object main.nef.p/src_application_pokegear_phone_overlay_101_021EFD20.c.o
    Object main.nef.p/src_application_pokegear_phone_overlay_101_021F017C.c.o
    Object main.nef.p/src_application_pokegear_phone_overlay_101_021F0880.c.o
    Object main.nef.p/src_application_pokegear_phone_overlay_101_021F0F48.c.o
    Object main.nef.p/src_application_pokegear_phone_overlay_101_021F1D74.c.o
    Object main.nef.p/src_application_pokegear_phone_scripts_phone_scripts_mother.c.o
    Object main.nef.p/src_application_pokegear_phone_scripts_phone_scripts_prof_elm.c.o
    Object main.nef.p/src_application_pokegear_phone_scripts_phone_scripts_generic.c.o
    Object main.nef.p/src_application_pokegear_phone_scripts_phone_scripts_prof_oak.c.o
    Object main.nef.p/src_application_pokegear_phone_scripts_phone_scripts_kurt.c.o
    Object main.nef.p/src_application_pokegear_phone_scripts_phone_scripts_bike_shop.c.o
    Object main.nef.p/src_application_pokegear_phone_scripts_phone_scripts_blackbelt_kenji.c.o
    Object main.nef.p/src_application_pokegear_phone_scripts_phone_scripts_bill.c.o
    Object main.nef.p/src_application_pokegear_phone_scripts_phone_scripts_daycare_man.c.o
    Object main.nef.p/src_application_pokegear_phone_scripts_phone_scripts_daycare_lady.c.o
    Object main.nef.p/src_application_pokegear_phone_scripts_phone_scripts_buena.c.o
    Object main.nef.p/src_application_pokegear_phone_scripts_phone_scripts_childhood_friend.c.o
    Object main.nef.p/src_application_pokegear_phone_scripts_phone_scripts_gym_leader.c.o
    Object main.nef.p/src_application_pokegear_phone_scripts_phone_scripts_baoba.c.o
    Object main.nef.p/src_application_pokegear_phone_scripts_phone_scripts_juggler_irwin.c.o
    Object main.nef.p/src_application_pokegear_phone_extra_ethan_lyra_data.c.o
    Object main.nef.p/src_application_pokegear_radio_pokegear_radio.c.o
    Object main.nef.p/src_application_pokegear_radio_overlay_101_021F49F8.c.o
    Object main.nef.p/src_application_pokegear_radio_overlay_101_021F4F34.c.o
    Object main.nef.p/src_application_pokegear_radio_overlay_101_021F57B8.c.o
    Object main.nef.p/src_application_pokegear_radio_shows_pokemon_music.c.o
    Object main.nef.p/src_application_pokegear_radio_shows_poke_flute.c.o
    Object main.nef.p/src_application_pokegear_radio_shows_unown.c.o
    Object main.nef.p/src_application_pokegear_radio_shows_team_rocket.c.o
    Object main.nef.p/src_application_pokegear_radio_shows_serial_radio_drama.c.o
    Object main.nef.p/src_application_pokegear_radio_shows_commercials.c.o
    Object main.nef.p/src_application_pokegear_radio_shows_pokemon_search_party.c.o
    Object main.nef.p/src_application_pokegear_radio_shows_buenas_password.c.o
    Object main.nef.p/src_application_pokegear_radio_shows_that_town_these_people.c.o
    Object main.nef.p/src_application_pokegear_radio_shows_trainer_profiles.c.o
    Object main.nef.p/src_application_pokegear_radio_shows_pokemon_talk.c.o
    Object main.nef.p/src_application_pokegear_radio_shows_mahogany_signal.c.o
    Object main.nef.p/src_application_pokegear_phone_phone_script_defs.c.o
    Object main.nef.p/src_application_pokegear_phone_phone_generic_headers.c.o
}
Overlay OVY_102
{
    After pokegear
    Object main.nef.p/asm_overlay_102.s.o
}
Overlay OVY_103
{
    After OVY_102
    Object main.nef.p/asm_overlay_103.s.o
}
Overlay OVY_104
{
    After main
    Object main.nef.p/asm_overlay_104.s.o
}
Overlay OVY_105
{
    After main
    Object main.nef.p/asm_overlay_105.s.o
}
Overlay OVY_106
{
    After main
    Object main.nef.p/asm_overlay_106.s.o
}
Overlay OVY_107
{
    After main
}
Overlay OVY_108
{
    After main
    Object main.nef.p/asm_overlay_108.s.o
    Object main.nef.p/asm_overlay_108_021E8850.s.o
}
Overlay OVY_109
{
    After main
    Object main.nef.p/asm_overlay_109.s.o
}
Overlay OVY_110
{
    After main
    Object main.nef.p/src_alph_puzzle.c.o
}
Overlay OVY_111
{
    After main
    Object main.nef.p/asm_overlay_111.s.o
}
Overlay OVY_112
{
    After main
    Object main.nef.p/asm_overlay_112.s.o
}
Overlay OVY_113
{
    After main
    Object main.nef.p/asm_overlay_113.s.o
}
Overlay OVY_114
{
    After OVY_31
    Object main.nef.p/asm_overlay_114.s.o
}
Overlay OVY_115
{
    After OVY_31
    Object main.nef.p/asm_overlay_115.s.o
}
Overlay OVY_116
{
    After OVY_31
    Object main.nef.p/asm_overlay_116.s.o
}
Overlay OVY_117
{
    After OVY_31
    Object main.nef.p/asm_overlay_117.s.o
}
Overlay OVY_118
{
    After OVY_31
    Object main.nef.p/asm_overlay_118.s.o
}
Overlay OVY_119
{
    After OVY_31
    Object main.nef.p/asm_overlay_119.s.o
}
Overlay OVY_120
{
    After OVY_31
    Object main.nef.p/asm_overlay_120.s.o
}
Overlay view_rankings_app
{
    After main
    Object main.nef.p/src_application_view_rankings.c.o
}
Overlay voltorb_flip
{
    After main
    Object main.nef.p/src_voltorb_flip_voltorb_flip.c.o
    Object main.nef.p/src_voltorb_flip_voltorb_flip_tasks.c.o
    Object main.nef.p/src_voltorb_flip_voltorb_flip_game.c.o
    Object main.nef.p/src_voltorb_flip_voltorb_flip_input.c.o
}
Overlay ds_protect
{
    After OVY_31
	Library libdsprot.a
}
Overlay OVY_124
{
    After ds_protect
    Object main.nef.p/src_overlay_124.c.o
}
Overlay OVY_125
{
    After ds_protect
}
Overlay OVY_126
{
    After ds_protect
}
Overlay OVY_127
{
    After ds_protect
}
Overlay OVY_128
{
    After ds_protect
}
