otherpoke_index_ncgr += {
    '0084' : files('west/back.png'),
    '0085' : files('east/back.png'),
    '0086' : files('west/front.png'),
    '0087' : files('east/front.png'),
}

otherpoke_index_nclr += {
    '182' : files('west/front.png'),
    '183' : files('west/back.png'),
    '184' : files('east/front.png'),
    '185' : files('east/back.png'),
}
