#ifndef POKEHEARTGOLD_CONSTANTS_APRICORNS_H
#define POKEHEARTGOLD_CONSTANTS_APRICORNS_H

#define APRICORN_NONE 0
#define APRICORN_RED  1
#define APRICORN_YLW  2
#define APRICORN_BLU  3
#define APRICORN_GRN  4
#define APRICORN_PNK  5
#define APRICORN_WHT  6
#define APRICORN_BLK  7

#endif // POKEHEARTGOLD_CONSTANTS_APRICORNS_H
