#ifndef POKEHEARTGOLD_CONSTANTS_BADGE_H
#define POKEHEARTGOLD_CONSTANTS_BADGE_H

#define BADGE_ZEPHYR  0
#define BADGE_HIVE    1
#define BADGE_PLAIN   2
#define BADGE_FOG     3
#define BADGE_STORM   4
#define BADGE_MINERAL 5
#define BADGE_GLACIER 6
#define BADGE_RISING  7

#define BADGE_BOULDER 8
#define BADGE_CASCADE 9
#define BADGE_THUNDER 10
#define BADGE_RAINBOW 11
#define BADGE_SOUL    12
#define BADGE_MARSH   13
#define BADGE_VOLCANO 14
#define BADGE_EARTH   15

#endif // POKEHEARTGOLD_CONSTANTS_BADGE_H
