#ifndef POKEHEARTGOLD_CONSTANTS_BATTLE_MENU_H
#define POKEHEARTGOLD_CONSTANTS_BATTLE_MENU_H

enum BattleMenuID {
	BATTLE_MENU_0 = 0,
	BATTLE_MENU_1,
	BATTLE_MENU_2,
	BATTLE_MENU_3,
	BATTLE_MENU_4,
	BATTLE_MENU_5,
	BATTLE_MENU_6,
	BATTLE_MENU_7,
	BATTLE_MENU_8,
	BATTLE_MENU_9,
	BATTLE_MENU_10,
	BATTLE_MENU_11,
	BATTLE_MENU_12,
	BATTLE_MENU_13,
	BATTLE_MENU_14,
	BATTLE_MENU_15,
	BATTLE_MENU_16,
	BATTLE_MENU_17,
	BATTLE_MENU_18,
	BATTLE_MENU_19,
	BATTLE_MENU_20,
	BATTLE_MENU_NONE = -1
};

#endif // POKEHEARTGOLD_CONSTANTS_BATTLE_MENU_H
