#ifndef POKEHEARTGOLD_CONSTANTS_BATTLE_SUBSCRIPT_H
#define POKEHEARTGOLD_CONSTANTS_BATTLE_SUBSCRIPT_H

enum NARCFilesBattleSubscript {
    BATTLE_SUBSCRIPT_NONE            = 0, 
    BATTLE_SUBSCRIPT_START_ENCOUNTER = 0,
    BATTLE_SUBSCRIPT_USE_MOVE,
    BATTLE_SUBSCRIPT_UPDATE_HP,
    BATTLE_SUBSCRIPT_ESCAPE,
    BATTLE_SUBSCRIPT_BATTLE_WON,
    BATTLE_SUBSCRIPT_BATTLE_LOST, //5
    BATTLE_SUBSCRIPT_FAINT_MON,
    BATTLE_SUBSCRIPT_MISSED,
    BATTLE_SUBSCRIPT_ESCAPE_FAILED,
    BATTLE_SUBSCRIPT_SWITCH_POKEMON,
    BATTLE_SUBSCRIPT_SHOW_PARTY_LIST, //10
    BATTLE_SUBSCRIPT_THROW_POKEBALL,
    BATTLE_SUBSCRIPT_UPDATE_STAT_STAGE,
    BATTLE_SUBSCRIPT_VANISH_ON_CHARGE_TURN,
    BATTLE_SUBSCRIPT_FLINCH_MON,
    BATTLE_SUBSCRIPT_FLINCHED, //15
    BATTLE_SUBSCRIPT_CRITICAL_HIT,
    BATTLE_SUBSCRIPT_HIT_X_TIMES,
    BATTLE_SUBSCRIPT_FALL_ASLEEP,
    BATTLE_SUBSCRIPT_WAKE_UP,
    BATTLE_SUBSCRIPT_SLEEPING, //20
    BATTLE_SUBSCRIPT_MOVE_FOLLOWUP_MESSAGE,
    BATTLE_SUBSCRIPT_POISON,
    BATTLE_SUBSCRIPT_POISON_DAMAGE,
    BATTLE_SUBSCRIPT_DRAIN_HALF_DAMAGE_DEALT,
    BATTLE_SUBSCRIPT_BURN, //25
    BATTLE_SUBSCRIPT_BURN_DAMAGE,
    BATTLE_SUBSCRIPT_FREEZE,
    BATTLE_SUBSCRIPT_FROZEN,
    BATTLE_SUBSCRIPT_THAW_OUT,
    BATTLE_SUBSCRIPT_DEFROSTED_BY_MOVE, //30
    BATTLE_SUBSCRIPT_PARALYZE,
    BATTLE_SUBSCRIPT_FULLY_PARALYZED,
    BATTLE_SUBSCRIPT_DREAM_EATER,
    BATTLE_SUBSCRIPT_RESET_ALL_STAT_STAGES,
    BATTLE_SUBSCRIPT_BIDE_START, //35
    BATTLE_SUBSCRIPT_BIDE_END,
    BATTLE_SUBSCRIPT_CONFUSE,
    BATTLE_SUBSCRIPT_CONFUSED,
    BATTLE_SUBSCRIPT_HURT_SELF_IN_CONFUSION, 
    BATTLE_SUBSCRIPT_SNAP_OUT_OF_CONFUSION, //40
    BATTLE_SUBSCRIPT_TRAINER_MESSAGE,
    BATTLE_SUBSCRIPT_NO_PP,
    BATTLE_SUBSCRIPT_STRUGGLE,
    BATTLE_SUBSCRIPT_THRASH,
    BATTLE_SUBSCRIPT_CONVERSION, //45
    BATTLE_SUBSCRIPT_RECOVER_HALF_MAX_HP,
    BATTLE_SUBSCRIPT_BADLY_POISON,
    BATTLE_SUBSCRIPT_PAY_DAY,
    BATTLE_SUBSCRIPT_LIGHT_SCREEN,
    BATTLE_SUBSCRIPT_MOVE_EFFECT_END, //50
    BATTLE_SUBSCRIPT_THRASH_END,
    BATTLE_SUBSCRIPT_REFLECT,
    BATTLE_SUBSCRIPT_53,
    BATTLE_SUBSCRIPT_MIST,
    BATTLE_SUBSCRIPT_REST, //55
    BATTLE_SUBSCRIPT_UPROAR,
    BATTLE_SUBSCRIPT_57,
    BATTLE_SUBSCRIPT_BIND_START,
    BATTLE_SUBSCRIPT_BIND_EFFECT,
    BATTLE_SUBSCRIPT_BIND_END, //60
    BATTLE_SUBSCRIPT_61,
    BATTLE_SUBSCRIPT_FOCUS_ENERGY,
    BATTLE_SUBSCRIPT_RECOIL_1_4,
    BATTLE_SUBSCRIPT_RECHARGE_TURN,
    BATTLE_SUBSCRIPT_RECHARGING, //65
    BATTLE_SUBSCRIPT_SET_RAGE_FLAG,
    BATTLE_SUSBEQ_MIMIC,
    BATTLE_SUBSCRIPT_LEECH_SEED_START,
    BATTLE_SUBSCRIPT_LEECH_SEED_EFFECT,
    BATTLE_SUBSCRIPT_DISABLE_START, //70
    BATTLE_SUBSCRIPT_MOVE_IS_DISABLED,
    BATTLE_SUBSCRIPT_DISABLE_END,
    BATTLE_SUBSCRIPT_ENCORE_START,
    BATTLE_SUBSCRIPT_ENCORE_END,
    BATTLE_SUBSCRIPT_75, //75
    BATTLE_SUBSCRIPT_76,
    BATTLE_SUBSCRIPT_PAIN_SPLIT,
    BATTLE_SUBSCRIPT_CONVERSION_2,
    BATTLE_SUBSCRIPT_LOCK_ON,
    BATTLE_SUBSCRIPT_SKETCH, //80
    BATTLE_SUBSCRIPT_FEINT,
    BATTLE_SUBSCRIPT_DESTINY_BOND,
    BATTLE_SUBSCRIPT_FAINT_CHECK_DESTINY_BOND,
    BATTLE_SUBSCRIPT_REDUCE_TARGET_PP,
    BATTLE_SUBSCRIPT_STEAL_ITEM, //85
    BATTLE_SUBSCRIPT_MEAN_LOOK,
    BATTLE_SUBSCRIPT_PROTECT,
    BATTLE_SUBSCRIPT_HEAL_BELL,
    BATTLE_SUBSCRIPT_TRY_SUBSTITUTE,
    BATTLE_SUBSCRIPT_HIT_SUBSTITUTE, //90
    BATTLE_SUBSCRIPT_FORCE_TARGET_TO_SWITCH_OR_FLEE,
    BATTLE_SUSBEQ_TRANSFORM_INTO_TARGET,
    BATTLE_SUBSCRIPT_NIGHTMARE_START,
    BATTLE_SUBSCRIPT_NIGHTMARE_EFFECT,
    BATTLE_SUBSCRIPT_MINIMIZE, //95
    BATTLE_SUBSCRIPT_CURSE_NORMAL,
    BATTLE_SUBSCRIPT_CURSE_GHOST,
    BATTLE_SUBSCRIPT_CURSE_DAMAGE,
    BATTLE_SUBSCRIPT_HAZARDS_CHECK,
    BATTLE_SUBSCRIPT_FORESIGHT, //100
    BATTLE_SUBSCRIPT_PERISH_SONG_START,
    BATTLE_SUBSCRIPT_CONTINUE_PERISH_SONG,
    BATTLE_SUBSCRIPT_WEATHER_START,
    BATTLE_SUBSCRIPT_WEATHER_CONTINUES,
    BATTLE_SUBSCRIPT_SWAGGER, //105
    BATTLE_SUBSCRIPT_INFATUATE,
    BATTLE_SUBSCRIPT_INFATUATED,
    BATTLE_SUBSCRIPT_IMMOBILIZED_BY_LOVE,
    BATTLE_SUBSCRIPT_SAFEGUARD_START,
    BATTLE_SUBSCRIPT_SAFEGUARD_END, //110
    BATTLE_SUBSCRIPT_111,
    BATTLE_SUBSCRIPT_PRESENT_HEAL,
    BATTLE_SUBSCRIPT_MAGNITUDE,
    BATTLE_SUBSCRIPT_BATON_PASS,
    BATTLE_SUBSCRIPT_RAPID_SPIN, //115
    BATTLE_SUBSCRIPT_BREAK_BIND_EFFECT,
    BATTLE_SUBSCRIPT_BLOW_AWAY_HAZARDS,
    BATTLE_SUBSCRIPT_GIVE_TARGET_OWN_STATUS,
    BATTLE_SUBSCRIPT_BOOST_ALL_STATS,
    BATTLE_SUBSCRIPT_BELLY_DRUM, //120
    BATTLE_SUBSCRIPT_FUTURE_SIGHT_DAMAGE,
    BATTLE_SUBSCRIPT_TELEPORT,
    BATTLE_SUBSCRIPT_FUTURE_SIGHT_START,
    BATTLE_SUBSCRIPT_STOCKPILE,
    BATTLE_SUBSCRIPT_SWALLOW, //125
    BATTLE_SUBSCRIPT_PRINT_MESSAGE_AND_PLAY_ANIMATION,
    BATTLE_SUBSCRIPT_TORMENT_START,
    BATTLE_SUBSCRIPT_FLATTER,
    BATTLE_SUBSCRIPT_MEMENTO,
    BATTLE_SUBSCRIPT_HEAL_TARGET_PARALYSIS, //130
    BATTLE_SUBSCRIPT_CHARGE,
    BATTLE_SUBSCRIPT_TAUNT_START,
    BATTLE_SUBSCRIPT_MOVE_FAIL_TAUNTED,
    BATTLE_SUBSCRIPT_EXCHANGE_ITEMS,
    BATTLE_SUBSCRIPT_COPY_ABILITY, //135
    BATTLE_SUBSCRIPT_WISH_HEAL,
    BATTLE_SUBSCRIPT_INGRAIN_HEAL,
    BATTLE_SUBSCRIPT_USER_ATK_AND_DEF_DOWN_1_STAGE,
    BATTLE_SUBSCRIPT_MAGIC_COAT,
    BATTLE_SUBSCRIPT_BREAK_SCREENS, //140
    BATTLE_SUBSCRIPT_YAWN,
    BATTLE_SUBSCRIPT_KNOCK_OFF,
    BATTLE_SUBSCRIPT_EXCHANGE_ABILITIES,
    BATTLE_SUBSCRIPT_MOVE_IS_IMPRISONED,
    BATTLE_SUBSCRIPT_RECOVER_PSN_PRZ_BRN, //145
    BATTLE_SUBSCRIPT_SNATCH,
    BATTLE_SUBSCRIPT_RECOIL_1_3,
    BATTLE_SUBSCRIPT_TARGET_ATK_AND_DEF_DOWN_1_STAGE,
    BATTLE_SUBSCRIPT_USER_DEF_AND_SPDEF_UP_1_STAGE,
    BATTLE_SUBSCRIPT_USER_ATK_AND_DEF_UP_1_STAGE, //150
    BATTLE_SUBSCRIPT_USER_SPATK_AND_SPDEF_UP_1_STAGE,
    BATTLE_SUBSCRIPT_USER_ATK_AND_SPEED_UP_1_STAGE,
    BATTLE_SUBSCRIPT_PURSUIT,
    BATTLE_SUBSCRIPT_ROOST,
    BATTLE_SUBSCRIPT_HEAL_TARGET_SLEEP, //155
    BATTLE_SUBSCRIPT_GRAVITY_START,
    BATTLE_SUBSCRIPT_MOVE_FAIL_GRAVITY,
    BATTLE_SUBSCRIPT_MIRACLE_EYE,
    BATTLE_SUBSCRIPT_HEALING_WISH,
    BATTLE_SUBSCRIPT_TAILWIND_START, //160
    BATTLE_SUBSCRIPT_USER_DEF_AND_SPDEF_DOWN_1_STAGE,
    BATTLE_SUBSCRIPT_USER_SWAP_ATK_AND_DEF,
    BATTLE_SUBSCRIPT_SUPPRESS_TARGET_ABILITY,
    BATTLE_SUBSCRIPT_LUCKY_CHANT_START,
    BATTLE_SUBSCRIPT_EXCHANGE_ATK_AND_SPATK_STAGES, //165
    BATTLE_SUBSCRIPT_EXCHANGE_DEF_AND_SPDEF_STAGES,
    BATTLE_SUBSCRIPT_GIVE_TARGET_INSOMNIA,
    BATTLE_SUBSCRIPT_EXCHANGE_ALL_STAT_STAGES,
    BATTLE_SUBSCRIPT_AQUA_RING_HEAL,
    BATTLE_SUBSCRIPT_RECOIL_1_3_CHANCE_TO_BURN, //170
    BATTLE_SUBSCRIPT_DEFOG,
    BATTLE_SUBSCRIPT_172,
    BATTLE_SUBSCRIPT_HEAL_BLOCK_START,
    BATTLE_SUBSCRIPT_MOVE_IS_HEAL_BLOCKED,
    BATTLE_SUBSCRIPT_ATTACK_THEN_SWITCH_OUT, //175

    BATTLE_SUBSCRIPT_MOLD_BREAKER = 177,
    BATTLE_SUBSCRIPT_ABILITY_RESTORES_HP,
    BATTLE_SUBSCRIPT_ABSORB_AND_BOOST_FIRE_TYPE_MOVES,
    BATTLE_SUBSCRIPT_LIGHTNING_ROD_REDIRECTED, //180
    BATTLE_SUBSCRIPT_BLOCKED_BY_SOUNDPROOF,
    BATTLE_SUBSCRIPT_ABSORB_AND_SPEED_UP_1_STAGE,
    BATTLE_SUBSCRIPT_DRIZZLE,
    BATTLE_SUBSCRIPT_SAND_STREAM,
    BATTLE_SUBSCRIPT_DROUGHT, //185
    BATTLE_SUBSCRIPT_INTIMIDATE,
    BATTLE_SUBSCRIPT_TRACE,
    BATTLE_SUBSCRIPT_COLOR_CHANGE,
    BATTLE_SUBSCRIPT_ROUGH_SKIN,
    BATTLE_SUBSCRIPT_ABILITY_RESTORE_STATUS,
    BATTLE_SUBSCRIPT_LOAFING_AROUND,

    BATTLE_SUBSCRIPT_AFTERMATH = 193,
    BATTLE_SUBSCRIPT_ANTICIPATION,
    BATTLE_SUBSCRIPT_FOREWARN, //195
    BATTLE_SUBSCRIPT_SLOW_START,
    BATTLE_SUBSCRIPT_SLOW_START_END,
    BATTLE_SUBSCRIPT_HELD_ITEM_HP_RESTORE,
    BATTLE_SUBSCRIPT_HELD_ITEM_PRZ_RESTORE,
    BATTLE_SUBSCRIPT_HELD_ITEM_SLP_RESTORE, //200
    BATTLE_SUBSCRIPT_HELD_ITEM_PSN_RESTORE,
    BATTLE_SUBSCRIPT_HELD_ITEM_BRN_RESTORE,
    BATTLE_SUBSCRIPT_HELD_ITEM_FRZ_RESTORE,
    BATTLE_SUBSCRIPT_HELD_ITEM_PP_RESTORE,
    BATTLE_SUBSCRIPT_HELD_ITEM_CNF_RESTORE, //205
    BATTLE_SUBSCRIPT_HELD_ITEM_MULTI_RESTORE,
    BATTLE_SUBSCRIPT_HELD_ITEM_DISLIKE_FLAVOR,
    BATTLE_SUBSCRIPT_HELD_ITEM_RAISE_STAT,
    BATTLE_SUBSCRIPT_HELD_ITEM_RAISE_CRIT,
    BATTLE_SUBSCRIPT_HELD_ITEM_SHARPLY_RAISE_STAT, //210
    BATTLE_SUBSCRIPT_HELD_ITEM_STATDOWN_RESTORE,
    BATTLE_SUBSCRIPT_HELD_ITEM_HEAL_INFATUATION,
    BATTLE_SUBSCRIPT_RESTORE_A_LITTLE_HP,
    BATTLE_SUBSCRIPT_LOSE_HP_FROM_ITEM,
    BATTLE_SUBSCRIPT_LOSE_HP_FROM_ITEM_WITH_MESSAGE,
    BATTLE_SUBSCRIPT_TRANSFER_STICKY_BARB = 216,
    
    BATTLE_SUBSCRIPT_EMBARGO_START = 218,
    BATTLE_SUBSCRIPT_PLUCK,
    BATTLE_SUBSCRIPT_FLING, //220
    BATTLE_SUBSCRIPT_ABILITY_FORBIDS_STATUS,
    BATTLE_SUBSCRIPT_ESCAPE_ITEM,
    BATTLE_SUBSCRIPT_BATTLE_ITEM,
    
    BATTLE_SUBSCRIPT_RECOIL_1_3_CHANCE_TO_PARALYZE = 226,
    BATTLE_SUBSCRIPT_SAFARI_THROW_BAIT,
    BATTLE_SUBSCRIPT_SAFARI_THROW_ROCK,
    BATTLE_SUBSCRIPT_SAFARI_ESCAPE,
    BATTLE_SUBSCRIPT_ENEMY_ESCAPE, //230
    BATTLE_SUBSCRIPT_REPLACE_FAINTED,
    BATTLE_SUBSCRIPT_TIGHTEN_FOCUS,
    BATTLE_SUBSCRIPT_TAILWIND_END,
    BATTLE_SUBSCRIPT_RAINING_END,
    BATTLE_SUBSCRIPT_SANDSTORM_END, //235
    BATTLE_SUBSCRIPT_SUNNY_END,
    BATTLE_SUBSCRIPT_HAILING_END,
    BATTLE_SUBSCRIPT_GRAVITY_END,
    BATTLE_SUBSCRIPT_CANNOT_HEAL,
    BATTLE_SUBSCRIPT_UPROAR_CONTINUES, //240
    BATTLE_SUBSCRIPT_UPROAR_END,
    BATTLE_SUBSCRIPT_MAGNET_RISE_END,
    BATTLE_SUBSCRIPT_HEAL_BLOCK_END,
    BATTLE_SUBSCRIPT_EMBARGO_END,
    BATTLE_SUBSCRIPT_RAGE_IS_BUILDING,//245
    BATTLE_SUBSCRIPT_RECOIL_1_2,
    BATTLE_SUBSCRIPT_BURN_OR_FLINCH,
    BATTLE_SUBSCRIPT_FREEZE_OR_FLINCH,
    BATTLE_SUBSCRIPT_PARALYZE_OR_FLINCH,
    BATTLE_SUBSCRIPT_LUCKY_CHANT_END, //250
    BATTLE_SUBSCRIPT_TRICK_ROOM_END,
    BATTLE_SUBSCRIPT_SNOW_WARNING,
    BATTLE_SUBSCRIPT_FRISK,
    BATTLE_SUBSCRIPT_DISOBEY_WHILE_ASLEEP,
    BATTLE_SUBSCRIPT_DISOBEY_DO_NOTHING, //255
    BATTLE_SUBSCRIPT_DISOBEY_ORDERS,
    BATTLE_SUBSCRIPT_DISOBEY_SLEEP,
    BATTLE_SUBSCRIPT_DISOBEY_HIT_SELF,

    BATTLE_SUBSCRIPT_CHATTER = 260,
    BATTLE_SUBSCRIPT_LUNAR_DANCE,
    BATTLE_SUBSCRIPT_FORM_CHANGE,
    BATTLE_SUBSCRIPT_BAD_DREAMS,

    BATTLE_SUBSCRIPT_HELD_ITEM_TEMP_ACC_UP = 265,
    BATTLE_SUBSCRIPT_HELD_ITEM_RECOIL_WHEN_HIT,
    BATTLE_SUBSCRIPT_USE_POTION,
    BATTLE_SUBSCRIPT_USE_STATUS_RECOVERY,
    BATTLE_SUBSCRIPT_USE_STAT_BOOSTER,
    BATTLE_SUBSCRIPT_USE_GUARD_SPEC, //270
    BATTLE_SUBSCRIPT_OVERWORLD_RAIN,
    BATTLE_SUBSCRIPT_OVERWORLD_HAIL,
    BATTLE_SUBSCRIPT_OVERWORLD_SAND,
    BATTLE_SUBSCRIPT_OVERWORLD_FOG,
    BATTLE_SUBSCRIPT_THROW_SAFARI_BALL, //275
    BATTLE_SUBSCRIPT_GRANT_EXP,
    BATTLE_SUBSCRIPT_AFTER_SELFDESTRUCT,
    BATTLE_SUBSCRIPT_CHECK_QUICK_CLAW,

    BATTLE_SUBSCRIPT_NO_TARGET = 281,
    BATTLE_SUBSCRIPT_BIDE_NO_TARGET,

    BATTLE_SUBSCRIPT_PRESSURE = 285,
    BATTLE_SUBSCRIPT_ENEMY_ESCAPE_FAILED,
    BATTLE_SUBSCRIPT_VANISH_OFF,
    BATTLE_SUBSCRIPT_TAUNT_END,
    BATTLE_SUBSCRIPT_USE_FULL_RESTORE,

    BATTLE_SUBSCRIPT_WAIT_MOVE_ANIMATION = 291,

    BATTLE_SUBSCRIPT_CHECK_SHAYMIN_FORM = 293,
    BATTLE_SUBSCRIPT_OVERWORLD_SUN,
    BATTLE_SUBSCRIPT_OVERWORLD_TRICK_ROOM,
    BATTLE_SUBSCRIPT_GIRATINA_FORM_CHANGE,
};

#endif
