#ifndef POKEHEARTGOLD_CONSTANTS_BATTLE_SCRIPT_H
#define POKEHEARTGOLD_CONSTANTS_BATTLE_SCRIPT_H

#define BSCRIPT_VAR_BATTLE_TYPE                            0
#define BSCRIPT_VAR_CRITICAL_BOOSTS                        1
#define BSCRIPT_VAR_SIDE_EFFECT_FLAGS_DIRECT               2
#define BSCRIPT_VAR_SIDE_EFFECT_FLAGS_INDIRECT             3
#define BSCRIPT_VAR_SIDE_EFFECT_FLAGS_ABILITY              4
#define BSCRIPT_VAR_SIDE_EFFECT_TYPE                       5
#define BSCRIPT_VAR_BATTLE_STATUS                          6
#define BSCRIPT_VAR_FIELD_CONDITION                        7
#define BSCRIPT_VAR_POWER_MULTI                            8
#define BSCRIPT_VAR_CALC_TEMP                              9
#define BSCRIPT_VAR_MOVE_STATUS_FLAGS                      10
#define BSCRIPT_VAR_SIDE_CONDITION_ATTACKER                11
#define BSCRIPT_VAR_SIDE_CONDITION_TARGET                  12
#define BSCRIPT_VAR_SIDE_CONDITION_STAT_CHANGE             13
#define BSCRIPT_VAR_DAMAGE                                 14
#define BSCRIPT_VAR_BATTLER_ATTACKER                       15
#define BSCRIPT_VAR_BATTLER_TARGET                         16
#define BSCRIPT_VAR_BATTLER_STAT_CHANGE                    17
#define BSCRIPT_VAR_BATTLER_FAINTED                        18
#define BSCRIPT_VAR_BATTLER_SWITCH                         19
#define BSCRIPT_VAR_MSG_BATTLER_TEMP                       20
#define BSCRIPT_VAR_ATTACKER_STORED_DAMAGE                 21
#define BSCRIPT_VAR_MESSAGE                                22
#define BSCRIPT_VAR_PAY_DAY_COUNT                          23
#define BSCRIPT_VAR_MOVE_NO_CUR                            24
#define BSCRIPT_VAR_TOTAL_TURNS                            25
#define BSCRIPT_VAR_MSG_ATTACKER                           26
#define BSCRIPT_VAR_MSG_DEFENDER                           27
#define BSCRIPT_VAR_MOVE_NO_TEMP                           28
#define BSCRIPT_VAR_LAST_BATTLER_ID                        29
#define BSCRIPT_VAR_MOVE_POWER                             30
#define BSCRIPT_VAR_AFTER_MOVE_MESSAGE_TYPE                31
#define BSCRIPT_VAR_HP_CALC                                32
#define BSCRIPT_VAR_BATTLE_OUTCOME                         33
#define BSCRIPT_VAR_SIDE_EFFECT_PARAM                      34
#define BSCRIPT_VAR_MSG_MOVE_TEMP                          35
#define BSCRIPT_VAR_MSG_ITEM_TEMP                          36
#define BSCRIPT_VAR_MSG_ABILITY_TEMP                       37
#define BSCRIPT_VAR_WEATHER_TURNS                          38
#define BSCRIPT_VAR_BATTLER_SPEED_TEMP                     39
#define BSCRIPT_VAR_MULTI_HIT_LOOP                         40
#define BSCRIPT_VAR_PHYSICAL_DAMAGE                        41
#define BSCRIPT_VAR_SPECIAL_DAMAGE                         42
#define BSCRIPT_VAR_TEMP_DATA                              43
#define BSCRIPT_VAR_CRIT_MULTIPLIER                        44
#define BSCRIPT_VAR_ATTACKER_LAST_DAMAGE_TAKEN             45
#define BSCRIPT_VAR_DEFENDER_LAST_DAMAGE_TAKEN             46
#define BSCRIPT_VAR_ATTACKER_SELF_TURN_STATUS_FLAGS        47
#define BSCRIPT_VAR_DEFENDER_SELF_TURN_STATUS_FLAGS        48
#define BSCRIPT_VAR_SIDE_EFFECT_MON_SELF_TURN_STATUS_FLAGS 49
#define BSCRIPT_VAR_FLING_DATA                             50
#define BSCRIPT_VAR_FLING_SCRIPT                           51
#define BSCRIPT_VAR_BATTLE_SYS_STATUS                      52
#define BSCRIPT_VAR_ATTACKER_LOCKED_MOVE                   53
#define BSCRIPT_VAR_HIT_DAMAGE                             54
#define BSCRIPT_VAR_SAFARI_BALL_CNT                        55
#define BSCRIPT_VAR_SWITCHED_MON_TEMP                      56
#define BSCRIPT_VAR_MOVE_TYPE                              57
#define BSCRIPT_VAR_MOVE_EFFECT_CHANCE                     58
#define BSCRIPT_VAR_REGULATION_FLAG                        59
#define BSCRIPT_VAR_BATTLE_STATUS_2                        60
#define BSCRIPT_VAR_TURN_ORDER_COUNTER                     61
#define BSCRIPT_VAR_MAX_BATTLERS                           62
#define BSCRIPT_VAR_BATTLER_ATTACKER_TEMP                  63
#define BSCRIPT_VAR_BATTLER_TARGET_TEMP                    64
#define BSCRIPT_VAR_PHYSICAL_DAMAGE_TAKEN                  65
#define BSCRIPT_VAR_MSG_BATTLER_TEMP_ASSURANCE_DAMAGE_MASK 66
#define BSCRIPT_VAR_DEFENDER_ASSURANCE_DAMAGE_MASK         67
#define BSCRIPT_VAR_ATTACKER_SHELL_BELL_DAMAGE_DEALT       68
#define BSCRIPT_VAR_WAITING_BATTLERS                       69
#define BSCRIPT_VAR_70                                     70

#endif
