#ifndef POKEHEARTGOLD_CONSTANTS_BATTLE_SCRIPT_H
#define POKEHEARTGOLD_CONSTANTS_BATTLE_SCRIPT_H

#define BSCRIPT_VAR_BATTLE_FLAGS                 0
#define BSCRIPT_VAR_CRIT_COUNT                   1
#define BSCRIPT_VAR_2                            2
#define BSCRIPT_VAR_3                            3
#define BSCRIPT_VAR_4                            4
#define BSCRIPT_VAR_STAT_CHANGE_TYPE             5
#define BSCRIPT_VAR_BATTLE_STATUS                6
#define BSCRIPT_VAR_FIELD_CONDITION              7
#define BSCRIPT_VAR_8                            8
#define BSCRIPT_VAR_CALC_TEMP                    9
#define BSCRIPT_VAR_MOVE_STATUS_FLAG            10
#define BSCRIPT_VAR_SIDE_CONDITION_ATTACKER     11
#define BSCRIPT_VAR_SIDE_CONDITION_TARGET       12
#define BSCRIPT_VAR_SIDE_CONDITION_STAT_CHANGE  13
#define BSCRIPT_VAR_DAMAGE                      14
#define BSCRIPT_VAR_BATTLER_ATTACKER            15
#define BSCRIPT_VAR_BATTLER_TARGET              16
#define BSCRIPT_VAR_BATTLER_STAT_CHANGE         17
#define BSCRIPT_VAR_BATTLER_FAINTED             18
#define BSCRIPT_VAR_BATTLER_SWITCH              19
#define BSCRIPT_VAR_BATTLER_TEMP                20
#define BSCRIPT_VAR_21                          21
#define BSCRIPT_VAR_MESSAGE                     22
#define BSCRIPT_VAR_23                          23
#define BSCRIPT_VAR_MOVE_NO_CUR                 24
#define BSCRIPT_VAR_TOTAL_TURNS                 25
#define BSCRIPT_VAR_26                          26
#define BSCRIPT_VAR_27                          27
#define BSCRIPT_VAR_MOVE_NO_TEMP                28
#define BSCRIPT_VAR_29                          29
#define BSCRIPT_VAR_MOVE_POWER                  30
#define BSCRIPT_VAR_31                          31
#define BSCRIPT_VAR_HP_CALC                     32
#define BSCRIPT_VAR_BATTLE_OUTCOME              33
#define BSCRIPT_VAR_STAT_CHANGE_PARAM           34
#define BSCRIPT_VAR_MOVE_TEMP                   35
#define BSCRIPT_VAR_ITEM_TEMP                   36
#define BSCRIPT_VAR_ABILITY_TEMP                37
#define BSCRIPT_VAR_WEATHER_TURNS               38
#define BSCRIPT_VAR_39                          39
#define BSCRIPT_VAR_40                          40
#define BSCRIPT_VAR_PHYSICAL_DAMAGE             41
#define BSCRIPT_VAR_SPECIAL_DAMAGE              42
#define BSCRIPT_VAR_TEMP_DATA                   43
#define BSCRIPT_VAR_CRIT_MULTIPLIER             44
#define BSCRIPT_VAR_45                          45
#define BSCRIPT_VAR_46                          46
#define BSCRIPT_VAR_47                          47
#define BSCRIPT_VAR_48                          48
#define BSCRIPT_VAR_49                          49
#define BSCRIPT_VAR_FLING_DATA                  50
#define BSCRIPT_VAR_FLING_SCRIPT                51
#define BSCRIPT_VAR_52                          52
#define BSCRIPT_VAR_MOVE_LOCKED_INTO_ATTACKER   53
#define BSCRIPT_VAR_HIT_DAMAGE                  54
#define BSCRIPT_VAR_SAFARI_BALL_CNT             55
#define BSCRIPT_VAR_BATTLER_SWITCH_TEMP         56
#define BSCRIPT_VAR_MOVE_TYPE                   57
#define BSCRIPT_VAR_58                          58
#define BSCRIPT_VAR_59                          59
#define BSCRIPT_VAR_BATTLE_STATUS_2             60
#define BSCRIPT_VAR_61                          61
#define BSCRIPT_VAR_MAX_BATTLERS                62
#define BSCRIPT_VAR_BATTLER_ATTACKER_TEMP       63
#define BSCRIPT_VAR_BATTLER_TARGET_TEMP         64
#define BSCRIPT_VAR_PHYSICAL_DAMAGE_TAKEN       65
#define BSCRIPT_VAR_66                          66
#define BSCRIPT_VAR_67                          67
#define BSCRIPT_VAR_SHELL_BELL_HP               68
#define BSCRIPT_VAR_BATTLERS_ON_FIELD           69
#define BSCRIPT_VAR_70                          70

#endif
