#ifndef POKEHEARTGOLD_CONSTANTS_BATTLE_MENU_H
#define POKEHEARTGOLD_CONSTANTS_BATTLE_MENU_H

enum BattleMenuTextObj {
    // Main Menu
    MENUTXT_FIGHT = 0,
    MENUTXT_BAG,
    MENUTXT_POKEMON,
    MENUTXT_RUN,

    // Bug Contest
    MENUTXT_BUG_GENDER = 4,
    MENUTXT_BUG_LEVEL,

    // Fight Menu
    MENUTXT_MOVE_1 = 0,
    MENUTXT_MOVE_2,
    MENUTXT_MOVE_3,
    MENUTXT_MOVE_4,
    MENUTXT_CANCEL,
    MENUTXT_PP_1,
    MENUTXT_PP_2,
    MENUTXT_PP_3,
    MENUTXT_PP_4,
    MENUTXT_PP_MAX_1,
    MENUTXT_PP_MAX_2,
    MENUTXT_PP_MAX_3,
    MENUTXT_PP_MAX_4,

    // Yes/No Menu
    MENUTXT_YES = 0,
    MENUTXT_NO,

    // Forget/Keep a Move Menu
    MENUTXT_FORGET_MOVE = 0,
    MENUTXT_KEEP_MOVE,

    // Give Up/Don't Give Up on a Move Menu
    MENUTXT_GIVEUP = 0,
    MENUTXT_DONT_GIVEUP,

    // Use Next Pokemon/Flee Menu
    MENUTXT_USE_NEXT_MON = 0,
    MENUTXT_FLEE,

    // Switch/Keep Menu
    MENUTXT_SWITCH = 0,
    MENUTXT_KEEP_BATTLING,

    // Target Menu
    MENUTXT_MON_NAME_1 = 0,
    MENUTXT_MON_NAME_2,
    MENUTXT_MON_NAME_3,
    MENUTXT_MON_NAME_4,
    MENUTXT_TARGET_CANCEL,
};

enum BattleMenuID {
    BATTLE_MENU_0 = 0,
    BATTLE_MENU_MAIN_INITIAL,
    BATTLE_MENU_MAIN,
    BATTLE_MENU_3,
    BATTLE_MENU_4,
    BATTLE_MENU_5,
    BATTLE_MENU_6,
    BATTLE_MENU_7,
    BATTLE_MENU_8,
    BATTLE_MENU_PAL_PARK_INITIAL,
    BATTLE_MENU_PAL_PARK,
    BATTLE_MENU_FIGHT,
    BATTLE_MENU_TARGET,
    BATTLE_MENU_YES_NO,
    BATTLE_MENU_KEEP_FORGET_MOVE,
    BATTLE_MENU_GIVE_UP_ON_MOVE,
    BATTLE_MENU_SWITCH_OR_FLEE,
    BATTLE_MENU_SWITCH_OR_KEEP,
    BATTLE_MENU_VS_RECORDER_PLAYBACK,
    BATTLE_MENU_19,
    BATTLE_MENU_20,
    BATTLE_MENU_NONE = -1
};

enum BattleMenuInputCodes {
    BATTLE_INPUT_0 = 0,

    // Main Menu
    BATTLE_INPUT_FIGHT = 1,
    BATTLE_INPUT_BAG,
    BATTLE_INPUT_POKEMON,
    BATTLE_INPUT_RUN,

    // Fight Menu
    BATTLE_INPUT_MOVE_1 = 1,
    BATTLE_INPUT_MOVE_2,
    BATTLE_INPUT_MOVE_3,
    BATTLE_INPUT_MOVE_4,

    // Yes/No
    BATTLE_INPUT_YES = 1,

    // Target Screen
    BATTLE_INPUT_TARGET_PLAYER_LEFT = 1,
    BATTLE_INPUT_TARGET_OPPONENT_RIGHT,
    BATTLE_INPUT_TARGET_PLAYER_RIGHT,
    BATTLE_INPUT_TARGET_OPPONENT_LEFT,

    // Pal Park
    BATTLE_INPUT_BALL = 1,

    // VS Recorder
    BATTLE_INPUT_STOP = 1,

    BATTLE_INPUT_CANCEL = 0xFF
};

enum BattleMenuCursorInput {
    // Main Menu
    CURSOR_INPUT_FIGHT = 0,
    CURSOR_INPUT_BAG,
    CURSOR_INPUT_POKEMON,
    CURSOR_INPUT_RUN,

    // Pal Park
    CURSOR_INPUT_PAL_PARK_BALL = 0,
    CURSOR_INPUT_PAL_PARK_RUN,

    // Fight Menu
    CURSOR_INPUT_FIGHT_CANCEL = 0,
    CURSOR_INPUT_MOVE_1,
    CURSOR_INPUT_MOVE_2,
    CURSOR_INPUT_MOVE_3,
    CURSOR_INPUT_MOVE_4,

    // Two Option Menu
    CURSOR_INPUT_TWO_OPTION_TOP = 0,
    CURSOR_INPUT_TWO_OPTION_BOTTOM,

    // Fight Menu
    CURSOR_INPUT_TARGET_PLAYER_LEFT = 0,
    CURSOR_INPUT_TARGET_OPPONENT_RIGHT,
    CURSOR_INPUT_TARGET_PLAYER_RIGHT,
    CURSOR_INPUT_TARGET_OPPONENT_LEFT,
    CURSOR_INPUT_TARGET_CANCEL,
};

enum BattleMenuTargetType {
    TARGET_ANY,
    TARGET_ALL_OPPONENTS,
    TARGET_ALL_NOT_PLAYER_LEFT,
    TARGET_ALL,
    TARGET_PLAYER_LEFT,
    TARGET_ALL_ALLIES,
    TARGET_PLAYER_RIGHT,
    TARGET_ALL_NOT_PLAYER_RIGHT,
    TARGET_ANY_NOT_PLAYER_LEFT,
    TARGET_ANY_NOT_PLAYER_RIGHT,
    TARGET_ANY_ALLY,
    TARGET_ANY_OPPONENT
};

#endif // POKEHEARTGOLD_CONSTANTS_BATTLE_MENU_H
