#ifndef POKEHEARTGOLD_CONSTANTS_FIELD_POISON_H
#define POKEHEARTGOLD_CONSTANTS_FIELD_POISON_H

#define FIELD_POISON_NONE       0
#define FIELD_POISON_DAMAGE     1
#define FIELD_POISON_SURVIVE    2

#endif // POKEHEARTGOLD_CONSTANTS_FIELD_POISON_H
