#ifndef POKEHEARTGOLD_CONSTANTS_FLYPOINTS_H
#define POKEHEARTGOLD_CONSTANTS_FLYPOINTS_H

#define FLYPOINT_PALLET       0
#define FLYPOINT_VIRIDIAN     1
#define FLYPOINT_PEWTER       2
#define FLYPOINT_CERULEAN     3
#define FLYPOINT_LAVENDER     4
#define FLYPOINT_VERMILION    5
#define FLYPOINT_CELADON      6
#define FLYPOINT_FUCHSIA      7
#define FLYPOINT_CINNABAR     8
#define FLYPOINT_INDIGO       9
#define FLYPOINT_SAFFRON      10
#define FLYPOINT_NEW_BARK     11
#define FLYPOINT_CHERRYGROVE  12
#define FLYPOINT_VIOLET       13
#define FLYPOINT_AZALEA       14
#define FLYPOINT_GOLDENROD    15
#define FLYPOINT_ECRUTEAK     16
#define FLYPOINT_OLIVINE      17
#define FLYPOINT_CIANWOOD     18
#define FLYPOINT_MAHOGANY     19
#define FLYPOINT_LAKE_OF_RAGE 20
#define FLYPOINT_BLACKTHORN   21
#define FLYPOINT_MT_SILVER    22
#define FLYPOINT_UNK23        23
#define FLYPOINT_UNK24        24
#define FLYPOINT_UNK25        25
#define FLYPOINT_UNK26        26
#define FLYPOINT_UNION_CAVE   27
#define FLYPOINT_UNK28        28
#define FLYPOINT_UNK29        29
#define FLYPOINT_SAFARI       30
#define FLYPOINT_FRONTIER     31
#define FLYPOINT_UNK32        32
#define FLYPOINT_VICTORY_ROAD 33
#define FLYPOINT_UNK34        34
#define FLYPOINT_POKEATHLON   35
#define FLYPOINT_MT_MOON      36
#define FLYPOINT_ROCK_TUNNEL  37

#endif // POKEHEARTGOLD_CONSTANTS_FLYPOINTS_H
