#ifndef POKEHEARTGOLD_CONSTANTS_FLYPOINTS_H
#define POKEHEARTGOLD_CONSTANTS_FLYPOINTS_H

#define VISITED_FLAG_PALLET       0
#define VISITED_FLAG_VIRIDIAN     1
#define VISITED_FLAG_PEWTER       2
#define VISITED_FLAG_CERULEAN     3
#define VISITED_FLAG_LAVENDER     4
#define VISITED_FLAG_VERMILION    5
#define VISITED_FLAG_CELADON      6
#define VISITED_FLAG_FUCHSIA      7
#define VISITED_FLAG_CINNABAR     8
#define VISITED_FLAG_INDIGO       9
#define VISITED_FLAG_SAFFRON      10
#define VISITED_FLAG_NEW_BARK     11
#define VISITED_FLAG_CHERRYGROVE  12
#define VISITED_FLAG_VIOLET       13
#define VISITED_FLAG_AZALEA       14
#define VISITED_FLAG_CIANWOOD     15
#define VISITED_FLAG_GOLDENROD    16
#define VISITED_FLAG_OLIVINE      17
#define VISITED_FLAG_ECRUTEAK     18
#define VISITED_FLAG_MAHOGANY     19
#define VISITED_FLAG_LAKE_OF_RAGE 20
#define VISITED_FLAG_BLACKTHORN   21
#define VISITED_FLAG_MT_SILVER    22
#define VISITED_FLAG_UNK23        23
#define VISITED_FLAG_UNK24        24
#define VISITED_FLAG_ROUTE_47     25
#define VISITED_FLAG_UNK26        26
#define VISITED_FLAG_UNION_CAVE   27
#define VISITED_FLAG_UNK28        28
#define VISITED_FLAG_PAL_PARK     29
#define VISITED_FLAG_SAFARI       30
#define VISITED_FLAG_FRONTIER     31
#define VISITED_FLAG_UNK32        32
#define VISITED_FLAG_VICTORY_ROAD 33
#define VISITED_FLAG_UNK34        34
#define VISITED_FLAG_POKEATHLON   35
#define VISITED_FLAG_MT_MOON      36
#define VISITED_FLAG_ROCK_TUNNEL  37

#endif // POKEHEARTGOLD_CONSTANTS_FLYPOINTS_H
