#ifndef POKEHEARTGOLD_FOLLOW_POKE_IDX_H
#define POKEHEARTGOLD_FOLLOW_POKE_IDX_H

#define TSURE_POKE_NONE                                  0
#define TSURE_POKE_BULBASAUR                             0
#define TSURE_POKE_IVYSAUR                               1
#define TSURE_POKE_VENUSAUR                              2
#define TSURE_POKE_VENUSAUR_F                            3
#define TSURE_POKE_CHARMANDER                            4
#define TSURE_POKE_CHARMELEON                            5
#define TSURE_POKE_CHARIZARD                             6
#define TSURE_POKE_SQUIRTLE                              7
#define TSURE_POKE_WARTORTLE                             8
#define TSURE_POKE_BLASTOISE                             9
#define TSURE_POKE_CATERPIE                             10
#define TSURE_POKE_METAPOD                              11
#define TSURE_POKE_BUTTERFREE                           12
#define TSURE_POKE_WEEDLE                               13
#define TSURE_POKE_KAKUNA                               14
#define TSURE_POKE_BEEDRILL                             15
#define TSURE_POKE_PIDGEY                               16
#define TSURE_POKE_PIDGEOTTO                            17
#define TSURE_POKE_PIDGEOT                              18
#define TSURE_POKE_RATTATA                              19
#define TSURE_POKE_RATICATE                             20
#define TSURE_POKE_SPEAROW                              21
#define TSURE_POKE_FEAROW                               22
#define TSURE_POKE_EKANS                                23
#define TSURE_POKE_ARBOK                                24
#define TSURE_POKE_PIKACHU                              25
#define TSURE_POKE_PIKACHU_F                            26
#define TSURE_POKE_RAICHU                               27
#define TSURE_POKE_SANDSHREW                            28
#define TSURE_POKE_SANDSLASH                            29
#define TSURE_POKE_NIDORAN_F                            30
#define TSURE_POKE_NIDORINA                             31
#define TSURE_POKE_NIDOQUEEN                            32
#define TSURE_POKE_NIDORAN_M                            33
#define TSURE_POKE_NIDORINO                             34
#define TSURE_POKE_NIDOKING                             35
#define TSURE_POKE_CLEFAIRY                             36
#define TSURE_POKE_CLEFABLE                             37
#define TSURE_POKE_VULPIX                               38
#define TSURE_POKE_NINETALES                            39
#define TSURE_POKE_JIGGLYPUFF                           40
#define TSURE_POKE_WIGGLYTUFF                           41
#define TSURE_POKE_ZUBAT                                42
#define TSURE_POKE_GOLBAT                               43
#define TSURE_POKE_ODDISH                               44
#define TSURE_POKE_GLOOM                                45
#define TSURE_POKE_VILEPLUME                            46
#define TSURE_POKE_PARAS                                47
#define TSURE_POKE_PARASECT                             48
#define TSURE_POKE_VENONAT                              49
#define TSURE_POKE_VENOMOTH                             50
#define TSURE_POKE_DIGLETT                              51
#define TSURE_POKE_DUGTRIO                              52
#define TSURE_POKE_MEOWTH                               53
#define TSURE_POKE_PERSIAN                              54
#define TSURE_POKE_PSYDUCK                              55
#define TSURE_POKE_GOLDUCK                              56
#define TSURE_POKE_MANKEY                               57
#define TSURE_POKE_PRIMEAPE                             58
#define TSURE_POKE_GROWLITHE                            59
#define TSURE_POKE_ARCANINE                             60
#define TSURE_POKE_POLIWAG                              61
#define TSURE_POKE_POLIWHIRL                            62
#define TSURE_POKE_POLIWRATH                            63
#define TSURE_POKE_ABRA                                 64
#define TSURE_POKE_KADABRA                              65
#define TSURE_POKE_ALAKAZAM                             66
#define TSURE_POKE_MACHOP                               67
#define TSURE_POKE_MACHOKE                              68
#define TSURE_POKE_MACHAMP                              69
#define TSURE_POKE_BELLSPROUT                           70
#define TSURE_POKE_WEEPINBELL                           71
#define TSURE_POKE_VICTREEBEL                           72
#define TSURE_POKE_TENTACOOL                            73
#define TSURE_POKE_TENTACRUEL                           74
#define TSURE_POKE_GEODUDE                              75
#define TSURE_POKE_GRAVELER                             76
#define TSURE_POKE_GOLEM                                77
#define TSURE_POKE_PONYTA                               78
#define TSURE_POKE_RAPIDASH                             79
#define TSURE_POKE_SLOWPOKE                             80
#define TSURE_POKE_SLOWBRO                              81
#define TSURE_POKE_MAGNEMITE                            82
#define TSURE_POKE_MAGNETON                             83
#define TSURE_POKE_FARFETCHD                            84
#define TSURE_POKE_DODUO                                85
#define TSURE_POKE_DODRIO                               86
#define TSURE_POKE_SEEL                                 87
#define TSURE_POKE_DEWGONG                              88
#define TSURE_POKE_GRIMER                               89
#define TSURE_POKE_MUK                                  90
#define TSURE_POKE_SHELLDER                             91
#define TSURE_POKE_CLOYSTER                             92
#define TSURE_POKE_GASTLY                               93
#define TSURE_POKE_HAUNTER                              94
#define TSURE_POKE_GENGAR                               95
#define TSURE_POKE_ONIX                                 96
#define TSURE_POKE_DROWZEE                              97
#define TSURE_POKE_HYPNO                                98
#define TSURE_POKE_KRABBY                               99
#define TSURE_POKE_KINGLER                             100
#define TSURE_POKE_VOLTORB                             101
#define TSURE_POKE_ELECTRODE                           102
#define TSURE_POKE_EXEGGCUTE                           103
#define TSURE_POKE_EXEGGUTOR                           104
#define TSURE_POKE_CUBONE                              105
#define TSURE_POKE_MAROWAK                             106
#define TSURE_POKE_HITMONLEE                           107
#define TSURE_POKE_HITMONCHAN                          108
#define TSURE_POKE_LICKITUNG                           109
#define TSURE_POKE_KOFFING                             110
#define TSURE_POKE_WEEZING                             111
#define TSURE_POKE_RHYHORN                             112
#define TSURE_POKE_RHYDON                              113
#define TSURE_POKE_CHANSEY                             114
#define TSURE_POKE_TANGELA                             115
#define TSURE_POKE_KANGASKHAN                          116
#define TSURE_POKE_HORSEA                              117
#define TSURE_POKE_SEADRA                              118
#define TSURE_POKE_GOLDEEN                             119
#define TSURE_POKE_SEAKING                             120
#define TSURE_POKE_STARYU                              121
#define TSURE_POKE_STARMIE                             122
#define TSURE_POKE_MR_MIME                             123
#define TSURE_POKE_SCYTHER                             124
#define TSURE_POKE_JYNX                                125
#define TSURE_POKE_ELECTABUZZ                          126
#define TSURE_POKE_MAGMAR                              127
#define TSURE_POKE_PINSIR                              128
#define TSURE_POKE_TAUROS                              129
#define TSURE_POKE_MAGIKARP                            130
#define TSURE_POKE_GYARADOS                            131
#define TSURE_POKE_LAPRAS                              132
#define TSURE_POKE_DITTO                               133
#define TSURE_POKE_EEVEE                               134
#define TSURE_POKE_VAPOREON                            135
#define TSURE_POKE_JOLTEON                             136
#define TSURE_POKE_FLAREON                             137
#define TSURE_POKE_PORYGON                             138
#define TSURE_POKE_OMANYTE                             139
#define TSURE_POKE_OMASTAR                             140
#define TSURE_POKE_KABUTO                              141
#define TSURE_POKE_KABUTOPS                            142
#define TSURE_POKE_AERODACTYL                          143
#define TSURE_POKE_SNORLAX                             144
#define TSURE_POKE_ARTICUNO                            145
#define TSURE_POKE_ZAPDOS                              146
#define TSURE_POKE_MOLTRES                             147
#define TSURE_POKE_DRATINI                             148
#define TSURE_POKE_DRAGONAIR                           149
#define TSURE_POKE_DRAGONITE                           150
#define TSURE_POKE_MEWTWO                              151
#define TSURE_POKE_MEW                                 152
#define TSURE_POKE_CHIKORITA                           153
#define TSURE_POKE_BAYLEEF                             154
#define TSURE_POKE_MEGANIUM                            155
#define TSURE_POKE_MEGANIUM_F                          156
#define TSURE_POKE_CYNDAQUIL                           157
#define TSURE_POKE_QUILAVA                             158
#define TSURE_POKE_TYPHLOSION                          159
#define TSURE_POKE_TOTODILE                            160
#define TSURE_POKE_CROCONAW                            161
#define TSURE_POKE_FERALIGATR                          162
#define TSURE_POKE_SENTRET                             163
#define TSURE_POKE_FURRET                              164
#define TSURE_POKE_HOOTHOOT                            165
#define TSURE_POKE_NOCTOWL                             166
#define TSURE_POKE_LEDYBA                              167
#define TSURE_POKE_LEDIAN                              168
#define TSURE_POKE_SPINARAK                            169
#define TSURE_POKE_ARIADOS                             170
#define TSURE_POKE_CROBAT                              171
#define TSURE_POKE_CHINCHOU                            172
#define TSURE_POKE_LANTURN                             173
#define TSURE_POKE_PICHU                               174
#define TSURE_POKE_PICHU_SPIKY                         175
#define TSURE_POKE_CLEFFA                              176
#define TSURE_POKE_IGGLYBUFF                           177
#define TSURE_POKE_TOGEPI                              178
#define TSURE_POKE_TOGETIC                             179
#define TSURE_POKE_NATU                                180
#define TSURE_POKE_XATU                                181
#define TSURE_POKE_MAREEP                              182
#define TSURE_POKE_FLAAFFY                             183
#define TSURE_POKE_AMPHAROS                            184
#define TSURE_POKE_BELLOSSOM                           185
#define TSURE_POKE_MARILL                              186
#define TSURE_POKE_AZUMARILL                           187
#define TSURE_POKE_SUDOWOODO                           188
#define TSURE_POKE_POLITOED                            189
#define TSURE_POKE_HOPPIP                              190
#define TSURE_POKE_SKIPLOOM                            191
#define TSURE_POKE_JUMPLUFF                            192
#define TSURE_POKE_AIPOM                               193
#define TSURE_POKE_SUNKERN                             194
#define TSURE_POKE_SUNFLORA                            195
#define TSURE_POKE_YANMA                               196
#define TSURE_POKE_WOOPER                              197
#define TSURE_POKE_QUAGSIRE                            198
#define TSURE_POKE_ESPEON                              199
#define TSURE_POKE_UMBREON                             200
#define TSURE_POKE_MURKROW                             201
#define TSURE_POKE_SLOWKING                            202
#define TSURE_POKE_MISDREAVUS                          203
#define TSURE_POKE_UNOWN_A                             204
#define TSURE_POKE_UNOWN_B                             205
#define TSURE_POKE_UNOWN_C                             206
#define TSURE_POKE_UNOWN_D                             207
#define TSURE_POKE_UNOWN_E                             208
#define TSURE_POKE_UNOWN_F                             209
#define TSURE_POKE_UNOWN_G                             210
#define TSURE_POKE_UNOWN_H                             211
#define TSURE_POKE_UNOWN_I                             212
#define TSURE_POKE_UNOWN_J                             213
#define TSURE_POKE_UNOWN_K                             214
#define TSURE_POKE_UNOWN_L                             215
#define TSURE_POKE_UNOWN_M                             216
#define TSURE_POKE_UNOWN_N                             217
#define TSURE_POKE_UNOWN_O                             218
#define TSURE_POKE_UNOWN_P                             219
#define TSURE_POKE_UNOWN_Q                             220
#define TSURE_POKE_UNOWN_R                             221
#define TSURE_POKE_UNOWN_S                             222
#define TSURE_POKE_UNOWN_T                             223
#define TSURE_POKE_UNOWN_U                             224
#define TSURE_POKE_UNOWN_V                             225
#define TSURE_POKE_UNOWN_W                             226
#define TSURE_POKE_UNOWN_X                             227
#define TSURE_POKE_UNOWN_Y                             228
#define TSURE_POKE_UNOWN_Z                             229
#define TSURE_POKE_UNOWN_QMARK                         230
#define TSURE_POKE_UNOWN_EXCL                          231
#define TSURE_POKE_WOBBUFFET                           232
#define TSURE_POKE_WOBBUFFET_F                         233
#define TSURE_POKE_GIRAFARIG                           234
#define TSURE_POKE_PINECO                              235
#define TSURE_POKE_FORRETRESS                          236
#define TSURE_POKE_DUNSPARCE                           237
#define TSURE_POKE_GLIGAR                              238
#define TSURE_POKE_STEELIX                             239
#define TSURE_POKE_STEELIX_F                           240
#define TSURE_POKE_SNUBBULL                            241
#define TSURE_POKE_GRANBULL                            242
#define TSURE_POKE_QWILFISH                            243
#define TSURE_POKE_SCIZOR                              244
#define TSURE_POKE_SHUCKLE                             245
#define TSURE_POKE_HERACROSS                           246
#define TSURE_POKE_HERACROSS_F                         247
#define TSURE_POKE_SNEASEL                             248
#define TSURE_POKE_TEDDIURSA                           249
#define TSURE_POKE_URSARING                            250
#define TSURE_POKE_SLUGMA                              251
#define TSURE_POKE_MAGCARGO                            252
#define TSURE_POKE_SWINUB                              253
#define TSURE_POKE_PILOSWINE                           254
#define TSURE_POKE_CORSOLA                             255
#define TSURE_POKE_REMORAID                            256
#define TSURE_POKE_OCTILLERY                           257
#define TSURE_POKE_DELIBIRD                            258
#define TSURE_POKE_MANTINE                             259
#define TSURE_POKE_SKARMORY                            260
#define TSURE_POKE_HOUNDOUR                            261
#define TSURE_POKE_HOUNDOOM                            262
#define TSURE_POKE_KINGDRA                             263
#define TSURE_POKE_PHANPY                              264
#define TSURE_POKE_DONPHAN                             265
#define TSURE_POKE_PORYGON2                            266
#define TSURE_POKE_STANTLER                            267
#define TSURE_POKE_SMEARGLE                            268
#define TSURE_POKE_TYROGUE                             269
#define TSURE_POKE_HITMONTOP                           270
#define TSURE_POKE_SMOOCHUM                            271
#define TSURE_POKE_ELEKID                              272
#define TSURE_POKE_MAGBY                               273
#define TSURE_POKE_MILTANK                             274
#define TSURE_POKE_BLISSEY                             275
#define TSURE_POKE_RAIKOU                              276
#define TSURE_POKE_ENTEI                               277
#define TSURE_POKE_SUICUNE                             278
#define TSURE_POKE_LARVITAR                            279
#define TSURE_POKE_PUPITAR                             280
#define TSURE_POKE_TYRANITAR                           281
#define TSURE_POKE_LUGIA                               282
#define TSURE_POKE_HO_OH                               283
#define TSURE_POKE_CELEBI                              284
#define TSURE_POKE_TREECKO                             285
#define TSURE_POKE_GROVYLE                             286
#define TSURE_POKE_SCEPTILE                            287
#define TSURE_POKE_TORCHIC                             288
#define TSURE_POKE_COMBUSKEN                           289
#define TSURE_POKE_BLAZIKEN                            290
#define TSURE_POKE_MUDKIP                              291
#define TSURE_POKE_MARSHTOMP                           292
#define TSURE_POKE_SWAMPERT                            293
#define TSURE_POKE_POOCHYENA                           294
#define TSURE_POKE_MIGHTYENA                           295
#define TSURE_POKE_ZIGZAGOON                           296
#define TSURE_POKE_LINOONE                             297
#define TSURE_POKE_WURMPLE                             298
#define TSURE_POKE_SILCOON                             299
#define TSURE_POKE_BEAUTIFLY                           300
#define TSURE_POKE_CASCOON                             301
#define TSURE_POKE_DUSTOX                              302
#define TSURE_POKE_LOTAD                               303
#define TSURE_POKE_LOMBRE                              304
#define TSURE_POKE_LUDICOLO                            305
#define TSURE_POKE_SEEDOT                              306
#define TSURE_POKE_NUZLEAF                             307
#define TSURE_POKE_SHIFTRY                             308
#define TSURE_POKE_TAILLOW                             309
#define TSURE_POKE_SWELLOW                             310
#define TSURE_POKE_WINGULL                             311
#define TSURE_POKE_PELIPPER                            312
#define TSURE_POKE_RALTS                               313
#define TSURE_POKE_KIRLIA                              314
#define TSURE_POKE_GARDEVOIR                           315
#define TSURE_POKE_SURSKIT                             316
#define TSURE_POKE_MASQUERAIN                          317
#define TSURE_POKE_SHROOMISH                           318
#define TSURE_POKE_BRELOOM                             319
#define TSURE_POKE_SLAKOTH                             320
#define TSURE_POKE_VIGOROTH                            321
#define TSURE_POKE_SLAKING                             322
#define TSURE_POKE_NINCADA                             323
#define TSURE_POKE_NINJASK                             324
#define TSURE_POKE_SHEDINJA                            325
#define TSURE_POKE_WHISMUR                             326
#define TSURE_POKE_LOUDRED                             327
#define TSURE_POKE_EXPLOUD                             328
#define TSURE_POKE_MAKUHITA                            329
#define TSURE_POKE_HARIYAMA                            330
#define TSURE_POKE_AZURILL                             331
#define TSURE_POKE_NOSEPASS                            332
#define TSURE_POKE_SKITTY                              333
#define TSURE_POKE_DELCATTY                            334
#define TSURE_POKE_SABLEYE                             335
#define TSURE_POKE_MAWILE                              336
#define TSURE_POKE_ARON                                337
#define TSURE_POKE_LAIRON                              338
#define TSURE_POKE_AGGRON                              339
#define TSURE_POKE_MEDITITE                            340
#define TSURE_POKE_MEDICHAM                            341
#define TSURE_POKE_ELECTRIKE                           342
#define TSURE_POKE_MANECTRIC                           343
#define TSURE_POKE_PLUSLE                              344
#define TSURE_POKE_MINUN                               345
#define TSURE_POKE_VOLBEAT                             346
#define TSURE_POKE_ILLUMISE                            347
#define TSURE_POKE_ROSELIA                             348
#define TSURE_POKE_GULPIN                              349
#define TSURE_POKE_SWALOT                              350
#define TSURE_POKE_CARVANHA                            351
#define TSURE_POKE_SHARPEDO                            352
#define TSURE_POKE_WAILMER                             353
#define TSURE_POKE_WAILORD                             354
#define TSURE_POKE_NUMEL                               355
#define TSURE_POKE_CAMERUPT                            356
#define TSURE_POKE_TORKOAL                             357
#define TSURE_POKE_SPOINK                              358
#define TSURE_POKE_GRUMPIG                             359
#define TSURE_POKE_SPINDA                              360
#define TSURE_POKE_TRAPINCH                            361
#define TSURE_POKE_VIBRAVA                             362
#define TSURE_POKE_FLYGON                              363
#define TSURE_POKE_CACNEA                              364
#define TSURE_POKE_CACTURNE                            365
#define TSURE_POKE_SWABLU                              366
#define TSURE_POKE_ALTARIA                             367
#define TSURE_POKE_ZANGOOSE                            368
#define TSURE_POKE_SEVIPER                             369
#define TSURE_POKE_LUNATONE                            370
#define TSURE_POKE_SOLROCK                             371
#define TSURE_POKE_BARBOACH                            372
#define TSURE_POKE_WHISCASH                            373
#define TSURE_POKE_CORPHISH                            374
#define TSURE_POKE_CRAWDAUNT                           375
#define TSURE_POKE_BALTOY                              376
#define TSURE_POKE_CLAYDOL                             377
#define TSURE_POKE_LILEEP                              378
#define TSURE_POKE_CRADILY                             379
#define TSURE_POKE_ANORITH                             380
#define TSURE_POKE_ARMALDO                             381
#define TSURE_POKE_FEEBAS                              382
#define TSURE_POKE_MILOTIC                             383
#define TSURE_POKE_CASTFORM                            384
#define TSURE_POKE_KECLEON                             385
#define TSURE_POKE_SHUPPET                             386
#define TSURE_POKE_BANETTE                             387
#define TSURE_POKE_DUSKULL                             388
#define TSURE_POKE_DUSCLOPS                            389
#define TSURE_POKE_TROPIUS                             390
#define TSURE_POKE_CHIMECHO                            391
#define TSURE_POKE_ABSOL                               392
#define TSURE_POKE_WYNAUT                              393
#define TSURE_POKE_SNORUNT                             394
#define TSURE_POKE_GLALIE                              395
#define TSURE_POKE_SPHEAL                              396
#define TSURE_POKE_SEALEO                              397
#define TSURE_POKE_WALREIN                             398
#define TSURE_POKE_CLAMPERL                            399
#define TSURE_POKE_HUNTAIL                             400
#define TSURE_POKE_GOREBYSS                            401
#define TSURE_POKE_RELICANTH                           402
#define TSURE_POKE_LUVDISC                             403
#define TSURE_POKE_BAGON                               404
#define TSURE_POKE_SHELGON                             405
#define TSURE_POKE_SALAMENCE                           406
#define TSURE_POKE_BELDUM                              407
#define TSURE_POKE_METANG                              408
#define TSURE_POKE_METAGROSS                           409
#define TSURE_POKE_REGIROCK                            410
#define TSURE_POKE_REGICE                              411
#define TSURE_POKE_REGISTEEL                           412
#define TSURE_POKE_LATIAS                              413
#define TSURE_POKE_LATIOS                              414
#define TSURE_POKE_KYOGRE                              415
#define TSURE_POKE_GROUDON                             416
#define TSURE_POKE_RAYQUAZA                            417
#define TSURE_POKE_JIRACHI                             418
#define TSURE_POKE_DEOXYS                              419
#define TSURE_POKE_DEOXYS_ATK                          420
#define TSURE_POKE_DEOXYS_DEF                          421
#define TSURE_POKE_DEOXYS_SPD                          422
#define TSURE_POKE_TURTWIG                             423
#define TSURE_POKE_GROTLE                              424
#define TSURE_POKE_TORTERRA                            425
#define TSURE_POKE_CHIMCHAR                            426
#define TSURE_POKE_MONFERNO                            427
#define TSURE_POKE_INFERNAPE                           428
#define TSURE_POKE_PIPLUP                              429
#define TSURE_POKE_PRINPLUP                            430
#define TSURE_POKE_EMPOLEON                            431
#define TSURE_POKE_STARLY                              432
#define TSURE_POKE_STARAVIA                            433
#define TSURE_POKE_STARAPTOR                           434
#define TSURE_POKE_BIDOOF                              435
#define TSURE_POKE_BIBAREL                             436
#define TSURE_POKE_KRICKETOT                           437
#define TSURE_POKE_KRICKETUNE                          438
#define TSURE_POKE_SHINX                               439
#define TSURE_POKE_LUXIO                               440
#define TSURE_POKE_LUXRAY                              441
#define TSURE_POKE_BUDEW                               442
#define TSURE_POKE_ROSERADE                            443
#define TSURE_POKE_CRANIDOS                            444
#define TSURE_POKE_RAMPARDOS                           445
#define TSURE_POKE_SHIELDON                            446
#define TSURE_POKE_BASTIODON                           447
#define TSURE_POKE_BURMY                               448
#define TSURE_POKE_BURMY_SANDY                         449
#define TSURE_POKE_BURMY_TRASH                         450
#define TSURE_POKE_WORMADAM                            451
#define TSURE_POKE_WORMADAM_SANDY                      452
#define TSURE_POKE_WORMADAM_TRASH                      453
#define TSURE_POKE_MOTHIM                              454
#define TSURE_POKE_COMBEE                              455
#define TSURE_POKE_COMBEE_F                            456
#define TSURE_POKE_VESPIQUEN                           457
#define TSURE_POKE_PACHIRISU                           458
#define TSURE_POKE_BUIZEL                              459
#define TSURE_POKE_FLOATZEL                            460
#define TSURE_POKE_CHERUBI                             461
#define TSURE_POKE_CHERRIM                             462
#define TSURE_POKE_SHELLOS_WEST                        463
#define TSURE_POKE_SHELLOS_EAST                        464
#define TSURE_POKE_GASTRODON_WEST                      465
#define TSURE_POKE_GASTRODON_EAST                      466
#define TSURE_POKE_AMBIPOM                             467
#define TSURE_POKE_DRIFLOON                            468
#define TSURE_POKE_DRIFBLIM                            469
#define TSURE_POKE_BUNEARY                             470
#define TSURE_POKE_LOPUNNY                             471
#define TSURE_POKE_MISMAGIUS                           472
#define TSURE_POKE_HONCHKROW                           473
#define TSURE_POKE_GLAMEOW                             474
#define TSURE_POKE_PURUGLY                             475
#define TSURE_POKE_CHINGLING                           476
#define TSURE_POKE_STUNKY                              477
#define TSURE_POKE_SKUNTANK                            478
#define TSURE_POKE_BRONZOR                             479
#define TSURE_POKE_BRONZONG                            480
#define TSURE_POKE_BONSLY                              481
#define TSURE_POKE_MIME_JR                             482
#define TSURE_POKE_HAPPINY                             483
#define TSURE_POKE_CHATOT                              484
#define TSURE_POKE_SPIRITOMB                           485
#define TSURE_POKE_GIBLE                               486
#define TSURE_POKE_GIBLE_F                             487
#define TSURE_POKE_GABITE                              488
#define TSURE_POKE_GABITE_F                            489
#define TSURE_POKE_GARCHOMP                            490
#define TSURE_POKE_GARCHOMP_F                          491
#define TSURE_POKE_MUNCHLAX                            492
#define TSURE_POKE_RIOLU                               493
#define TSURE_POKE_LUCARIO                             494
#define TSURE_POKE_HIPPOPOTAS                          495
#define TSURE_POKE_HIPPOPOTAS_F                        496
#define TSURE_POKE_HIPPOWDON                           497
#define TSURE_POKE_HIPPOWDON_F                         498
#define TSURE_POKE_SKORUPI                             499
#define TSURE_POKE_DRAPION                             500
#define TSURE_POKE_CROAGUNK                            501
#define TSURE_POKE_TOXICROAK                           502
#define TSURE_POKE_CARNIVINE                           503
#define TSURE_POKE_FINNEON                             504
#define TSURE_POKE_LUMINEON                            505
#define TSURE_POKE_MANTYKE                             506
#define TSURE_POKE_SNOVER                              507
#define TSURE_POKE_ABOMASNOW                           508
#define TSURE_POKE_WEAVILE                             509
#define TSURE_POKE_MAGNEZONE                           510
#define TSURE_POKE_LICKILICKY                          511
#define TSURE_POKE_RHYPERIOR                           512
#define TSURE_POKE_TANGROWTH                           513
#define TSURE_POKE_ELECTIVIRE                          514
#define TSURE_POKE_MAGMORTAR                           515
#define TSURE_POKE_TOGEKISS                            516
#define TSURE_POKE_YANMEGA                             517
#define TSURE_POKE_LEAFEON                             518
#define TSURE_POKE_GLACEON                             519
#define TSURE_POKE_GLISCOR                             520
#define TSURE_POKE_MAMOSWINE                           521
#define TSURE_POKE_PORYGON_Z                           522
#define TSURE_POKE_GALLADE                             523
#define TSURE_POKE_PROBOPASS                           524
#define TSURE_POKE_DUSKNOIR                            525
#define TSURE_POKE_FROSLASS                            526
#define TSURE_POKE_ROTOM                               527
#define TSURE_POKE_ROTOM_HEAT                          528
#define TSURE_POKE_ROTOM_WASH                          529
#define TSURE_POKE_ROTOM_FROST                         530
#define TSURE_POKE_ROTOM_FAN                           531
#define TSURE_POKE_ROTOM_MOW                           532
#define TSURE_POKE_UXIE                                533
#define TSURE_POKE_MESPRIT                             534
#define TSURE_POKE_AZELF                               535
#define TSURE_POKE_DIALGA                              536
#define TSURE_POKE_PALKIA                              537
#define TSURE_POKE_HEATRAN                             538
#define TSURE_POKE_REGIGIGAS                           539
#define TSURE_POKE_GIRATINA                            540
#define TSURE_POKE_GIRATINA_ORIGIN                     541
#define TSURE_POKE_CRESSELIA                           542
#define TSURE_POKE_PHIONE                              543
#define TSURE_POKE_MANAPHY                             544
#define TSURE_POKE_DARKRAI                             545
#define TSURE_POKE_SHAYMIN                             546
#define TSURE_POKE_SHAYMIN_SKY                         547
#define TSURE_POKE_ARCEUS_NORMAL                       548
#define TSURE_POKE_ARCEUS_FIGHTING                     549
#define TSURE_POKE_ARCEUS_FLYING                       550
#define TSURE_POKE_ARCEUS_POISON                       551
#define TSURE_POKE_ARCEUS_GROUND                       552
#define TSURE_POKE_ARCEUS_ROCK                         553
#define TSURE_POKE_ARCEUS_BUG                          554
#define TSURE_POKE_ARCEUS_GHOST                        555
#define TSURE_POKE_ARCEUS_STEEL                        556
#define TSURE_POKE_ARCEUS_MYSTERY                      557
#define TSURE_POKE_ARCEUS_FIRE                         558
#define TSURE_POKE_ARCEUS_WATER                        559
#define TSURE_POKE_ARCEUS_GRASS                        560
#define TSURE_POKE_ARCEUS_ELECTRIC                     561
#define TSURE_POKE_ARCEUS_PSYCHIC                      562
#define TSURE_POKE_ARCEUS_ICE                          563
#define TSURE_POKE_ARCEUS_DRAGON                       564
#define TSURE_POKE_ARCEUS_DARK                         565

#endif //POKEHEARTGOLD_FOLLOW_POKE_IDX_H
