#ifndef GUARD_POKEHEARTGOLD_CONSTANTS_GEONET_GLOBE_H
#define GUARD_POKEHEARTGOLD_CONSTANTS_GEONET_GLOBE_H

#define COUNTRY_NONE                               0
#define COUNTRY_AFGHANISTAN                        1
#define COUNTRY_ALBANIA                            2
#define COUNTRY_ALGERIA                            3
#define COUNTRY_AMERICAN_SAMOA                     4
#define COUNTRY_ANDORRA                            5
#define COUNTRY_ANGOLA                             6
#define COUNTRY_ANGUILLA                           7
#define COUNTRY_ANTIGUA_AND_BARBUDA                8
#define COUNTRY_ARGENTINA                          9
#define COUNTRY_ARMENIA                            10
#define COUNTRY_ARUBA                              11
#define COUNTRY_AUSTRALIA                          12
#define COUNTRY_AUSTRIA                            13
#define COUNTRY_AZERBAIJAN                         14
#define COUNTRY_BAHAMAS                            15
#define COUNTRY_BAHRAIN                            16
#define COUNTRY_BANGLADESH                         17
#define COUNTRY_BARBADOS                           18
#define COUNTRY_BELARUS                            19
#define COUNTRY_BELGIUM                            20
#define COUNTRY_BELIZE                             21
#define COUNTRY_BENIN                              22
#define COUNTRY_BERMUDA                            23
#define COUNTRY_BHUTAN                             24
#define COUNTRY_BOLIVIA                            25
#define COUNTRY_BOSNIA_AND_HERZEGOVINA             26
#define COUNTRY_BOTSWANA                           27
#define COUNTRY_BRAZIL                             28
#define COUNTRY_BRITISH_VIRGIN_ISLANDS             29
#define COUNTRY_BRUNEI_DARUSSALAM                  30
#define COUNTRY_BULGARIA                           31
#define COUNTRY_BURKINA_FASO                       32
#define COUNTRY_BURUNDI                            33
#define COUNTRY_CAMBODIA                           34
#define COUNTRY_CAMEROON                           35
#define COUNTRY_CANADA                             36
#define COUNTRY_CAPE_VERDE                         37
#define COUNTRY_CAYMAN_ISLANDS                     38
#define COUNTRY_CENTRAL_AFRICAN_REPUBLIC           39
#define COUNTRY_CHAD                               40
#define COUNTRY_CHANNEL_ISLANDS                    41
#define COUNTRY_CHILE                              42
#define COUNTRY_CHINA                              43
#define COUNTRY_CHRISTMAS_ISLAND                   44
#define COUNTRY_COLOMBIA                           45
#define COUNTRY_COMOROS                            46
#define COUNTRY_DEMOCRATIC_REPUBLIC_OF_THE_CONGO   47
#define COUNTRY_CONGO                              48
#define COUNTRY_COOK_ISLANDS                       49
#define COUNTRY_COSTA_RICA                         50
#define COUNTRY_COTE_D_IVOIRE                      51
#define COUNTRY_CROATIA                            52
#define COUNTRY_CUBA                               53
#define COUNTRY_CYPRUS                             54
#define COUNTRY_CZECH_REPUBLIC                     55
#define COUNTRY_DENMARK                            56
#define COUNTRY_DJIBOUTI                           57
#define COUNTRY_DOMINICA                           58
#define COUNTRY_DOMINICAN_REPUBLIC                 59
#define COUNTRY_ECUADOR                            60
#define COUNTRY_EGYPT                              61
#define COUNTRY_EL_SALVADOR                        62
#define COUNTRY_EQUATORIAL_GUINEA                  63
#define COUNTRY_ERITREA                            64
#define COUNTRY_ESTONIA                            65
#define COUNTRY_ETHIOPIA                           66
#define COUNTRY_FAROE_ISLANDS                      67
#define COUNTRY_FALKLAND_ISLANDS                   68
#define COUNTRY_FIJI                               69
#define COUNTRY_FINLAND                            70
#define COUNTRY_FRANCE                             71
#define COUNTRY_FRENCH_GUIANA                      72
#define COUNTRY_FRENCH_POLYNESIA                   73
#define COUNTRY_GABON                              74
#define COUNTRY_GAMBIA                             75
#define COUNTRY_GEORGIA                            76
#define COUNTRY_GERMANY                            77
#define COUNTRY_GHANA                              78
#define COUNTRY_GIBRALTAR                          79
#define COUNTRY_GREECE                             80
#define COUNTRY_GREENLAND                          81
#define COUNTRY_GRENADA                            82
#define COUNTRY_GUADELOUPE                         83
#define COUNTRY_GUAM                               84
#define COUNTRY_GUATEMALA                          85
#define COUNTRY_GUINEA                             86
#define COUNTRY_GUINEA_BISSAU                      87
#define COUNTRY_GUYANA                             88
#define COUNTRY_HAITI                              89
#define COUNTRY_HONDURAS                           90
#define COUNTRY_HONG_KONG                          91
#define COUNTRY_HUNGARY                            92
#define COUNTRY_ICELAND                            93
#define COUNTRY_INDIA                              94
#define COUNTRY_INDONESIA                          95
#define COUNTRY_IRAN                               96
#define COUNTRY_IRAQ                               97
#define COUNTRY_IRELAND                            98
#define COUNTRY_ISLE_OF_MAN_                       99
#define COUNTRY_ISRAEL                             100
#define COUNTRY_ITALY                              101
#define COUNTRY_JAMAICA                            102
#define COUNTRY_JAPAN                              103
#define COUNTRY_JORDAN                             104
#define COUNTRY_KASHMIR                            105
#define COUNTRY_KAZAKHSTAN                         106
#define COUNTRY_KENYA                              107
#define COUNTRY_KIRIBATI                           108
#define COUNTRY_D_P__REPUBLIC_OF_KOREA             109
#define COUNTRY_REPUBLIC_OF_KOREA                  110
#define COUNTRY_KUWAIT                             111
#define COUNTRY_KYRGYZSTAN                         112
#define COUNTRY_LAO_PEOPLE_S_DEMOCRATIC_REPUBLIC   113
#define COUNTRY_LATVIA                             114
#define COUNTRY_LEBANON                            115
#define COUNTRY_LESOTHO                            116
#define COUNTRY_LIBERIA                            117
#define COUNTRY_LIBYAN_ARAB_JAMAHIRIYA             118
#define COUNTRY_LIECHTENSTEIN                      119
#define COUNTRY_LITHUANIA                          120
#define COUNTRY_LUXEMBOURG                         121
#define COUNTRY_MACAU                              122
#define COUNTRY_MACEDONIA__FYROM_                  123
#define COUNTRY_MADAGASCAR                         124
#define COUNTRY_MALAWI                             125
#define COUNTRY_MALAYSIA                           126
#define COUNTRY_MALDIVES                           127
#define COUNTRY_MALI                               128
#define COUNTRY_MALTA                              129
#define COUNTRY_MARSHALL_ISLANDS                   130
#define COUNTRY_MARTINIQUE                         131
#define COUNTRY_MAURITANIA                         132
#define COUNTRY_MAURITIUS                          133
#define COUNTRY_MAYOTTE                            134
#define COUNTRY_MEXICO                             135
#define COUNTRY_MICRONESIA                         136
#define COUNTRY_REPUBLIC_OF_MOLDOVA                137
#define COUNTRY_MONACO                             138
#define COUNTRY_MONGOLIA                           139
#define COUNTRY_MOROCCO                            140
#define COUNTRY_MOZAMBIQUE                         141
#define COUNTRY_MYANMAR                            142
#define COUNTRY_NAMIBIA                            143
#define COUNTRY_NAURU                              144
#define COUNTRY_NEPAL                              145
#define COUNTRY_NETHERLANDS                        146
#define COUNTRY_NETHERLANDS_ANTILLES               147
#define COUNTRY_NEW_CALEDONIA                      148
#define COUNTRY_NEW_ZEALAND                        149
#define COUNTRY_NICARAGUA                          150
#define COUNTRY_NIGER                              151
#define COUNTRY_NIGERIA                            152
#define COUNTRY_NIUE                               153
#define COUNTRY_NORFOLK_ISLAND                     154
#define COUNTRY_NORTHERN_MARIANA_ISLANDS           155
#define COUNTRY_NORWAY                             156
#define COUNTRY_OMAN                               157
#define COUNTRY_PAKISTAN                           158
#define COUNTRY_PALAU                              159
#define COUNTRY_PANAMA                             160
#define COUNTRY_PAPUA_NEW_GUINEA                   161
#define COUNTRY_PARAGUAY                           162
#define COUNTRY_PERU                               163
#define COUNTRY_PHILIPPINES                        164
#define COUNTRY_PITCAIRN_ISLANDS                   165
#define COUNTRY_POLAND                             166
#define COUNTRY_PORTUGAL                           167
#define COUNTRY_PUERTO_RICO                        168
#define COUNTRY_QATAR                              169
#define COUNTRY_REUNION                            170
#define COUNTRY_ROMANIA                            171
#define COUNTRY_RUSSIAN_FEDERATION                 172
#define COUNTRY_RWANDA                             173
#define COUNTRY_SAINT_HELENA                       174
#define COUNTRY_SAINT_KITTS_AND_NEVIS              175
#define COUNTRY_SAINT_LUCIA                        176
#define COUNTRY_SAINT_PIERRE_AND_MIQUELON          177
#define COUNTRY_SAINT_VINCENT_AND_THE_GRENADINES   178
#define COUNTRY_SAMOA                              179
#define COUNTRY_SAN_MARINO                         180
#define COUNTRY_SAO_TOME_AND_PRINCIPE              181
#define COUNTRY_SAUDI_ARABIA                       182
#define COUNTRY_SENEGAL                            183
#define COUNTRY_SERBIA_AND_MONTENEGRO              184
#define COUNTRY_SEYCHELLES                         185
#define COUNTRY_SIERRA_LEONE                       186
#define COUNTRY_SINGAPORE                          187
#define COUNTRY_SLOVAKIA                           188
#define COUNTRY_SLOVENIA                           189
#define COUNTRY_SOLOMON_ISLANDS                    190
#define COUNTRY_SOMALIA                            191
#define COUNTRY_SOUTH_AFRICA                       192
#define COUNTRY_SPAIN                              193
#define COUNTRY_SRI_LANKA                          194
#define COUNTRY_SUDAN                              195
#define COUNTRY_SURINAME                           196
#define COUNTRY_JAN_MAYEN_ISLAND                   197
#define COUNTRY_SWAZILAND                          198
#define COUNTRY_SWEDEN                             199
#define COUNTRY_SWISS_CONFEDERATION                200
#define COUNTRY_SYRIAN_ARAB_REPUBLIC               201
#define COUNTRY_TAIWAN                             202
#define COUNTRY_TAJIKISTAN                         203
#define COUNTRY_UNITED_REPUBLIC_OF_TANZANIA        204
#define COUNTRY_THAILAND                           205
#define COUNTRY_DEMOCRATIC_REPUBLIC_OF_TIMOR_LESTE 206
#define COUNTRY_TOGO                               207
#define COUNTRY_TOKELAU                            208
#define COUNTRY_TONGA                              209
#define COUNTRY_TRINIDAD_AND_TOBAGO                210
#define COUNTRY_TUNISIA                            211
#define COUNTRY_TURKEY                             212
#define COUNTRY_TURKMENISTAN                       213
#define COUNTRY_TURKS_AND_CAICOS_ISLANDS           214
#define COUNTRY_TUVALU                             215
#define COUNTRY_UGANDA                             216
#define COUNTRY_UKRAINE                            217
#define COUNTRY_UNITED_ARAB_EMIRATES               218
#define COUNTRY_UNITED_KINGDOM                     219
#define COUNTRY_UNITED_STATES_OF_AMERICA           220
#define COUNTRY_UNITED_STATES_VIRGIN_ISLANDS       221
#define COUNTRY_URUGUAY                            222
#define COUNTRY_UZBEKISTAN                         223
#define COUNTRY_VANUATU                            224
#define COUNTRY_VATICAN_CITY                       225
#define COUNTRY_VENEZUELA                          226
#define COUNTRY_VIETNAM                            227
#define COUNTRY_WALLIS_AND_FUTUNA                  228
#define COUNTRY_PALESTINE                          229
#define COUNTRY_WESTERN_SAHARA                     230
#define COUNTRY_YEMEN                              231
#define COUNTRY_ZAMBIA                             232
#define COUNTRY_ZIMBABWE                           233
#define COUNTRY_COUNT                              234

#define STATE_ARGENTINA_NONE                             0
#define STATE_ARGENTINA_BUENOS_AIRES                     1
#define STATE_ARGENTINA_CIUDAD_AUTONOMA_DE_BUENOS_AIRES_ 2
#define STATE_ARGENTINA_CATAMARCA                        3
#define STATE_ARGENTINA_CHACO                            4
#define STATE_ARGENTINA_CHUBUT                           5
#define STATE_ARGENTINA_CORDOBA                          6
#define STATE_ARGENTINA_CORRIENTES                       7
#define STATE_ARGENTINA_ENTRE_RIOS                       8
#define STATE_ARGENTINA_FORMOSA                          9
#define STATE_ARGENTINA_JUJUY                            10
#define STATE_ARGENTINA_LA_PAMPA                         11
#define STATE_ARGENTINA_LA_RIOJA                         12
#define STATE_ARGENTINA_MENDOZA                          13
#define STATE_ARGENTINA_MISIONES                         14
#define STATE_ARGENTINA_NEUQUEN                          15
#define STATE_ARGENTINA_RIO_NEGRO                        16
#define STATE_ARGENTINA_SALTA                            17
#define STATE_ARGENTINA_SAN_JUAN                         18
#define STATE_ARGENTINA_SAN_LUIS                         19
#define STATE_ARGENTINA_SANTA_CRUZ                       20
#define STATE_ARGENTINA_SANTA_FE                         21
#define STATE_ARGENTINA_SANTIAGO_DEL_ESTERO              22
#define STATE_ARGENTINA_TIERRA_DEL_FUEGO                 23
#define STATE_ARGENTINA_TUCMAN                           24
#define STATE_ARGENTINA_COUNT                            25

#define STATE_AUSTRALIA_NONE              0
#define STATE_AUSTRALIA_NEW_SOUTH_WALES   1
#define STATE_AUSTRALIA_NORTH             2
#define STATE_AUSTRALIA_QUEENSLAND        3
#define STATE_AUSTRALIA_SOUTH_AUSTRALIA   4
#define STATE_AUSTRALIA_TASMANIA          5
#define STATE_AUSTRALIA_VICTORIA          6
#define STATE_AUSTRALIA_WESTERN_AUSTRALIA 7
#define STATE_AUSTRALIA_COUNT             8

#define STATE_BRAZIL_NONE                0
#define STATE_BRAZIL_ACRE                1
#define STATE_BRAZIL_RONDONIA            2
#define STATE_BRAZIL_ALAGOAS             3
#define STATE_BRAZIL_AMAPA               4
#define STATE_BRAZIL_AMAZONAS            5
#define STATE_BRAZIL_BAHIA               6
#define STATE_BRAZIL_CEARA               7
#define STATE_BRAZIL_DISTRITO_FEDERAL    8
#define STATE_BRAZIL_ESPIRITO_SANTO      9
#define STATE_BRAZIL_GOIAS               10
#define STATE_BRAZIL_MARANHAO            11
#define STATE_BRAZIL_MATO_GROSSO         12
#define STATE_BRAZIL_MATO_GROSSO_DO_SUL  13
#define STATE_BRAZIL_MINAS_GERAIS        14
#define STATE_BRAZIL_PARA                15
#define STATE_BRAZIL_PARAIBA             16
#define STATE_BRAZIL_PARANA              17
#define STATE_BRAZIL_PERNAMBUCO          18
#define STATE_BRAZIL_PIAUI               19
#define STATE_BRAZIL_RIO_DE_JANEIRO      20
#define STATE_BRAZIL_RIO_GRANDE_DO_SUL   21
#define STATE_BRAZIL_RIO_GRANDE_DO_NORTE 22
#define STATE_BRAZIL_RORAIMA             23
#define STATE_BRAZIL_SANTA_CATARINA      24
#define STATE_BRAZIL_SAO_PAULO           25
#define STATE_BRAZIL_SERGIPE             26
#define STATE_BRAZIL_TOCANTINS           27
#define STATE_BRAZIL_COUNT               28

#define STATE_CANADA_NONE                      0
#define STATE_CANADA_ALBERTA                   1
#define STATE_CANADA_BRITISH_COLUMBIA          2
#define STATE_CANADA_MANITOBA                  3
#define STATE_CANADA_NEW_BRUNSWICK             4
#define STATE_CANADA_NEWFOUNDLAND_AND_LABRADOR 5
#define STATE_CANADA_NORTHWEST_TERRITORIES     6
#define STATE_CANADA_NOVA_SCOTIA               7
#define STATE_CANADA_NUNAVUT                   8
#define STATE_CANADA_ONTARIO                   9
#define STATE_CANADA_PRINCE_EDWARD_ISLAND      10
#define STATE_CANADA_QUEBEC                    11
#define STATE_CANADA_SASKATCHEWAN              12
#define STATE_CANADA_YUKON_TERRITORY           13
#define STATE_CANADA_COUNT                     14

#define STATE_CHINA_NONE         0
#define STATE_CHINA_ANHUI        1
#define STATE_CHINA_BEIJING      2
#define STATE_CHINA_CHONGQING    3
#define STATE_CHINA_FUJIAN       4
#define STATE_CHINA_GANSU        5
#define STATE_CHINA_GUANGDONG    6
#define STATE_CHINA_GUANXI       7
#define STATE_CHINA_GUIZHOU      8
#define STATE_CHINA_HAINAN       9
#define STATE_CHINA_HEBEI        10
#define STATE_CHINA_HEILONGJIANG 11
#define STATE_CHINA_HENAN        12
#define STATE_CHINA_HUBEI        13
#define STATE_CHINA_HUNAN        14
#define STATE_CHINA_JIANGSU      15
#define STATE_CHINA_JIANGXI      16
#define STATE_CHINA_JILIN        17
#define STATE_CHINA_LIAONING     18
#define STATE_CHINA_NEIMENGGU    19
#define STATE_CHINA_NINGXIA      20
#define STATE_CHINA_QINGHAI      21
#define STATE_CHINA_SHAANXI      22
#define STATE_CHINA_SHANDONG     23
#define STATE_CHINA_SHANGHAI     24
#define STATE_CHINA_SHANXI       25
#define STATE_CHINA_SICHUAN      26
#define STATE_CHINA_TIANJIN      27
#define STATE_CHINA_XINJIANG     28
#define STATE_CHINA_XIZANG       29
#define STATE_CHINA_YUNNAN       30
#define STATE_CHINA_ZHEJIANG     31
#define STATE_CHINA_COUNT        32

#define STATE_GERMANY_NONE                   0
#define STATE_GERMANY_BADEN_WURTTEMBERG      1
#define STATE_GERMANY_BAYERN                 2
#define STATE_GERMANY_BERLIN                 3
#define STATE_GERMANY_BRANDENBURG            4
#define STATE_GERMANY_BREMEN                 5
#define STATE_GERMANY_HAMBURG                6
#define STATE_GERMANY_HESSEN                 7
#define STATE_GERMANY_MECKLENBURG_VORPOMMERN 8
#define STATE_GERMANY_NIEDERSACHSEN          9
#define STATE_GERMANY_NORDRHEIN_WESTFALEN    10
#define STATE_GERMANY_RHEINLAND_PFALZ        11
#define STATE_GERMANY_SAARLAND               12
#define STATE_GERMANY_SACHSEN                13
#define STATE_GERMANY_SACHSEN_ANHALT         14
#define STATE_GERMANY_SCHLESWIG_HOLSTEIN     15
#define STATE_GERMANY_FREISTAAT_THURINGEN    16
#define STATE_GERMANY_COUNT                  17

#define STATE_SPAIN_NONE                  0
#define STATE_SPAIN_ANDALUCIA             1
#define STATE_SPAIN_ARAGON                2
#define STATE_SPAIN_ASTURIAS_             3
#define STATE_SPAIN_ISLAS_BALEARES        4
#define STATE_SPAIN_PAIS_VASCO            5
#define STATE_SPAIN_ISLAS_CANARIAS        6
#define STATE_SPAIN_CANTABRIA             7
#define STATE_SPAIN_CASTILLA_LA_MANCHA    8
#define STATE_SPAIN_CASTILLA_LEON         9
#define STATE_SPAIN_CATALUNA              10
#define STATE_SPAIN_EXTREMADURA           11
#define STATE_SPAIN_GALICIA               12
#define STATE_SPAIN_MADRID                13
#define STATE_SPAIN_MURCIA                14
#define STATE_SPAIN_NAVARRA               15
#define STATE_SPAIN_LA_RIOJA              16
#define STATE_SPAIN_COMUNIDAD_VALENCIANA_ 17
#define STATE_SPAIN_COUNT                 18

#define STATE_FINLAND_NONE          0
#define STATE_FINLAND_ALAND_ISLANDS 1
#define STATE_FINLAND_LAPLAND       2
#define STATE_FINLAND_EAST_FINLAND  3
#define STATE_FINLAND_SOUTH_FINLAND 4
#define STATE_FINLAND_OULUN         5
#define STATE_FINLAND_WEST_FINLAND  6
#define STATE_FINLAND_COUNT         7

#define STATE_FRANCE_NONE                 0
#define STATE_FRANCE_AQUITAINE            1
#define STATE_FRANCE_ALSACE               2
#define STATE_FRANCE_ILE_DE_FRANCE        3
#define STATE_FRANCE_AUVERGNE             4
#define STATE_FRANCE_COTE_D_AZUR          5
#define STATE_FRANCE_CORSE                6
#define STATE_FRANCE_CHAMPAGNE_ARDENNE    7
#define STATE_FRANCE_NORD_PAS_DE_CALAIS   8
#define STATE_FRANCE_NORMANDIE            9
#define STATE_FRANCE_PICARDIE             10
#define STATE_FRANCE_FRANCHE_COMTE        11
#define STATE_FRANCE_BOURGOGNE            12
#define STATE_FRANCE_BRETAGNE             13
#define STATE_FRANCE_PROVENCE             14
#define STATE_FRANCE_PAYS_DE_LA_LOIRE     15
#define STATE_FRANCE_POITOU_CHARENTES     16
#define STATE_FRANCE_MIDI_PYRENEES        17
#define STATE_FRANCE_LANGUEDOC_ROUSSILLON 18
#define STATE_FRANCE_LIMOUSIN             19
#define STATE_FRANCE_RHONE_ALPES          20
#define STATE_FRANCE_LORRAINE             21
#define STATE_FRANCE_LOIRE                22
#define STATE_FRANCE_COUNT                23

#define STATE_UNITED_KINGDOM_NONE                     0
#define STATE_UNITED_KINGDOM_EAST_OF_ENGLAND          1
#define STATE_UNITED_KINGDOM_EAST_MIDLANDS            2
#define STATE_UNITED_KINGDOM_GREATER_LONDON           3
#define STATE_UNITED_KINGDOM_NORTH_EAST_ENGLAND       4
#define STATE_UNITED_KINGDOM_NORTH_WEST_ENGLAND       5
#define STATE_UNITED_KINGDOM_NORTHERN_IRELAND         6
#define STATE_UNITED_KINGDOM_SCOTLAND                 7
#define STATE_UNITED_KINGDOM_SOUTH_EAST_ENGLAND       8
#define STATE_UNITED_KINGDOM_SOUTH_WEST_ENGLAND       9
#define STATE_UNITED_KINGDOM_WALES                    10
#define STATE_UNITED_KINGDOM_WEST_MIDLANDS            11
#define STATE_UNITED_KINGDOM_YORKSHIRE_AND_THE_HUMBER 12
#define STATE_UNITED_KINGDOM_COUNT                    13

#define STATE_INDIA_NONE                        0
#define STATE_INDIA_ANDAMAN_AND_NICOBAR_ISLANDS 1
#define STATE_INDIA_ANDHRA_PRADESH_             2
#define STATE_INDIA_ARUNACHAL_PRADESH           3
#define STATE_INDIA_ASSAM                       4
#define STATE_INDIA_BIHAR                       5
#define STATE_INDIA_CHANDIGARH                  6
#define STATE_INDIA_CHHATTISGARH                7
#define STATE_INDIA_DADRA_AND_NAGAR_HAVELI      8
#define STATE_INDIA_DAMAN_AND_DIU               9
#define STATE_INDIA_DELHI                       10
#define STATE_INDIA_GOA                         11
#define STATE_INDIA_GUJARAT                     12
#define STATE_INDIA_HARYANA                     13
#define STATE_INDIA_HIMACHAL_PRADESH            14
#define STATE_INDIA_JAMMU_AND_KASHMIR           15
#define STATE_INDIA_JHARKHAND                   16
#define STATE_INDIA_KARNATAKA_                  17
#define STATE_INDIA_KERALA_                     18
#define STATE_INDIA_LAKSHADWEEP                 19
#define STATE_INDIA_MADHYA_PRADESH              20
#define STATE_INDIA_MAHARASHTRA                 21
#define STATE_INDIA_MEGHALAYA                   22
#define STATE_INDIA_MIZORAM                     23
#define STATE_INDIA_MANIPUR                     24
#define STATE_INDIA_NAGALAND                    25
#define STATE_INDIA_ORISSA                      26
#define STATE_INDIA_PUDUCHERRY                  27
#define STATE_INDIA_PUNJAB                      28
#define STATE_INDIA_RAJASTHAN                   29
#define STATE_INDIA_SIKKIM                      30
#define STATE_INDIA_TAMIL_NADU_                 31
#define STATE_INDIA_TRIPURA                     32
#define STATE_INDIA_UTTAR_PRADESH               33
#define STATE_INDIA_UTTARANCHAL                 34
#define STATE_INDIA_WEST_BENGAL                 35
#define STATE_INDIA_COUNT                       36

#define STATE_ITALY_NONE                  0
#define STATE_ITALY_ABRUZZO               1
#define STATE_ITALY_BASILICATA            2
#define STATE_ITALY_CALABRIA              3
#define STATE_ITALY_CAMPANIA              4
#define STATE_ITALY_EMILIA_ROMAGNA        5
#define STATE_ITALY_FRIULI_VENEZIA_GIULIA 6
#define STATE_ITALY_LAZIO                 7
#define STATE_ITALY_LIGURIA               8
#define STATE_ITALY_LOMBARDIA             9
#define STATE_ITALY_MARCHE                10
#define STATE_ITALY_MOLISE                11
#define STATE_ITALY_PIEMONTE              12
#define STATE_ITALY_PUGLIA                13
#define STATE_ITALY_SARDEGNA              14
#define STATE_ITALY_SICILIA               15
#define STATE_ITALY_TOSCANA               16
#define STATE_ITALY_TRENTINO_ALTO_ADIGE   17
#define STATE_ITALY_UMBRIA                18
#define STATE_ITALY_VALLE_D_AOSTA         19
#define STATE_ITALY_VENETO                20
#define STATE_ITALY_COUNT                 21

#define STATE_JAPAN_NONE                0
#define STATE_JAPAN_HOKKAIDO__SAPPORO_  1
#define STATE_JAPAN_HOKKAIDO__HAKODATE_ 2
#define STATE_JAPAN_HOKKAIDO__WAKKANAI_ 3
#define STATE_JAPAN_HOKKAIDO__KUSHIRO_  4
#define STATE_JAPAN_AOMORI              5
#define STATE_JAPAN_IWATE               6
#define STATE_JAPAN_MIYAGI              7
#define STATE_JAPAN_AKITA               8
#define STATE_JAPAN_YAMAGATA            9
#define STATE_JAPAN_FUKUSHIMA           10
#define STATE_JAPAN_IBARAKI             11
#define STATE_JAPAN_TOCHIGI             12
#define STATE_JAPAN_GUNMA               13
#define STATE_JAPAN_SAITAMA             14
#define STATE_JAPAN_CHIBA               15
#define STATE_JAPAN_TOKYO               16
#define STATE_JAPAN_KANAGAWA            17
#define STATE_JAPAN_NIIGATA             18
#define STATE_JAPAN_TOYAMA              19
#define STATE_JAPAN_ISHIKAWA            20
#define STATE_JAPAN_FUKUI               21
#define STATE_JAPAN_YAMANASHI           22
#define STATE_JAPAN_NAGANO              23
#define STATE_JAPAN_GIFU                24
#define STATE_JAPAN_SHIZUOKA            25
#define STATE_JAPAN_AICHI               26
#define STATE_JAPAN_MIE                 27
#define STATE_JAPAN_SHIGA               28
#define STATE_JAPAN_KYOTO               29
#define STATE_JAPAN_OSAKA               30
#define STATE_JAPAN_HYOGO               31
#define STATE_JAPAN_NARA                32
#define STATE_JAPAN_WAKAYAMA            33
#define STATE_JAPAN_TOTTORI             34
#define STATE_JAPAN_SHIMANE             35
#define STATE_JAPAN_OKAYAMA             36
#define STATE_JAPAN_HIROSHIMA           37
#define STATE_JAPAN_YAMAGUCHI           38
#define STATE_JAPAN_TOKUSHIMA           39
#define STATE_JAPAN_KAGAWA              40
#define STATE_JAPAN_EHIME               41
#define STATE_JAPAN_KOCHI               42
#define STATE_JAPAN_FUKUOKA             43
#define STATE_JAPAN_SAGA                44
#define STATE_JAPAN_NAGASAKI            45
#define STATE_JAPAN_KUMAMOTO            46
#define STATE_JAPAN_OITA                47
#define STATE_JAPAN_MIYAZAKI            48
#define STATE_JAPAN_KAGOSHIMA           49
#define STATE_JAPAN_OKINAWA             50
#define STATE_JAPAN_COUNT               51

#define STATE_NORWAY_NONE             0
#define STATE_NORWAY_AKERSHUS         1
#define STATE_NORWAY_AUST_AGDER       2
#define STATE_NORWAY_BUSKERUD         3
#define STATE_NORWAY_FINNMARK         4
#define STATE_NORWAY_HEDMARK          5
#define STATE_NORWAY_HORDALAND        6
#define STATE_NORWAY_LOFOTEN          7
#define STATE_NORWAY_MORE_OG_ROMSDAL  8
#define STATE_NORWAY_NORDLAND         9
#define STATE_NORWAY_NORD_TRONDELAG   10
#define STATE_NORWAY_OPPLAND          11
#define STATE_NORWAY_OSLO             12
#define STATE_NORWAY_ROGALAND         13
#define STATE_NORWAY_SOGN_OG_FJORDANE 14
#define STATE_NORWAY_SOR_TRONDELAG    15
#define STATE_NORWAY_SVALBARD         16
#define STATE_NORWAY_TELEMARK         17
#define STATE_NORWAY_TROMS            18
#define STATE_NORWAY_VEST_AGDER       19
#define STATE_NORWAY_OSTFOLD          20
#define STATE_NORWAY_COUNT            21

#define STATE_POLAND_NONE                0
#define STATE_POLAND_DOLNOSLASKIE        1
#define STATE_POLAND_KUJAWSKO_POMORSKIE  2
#define STATE_POLAND_LUBELSKIE           3
#define STATE_POLAND_LUBUSKIE            4
#define STATE_POLAND_LODZKIE             5
#define STATE_POLAND_MALOPOLSKIE         6
#define STATE_POLAND_MAZOWIECKIE         7
#define STATE_POLAND_OPOLSKIE            8
#define STATE_POLAND_PODKARPACKIE        9
#define STATE_POLAND_PODLASKIE           10
#define STATE_POLAND_POMORSKIE           11
#define STATE_POLAND_SLASKIE             12
#define STATE_POLAND_SWIETOKRZYSKIE      13
#define STATE_POLAND_WARMINSKO_MAZURSKIE 14
#define STATE_POLAND_WIELKOPOLSKIE       15
#define STATE_POLAND_ZACHODNIOPOMORSKIE  16
#define STATE_POLAND_COUNT               17

#define STATE_RUSSIAN_FEDERATION_NONE                          0
#define STATE_RUSSIAN_FEDERATION_CENTRAL_FEDERAL_DISTRICT      1
#define STATE_RUSSIAN_FEDERATION_FAR_EASTERN_FEDERAL_DISTRICT_ 2
#define STATE_RUSSIAN_FEDERATION_NORTHWESTERN_FEDERAL_DISTRICT 3
#define STATE_RUSSIAN_FEDERATION_VOLGA_FEDERAL_DISTRICT_       4
#define STATE_RUSSIAN_FEDERATION_SIBERIAN_FEDERAL_DISTRICT     5
#define STATE_RUSSIAN_FEDERATION_SOUTHERN_FEDERAL_DISTRICT     6
#define STATE_RUSSIAN_FEDERATION_URALS_FEDERAL_DISTRICT_       7
#define STATE_RUSSIAN_FEDERATION_COUNT                         8

#define STATE_SWEDEN_NONE                         0
#define STATE_SWEDEN_ANGERMANLAND                 1
#define STATE_SWEDEN_BLEKINGE                     2
#define STATE_SWEDEN_BOHUSLAN                     3
#define STATE_SWEDEN_DALARNA                      4
#define STATE_SWEDEN_DALSLAND                     5
#define STATE_SWEDEN_GASTRIKLAND                  6
#define STATE_SWEDEN_GOTLAND                      7
#define STATE_SWEDEN_HALLAND                      8
#define STATE_SWEDEN_HALSINGLAND                  9
#define STATE_SWEDEN_JAMTLAND                     10
#define STATE_SWEDEN_NORTH_LAPLAND                11
#define STATE_SWEDEN_SOUTH_LAPLAND                12
#define STATE_SWEDEN_MEDELPAD                     13
#define STATE_SWEDEN_NARKE                        14
#define STATE_SWEDEN_NORRBOTTEN                   15
#define STATE_SWEDEN_OLAND                        16
#define STATE_SWEDEN_OSTERGOTLAND___VASTERGOTLAND 17
#define STATE_SWEDEN_SKANE                        18
#define STATE_SWEDEN_SMALAND                      19
#define STATE_SWEDEN_SODERMANLAND                 20
#define STATE_SWEDEN_UPPLAND                      21
#define STATE_SWEDEN_VARMLAND                     22
#define STATE_SWEDEN_VASTERBOTTEN                 23
#define STATE_SWEDEN_VASTMANLAND                  24
#define STATE_SWEDEN_COUNT                        25

#define STATE_UNITED_STATES_OF_AMERICA_NONE            0
#define STATE_UNITED_STATES_OF_AMERICA_ALABAMA         1
#define STATE_UNITED_STATES_OF_AMERICA_ALASKA          2
#define STATE_UNITED_STATES_OF_AMERICA_ARIZONA         3
#define STATE_UNITED_STATES_OF_AMERICA_ARKANSAS        4
#define STATE_UNITED_STATES_OF_AMERICA_CALIFORNIA      5
#define STATE_UNITED_STATES_OF_AMERICA_COLORADO        6
#define STATE_UNITED_STATES_OF_AMERICA_CONNECTICUT     7
#define STATE_UNITED_STATES_OF_AMERICA_DELAWARE        8
#define STATE_UNITED_STATES_OF_AMERICA_FLORIDA         9
#define STATE_UNITED_STATES_OF_AMERICA_GEORGIA         10
#define STATE_UNITED_STATES_OF_AMERICA_HAWAII          11
#define STATE_UNITED_STATES_OF_AMERICA_IDAHO           12
#define STATE_UNITED_STATES_OF_AMERICA_ILLINOIS        13
#define STATE_UNITED_STATES_OF_AMERICA_INDIANA         14
#define STATE_UNITED_STATES_OF_AMERICA_IOWA            15
#define STATE_UNITED_STATES_OF_AMERICA_KANSAS          16
#define STATE_UNITED_STATES_OF_AMERICA_KENTUCKY        17
#define STATE_UNITED_STATES_OF_AMERICA_LOUISIANA       18
#define STATE_UNITED_STATES_OF_AMERICA_MAINE           19
#define STATE_UNITED_STATES_OF_AMERICA_MARYLAND        20
#define STATE_UNITED_STATES_OF_AMERICA_MASSACHUSETTS   21
#define STATE_UNITED_STATES_OF_AMERICA_MICHIGAN        22
#define STATE_UNITED_STATES_OF_AMERICA_MINNESOTA       23
#define STATE_UNITED_STATES_OF_AMERICA_MISSISSIPPI     24
#define STATE_UNITED_STATES_OF_AMERICA_MISSOURI        25
#define STATE_UNITED_STATES_OF_AMERICA_MONTANA         26
#define STATE_UNITED_STATES_OF_AMERICA_NEBRASKA        27
#define STATE_UNITED_STATES_OF_AMERICA_NEVADA          28
#define STATE_UNITED_STATES_OF_AMERICA_NEW_HAMPSHIRE   29
#define STATE_UNITED_STATES_OF_AMERICA_NEW_JERSEY      30
#define STATE_UNITED_STATES_OF_AMERICA_NEW_MEXICO      31
#define STATE_UNITED_STATES_OF_AMERICA_NEW_YORK        32
#define STATE_UNITED_STATES_OF_AMERICA_NORTH_CAROLINA  33
#define STATE_UNITED_STATES_OF_AMERICA_NORTH_DAKOTA    34
#define STATE_UNITED_STATES_OF_AMERICA_OHIO            35
#define STATE_UNITED_STATES_OF_AMERICA_OKLAHOMA        36
#define STATE_UNITED_STATES_OF_AMERICA_OREGON          37
#define STATE_UNITED_STATES_OF_AMERICA_PENNSYLVANIA    38
#define STATE_UNITED_STATES_OF_AMERICA_RHODE_ISLAND    39
#define STATE_UNITED_STATES_OF_AMERICA_SOUTH_CAROLINA  40
#define STATE_UNITED_STATES_OF_AMERICA_SOUTH_DAKOTA    41
#define STATE_UNITED_STATES_OF_AMERICA_TENNESSEE       42
#define STATE_UNITED_STATES_OF_AMERICA_TEXAS           43
#define STATE_UNITED_STATES_OF_AMERICA_UTAH            44
#define STATE_UNITED_STATES_OF_AMERICA_VERMONT         45
#define STATE_UNITED_STATES_OF_AMERICA_VIRGINIA        46
#define STATE_UNITED_STATES_OF_AMERICA_WASHINGTON      47
#define STATE_UNITED_STATES_OF_AMERICA_WASHINGTON__DC_ 48
#define STATE_UNITED_STATES_OF_AMERICA_WEST_VIRGINIA   49
#define STATE_UNITED_STATES_OF_AMERICA_WISCONSIN       50
#define STATE_UNITED_STATES_OF_AMERICA_WYOMING         51
#define STATE_UNITED_STATES_OF_AMERICA_COUNT           52

#endif // GUARD_POKEHEARTGOLD_CONSTANTS_GEONET_GLOBE_H
