#ifndef GUARD_POKEHEARTGOLD_CONSTANTS_GEONET_GLOBE_H
#define GUARD_POKEHEARTGOLD_CONSTANTS_GEONET_GLOBE_H

#define COUNTRY_NONE                                         0
#define COUNTRY_AFGHANISTAN                                  1
#define COUNTRY_ALBANIA                                      2
#define COUNTRY_ALGERIA                                      3
#define COUNTRY_AMERICAN_SAMOA                               4
#define COUNTRY_ANDORRA                                      5
#define COUNTRY_ANGOLA                                       6
#define COUNTRY_ANGUILLA                                     7
#define COUNTRY_ANTIGUA_AND_BARBUDA                          8
#define COUNTRY_ARGENTINA                                    9
#define COUNTRY_ARMENIA                                     10
#define COUNTRY_ARUBA                                       11
#define COUNTRY_AUSTRALIA                                   12
#define COUNTRY_AUSTRIA                                     13
#define COUNTRY_AZERBAIJAN                                  14
#define COUNTRY_BAHAMAS                                     15
#define COUNTRY_BAHRAIN                                     16
#define COUNTRY_BANGLADESH                                  17
#define COUNTRY_BARBADOS                                    18
#define COUNTRY_BELARUS                                     19
#define COUNTRY_BELGIUM                                     20
#define COUNTRY_BELIZE                                      21
#define COUNTRY_BENIN                                       22
#define COUNTRY_BERMUDA                                     23
#define COUNTRY_BHUTAN                                      24
#define COUNTRY_BOLIVIA                                     25
#define COUNTRY_BOSNIA_AND_HERZEGOVINA                      26
#define COUNTRY_BOTSWANA                                    27
#define COUNTRY_BRAZIL                                      28
#define COUNTRY_BRITISH_VIRGIN_ISLANDS                      29
#define COUNTRY_BRUNEI_DARUSSALAM                           30
#define COUNTRY_BULGARIA                                    31
#define COUNTRY_BURKINA_FASO                                32
#define COUNTRY_BURUNDI                                     33
#define COUNTRY_CAMBODIA                                    34
#define COUNTRY_CAMEROON                                    35
#define COUNTRY_CANADA                                      36
#define COUNTRY_CAPE_VERDE                                  37
#define COUNTRY_CAYMAN_ISLANDS                              38
#define COUNTRY_CENTRAL_AFRICAN_REPUBLIC                    39
#define COUNTRY_CHAD                                        40
#define COUNTRY_CHANNEL_ISLANDS                             41
#define COUNTRY_CHILE                                       42
#define COUNTRY_CHINA                                       43
#define COUNTRY_CHRISTMAS_ISLAND                            44
#define COUNTRY_COLOMBIA                                    45
#define COUNTRY_COMOROS                                     46
#define COUNTRY_DEMOCRATIC_REPUBLIC_OF_THE_CONGO            47
#define COUNTRY_CONGO                                       48
#define COUNTRY_COOK_ISLANDS                                49
#define COUNTRY_COSTA_RICA                                  50
#define COUNTRY_COTE_D_IVOIRE                               51
#define COUNTRY_CROATIA                                     52
#define COUNTRY_CUBA                                        53
#define COUNTRY_CYPRUS                                      54
#define COUNTRY_CZECH_REPUBLIC                              55
#define COUNTRY_DENMARK                                     56
#define COUNTRY_DJIBOUTI                                    57
#define COUNTRY_DOMINICA                                    58
#define COUNTRY_DOMINICAN_REPUBLIC                          59
#define COUNTRY_ECUADOR                                     60
#define COUNTRY_EGYPT                                       61
#define COUNTRY_EL_SALVADOR                                 62
#define COUNTRY_EQUATORIAL_GUINEA                           63
#define COUNTRY_ERITREA                                     64
#define COUNTRY_ESTONIA                                     65
#define COUNTRY_ETHIOPIA                                    66
#define COUNTRY_FAROE_ISLANDS                               67
#define COUNTRY_FALKLAND_ISLANDS                            68
#define COUNTRY_FIJI                                        69
#define COUNTRY_FINLAND                                     70
#define COUNTRY_FRANCE                                      71
#define COUNTRY_FRENCH_GUIANA                               72
#define COUNTRY_FRENCH_POLYNESIA                            73
#define COUNTRY_GABON                                       74
#define COUNTRY_GAMBIA                                      75
#define COUNTRY_GEORGIA                                     76
#define COUNTRY_GERMANY                                     77
#define COUNTRY_GHANA                                       78
#define COUNTRY_GIBRALTAR                                   79
#define COUNTRY_GREECE                                      80
#define COUNTRY_GREENLAND                                   81
#define COUNTRY_GRENADA                                     82
#define COUNTRY_GUADELOUPE                                  83
#define COUNTRY_GUAM                                        84
#define COUNTRY_GUATEMALA                                   85
#define COUNTRY_GUINEA                                      86
#define COUNTRY_GUINEA_BISSAU                               87
#define COUNTRY_GUYANA                                      88
#define COUNTRY_HAITI                                       89
#define COUNTRY_HONDURAS                                    90
#define COUNTRY_HONG_KONG                                   91
#define COUNTRY_HUNGARY                                     92
#define COUNTRY_ICELAND                                     93
#define COUNTRY_INDIA                                       94
#define COUNTRY_INDONESIA                                   95
#define COUNTRY_IRAN                                        96
#define COUNTRY_IRAQ                                        97
#define COUNTRY_IRELAND                                     98
#define COUNTRY_ISLE_OF_MAN_                                99
#define COUNTRY_ISRAEL                                     100
#define COUNTRY_ITALY                                      101
#define COUNTRY_JAMAICA                                    102
#define COUNTRY_JAPAN                                      103
#define COUNTRY_JORDAN                                     104
#define COUNTRY_KASHMIR                                    105
#define COUNTRY_KAZAKHSTAN                                 106
#define COUNTRY_KENYA                                      107
#define COUNTRY_KIRIBATI                                   108
#define COUNTRY_D_P__REPUBLIC_OF_KOREA                     109
#define COUNTRY_REPUBLIC_OF_KOREA                          110
#define COUNTRY_KUWAIT                                     111
#define COUNTRY_KYRGYZSTAN                                 112
#define COUNTRY_LAO_PEOPLE_S_DEMOCRATIC_REPUBLIC           113
#define COUNTRY_LATVIA                                     114
#define COUNTRY_LEBANON                                    115
#define COUNTRY_LESOTHO                                    116
#define COUNTRY_LIBERIA                                    117
#define COUNTRY_LIBYAN_ARAB_JAMAHIRIYA                     118
#define COUNTRY_LIECHTENSTEIN                              119
#define COUNTRY_LITHUANIA                                  120
#define COUNTRY_LUXEMBOURG                                 121
#define COUNTRY_MACAU                                      122
#define COUNTRY_MACEDONIA__FYROM_                          123
#define COUNTRY_MADAGASCAR                                 124
#define COUNTRY_MALAWI                                     125
#define COUNTRY_MALAYSIA                                   126
#define COUNTRY_MALDIVES                                   127
#define COUNTRY_MALI                                       128
#define COUNTRY_MALTA                                      129
#define COUNTRY_MARSHALL_ISLANDS                           130
#define COUNTRY_MARTINIQUE                                 131
#define COUNTRY_MAURITANIA                                 132
#define COUNTRY_MAURITIUS                                  133
#define COUNTRY_MAYOTTE                                    134
#define COUNTRY_MEXICO                                     135
#define COUNTRY_MICRONESIA                                 136
#define COUNTRY_REPUBLIC_OF_MOLDOVA                        137
#define COUNTRY_MONACO                                     138
#define COUNTRY_MONGOLIA                                   139
#define COUNTRY_MOROCCO                                    140
#define COUNTRY_MOZAMBIQUE                                 141
#define COUNTRY_MYANMAR                                    142
#define COUNTRY_NAMIBIA                                    143
#define COUNTRY_NAURU                                      144
#define COUNTRY_NEPAL                                      145
#define COUNTRY_NETHERLANDS                                146
#define COUNTRY_NETHERLANDS_ANTILLES                       147
#define COUNTRY_NEW_CALEDONIA                              148
#define COUNTRY_NEW_ZEALAND                                149
#define COUNTRY_NICARAGUA                                  150
#define COUNTRY_NIGER                                      151
#define COUNTRY_NIGERIA                                    152
#define COUNTRY_NIUE                                       153
#define COUNTRY_NORFOLK_ISLAND                             154
#define COUNTRY_NORTHERN_MARIANA_ISLANDS                   155
#define COUNTRY_NORWAY                                     156
#define COUNTRY_OMAN                                       157
#define COUNTRY_PAKISTAN                                   158
#define COUNTRY_PALAU                                      159
#define COUNTRY_PANAMA                                     160
#define COUNTRY_PAPUA_NEW_GUINEA                           161
#define COUNTRY_PARAGUAY                                   162
#define COUNTRY_PERU                                       163
#define COUNTRY_PHILIPPINES                                164
#define COUNTRY_PITCAIRN_ISLANDS                           165
#define COUNTRY_POLAND                                     166
#define COUNTRY_PORTUGAL                                   167
#define COUNTRY_PUERTO_RICO                                168
#define COUNTRY_QATAR                                      169
#define COUNTRY_REUNION                                    170
#define COUNTRY_ROMANIA                                    171
#define COUNTRY_RUSSIAN_FEDERATION                         172
#define COUNTRY_RWANDA                                     173
#define COUNTRY_SAINT_HELENA                               174
#define COUNTRY_SAINT_KITTS_AND_NEVIS                      175
#define COUNTRY_SAINT_LUCIA                                176
#define COUNTRY_SAINT_PIERRE_AND_MIQUELON                  177
#define COUNTRY_SAINT_VINCENT_AND_THE_GRENADINES           178
#define COUNTRY_SAMOA                                      179
#define COUNTRY_SAN_MARINO                                 180
#define COUNTRY_SAO_TOME_AND_PRINCIPE                      181
#define COUNTRY_SAUDI_ARABIA                               182
#define COUNTRY_SENEGAL                                    183
#define COUNTRY_SERBIA_AND_MONTENEGRO                      184
#define COUNTRY_SEYCHELLES                                 185
#define COUNTRY_SIERRA_LEONE                               186
#define COUNTRY_SINGAPORE                                  187
#define COUNTRY_SLOVAKIA                                   188
#define COUNTRY_SLOVENIA                                   189
#define COUNTRY_SOLOMON_ISLANDS                            190
#define COUNTRY_SOMALIA                                    191
#define COUNTRY_SOUTH_AFRICA                               192
#define COUNTRY_SPAIN                                      193
#define COUNTRY_SRI_LANKA                                  194
#define COUNTRY_SUDAN                                      195
#define COUNTRY_SURINAME                                   196
#define COUNTRY_JAN_MAYEN_ISLAND                           197
#define COUNTRY_SWAZILAND                                  198
#define COUNTRY_SWEDEN                                     199
#define COUNTRY_SWISS_CONFEDERATION                        200
#define COUNTRY_SYRIAN_ARAB_REPUBLIC                       201
#define COUNTRY_TAIWAN                                     202
#define COUNTRY_TAJIKISTAN                                 203
#define COUNTRY_UNITED_REPUBLIC_OF_TANZANIA                204
#define COUNTRY_THAILAND                                   205
#define COUNTRY_DEMOCRATIC_REPUBLIC_OF_TIMOR_LESTE         206
#define COUNTRY_TOGO                                       207
#define COUNTRY_TOKELAU                                    208
#define COUNTRY_TONGA                                      209
#define COUNTRY_TRINIDAD_AND_TOBAGO                        210
#define COUNTRY_TUNISIA                                    211
#define COUNTRY_TURKEY                                     212
#define COUNTRY_TURKMENISTAN                               213
#define COUNTRY_TURKS_AND_CAICOS_ISLANDS                   214
#define COUNTRY_TUVALU                                     215
#define COUNTRY_UGANDA                                     216
#define COUNTRY_UKRAINE                                    217
#define COUNTRY_UNITED_ARAB_EMIRATES                       218
#define COUNTRY_UNITED_KINGDOM                             219
#define COUNTRY_UNITED_STATES_OF_AMERICA                   220
#define COUNTRY_UNITED_STATES_VIRGIN_ISLANDS               221
#define COUNTRY_URUGUAY                                    222
#define COUNTRY_UZBEKISTAN                                 223
#define COUNTRY_VANUATU                                    224
#define COUNTRY_VATICAN_CITY                               225
#define COUNTRY_VENEZUELA                                  226
#define COUNTRY_VIETNAM                                    227
#define COUNTRY_WALLIS_AND_FUTUNA                          228
#define COUNTRY_PALESTINE                                  229
#define COUNTRY_WESTERN_SAHARA                             230
#define COUNTRY_YEMEN                                      231
#define COUNTRY_ZAMBIA                                     232
#define COUNTRY_ZIMBABWE                                   233

#endif //GUARD_POKEHEARTGOLD_CONSTANTS_GEONET_GLOBE_H
