#ifndef POKEHEARTGOLD_CONSTANTS_MAIL_H
#define POKEHEARTGOLD_CONSTANTS_MAIL_H

#define MAIL_GRASS  0
#define MAIL_FLAME  1
#define MAIL_BUBBLE 2
#define MAIL_BLOOM  3
#define MAIL_TUNNEL 4
#define MAIL_STEEL  5
#define MAIL_HEART  6
#define MAIL_SNOW   7
#define MAIL_SPACE  8
#define MAIL_AIR    9
#define MAIL_MOSAIC 10
#define MAIL_BRICK  11
#define NUM_MAIL    12

#define MAIL_NONE 0xFF

#endif // POKEHEARTGOLD_CONSTANTS_MAIL_H
