#ifndef POKEHEARTGOLD_CONSTANTS_MESSAGE_TAGS_H
#define POKEHEARTGOLD_CONSTANTS_MESSAGE_TAGS_H

#define TAG_NONE                                            0
#define TAG_NONE_SIDE                                       1
#define TAG_NICKNAME                                        2
#define TAG_MOVE                                            3
#define TAG_STAT                                            4
#define TAG_ITEM                                            5
#define TAG_NUMBER                                          6
#define TAG_NUMBERS                                         7
#define TAG_TRNAME                                          8
#define TAG_NICKNAME_NICKNAME                               9
#define TAG_NICKNAME_MOVE                                   10
#define TAG_NICKNAME_ABILITY                                11
#define TAG_NICKNAME_STAT                                   12
#define TAG_NICKNAME_TYPE                                   13
#define TAG_NICKNAME_POKE                                   14
#define TAG_NICKNAME_ITEM                                   15
#define TAG_NICKNAME_POFFIN                                 16
#define TAG_NICKNAME_NUM                                    17
#define TAG_NICKNAME_TRNAME                                 18
#define TAG_NICKNAME_BOX                                    19
#define TAG_MOVE_SIDE                                       20
#define TAG_MOVE_NICKNAME                                   21
#define TAG_MOVE_MOVE                                       22
#define TAG_ABILITY_NICKNAME                                23
#define TAG_ITEM_MOVE                                       24
#define TAG_NUMBER_NUMBER                                   25
#define TAG_TRNAME_TRNAME                                   26
#define TAG_TRNAME_NICKNAME                                 27
#define TAG_TRNAME_ITEM                                     28
#define TAG_TRNAME_NUM                                      29
#define TAG_TRCLASS_TRNAME                                  30
#define TAG_NICKNAME_NICKNAME_MOVE                          31
#define TAG_NICKNAME_NICKNAME_ABILITY                       32
#define TAG_NICKNAME_NICKNAME_ITEM                          33
#define TAG_NICKNAME_MOVE_MOVE                              34
#define TAG_NICKNAME_MOVE_NUMBER                            35
#define TAG_NICKNAME_ABILITY_NICKNAME                       36
#define TAG_NICKNAME_ABILITY_MOVE                           37
#define TAG_NICKNAME_ABILITY_ITEM                           38
#define TAG_NICKNAME_ABILITY_STAT                           39
#define TAG_NICKNAME_ABILITY_TYPE                           40
#define TAG_NICKNAME_ABILITY_STATUS                         41
#define TAG_NICKNAME_ABILITY_NUMBER                         42
#define TAG_NICKNAME_ITEM_NICKNAME                          43
#define TAG_NICKNAME_ITEM_MOVE                              44
#define TAG_NICKNAME_ITEM_STAT                              45
#define TAG_NICKNAME_ITEM_STATUS                            46
#define TAG_NICKNAME_BOX_BOX                                47
#define TAG_ITEM_NICKNAME_FLAVOR                            48
#define TAG_TRNAME_NICKNAME_NICKNAME                        49
#define TAG_TRCLASS_TRNAME_NICKNAME                         50
#define TAG_TRCLASS_TRNAME_ITEM                             51
#define TAG_NICKNAME_ABILITY_NICKNAME_MOVE                  52
#define TAG_NICKNAME_ABILITY_NICKNAME_ABILITY               53
#define TAG_NICKNAME_ABILITY_NICKNAME_STAT                  54
#define TAG_NICKNAME_ITEM_NICKNAME_ITEM                     55
#define TAG_TRNAME_NICKNAME_TRNAME_NICKNAME                 56
#define TAG_TRCLASS_TRNAME_NICKNAME_NICKNAME                57
#define TAG_TRCLASS_TRNAME_NICKNAME_TRNAME                  58
#define TAG_TRCLASS_TRNAME_TRCLASS_TRNAME                   59
#define TAG_TRCLASS_TRNAME_NICKNAME_TRCLASS_TRNAME_NICKNAME 60

#endif
