#ifndef POKEHEARTGOLD_CONSTANTS_MMODEL_H
#define POKEHEARTGOLD_CONSTANTS_MMODEL_H
#define MMODEL_BABYBOY1                            0
#define MMODEL_BABYGIRL1                           1
#define MMODEL_BOY1                                2
#define MMODEL_BOY2                                3
#define MMODEL_BOY3                                4
#define MMODEL_GIRL1                               5
#define MMODEL_GIRL2                               6
#define MMODEL_GIRL3                               7
#define MMODEL_MAN1                                8
#define MMODEL_MAN2                                9
#define MMODEL_MAN3                               10
#define MMODEL_MAN5                               11
#define MMODEL_WOMAN1                             12
#define MMODEL_WOMAN2                             13
#define MMODEL_WOMAN3                             14
#define MMODEL_WOMAN5                             15
#define MMODEL_MIDDLEMAN1                         16
#define MMODEL_MIDDLEWOMAN1                       17
#define MMODEL_OLDMAN1                            18
#define MMODEL_OLDWOMAN1                          19
#define MMODEL_CYCLEM                             20
#define MMODEL_CYCLEW                             21
#define MMODEL_SKIERW                             22
#define MMODEL_SHOPM1                             23
#define MMODEL_SHOPW1                             24
#define MMODEL_ASSISTANTM                         25
#define MMODEL_ASSISTANTW                         26
#define MMODEL_GORGGEOUSM                         27
#define MMODEL_GORGGEOUSW                         28
#define MMODEL_WAITER                             29
#define MMODEL_WAITRESS                           30
#define MMODEL_REPORTER                           31
#define MMODEL_CAMERAMAN                          32
#define MMODEL_MYSTERY                            33
#define MMODEL_BIGMAN                             34
#define MMODEL_MOUNT                              35
#define MMODEL_BADMAN                             36
#define MMODEL_POLICEMAN                          37
#define MMODEL_IDOL                               38
#define MMODEL_GENTLEMAN                          39
#define MMODEL_LADY                               40
#define MMODEL_WORKMAN                            41
#define MMODEL_FARMER                             42
#define MMODEL_COWGIRL                            43
#define MMODEL_CLOWN                              44
#define MMODEL_ARTIST                             45
#define MMODEL_SPORTSMAN                          46
#define MMODEL_EXPLORE                            47
#define MMODEL_FIGHTER                            48
#define MMODEL_CAMPBOY                            49
#define MMODEL_PICNICGIRL                         50
#define MMODEL_FISHING                            51
#define MMODEL_AMBRELLA                           52
#define MMODEL_SEAMAN                             53
#define MMODEL_DOCTOR                             54
#define MMODEL_MAID                               55
#define MMODEL_DELIVERY                           56
#define MMODEL_SUNGLASSES                         57
#define MMODEL_GSRIVEL                            58
#define MMODEL_DAIGO                              59
#define MMODEL_CHAMPION                           60
#define MMODEL_TOWERBOSS                          61
#define MMODEL_SEVEN1                             62
#define MMODEL_SEVEN2                             63
#define MMODEL_SEVEN3                             64
#define MMODEL_SEVEN4                             65
#define MMODEL_SEVEN5                             66
#define MMODEL_GSBOY1                             67
#define MMODEL_PIKACHU                            68
#define MMODEL_HERO                               69
#define MMODEL_HEROINE                            70
#define MMODEL_CYCLEHERO                          71
#define MMODEL_CYCLEHEROINE                       72
#define MMODEL_SWIMHERO                           73
#define MMODEL_SWIMHEROINE                        74
#define MMODEL_SPHERO                             75
#define MMODEL_SPHEROINE                          76
#define MMODEL_WATERHERO                          77
#define MMODEL_WATERHEROINE                       78
#define MMODEL_FISHINGHERO                        79
#define MMODEL_FISH_HEROINE                       80
#define MMODEL_LADDERHERO                         81
#define MMODEL_LADDERHEROINE                      82
#define MMODEL_ITAKO                              83
#define MMODEL_ITAKO_                             84
#define MMODEL_POKEHERO                           85
#define MMODEL_POKEHEROINE                        86
#define MMODEL_SAVEHERO                           87
#define MMODEL_SAVEHEROINE                        88
#define MMODEL_BANZAIHERO                         89
#define MMODEL_BANZAIHEROINE                      90
#define MMODEL_ROCK                               91
#define MMODEL_BREAKROCK                          92
#define MMODEL_TREE                               93
#define MMODEL_MONSTARBALL                        94
#define MMODEL_RHERO                              95
#define MMODEL_RHEROINE                           96
#define MMODEL_RBANZAIHERO                        97
#define MMODEL_RBANZAIINE                         98
#define MMODEL_PKTHHERO                           99
#define MMODEL_PKTHHEROINE                       100
#define MMODEL_WIFISM                            101
#define MMODEL_WIFISF                            102
#define MMODEL_BRAINS1                           103
#define MMODEL_BRAINS2                           104
#define MMODEL_BRAINS3                           105
#define MMODEL_BRAINS4                           106
#define MMODEL_PRINCESS                          107
#define MMODEL_BFSM                              108
#define MMODEL_BFSW1                             109
#define MMODEL_BFSW2                             110
#define MMODEL_AJI_PERU                          111
#define MMODEL_LEAG_DOOR2                        112
#define MMODEL_GSBABYBOY1                        113
#define MMODEL_GSBABYGIRL1                       114
#define MMODEL_GSBOY2                            115
#define MMODEL_GSBOY3                            116
#define MMODEL_GSGIRL1                           117
#define MMODEL_GSGIRL2                           118
#define MMODEL_GSGIRL3                           119
#define MMODEL_GSMAN1                            120
#define MMODEL_GSMAN2                            121
#define MMODEL_GSMAN3                            122
#define MMODEL_GSWOMAN1                          123
#define MMODEL_GSWOMAN2                          124
#define MMODEL_GSWOMAN3                          125
#define MMODEL_GSMIDDLEMAN1                      126
#define MMODEL_MIDDLEWOMAN1_2                    127
#define MMODEL_GSOLDMAN1                         128
#define MMODEL_GSOLDWOMAN1                       129
#define MMODEL_GSBIGMAN                          130
#define MMODEL_MOUNT_2                           131
#define MMODEL_SHOPM1_2                          132
#define MMODEL_PCWOMAN1                          133
#define MMODEL_PCWOMAN2                          134
#define MMODEL_PCWOMAN3                          135
#define MMODEL_GSASSISTANTM                      136
#define MMODEL_GSGENTLEMAN                       137
#define MMODEL_GSSWIMMERM                        138
#define MMODEL_GSSWIMMERW                        139
#define MMODEL_GSFIGHTER                         140
#define MMODEL_CAMPBOY_2                         141
#define MMODEL_PICNICGIRL_2                      142
#define MMODEL_FISHING_2                         143
#define MMODEL_SEAMAN_2                          144
#define MMODEL_MYSTERY_2                         145
#define MMODEL_GSLEADER1                         146
#define MMODEL_GSLEADER2                         147
#define MMODEL_GSLEADER3                         148
#define MMODEL_GSLEADER4                         149
#define MMODEL_GSLEADER5                         150
#define MMODEL_GSLEADER6                         151
#define MMODEL_GSLEADER7                         152
#define MMODEL_GSLEADER8                         153
#define MMODEL_GSBIGFOUR1                        154
#define MMODEL_GSBIGFOUR2                        155
#define MMODEL_GSBIGFOUR3                        156
#define MMODEL_GSBIGFOUR4                        157
#define MMODEL_WATARU                            158
#define MMODEL_GSMAMA                            159
#define MMODEL_OOKIDO                            160
#define MMODEL_GSDSBOY                           161
#define MMODEL_GSLEADER9                         162
#define MMODEL_GSLEADER10                        163
#define MMODEL_GSLEADER11                        164
#define MMODEL_GSLEADER12                        165
#define MMODEL_GSLEADER13                        166
#define MMODEL_GSLEADER14                        167
#define MMODEL_GSLEADER15                        168
#define MMODEL_GSLEADER16                        169
#define MMODEL_RED                               170
#define MMODEL_THIEF                             171
#define MMODEL_BOZU                              172
#define MMODEL_ROCKETW                           173
#define MMODEL_ROCKETM                           174
#define MMODEL_RKANBUW                           175
#define MMODEL_RKANBUM                           176
#define MMODEL_BOARDER                           177
#define MMODEL_FIRE                              178
#define MMODEL_GANG                              179
#define MMODEL_DANCER                            180
#define MMODEL_MASAKI                            181
#define MMODEL_CAPTAIN                           182
#define MMODEL_RGYARADOSU                        183
#define MMODEL_MANIA                             184
#define MMODEL_JUGGRER                           185
#define MMODEL_USOKKY                            186
#define MMODEL_MINAKI                            187
#define MMODEL_THLONOWNER                        188
#define MMODEL_INSTRUCTOR                        189
#define MMODEL_KURUMI                            190
#define MMODEL_NANAMI                            191
#define MMODEL_REDMAMA                           192
#define MMODEL_COUNTERM                          193
#define MMODEL_KABIGON                           194
#define MMODEL_ICE                               195
#define MMODEL_ROTOMG                            196
#define MMODEL_ROTOMI                            197
#define MMODEL_ROTOMS                            198
#define MMODEL_ROTOMW                            199
#define MMODEL_ROTOMF                            200
#define MMODEL_TSURE_POKE                        201
#define MMODEL_TSURE_POKE_2                      202
#define MMODEL_TSURE_POKE_3                      203
#define MMODEL_TSURE_POKE_4                      204
#define MMODEL_TSURE_POKE_5                      205
#define MMODEL_TSURE_POKE_6                      206
#define MMODEL_SHAKEHERO                         207
#define MMODEL_SHAKEHEROINE                      208
#define MMODEL_YADON                             209
#define MMODEL_HOU_OBJ01                         210
#define MMODEL_LUG_OBJ01                         211
#define MMODEL_GSWOMAN6                          212
#define MMODEL_HERO_2                            213
#define MMODEL_HEROINE_2                         214
#define MMODEL_LEADER1                           215
#define MMODEL_LEADER2                           216
#define MMODEL_LEADER3                           217
#define MMODEL_LEADER4                           218
#define MMODEL_LEADER5                           219
#define MMODEL_LEADER6                           220
#define MMODEL_LEADER7                           221
#define MMODEL_LEADER8                           222
#define MMODEL_GANTETSU                          223
#define MMODEL_JUPETTA                           224
#define MMODEL_SAKAKI                            225
#define MMODEL_SUIT                              226
#define MMODEL_CHOUROU                           227
#define MMODEL_RAPURASU                          228
#define MMODEL_GTOROPHY                          229
#define MMODEL_STOROPHY                          230
#define MMODEL_BTOROPHY                          231
#define MMODEL_STATUEHERO                        232
#define MMODEL_STATUEHEROINE                     233
#define MMODEL_SIGNCLOTHES                       234
#define MMODEL_SIGNFLAG                          235
#define MMODEL_SIGNPOKEGEAR                      236
#define MMODEL_SIGNSHOES                         237
#define MMODEL_SIGNBALL                          238
#define MMODEL_POKEWALL                          239
#define MMODEL_SCROLL                            240
#define MMODEL_MEDAL                             241
#define MMODEL_MONO_PIP                          242
#define MMODEL_STOP                              243
#define MMODEL_RKANBUM2                          244
#define MMODEL_RKANBUM3                          245
#define MMODEL_PL_BOY01C                         246
#define MMODEL_PL_GIRL01C                        247
#define MMODEL_SAVERHERO                         248
#define MMODEL_SAVERHEROINE                      249
#define MMODEL_DELIVERY2                         250
#define MMODEL_BONGURI                           251
#define MMODEL_BONGURI_B                         252
#define MMODEL_BONGURI_BK                        253
#define MMODEL_BONGURI_G                         254
#define MMODEL_BONGURI_R                         255
#define MMODEL_BONGURI_W                         256
#define MMODEL_BONGURI_P                         257
#define MMODEL_BONGURI_Y                         258
#define MMODEL_BONMI_B                           259
#define MMODEL_BONMI_BK                          260
#define MMODEL_BONMI_G                           261
#define MMODEL_BONMI_R                           262
#define MMODEL_BONMI_W                           263
#define MMODEL_BONMI_P                           264
#define MMODEL_BONMI_Y                           265
#define MMODEL_F_HERO                            266
#define MMODEL_ROCK_2                            267
#define MMODEL_BREAKROCK_2                       268
#define MMODEL_SPPOKE4                           269
#define MMODEL_FISHINGHERO_2                     270
#define MMODEL_FISHINGHERO_3                     271
#define MMODEL_GINGA_DOOR                        272
#define MMODEL_T5_O01_C                          273
#define MMODEL_TSURE_250                         274
#define MMODEL_TSURE_250_2                       275
#define MMODEL_F_HERO_2                          276
#define MMODEL_R09_O01                           277
#define MMODEL_BONGURI_2                         278
#define MMODEL_LEAG_DOOR2_2                      279
#define MMODEL_TSURE_POKE_7                      297
#define MMODEL_TSURE_POKE_8                      298
#define MMODEL_TSURE_POKE_9                      299
#define MMODEL_TSURE_POKE_10                     300
#define MMODEL_TSURE_POKE_11                     301
#define MMODEL_TSURE_POKE_12                     302
#define MMODEL_TSURE_POKE_13                     303
#define MMODEL_TSURE_POKE_14                     304
#define MMODEL_TSURE_POKE_15                     305
#define MMODEL_TSURE_POKE_16                     306
#define MMODEL_TSURE_POKE_17                     307
#define MMODEL_TSURE_POKE_18                     308
#define MMODEL_TSURE_POKE_19                     309
#define MMODEL_TSURE_POKE_20                     310
#define MMODEL_TSURE_POKE_21                     311
#define MMODEL_TSURE_POKE_22                     312
#define MMODEL_TSURE_POKE_23                     313
#define MMODEL_TSURE_POKE_24                     314
#define MMODEL_TSURE_POKE_25                     315
#define MMODEL_TSURE_POKE_26                     316
#define MMODEL_TSURE_POKE_27                     317
#define MMODEL_TSURE_POKE_28                     318
#define MMODEL_TSURE_POKE_29                     319
#define MMODEL_TSURE_POKE_30                     320
#define MMODEL_TSURE_POKE_31                     321
#define MMODEL_TSURE_POKE_32                     322
#define MMODEL_TSURE_POKE_33                     323
#define MMODEL_TSURE_POKE_34                     324
#define MMODEL_TSURE_POKE_35                     325
#define MMODEL_TSURE_POKE_36                     326
#define MMODEL_TSURE_POKE_37                     327
#define MMODEL_TSURE_POKE_38                     328
#define MMODEL_TSURE_POKE_39                     329
#define MMODEL_TSURE_POKE_40                     330
#define MMODEL_TSURE_POKE_41                     331
#define MMODEL_TSURE_POKE_42                     332
#define MMODEL_TSURE_POKE_43                     333
#define MMODEL_TSURE_POKE_44                     334
#define MMODEL_TSURE_POKE_45                     335
#define MMODEL_TSURE_POKE_46                     336
#define MMODEL_TSURE_POKE_47                     337
#define MMODEL_TSURE_POKE_48                     338
#define MMODEL_TSURE_POKE_49                     339
#define MMODEL_TSURE_POKE_50                     340
#define MMODEL_TSURE_POKE_51                     341
#define MMODEL_TSURE_POKE_52                     342
#define MMODEL_TSURE_POKE_53                     343
#define MMODEL_TSURE_POKE_54                     344
#define MMODEL_TSURE_POKE_55                     345
#define MMODEL_TSURE_POKE_56                     346
#define MMODEL_TSURE_POKE_57                     347
#define MMODEL_TSURE_POKE_58                     348
#define MMODEL_TSURE_POKE_59                     349
#define MMODEL_TSURE_POKE_60                     350
#define MMODEL_TSURE_POKE_61                     351
#define MMODEL_TSURE_POKE_62                     352
#define MMODEL_TSURE_POKE_63                     353
#define MMODEL_TSURE_POKE_64                     354
#define MMODEL_TSURE_POKE_65                     355
#define MMODEL_TSURE_POKE_66                     356
#define MMODEL_TSURE_POKE_67                     357
#define MMODEL_TSURE_POKE_68                     358
#define MMODEL_TSURE_POKE_69                     359
#define MMODEL_TSURE_POKE_70                     360
#define MMODEL_TSURE_POKE_71                     361
#define MMODEL_TSURE_POKE_72                     362
#define MMODEL_TSURE_POKE_73                     363
#define MMODEL_TSURE_POKE_74                     364
#define MMODEL_TSURE_POKE_75                     365
#define MMODEL_TSURE_POKE_76                     366
#define MMODEL_TSURE_POKE_77                     367
#define MMODEL_TSURE_POKE_78                     368
#define MMODEL_TSURE_POKE_79                     369
#define MMODEL_TSURE_POKE_80                     370
#define MMODEL_TSURE_POKE_81                     371
#define MMODEL_TSURE_POKE_82                     372
#define MMODEL_TSURE_POKE_83                     373
#define MMODEL_TSURE_POKE_84                     374
#define MMODEL_TSURE_POKE_85                     375
#define MMODEL_TSURE_POKE_86                     376
#define MMODEL_TSURE_POKE_87                     377
#define MMODEL_TSURE_POKE_88                     378
#define MMODEL_TSURE_POKE_89                     379
#define MMODEL_TSURE_POKE_90                     380
#define MMODEL_TSURE_POKE_91                     381
#define MMODEL_TSURE_POKE_92                     382
#define MMODEL_TSURE_POKE_93                     383
#define MMODEL_TSURE_POKE_94                     384
#define MMODEL_TSURE_POKE_95                     385
#define MMODEL_TSURE_POKE_96                     386
#define MMODEL_TSURE_POKE_97                     387
#define MMODEL_TSURE_POKE_98                     388
#define MMODEL_TSURE_POKE_99                     389
#define MMODEL_TSURE_POKE_100                    390
#define MMODEL_TSURE_POKE_101                    391
#define MMODEL_TSURE_POKE_102                    392
#define MMODEL_TSURE_POKE_103                    393
#define MMODEL_TSURE_POKE_104                    394
#define MMODEL_TSURE_POKE_105                    395
#define MMODEL_TSURE_POKE_106                    396
#define MMODEL_TSURE_POKE_107                    397
#define MMODEL_TSURE_POKE_108                    398
#define MMODEL_TSURE_POKE_109                    399
#define MMODEL_TSURE_POKE_110                    400
#define MMODEL_TSURE_POKE_111                    401
#define MMODEL_TSURE_POKE_112                    402
#define MMODEL_TSURE_POKE_113                    403
#define MMODEL_TSURE_POKE_114                    404
#define MMODEL_TSURE_POKE_115                    405
#define MMODEL_TSURE_POKE_116                    406
#define MMODEL_TSURE_POKE_117                    407
#define MMODEL_TSURE_POKE_118                    408
#define MMODEL_TSURE_POKE_119                    409
#define MMODEL_TSURE_POKE_120                    410
#define MMODEL_TSURE_POKE_121                    411
#define MMODEL_TSURE_POKE_122                    412
#define MMODEL_TSURE_POKE_123                    413
#define MMODEL_TSURE_POKE_124                    414
#define MMODEL_TSURE_POKE_125                    415
#define MMODEL_TSURE_POKE_126                    416
#define MMODEL_TSURE_POKE_127                    417
#define MMODEL_TSURE_POKE_128                    418
#define MMODEL_TSURE_POKE_129                    419
#define MMODEL_TSURE_POKE_130                    420
#define MMODEL_TSURE_POKE_131                    421
#define MMODEL_TSURE_POKE_132                    422
#define MMODEL_TSURE_POKE_133                    423
#define MMODEL_TSURE_POKE_134                    424
#define MMODEL_TSURE_POKE_135                    425
#define MMODEL_TSURE_POKE_136                    426
#define MMODEL_TSURE_POKE_137                    427
#define MMODEL_TSURE_POKE_138                    428
#define MMODEL_TSURE_POKE_139                    429
#define MMODEL_TSURE_POKE_140                    430
#define MMODEL_TSURE_POKE_141                    431
#define MMODEL_TSURE_POKE_142                    432
#define MMODEL_TSURE_POKE_143                    433
#define MMODEL_TSURE_POKE_144                    434
#define MMODEL_TSURE_POKE_145                    435
#define MMODEL_TSURE_POKE_146                    436
#define MMODEL_TSURE_POKE_147                    437
#define MMODEL_TSURE_POKE_148                    438
#define MMODEL_TSURE_POKE_149                    439
#define MMODEL_TSURE_POKE_150                    440
#define MMODEL_TSURE_POKE_151                    441
#define MMODEL_TSURE_POKE_152                    442
#define MMODEL_TSURE_POKE_153                    443
#define MMODEL_TSURE_POKE_154                    444
#define MMODEL_TSURE_POKE_155                    445
#define MMODEL_TSURE_POKE_156                    446
#define MMODEL_TSURE_POKE_157                    447
#define MMODEL_TSURE_POKE_158                    448
#define MMODEL_TSURE_POKE_159                    449
#define MMODEL_TSURE_POKE_160                    450
#define MMODEL_TSURE_POKE_161                    451
#define MMODEL_TSURE_POKE_162                    452
#define MMODEL_TSURE_POKE_163                    453
#define MMODEL_TSURE_POKE_164                    454
#define MMODEL_TSURE_POKE_165                    455
#define MMODEL_TSURE_POKE_166                    456
#define MMODEL_TSURE_POKE_167                    457
#define MMODEL_TSURE_POKE_168                    458
#define MMODEL_TSURE_POKE_169                    459
#define MMODEL_TSURE_POKE_170                    460
#define MMODEL_TSURE_POKE_171                    461
#define MMODEL_TSURE_POKE_172                    462
#define MMODEL_TSURE_POKE_173                    463
#define MMODEL_TSURE_POKE_174                    464
#define MMODEL_TSURE_POKE_175                    465
#define MMODEL_TSURE_POKE_176                    466
#define MMODEL_TSURE_POKE_177                    467
#define MMODEL_TSURE_POKE_178                    468
#define MMODEL_TSURE_POKE_179                    469
#define MMODEL_TSURE_POKE_180                    470
#define MMODEL_TSURE_POKE_181                    471
#define MMODEL_TSURE_POKE_182                    472
#define MMODEL_TSURE_POKE_183                    473
#define MMODEL_TSURE_POKE_184                    474
#define MMODEL_TSURE_POKE_185                    475
#define MMODEL_TSURE_POKE_186                    476
#define MMODEL_TSURE_POKE_187                    477
#define MMODEL_TSURE_POKE_188                    478
#define MMODEL_TSURE_POKE_189                    479
#define MMODEL_TSURE_POKE_190                    480
#define MMODEL_TSURE_POKE_191                    481
#define MMODEL_TSURE_POKE_192                    482
#define MMODEL_TSURE_POKE_193                    483
#define MMODEL_TSURE_POKE_194                    484
#define MMODEL_TSURE_POKE_195                    485
#define MMODEL_TSURE_POKE_196                    486
#define MMODEL_TSURE_POKE_197                    487
#define MMODEL_TSURE_POKE_198                    488
#define MMODEL_TSURE_POKE_199                    489
#define MMODEL_TSURE_POKE_200                    490
#define MMODEL_TSURE_POKE_201                    491
#define MMODEL_TSURE_POKE_202                    492
#define MMODEL_TSURE_POKE_203                    493
#define MMODEL_TSURE_POKE_204                    494
#define MMODEL_TSURE_POKE_205                    495
#define MMODEL_TSURE_POKE_206                    496
#define MMODEL_TSURE_POKE_207                    497
#define MMODEL_TSURE_POKE_208                    498
#define MMODEL_TSURE_POKE_209                    499
#define MMODEL_TSURE_POKE_210                    500
#define MMODEL_TSURE_POKE_211                    501
#define MMODEL_TSURE_POKE_212                    502
#define MMODEL_TSURE_POKE_213                    503
#define MMODEL_TSURE_POKE_214                    504
#define MMODEL_TSURE_POKE_215                    505
#define MMODEL_TSURE_POKE_216                    506
#define MMODEL_TSURE_POKE_217                    507
#define MMODEL_TSURE_POKE_218                    508
#define MMODEL_TSURE_POKE_219                    509
#define MMODEL_TSURE_POKE_220                    510
#define MMODEL_TSURE_POKE_221                    511
#define MMODEL_TSURE_POKE_222                    512
#define MMODEL_TSURE_POKE_223                    513
#define MMODEL_TSURE_POKE_224                    514
#define MMODEL_TSURE_POKE_225                    515
#define MMODEL_TSURE_POKE_226                    516
#define MMODEL_TSURE_POKE_227                    517
#define MMODEL_TSURE_POKE_228                    518
#define MMODEL_TSURE_POKE_229                    519
#define MMODEL_TSURE_POKE_230                    520
#define MMODEL_TSURE_POKE_231                    521
#define MMODEL_TSURE_POKE_232                    522
#define MMODEL_TSURE_POKE_233                    523
#define MMODEL_TSURE_POKE_234                    524
#define MMODEL_TSURE_POKE_235                    525
#define MMODEL_TSURE_POKE_236                    526
#define MMODEL_TSURE_POKE_237                    527
#define MMODEL_TSURE_POKE_238                    528
#define MMODEL_TSURE_POKE_239                    529
#define MMODEL_TSURE_POKE_240                    530
#define MMODEL_TSURE_POKE_241                    531
#define MMODEL_TSURE_POKE_242                    532
#define MMODEL_TSURE_POKE_243                    533
#define MMODEL_TSURE_POKE_244                    534
#define MMODEL_TSURE_POKE_245                    535
#define MMODEL_TSURE_POKE_246                    536
#define MMODEL_TSURE_POKE_247                    537
#define MMODEL_TSURE_POKE_248                    538
#define MMODEL_TSURE_POKE_249                    539
#define MMODEL_TSURE_POKE_250                    540
#define MMODEL_TSURE_POKE_251                    541
#define MMODEL_TSURE_POKE_252                    542
#define MMODEL_TSURE_POKE_253                    543
#define MMODEL_TSURE_POKE_254                    544
#define MMODEL_TSURE_POKE_255                    545
#define MMODEL_TSURE_POKE_256                    546
#define MMODEL_TSURE_POKE_257                    547
#define MMODEL_TSURE_POKE_258                    548
#define MMODEL_TSURE_POKE_259                    549
#define MMODEL_TSURE_POKE_260                    550
#define MMODEL_TSURE_POKE_261                    551
#define MMODEL_TSURE_POKE_262                    552
#define MMODEL_TSURE_POKE_263                    553
#define MMODEL_TSURE_POKE_264                    554
#define MMODEL_TSURE_POKE_265                    555
#define MMODEL_TSURE_POKE_266                    556
#define MMODEL_TSURE_POKE_267                    557
#define MMODEL_TSURE_POKE_268                    558
#define MMODEL_TSURE_POKE_269                    559
#define MMODEL_TSURE_POKE_270                    560
#define MMODEL_TSURE_POKE_271                    561
#define MMODEL_TSURE_POKE_272                    562
#define MMODEL_TSURE_POKE_273                    563
#define MMODEL_TSURE_POKE_274                    564
#define MMODEL_TSURE_POKE_275                    565
#define MMODEL_TSURE_POKE_276                    566
#define MMODEL_TSURE_POKE_277                    567
#define MMODEL_TSURE_POKE_278                    568
#define MMODEL_TSURE_POKE_279                    569
#define MMODEL_TSURE_POKE_280                    570
#define MMODEL_TSURE_POKE_281                    571
#define MMODEL_TSURE_POKE_282                    572
#define MMODEL_TSURE_POKE_283                    573
#define MMODEL_TSURE_POKE_284                    574
#define MMODEL_TSURE_POKE_285                    575
#define MMODEL_TSURE_POKE_286                    576
#define MMODEL_TSURE_POKE_287                    577
#define MMODEL_TSURE_POKE_288                    578
#define MMODEL_TSURE_POKE_289                    579
#define MMODEL_TSURE_POKE_290                    580
#define MMODEL_TSURE_POKE_291                    581
#define MMODEL_TSURE_POKE_292                    582
#define MMODEL_TSURE_POKE_293                    583
#define MMODEL_TSURE_POKE_294                    584
#define MMODEL_TSURE_POKE_295                    585
#define MMODEL_TSURE_POKE_296                    586
#define MMODEL_TSURE_POKE_297                    587
#define MMODEL_TSURE_POKE_298                    588
#define MMODEL_TSURE_POKE_299                    589
#define MMODEL_TSURE_POKE_300                    590
#define MMODEL_TSURE_POKE_301                    591
#define MMODEL_TSURE_POKE_302                    592
#define MMODEL_TSURE_POKE_303                    593
#define MMODEL_TSURE_POKE_304                    594
#define MMODEL_TSURE_POKE_305                    595
#define MMODEL_TSURE_POKE_306                    596
#define MMODEL_TSURE_POKE_307                    597
#define MMODEL_TSURE_POKE_308                    598
#define MMODEL_TSURE_POKE_309                    599
#define MMODEL_TSURE_POKE_310                    600
#define MMODEL_TSURE_POKE_311                    601
#define MMODEL_TSURE_POKE_312                    602
#define MMODEL_TSURE_POKE_313                    603
#define MMODEL_TSURE_POKE_314                    604
#define MMODEL_TSURE_POKE_315                    605
#define MMODEL_TSURE_POKE_316                    606
#define MMODEL_TSURE_POKE_317                    607
#define MMODEL_TSURE_POKE_318                    608
#define MMODEL_TSURE_POKE_319                    609
#define MMODEL_TSURE_POKE_320                    610
#define MMODEL_TSURE_POKE_321                    611
#define MMODEL_TSURE_POKE_322                    612
#define MMODEL_TSURE_POKE_323                    613
#define MMODEL_TSURE_POKE_324                    614
#define MMODEL_TSURE_POKE_325                    615
#define MMODEL_TSURE_POKE_326                    616
#define MMODEL_TSURE_POKE_327                    617
#define MMODEL_TSURE_POKE_328                    618
#define MMODEL_TSURE_POKE_329                    619
#define MMODEL_TSURE_POKE_330                    620
#define MMODEL_TSURE_POKE_331                    621
#define MMODEL_TSURE_POKE_332                    622
#define MMODEL_TSURE_POKE_333                    623
#define MMODEL_TSURE_POKE_334                    624
#define MMODEL_TSURE_POKE_335                    625
#define MMODEL_TSURE_POKE_336                    626
#define MMODEL_TSURE_POKE_337                    627
#define MMODEL_TSURE_POKE_338                    628
#define MMODEL_TSURE_POKE_339                    629
#define MMODEL_TSURE_POKE_340                    630
#define MMODEL_TSURE_POKE_341                    631
#define MMODEL_TSURE_POKE_342                    632
#define MMODEL_TSURE_POKE_343                    633
#define MMODEL_TSURE_POKE_344                    634
#define MMODEL_TSURE_POKE_345                    635
#define MMODEL_TSURE_POKE_346                    636
#define MMODEL_TSURE_POKE_347                    637
#define MMODEL_TSURE_POKE_348                    638
#define MMODEL_TSURE_POKE_349                    639
#define MMODEL_TSURE_POKE_350                    640
#define MMODEL_TSURE_POKE_351                    641
#define MMODEL_TSURE_POKE_352                    642
#define MMODEL_TSURE_POKE_353                    643
#define MMODEL_TSURE_POKE_354                    644
#define MMODEL_TSURE_POKE_355                    645
#define MMODEL_TSURE_POKE_356                    646
#define MMODEL_TSURE_POKE_357                    647
#define MMODEL_TSURE_POKE_358                    648
#define MMODEL_TSURE_POKE_359                    649
#define MMODEL_TSURE_POKE_360                    650
#define MMODEL_TSURE_POKE_361                    651
#define MMODEL_TSURE_POKE_362                    652
#define MMODEL_TSURE_POKE_363                    653
#define MMODEL_TSURE_POKE_364                    654
#define MMODEL_TSURE_POKE_365                    655
#define MMODEL_TSURE_POKE_366                    656
#define MMODEL_TSURE_POKE_367                    657
#define MMODEL_TSURE_POKE_368                    658
#define MMODEL_TSURE_POKE_369                    659
#define MMODEL_TSURE_POKE_370                    660
#define MMODEL_TSURE_POKE_371                    661
#define MMODEL_TSURE_POKE_372                    662
#define MMODEL_TSURE_POKE_373                    663
#define MMODEL_TSURE_POKE_374                    664
#define MMODEL_TSURE_POKE_375                    665
#define MMODEL_TSURE_POKE_376                    666
#define MMODEL_TSURE_POKE_377                    667
#define MMODEL_TSURE_POKE_378                    668
#define MMODEL_TSURE_POKE_379                    669
#define MMODEL_TSURE_POKE_380                    670
#define MMODEL_TSURE_POKE_381                    671
#define MMODEL_TSURE_POKE_382                    672
#define MMODEL_TSURE_POKE_383                    673
#define MMODEL_TSURE_POKE_384                    674
#define MMODEL_TSURE_POKE_385                    675
#define MMODEL_TSURE_POKE_386                    676
#define MMODEL_TSURE_POKE_387                    677
#define MMODEL_TSURE_POKE_388                    678
#define MMODEL_TSURE_POKE_389                    679
#define MMODEL_TSURE_POKE_390                    680
#define MMODEL_TSURE_POKE_391                    681
#define MMODEL_TSURE_POKE_392                    682
#define MMODEL_TSURE_POKE_393                    683
#define MMODEL_TSURE_POKE_394                    684
#define MMODEL_TSURE_POKE_395                    685
#define MMODEL_TSURE_POKE_396                    686
#define MMODEL_TSURE_POKE_397                    687
#define MMODEL_TSURE_POKE_398                    688
#define MMODEL_TSURE_POKE_399                    689
#define MMODEL_TSURE_POKE_400                    690
#define MMODEL_TSURE_POKE_401                    691
#define MMODEL_TSURE_POKE_402                    692
#define MMODEL_TSURE_POKE_403                    693
#define MMODEL_TSURE_POKE_404                    694
#define MMODEL_TSURE_POKE_405                    695
#define MMODEL_TSURE_POKE_406                    696
#define MMODEL_TSURE_POKE_407                    697
#define MMODEL_TSURE_POKE_408                    698
#define MMODEL_TSURE_POKE_409                    699
#define MMODEL_TSURE_POKE_410                    700
#define MMODEL_TSURE_POKE_411                    701
#define MMODEL_TSURE_POKE_412                    702
#define MMODEL_TSURE_POKE_413                    703
#define MMODEL_TSURE_POKE_414                    704
#define MMODEL_TSURE_POKE_415                    705
#define MMODEL_TSURE_POKE_416                    706
#define MMODEL_TSURE_POKE_417                    707
#define MMODEL_TSURE_POKE_418                    708
#define MMODEL_TSURE_POKE_419                    709
#define MMODEL_TSURE_POKE_420                    710
#define MMODEL_TSURE_POKE_421                    711
#define MMODEL_TSURE_POKE_422                    712
#define MMODEL_TSURE_POKE_423                    713
#define MMODEL_TSURE_POKE_424                    714
#define MMODEL_TSURE_POKE_425                    715
#define MMODEL_TSURE_POKE_426                    716
#define MMODEL_TSURE_POKE_427                    717
#define MMODEL_TSURE_POKE_428                    718
#define MMODEL_TSURE_POKE_429                    719
#define MMODEL_TSURE_POKE_430                    720
#define MMODEL_TSURE_POKE_431                    721
#define MMODEL_TSURE_POKE_432                    722
#define MMODEL_TSURE_POKE_433                    723
#define MMODEL_TSURE_POKE_434                    724
#define MMODEL_TSURE_POKE_435                    725
#define MMODEL_TSURE_POKE_436                    726
#define MMODEL_TSURE_POKE_437                    727
#define MMODEL_TSURE_POKE_438                    728
#define MMODEL_TSURE_POKE_439                    729
#define MMODEL_TSURE_POKE_440                    730
#define MMODEL_TSURE_POKE_441                    731
#define MMODEL_TSURE_POKE_442                    732
#define MMODEL_TSURE_POKE_443                    733
#define MMODEL_TSURE_POKE_444                    734
#define MMODEL_TSURE_POKE_445                    735
#define MMODEL_TSURE_POKE_446                    736
#define MMODEL_TSURE_POKE_447                    737
#define MMODEL_TSURE_POKE_448                    738
#define MMODEL_TSURE_POKE_449                    739
#define MMODEL_TSURE_POKE_450                    740
#define MMODEL_TSURE_POKE_451                    741
#define MMODEL_TSURE_POKE_452                    742
#define MMODEL_TSURE_POKE_453                    743
#define MMODEL_TSURE_POKE_454                    744
#define MMODEL_TSURE_POKE_455                    745
#define MMODEL_TSURE_POKE_456                    746
#define MMODEL_TSURE_POKE_457                    747
#define MMODEL_TSURE_POKE_458                    748
#define MMODEL_TSURE_POKE_459                    749
#define MMODEL_TSURE_POKE_460                    750
#define MMODEL_TSURE_POKE_461                    751
#define MMODEL_TSURE_POKE_462                    752
#define MMODEL_TSURE_POKE_463                    753
#define MMODEL_TSURE_POKE_464                    754
#define MMODEL_TSURE_POKE_465                    755
#define MMODEL_TSURE_POKE_466                    756
#define MMODEL_TSURE_POKE_467                    757
#define MMODEL_TSURE_POKE_468                    758
#define MMODEL_TSURE_POKE_469                    759
#define MMODEL_TSURE_POKE_470                    760
#define MMODEL_TSURE_POKE_471                    761
#define MMODEL_TSURE_POKE_472                    762
#define MMODEL_TSURE_POKE_473                    763
#define MMODEL_TSURE_POKE_474                    764
#define MMODEL_TSURE_POKE_475                    765
#define MMODEL_TSURE_POKE_476                    766
#define MMODEL_TSURE_POKE_477                    767
#define MMODEL_TSURE_POKE_478                    768
#define MMODEL_TSURE_POKE_479                    769
#define MMODEL_TSURE_POKE_480                    770
#define MMODEL_TSURE_POKE_481                    771
#define MMODEL_TSURE_POKE_482                    772
#define MMODEL_TSURE_POKE_483                    773
#define MMODEL_TSURE_POKE_484                    774
#define MMODEL_TSURE_POKE_485                    775
#define MMODEL_TSURE_POKE_486                    776
#define MMODEL_TSURE_POKE_487                    777
#define MMODEL_TSURE_POKE_488                    778
#define MMODEL_TSURE_POKE_489                    779
#define MMODEL_TSURE_POKE_490                    780
#define MMODEL_TSURE_POKE_491                    781
#define MMODEL_TSURE_POKE_492                    782
#define MMODEL_TSURE_POKE_493                    783
#define MMODEL_TSURE_POKE_494                    784
#define MMODEL_TSURE_POKE_495                    785
#define MMODEL_TSURE_POKE_496                    786
#define MMODEL_TSURE_POKE_497                    787
#define MMODEL_TSURE_POKE_498                    788
#define MMODEL_TSURE_POKE_499                    789
#define MMODEL_TSURE_POKE_500                    790
#define MMODEL_TSURE_POKE_501                    791
#define MMODEL_TSURE_POKE_502                    792
#define MMODEL_TSURE_POKE_503                    793
#define MMODEL_TSURE_POKE_504                    794
#define MMODEL_TSURE_POKE_505                    795
#define MMODEL_TSURE_POKE_506                    796
#define MMODEL_TSURE_POKE_507                    797
#define MMODEL_TSURE_POKE_508                    798
#define MMODEL_TSURE_POKE_509                    799
#define MMODEL_TSURE_POKE_510                    800
#define MMODEL_TSURE_POKE_511                    801
#define MMODEL_TSURE_POKE_512                    802
#define MMODEL_TSURE_POKE_513                    803
#define MMODEL_TSURE_POKE_514                    804
#define MMODEL_TSURE_POKE_515                    805
#define MMODEL_TSURE_POKE_516                    806
#define MMODEL_TSURE_POKE_517                    807
#define MMODEL_TSURE_POKE_518                    808
#define MMODEL_TSURE_POKE_519                    809
#define MMODEL_TSURE_POKE_520                    810
#define MMODEL_TSURE_POKE_521                    811
#define MMODEL_TSURE_POKE_522                    812
#define MMODEL_TSURE_POKE_523                    813
#define MMODEL_TSURE_POKE_524                    814
#define MMODEL_TSURE_POKE_525                    815
#define MMODEL_TSURE_POKE_526                    816
#define MMODEL_TSURE_POKE_527                    817
#define MMODEL_TSURE_POKE_528                    818
#define MMODEL_TSURE_POKE_529                    819
#define MMODEL_TSURE_POKE_530                    820
#define MMODEL_TSURE_POKE_531                    821
#define MMODEL_TSURE_POKE_532                    822
#define MMODEL_TSURE_POKE_533                    823
#define MMODEL_TSURE_POKE_534                    824
#define MMODEL_TSURE_POKE_535                    825
#define MMODEL_TSURE_POKE_536                    826
#define MMODEL_TSURE_POKE_537                    827
#define MMODEL_TSURE_POKE_538                    828
#define MMODEL_TSURE_POKE_539                    829
#define MMODEL_TSURE_POKE_540                    830
#define MMODEL_TSURE_POKE_541                    831
#define MMODEL_TSURE_POKE_542                    832
#define MMODEL_TSURE_POKE_543                    833
#define MMODEL_TSURE_POKE_544                    834
#define MMODEL_TSURE_POKE_545                    835
#define MMODEL_TSURE_POKE_546                    836
#define MMODEL_TSURE_POKE_547                    837
#define MMODEL_TSURE_POKE_548                    838
#define MMODEL_TSURE_POKE_549                    839
#define MMODEL_TSURE_POKE_550                    840
#define MMODEL_TSURE_POKE_551                    841
#define MMODEL_TSURE_POKE_552                    842
#define MMODEL_TSURE_POKE_553                    843
#define MMODEL_TSURE_POKE_554                    844
#define MMODEL_TSURE_POKE_555                    845
#define MMODEL_TSURE_POKE_556                    846
#define MMODEL_TSURE_POKE_557                    847
#define MMODEL_TSURE_POKE_558                    848
#define MMODEL_TSURE_POKE_559                    849
#define MMODEL_TSURE_POKE_560                    850
#define MMODEL_TSURE_POKE_561                    851
#define MMODEL_TSURE_POKE_562                    852
#define MMODEL_TSURE_POKE_563                    853
#define MMODEL_TSURE_POKE_564                    854
#define MMODEL_TSURE_POKE_565                    855
#define MMODEL_TSURE_POKE_566                    856
#define MMODEL_TSURE_POKE_567                    857
#define MMODEL_TSURE_POKE_568                    858
#define MMODEL_TSURE_POKE_569                    859
#define MMODEL_TSURE_POKE_570                    860
#define MMODEL_TSURE_POKE_571                    861
#define MMODEL_TSURE_POKE_572                    862

#endif //POKEHEARTGOLD_CONSTANTS_MMODEL_H
