#ifndef POKEHEARTGOLD_CONSTANTS_MMODEL_H
#define POKEHEARTGOLD_CONSTANTS_MMODEL_H
#define MMODEL_BABYBOY1                            0
#define MMODEL_BABYGIRL1                           1
#define MMODEL_BOY1                                2
#define MMODEL_BOY2                                3
#define MMODEL_BOY3                                4
#define MMODEL_GIRL1                               5
#define MMODEL_GIRL2                               6
#define MMODEL_GIRL3                               7
#define MMODEL_MAN1                                8
#define MMODEL_MAN2                                9
#define MMODEL_MAN3                               10
#define MMODEL_MAN5                               11
#define MMODEL_WOMAN1                             12
#define MMODEL_WOMAN2                             13
#define MMODEL_WOMAN3                             14
#define MMODEL_WOMAN5                             15
#define MMODEL_MIDDLEMAN1                         16
#define MMODEL_MIDDLEWOMAN1                       17
#define MMODEL_OLDMAN1                            18
#define MMODEL_OLDWOMAN1                          19
#define MMODEL_CYCLEM                             20
#define MMODEL_CYCLEW                             21
#define MMODEL_SKIERW                             22
#define MMODEL_SHOPM1                             23
#define MMODEL_SHOPW1                             24
#define MMODEL_ASSISTANTM                         25
#define MMODEL_ASSISTANTW                         26
#define MMODEL_GORGGEOUSM                         27
#define MMODEL_GORGGEOUSW                         28
#define MMODEL_WAITER                             29
#define MMODEL_WAITRESS                           30
#define MMODEL_REPORTER                           31
#define MMODEL_CAMERAMAN                          32
#define MMODEL_MYSTERY                            33
#define MMODEL_BIGMAN                             34
#define MMODEL_MOUNT                              35
#define MMODEL_BADMAN                             36
#define MMODEL_POLICEMAN                          37
#define MMODEL_IDOL                               38
#define MMODEL_GENTLEMAN                          39
#define MMODEL_LADY                               40
#define MMODEL_WORKMAN                            41
#define MMODEL_FARMER                             42
#define MMODEL_COWGIRL                            43
#define MMODEL_CLOWN                              44
#define MMODEL_ARTIST                             45
#define MMODEL_SPORTSMAN                          46
#define MMODEL_EXPLORE                            47
#define MMODEL_FIGHTER                            48
#define MMODEL_CAMPBOY                            49
#define MMODEL_PICNICGIRL                         50
#define MMODEL_FISHING                            51
#define MMODEL_AMBRELLA                           52
#define MMODEL_SEAMAN                             53
#define MMODEL_DOCTOR                             54
#define MMODEL_MAID                               55
#define MMODEL_DELIVERY                           56
#define MMODEL_SUNGLASSES                         57
#define MMODEL_GSRIVEL                            58
#define MMODEL_DAIGO                              59
#define MMODEL_CHAMPION                           60
#define MMODEL_TOWERBOSS                          61
#define MMODEL_SEVEN1                             62
#define MMODEL_SEVEN2                             63
#define MMODEL_SEVEN3                             64
#define MMODEL_SEVEN4                             65
#define MMODEL_SEVEN5                             66
#define MMODEL_GSBOY1                             67
#define MMODEL_PIKACHU                            68
#define MMODEL_HERO                               69
#define MMODEL_HEROINE                            70
#define MMODEL_CYCLEHERO                          71
#define MMODEL_CYCLEHEROINE                       72
#define MMODEL_SWIMHERO                           73
#define MMODEL_SWIMHEROINE                        74
#define MMODEL_SPHERO                             75
#define MMODEL_SPHEROINE                          76
#define MMODEL_WATERHERO                          77
#define MMODEL_WATERHEROINE                       78
#define MMODEL_FISHINGHERO                        79
#define MMODEL_FISH_HEROINE                       80
#define MMODEL_LADDERHERO                         81
#define MMODEL_LADDERHEROINE                      82
#define MMODEL_ITAKO                              83
#define MMODEL_ITAKO_                             84
#define MMODEL_POKEHERO                           85
#define MMODEL_POKEHEROINE                        86
#define MMODEL_SAVEHERO                           87
#define MMODEL_SAVEHEROINE                        88
#define MMODEL_BANZAIHERO                         89
#define MMODEL_BANZAIHEROINE                      90
#define MMODEL_ROCK                               91
#define MMODEL_BREAKROCK                          92
#define MMODEL_TREE                               93
#define MMODEL_MONSTARBALL                        94
#define MMODEL_RHERO                              95
#define MMODEL_RHEROINE                           96
#define MMODEL_RBANZAIHERO                        97
#define MMODEL_RBANZAIINE                         98
#define MMODEL_PKTHHERO                           99
#define MMODEL_PKTHHEROINE                       100
#define MMODEL_WIFISM                            101
#define MMODEL_WIFISF                            102
#define MMODEL_BRAINS1                           103
#define MMODEL_BRAINS2                           104
#define MMODEL_BRAINS3                           105
#define MMODEL_BRAINS4                           106
#define MMODEL_PRINCESS                          107
#define MMODEL_BFSM                              108
#define MMODEL_BFSW1                             109
#define MMODEL_BFSW2                             110
#define MMODEL_AJI_PERU                          111
#define MMODEL_LEAG_DOOR2                        112
#define MMODEL_GSBABYBOY1                        113
#define MMODEL_GSBABYGIRL1                       114
#define MMODEL_GSBOY2                            115
#define MMODEL_GSBOY3                            116
#define MMODEL_GSGIRL1                           117
#define MMODEL_GSGIRL2                           118
#define MMODEL_GSGIRL3                           119
#define MMODEL_GSMAN1                            120
#define MMODEL_GSMAN2                            121
#define MMODEL_GSMAN3                            122
#define MMODEL_GSWOMAN1                          123
#define MMODEL_GSWOMAN2                          124
#define MMODEL_GSWOMAN3                          125
#define MMODEL_GSMIDDLEMAN1                      126
#define MMODEL_MIDDLEWOMAN1_2                    127
#define MMODEL_GSOLDMAN1                         128
#define MMODEL_GSOLDWOMAN1                       129
#define MMODEL_GSBIGMAN                          130
#define MMODEL_MOUNT_2                           131
#define MMODEL_SHOPM1_2                          132
#define MMODEL_PCWOMAN1                          133
#define MMODEL_PCWOMAN2                          134
#define MMODEL_PCWOMAN3                          135
#define MMODEL_GSASSISTANTM                      136
#define MMODEL_GSGENTLEMAN                       137
#define MMODEL_GSSWIMMERM                        138
#define MMODEL_GSSWIMMERW                        139
#define MMODEL_GSFIGHTER                         140
#define MMODEL_CAMPBOY_2                         141
#define MMODEL_PICNICGIRL_2                      142
#define MMODEL_FISHING_2                         143
#define MMODEL_SEAMAN_2                          144
#define MMODEL_MYSTERY_2                         145
#define MMODEL_GSLEADER1                         146
#define MMODEL_GSLEADER2                         147
#define MMODEL_GSLEADER3                         148
#define MMODEL_GSLEADER4                         149
#define MMODEL_GSLEADER5                         150
#define MMODEL_GSLEADER6                         151
#define MMODEL_GSLEADER7                         152
#define MMODEL_GSLEADER8                         153
#define MMODEL_GSBIGFOUR1                        154
#define MMODEL_GSBIGFOUR2                        155
#define MMODEL_GSBIGFOUR3                        156
#define MMODEL_GSBIGFOUR4                        157
#define MMODEL_WATARU                            158
#define MMODEL_GSMAMA                            159
#define MMODEL_OOKIDO                            160
#define MMODEL_GSDSBOY                           161
#define MMODEL_GSLEADER9                         162
#define MMODEL_GSLEADER10                        163
#define MMODEL_GSLEADER11                        164
#define MMODEL_GSLEADER12                        165
#define MMODEL_GSLEADER13                        166
#define MMODEL_GSLEADER14                        167
#define MMODEL_GSLEADER15                        168
#define MMODEL_GSLEADER16                        169
#define MMODEL_RED                               170
#define MMODEL_THIEF                             171
#define MMODEL_BOZU                              172
#define MMODEL_ROCKETW                           173
#define MMODEL_ROCKETM                           174
#define MMODEL_RKANBUW                           175
#define MMODEL_RKANBUM                           176
#define MMODEL_BOARDER                           177
#define MMODEL_FIRE                              178
#define MMODEL_GANG                              179
#define MMODEL_DANCER                            180
#define MMODEL_MASAKI                            181
#define MMODEL_CAPTAIN                           182
#define MMODEL_RGYARADOSU                        183
#define MMODEL_MANIA                             184
#define MMODEL_JUGGRER                           185
#define MMODEL_USOKKY                            186
#define MMODEL_MINAKI                            187
#define MMODEL_THLONOWNER                        188
#define MMODEL_INSTRUCTOR                        189
#define MMODEL_KURUMI                            190
#define MMODEL_NANAMI                            191
#define MMODEL_REDMAMA                           192
#define MMODEL_COUNTERM                          193
#define MMODEL_KABIGON                           194
#define MMODEL_ICE                               195
#define MMODEL_ROTOMG                            196
#define MMODEL_ROTOMI                            197
#define MMODEL_ROTOMS                            198
#define MMODEL_ROTOMW                            199
#define MMODEL_ROTOMF                            200
#define MMODEL_TSURE_POKE                        201
#define MMODEL_TSURE_POKE_2                      202
#define MMODEL_TSURE_POKE_3                      203
#define MMODEL_TSURE_POKE_4                      204
#define MMODEL_TSURE_POKE_5                      205
#define MMODEL_TSURE_POKE_6                      206
#define MMODEL_SHAKEHERO                         207
#define MMODEL_SHAKEHEROINE                      208
#define MMODEL_YADON                             209
#define MMODEL_HOU_OBJ01                         210
#define MMODEL_LUG_OBJ01                         211
#define MMODEL_GSWOMAN6                          212
#define MMODEL_HERO_2                            213
#define MMODEL_HEROINE_2                         214
#define MMODEL_LEADER1                           215
#define MMODEL_LEADER2                           216
#define MMODEL_LEADER3                           217
#define MMODEL_LEADER4                           218
#define MMODEL_LEADER5                           219
#define MMODEL_LEADER6                           220
#define MMODEL_LEADER7                           221
#define MMODEL_LEADER8                           222
#define MMODEL_GANTETSU                          223
#define MMODEL_JUPETTA                           224
#define MMODEL_SAKAKI                            225
#define MMODEL_SUIT                              226
#define MMODEL_CHOUROU                           227
#define MMODEL_RAPURASU                          228
#define MMODEL_GTOROPHY                          229
#define MMODEL_STOROPHY                          230
#define MMODEL_BTOROPHY                          231
#define MMODEL_STATUEHERO                        232
#define MMODEL_STATUEHEROINE                     233
#define MMODEL_SIGNCLOTHES                       234
#define MMODEL_SIGNFLAG                          235
#define MMODEL_SIGNPOKEGEAR                      236
#define MMODEL_SIGNSHOES                         237
#define MMODEL_SIGNBALL                          238
#define MMODEL_POKEWALL                          239
#define MMODEL_SCROLL                            240
#define MMODEL_MEDAL                             241
#define MMODEL_MONO_PIP                          242
#define MMODEL_STOP                              243
#define MMODEL_RKANBUM2                          244
#define MMODEL_RKANBUM3                          245
#define MMODEL_PL_BOY01C                         246
#define MMODEL_PL_GIRL01C                        247
#define MMODEL_SAVERHERO                         248
#define MMODEL_SAVERHEROINE                      249
#define MMODEL_DELIVERY2                         250
#define MMODEL_BONGURI                           251
#define MMODEL_BONGURI_B                         252
#define MMODEL_BONGURI_BK                        253
#define MMODEL_BONGURI_G                         254
#define MMODEL_BONGURI_R                         255
#define MMODEL_BONGURI_W                         256
#define MMODEL_BONGURI_P                         257
#define MMODEL_BONGURI_Y                         258
#define MMODEL_BONMI_B                           259
#define MMODEL_BONMI_BK                          260
#define MMODEL_BONMI_G                           261
#define MMODEL_BONMI_R                           262
#define MMODEL_BONMI_W                           263
#define MMODEL_BONMI_P                           264
#define MMODEL_BONMI_Y                           265
#define MMODEL_F_HERO                            266
#define MMODEL_ROCK_2                            267
#define MMODEL_BREAKROCK_2                       268
#define MMODEL_SPPOKE4                           269
#define MMODEL_FISHINGHERO_2                     270
#define MMODEL_FISHINGHERO_3                     271
#define MMODEL_GINGA_DOOR                        272
#define MMODEL_T5_O01_C                          273
#define MMODEL_TSURE_250                         274
#define MMODEL_TSURE_250_2                       275
#define MMODEL_F_HERO_2                          276
#define MMODEL_R09_O01                           277
#define MMODEL_BONGURI_2                         278
#define MMODEL_LEAG_DOOR2_2                      279
#define MMODEL_TSURE_POKE_BULBASAUR              297
#define MMODEL_TSURE_POKE_IVYSAUR                298
#define MMODEL_TSURE_POKE_VENUSAUR               299
#define MMODEL_TSURE_POKE_VENUSAUR_F             300
#define MMODEL_TSURE_POKE_CHARMANDER             301
#define MMODEL_TSURE_POKE_CHARMELEON             302
#define MMODEL_TSURE_POKE_CHARIZARD              303
#define MMODEL_TSURE_POKE_SQUIRTLE               304
#define MMODEL_TSURE_POKE_WARTORTLE              305
#define MMODEL_TSURE_POKE_BLASTOISE              306
#define MMODEL_TSURE_POKE_CATERPIE               307
#define MMODEL_TSURE_POKE_METAPOD                308
#define MMODEL_TSURE_POKE_BUTTERFREE             309
#define MMODEL_TSURE_POKE_WEEDLE                 310
#define MMODEL_TSURE_POKE_KAKUNA                 311
#define MMODEL_TSURE_POKE_BEEDRILL               312
#define MMODEL_TSURE_POKE_PIDGEY                 313
#define MMODEL_TSURE_POKE_PIDGEOTTO              314
#define MMODEL_TSURE_POKE_PIDGEOT                315
#define MMODEL_TSURE_POKE_RATTATA                316
#define MMODEL_TSURE_POKE_RATICATE               317
#define MMODEL_TSURE_POKE_SPEAROW                318
#define MMODEL_TSURE_POKE_FEAROW                 319
#define MMODEL_TSURE_POKE_EKANS                  320
#define MMODEL_TSURE_POKE_ARBOK                  321
#define MMODEL_TSURE_POKE_PIKACHU                322
#define MMODEL_TSURE_POKE_PIKACHU_F              323
#define MMODEL_TSURE_POKE_RAICHU                 324
#define MMODEL_TSURE_POKE_SANDSHREW              325
#define MMODEL_TSURE_POKE_SANDSLASH              326
#define MMODEL_TSURE_POKE_NIDORAN_F              327
#define MMODEL_TSURE_POKE_NIDORINA               328
#define MMODEL_TSURE_POKE_NIDOQUEEN              329
#define MMODEL_TSURE_POKE_NIDORAN_M              330
#define MMODEL_TSURE_POKE_NIDORINO               331
#define MMODEL_TSURE_POKE_NIDOKING               332
#define MMODEL_TSURE_POKE_CLEFAIRY               333
#define MMODEL_TSURE_POKE_CLEFABLE               334
#define MMODEL_TSURE_POKE_VULPIX                 335
#define MMODEL_TSURE_POKE_NINETALES              336
#define MMODEL_TSURE_POKE_JIGGLYPUFF             337
#define MMODEL_TSURE_POKE_WIGGLYTUFF             338
#define MMODEL_TSURE_POKE_ZUBAT                  339
#define MMODEL_TSURE_POKE_GOLBAT                 340
#define MMODEL_TSURE_POKE_ODDISH                 341
#define MMODEL_TSURE_POKE_GLOOM                  342
#define MMODEL_TSURE_POKE_VILEPLUME              343
#define MMODEL_TSURE_POKE_PARAS                  344
#define MMODEL_TSURE_POKE_PARASECT               345
#define MMODEL_TSURE_POKE_VENONAT                346
#define MMODEL_TSURE_POKE_VENOMOTH               347
#define MMODEL_TSURE_POKE_DIGLETT                348
#define MMODEL_TSURE_POKE_DUGTRIO                349
#define MMODEL_TSURE_POKE_MEOWTH                 350
#define MMODEL_TSURE_POKE_PERSIAN                351
#define MMODEL_TSURE_POKE_PSYDUCK                352
#define MMODEL_TSURE_POKE_GOLDUCK                353
#define MMODEL_TSURE_POKE_MANKEY                 354
#define MMODEL_TSURE_POKE_PRIMEAPE               355
#define MMODEL_TSURE_POKE_GROWLITHE              356
#define MMODEL_TSURE_POKE_ARCANINE               357
#define MMODEL_TSURE_POKE_POLIWAG                358
#define MMODEL_TSURE_POKE_POLIWHIRL              359
#define MMODEL_TSURE_POKE_POLIWRATH              360
#define MMODEL_TSURE_POKE_ABRA                   361
#define MMODEL_TSURE_POKE_KADABRA                362
#define MMODEL_TSURE_POKE_ALAKAZAM               363
#define MMODEL_TSURE_POKE_MACHOP                 364
#define MMODEL_TSURE_POKE_MACHOKE                365
#define MMODEL_TSURE_POKE_MACHAMP                366
#define MMODEL_TSURE_POKE_BELLSPROUT             367
#define MMODEL_TSURE_POKE_WEEPINBELL             368
#define MMODEL_TSURE_POKE_VICTREEBEL             369
#define MMODEL_TSURE_POKE_TENTACOOL              370
#define MMODEL_TSURE_POKE_TENTACRUEL             371
#define MMODEL_TSURE_POKE_GEODUDE                372
#define MMODEL_TSURE_POKE_GRAVELER               373
#define MMODEL_TSURE_POKE_GOLEM                  374
#define MMODEL_TSURE_POKE_PONYTA                 375
#define MMODEL_TSURE_POKE_RAPIDASH               376
#define MMODEL_TSURE_POKE_SLOWPOKE               377
#define MMODEL_TSURE_POKE_SLOWBRO                378
#define MMODEL_TSURE_POKE_MAGNEMITE              379
#define MMODEL_TSURE_POKE_MAGNETON               380
#define MMODEL_TSURE_POKE_FARFETCHD              381
#define MMODEL_TSURE_POKE_DODUO                  382
#define MMODEL_TSURE_POKE_DODRIO                 383
#define MMODEL_TSURE_POKE_SEEL                   384
#define MMODEL_TSURE_POKE_DEWGONG                385
#define MMODEL_TSURE_POKE_GRIMER                 386
#define MMODEL_TSURE_POKE_MUK                    387
#define MMODEL_TSURE_POKE_SHELLDER               388
#define MMODEL_TSURE_POKE_CLOYSTER               389
#define MMODEL_TSURE_POKE_GASTLY                 390
#define MMODEL_TSURE_POKE_HAUNTER                391
#define MMODEL_TSURE_POKE_GENGAR                 392
#define MMODEL_TSURE_POKE_ONIX                   393
#define MMODEL_TSURE_POKE_DROWZEE                394
#define MMODEL_TSURE_POKE_HYPNO                  395
#define MMODEL_TSURE_POKE_KRABBY                 396
#define MMODEL_TSURE_POKE_KINGLER                397
#define MMODEL_TSURE_POKE_VOLTORB                398
#define MMODEL_TSURE_POKE_ELECTRODE              399
#define MMODEL_TSURE_POKE_EXEGGCUTE              400
#define MMODEL_TSURE_POKE_EXEGGUTOR              401
#define MMODEL_TSURE_POKE_CUBONE                 402
#define MMODEL_TSURE_POKE_MAROWAK                403
#define MMODEL_TSURE_POKE_HITMONLEE              404
#define MMODEL_TSURE_POKE_HITMONCHAN             405
#define MMODEL_TSURE_POKE_LICKITUNG              406
#define MMODEL_TSURE_POKE_KOFFING                407
#define MMODEL_TSURE_POKE_WEEZING                408
#define MMODEL_TSURE_POKE_RHYHORN                409
#define MMODEL_TSURE_POKE_RHYDON                 410
#define MMODEL_TSURE_POKE_CHANSEY                411
#define MMODEL_TSURE_POKE_TANGELA                412
#define MMODEL_TSURE_POKE_KANGASKHAN             413
#define MMODEL_TSURE_POKE_HORSEA                 414
#define MMODEL_TSURE_POKE_SEADRA                 415
#define MMODEL_TSURE_POKE_GOLDEEN                416
#define MMODEL_TSURE_POKE_SEAKING                417
#define MMODEL_TSURE_POKE_STARYU                 418
#define MMODEL_TSURE_POKE_STARMIE                419
#define MMODEL_TSURE_POKE_MR_MIME                420
#define MMODEL_TSURE_POKE_SCYTHER                421
#define MMODEL_TSURE_POKE_JYNX                   422
#define MMODEL_TSURE_POKE_ELECTABUZZ             423
#define MMODEL_TSURE_POKE_MAGMAR                 424
#define MMODEL_TSURE_POKE_PINSIR                 425
#define MMODEL_TSURE_POKE_TAUROS                 426
#define MMODEL_TSURE_POKE_MAGIKARP               427
#define MMODEL_TSURE_POKE_GYARADOS               428
#define MMODEL_TSURE_POKE_LAPRAS                 429
#define MMODEL_TSURE_POKE_DITTO                  430
#define MMODEL_TSURE_POKE_EEVEE                  431
#define MMODEL_TSURE_POKE_VAPOREON               432
#define MMODEL_TSURE_POKE_JOLTEON                433
#define MMODEL_TSURE_POKE_FLAREON                434
#define MMODEL_TSURE_POKE_PORYGON                435
#define MMODEL_TSURE_POKE_OMANYTE                436
#define MMODEL_TSURE_POKE_OMASTAR                437
#define MMODEL_TSURE_POKE_KABUTO                 438
#define MMODEL_TSURE_POKE_KABUTOPS               439
#define MMODEL_TSURE_POKE_AERODACTYL             440
#define MMODEL_TSURE_POKE_SNORLAX                441
#define MMODEL_TSURE_POKE_ARTICUNO               442
#define MMODEL_TSURE_POKE_ZAPDOS                 443
#define MMODEL_TSURE_POKE_MOLTRES                444
#define MMODEL_TSURE_POKE_DRATINI                445
#define MMODEL_TSURE_POKE_DRAGONAIR              446
#define MMODEL_TSURE_POKE_DRAGONITE              447
#define MMODEL_TSURE_POKE_MEWTWO                 448
#define MMODEL_TSURE_POKE_MEW                    449
#define MMODEL_TSURE_POKE_CHIKORITA              450
#define MMODEL_TSURE_POKE_BAYLEEF                451
#define MMODEL_TSURE_POKE_MEGANIUM               452
#define MMODEL_TSURE_POKE_MEGANIUM_F             453
#define MMODEL_TSURE_POKE_CYNDAQUIL              454
#define MMODEL_TSURE_POKE_QUILAVA                455
#define MMODEL_TSURE_POKE_TYPHLOSION             456
#define MMODEL_TSURE_POKE_TOTODILE               457
#define MMODEL_TSURE_POKE_CROCONAW               458
#define MMODEL_TSURE_POKE_FERALIGATR             459
#define MMODEL_TSURE_POKE_SENTRET                460
#define MMODEL_TSURE_POKE_FURRET                 461
#define MMODEL_TSURE_POKE_HOOTHOOT               462
#define MMODEL_TSURE_POKE_NOCTOWL                463
#define MMODEL_TSURE_POKE_LEDYBA                 464
#define MMODEL_TSURE_POKE_LEDIAN                 465
#define MMODEL_TSURE_POKE_SPINARAK               466
#define MMODEL_TSURE_POKE_ARIADOS                467
#define MMODEL_TSURE_POKE_CROBAT                 468
#define MMODEL_TSURE_POKE_CHINCHOU               469
#define MMODEL_TSURE_POKE_LANTURN                470
#define MMODEL_TSURE_POKE_PICHU                  471
#define MMODEL_TSURE_POKE_PICHU_SPIKY            472
#define MMODEL_TSURE_POKE_CLEFFA                 473
#define MMODEL_TSURE_POKE_IGGLYBUFF              474
#define MMODEL_TSURE_POKE_TOGEPI                 475
#define MMODEL_TSURE_POKE_TOGETIC                476
#define MMODEL_TSURE_POKE_NATU                   477
#define MMODEL_TSURE_POKE_XATU                   478
#define MMODEL_TSURE_POKE_MAREEP                 479
#define MMODEL_TSURE_POKE_FLAAFFY                480
#define MMODEL_TSURE_POKE_AMPHAROS               481
#define MMODEL_TSURE_POKE_BELLOSSOM              482
#define MMODEL_TSURE_POKE_MARILL                 483
#define MMODEL_TSURE_POKE_AZUMARILL              484
#define MMODEL_TSURE_POKE_SUDOWOODO              485
#define MMODEL_TSURE_POKE_POLITOED               486
#define MMODEL_TSURE_POKE_HOPPIP                 487
#define MMODEL_TSURE_POKE_SKIPLOOM               488
#define MMODEL_TSURE_POKE_JUMPLUFF               489
#define MMODEL_TSURE_POKE_AIPOM                  490
#define MMODEL_TSURE_POKE_SUNKERN                491
#define MMODEL_TSURE_POKE_SUNFLORA               492
#define MMODEL_TSURE_POKE_YANMA                  493
#define MMODEL_TSURE_POKE_WOOPER                 494
#define MMODEL_TSURE_POKE_QUAGSIRE               495
#define MMODEL_TSURE_POKE_ESPEON                 496
#define MMODEL_TSURE_POKE_UMBREON                497
#define MMODEL_TSURE_POKE_MURKROW                498
#define MMODEL_TSURE_POKE_SLOWKING               499
#define MMODEL_TSURE_POKE_MISDREAVUS             500
#define MMODEL_TSURE_POKE_UNOWN_A                501
#define MMODEL_TSURE_POKE_UNOWN_B                502
#define MMODEL_TSURE_POKE_UNOWN_C                503
#define MMODEL_TSURE_POKE_UNOWN_D                504
#define MMODEL_TSURE_POKE_UNOWN_E                505
#define MMODEL_TSURE_POKE_UNOWN_F                506
#define MMODEL_TSURE_POKE_UNOWN_G                507
#define MMODEL_TSURE_POKE_UNOWN_H                508
#define MMODEL_TSURE_POKE_UNOWN_I                509
#define MMODEL_TSURE_POKE_UNOWN_J                510
#define MMODEL_TSURE_POKE_UNOWN_K                511
#define MMODEL_TSURE_POKE_UNOWN_L                512
#define MMODEL_TSURE_POKE_UNOWN_M                513
#define MMODEL_TSURE_POKE_UNOWN_N                514
#define MMODEL_TSURE_POKE_UNOWN_O                515
#define MMODEL_TSURE_POKE_UNOWN_P                516
#define MMODEL_TSURE_POKE_UNOWN_Q                517
#define MMODEL_TSURE_POKE_UNOWN_R                518
#define MMODEL_TSURE_POKE_UNOWN_S                519
#define MMODEL_TSURE_POKE_UNOWN_T                520
#define MMODEL_TSURE_POKE_UNOWN_U                521
#define MMODEL_TSURE_POKE_UNOWN_V                522
#define MMODEL_TSURE_POKE_UNOWN_W                523
#define MMODEL_TSURE_POKE_UNOWN_X                524
#define MMODEL_TSURE_POKE_UNOWN_Y                525
#define MMODEL_TSURE_POKE_UNOWN_Z                526
#define MMODEL_TSURE_POKE_UNOWN_QMARK            527
#define MMODEL_TSURE_POKE_UNOWN_EXCL             528
#define MMODEL_TSURE_POKE_WOBBUFFET              529
#define MMODEL_TSURE_POKE_WOBBUFFET_F            530
#define MMODEL_TSURE_POKE_GIRAFARIG              531
#define MMODEL_TSURE_POKE_PINECO                 532
#define MMODEL_TSURE_POKE_FORRETRESS             533
#define MMODEL_TSURE_POKE_DUNSPARCE              534
#define MMODEL_TSURE_POKE_GLIGAR                 535
#define MMODEL_TSURE_POKE_STEELIX                536
#define MMODEL_TSURE_POKE_STEELIX_F              537
#define MMODEL_TSURE_POKE_SNUBBULL               538
#define MMODEL_TSURE_POKE_GRANBULL               539
#define MMODEL_TSURE_POKE_QWILFISH               540
#define MMODEL_TSURE_POKE_SCIZOR                 541
#define MMODEL_TSURE_POKE_SHUCKLE                542
#define MMODEL_TSURE_POKE_HERACROSS              543
#define MMODEL_TSURE_POKE_HERACROSS_F            544
#define MMODEL_TSURE_POKE_SNEASEL                545
#define MMODEL_TSURE_POKE_TEDDIURSA              546
#define MMODEL_TSURE_POKE_URSARING               547
#define MMODEL_TSURE_POKE_SLUGMA                 548
#define MMODEL_TSURE_POKE_MAGCARGO               549
#define MMODEL_TSURE_POKE_SWINUB                 550
#define MMODEL_TSURE_POKE_PILOSWINE              551
#define MMODEL_TSURE_POKE_CORSOLA                552
#define MMODEL_TSURE_POKE_REMORAID               553
#define MMODEL_TSURE_POKE_OCTILLERY              554
#define MMODEL_TSURE_POKE_DELIBIRD               555
#define MMODEL_TSURE_POKE_MANTINE                556
#define MMODEL_TSURE_POKE_SKARMORY               557
#define MMODEL_TSURE_POKE_HOUNDOUR               558
#define MMODEL_TSURE_POKE_HOUNDOOM               559
#define MMODEL_TSURE_POKE_KINGDRA                560
#define MMODEL_TSURE_POKE_PHANPY                 561
#define MMODEL_TSURE_POKE_DONPHAN                562
#define MMODEL_TSURE_POKE_PORYGON2               563
#define MMODEL_TSURE_POKE_STANTLER               564
#define MMODEL_TSURE_POKE_SMEARGLE               565
#define MMODEL_TSURE_POKE_TYROGUE                566
#define MMODEL_TSURE_POKE_HITMONTOP              567
#define MMODEL_TSURE_POKE_SMOOCHUM               568
#define MMODEL_TSURE_POKE_ELEKID                 569
#define MMODEL_TSURE_POKE_MAGBY                  570
#define MMODEL_TSURE_POKE_MILTANK                571
#define MMODEL_TSURE_POKE_BLISSEY                572
#define MMODEL_TSURE_POKE_RAIKOU                 573
#define MMODEL_TSURE_POKE_ENTEI                  574
#define MMODEL_TSURE_POKE_SUICUNE                575
#define MMODEL_TSURE_POKE_LARVITAR               576
#define MMODEL_TSURE_POKE_PUPITAR                577
#define MMODEL_TSURE_POKE_TYRANITAR              578
#define MMODEL_TSURE_POKE_LUGIA                  579
#define MMODEL_TSURE_POKE_HO_OH                  580
#define MMODEL_TSURE_POKE_CELEBI                 581
#define MMODEL_TSURE_POKE_TREECKO                582
#define MMODEL_TSURE_POKE_GROVYLE                583
#define MMODEL_TSURE_POKE_SCEPTILE               584
#define MMODEL_TSURE_POKE_TORCHIC                585
#define MMODEL_TSURE_POKE_COMBUSKEN              586
#define MMODEL_TSURE_POKE_BLAZIKEN               587
#define MMODEL_TSURE_POKE_MUDKIP                 588
#define MMODEL_TSURE_POKE_MARSHTOMP              589
#define MMODEL_TSURE_POKE_SWAMPERT               590
#define MMODEL_TSURE_POKE_POOCHYENA              591
#define MMODEL_TSURE_POKE_MIGHTYENA              592
#define MMODEL_TSURE_POKE_ZIGZAGOON              593
#define MMODEL_TSURE_POKE_LINOONE                594
#define MMODEL_TSURE_POKE_WURMPLE                595
#define MMODEL_TSURE_POKE_SILCOON                596
#define MMODEL_TSURE_POKE_BEAUTIFLY              597
#define MMODEL_TSURE_POKE_CASCOON                598
#define MMODEL_TSURE_POKE_DUSTOX                 599
#define MMODEL_TSURE_POKE_LOTAD                  600
#define MMODEL_TSURE_POKE_LOMBRE                 601
#define MMODEL_TSURE_POKE_LUDICOLO               602
#define MMODEL_TSURE_POKE_SEEDOT                 603
#define MMODEL_TSURE_POKE_NUZLEAF                604
#define MMODEL_TSURE_POKE_SHIFTRY                605
#define MMODEL_TSURE_POKE_TAILLOW                606
#define MMODEL_TSURE_POKE_SWELLOW                607
#define MMODEL_TSURE_POKE_WINGULL                608
#define MMODEL_TSURE_POKE_PELIPPER               609
#define MMODEL_TSURE_POKE_RALTS                  610
#define MMODEL_TSURE_POKE_KIRLIA                 611
#define MMODEL_TSURE_POKE_GARDEVOIR              612
#define MMODEL_TSURE_POKE_SURSKIT                613
#define MMODEL_TSURE_POKE_MASQUERAIN             614
#define MMODEL_TSURE_POKE_SHROOMISH              615
#define MMODEL_TSURE_POKE_BRELOOM                616
#define MMODEL_TSURE_POKE_SLAKOTH                617
#define MMODEL_TSURE_POKE_VIGOROTH               618
#define MMODEL_TSURE_POKE_SLAKING                619
#define MMODEL_TSURE_POKE_NINCADA                620
#define MMODEL_TSURE_POKE_NINJASK                621
#define MMODEL_TSURE_POKE_SHEDINJA               622
#define MMODEL_TSURE_POKE_WHISMUR                623
#define MMODEL_TSURE_POKE_LOUDRED                624
#define MMODEL_TSURE_POKE_EXPLOUD                625
#define MMODEL_TSURE_POKE_MAKUHITA               626
#define MMODEL_TSURE_POKE_HARIYAMA               627
#define MMODEL_TSURE_POKE_AZURILL                628
#define MMODEL_TSURE_POKE_NOSEPASS               629
#define MMODEL_TSURE_POKE_SKITTY                 630
#define MMODEL_TSURE_POKE_DELCATTY               631
#define MMODEL_TSURE_POKE_SABLEYE                632
#define MMODEL_TSURE_POKE_MAWILE                 633
#define MMODEL_TSURE_POKE_ARON                   634
#define MMODEL_TSURE_POKE_LAIRON                 635
#define MMODEL_TSURE_POKE_AGGRON                 636
#define MMODEL_TSURE_POKE_MEDITITE               637
#define MMODEL_TSURE_POKE_MEDICHAM               638
#define MMODEL_TSURE_POKE_ELECTRIKE              639
#define MMODEL_TSURE_POKE_MANECTRIC              640
#define MMODEL_TSURE_POKE_PLUSLE                 641
#define MMODEL_TSURE_POKE_MINUN                  642
#define MMODEL_TSURE_POKE_VOLBEAT                643
#define MMODEL_TSURE_POKE_ILLUMISE               644
#define MMODEL_TSURE_POKE_ROSELIA                645
#define MMODEL_TSURE_POKE_GULPIN                 646
#define MMODEL_TSURE_POKE_SWALOT                 647
#define MMODEL_TSURE_POKE_CARVANHA               648
#define MMODEL_TSURE_POKE_SHARPEDO               649
#define MMODEL_TSURE_POKE_WAILMER                650
#define MMODEL_TSURE_POKE_WAILORD                651
#define MMODEL_TSURE_POKE_NUMEL                  652
#define MMODEL_TSURE_POKE_CAMERUPT               653
#define MMODEL_TSURE_POKE_TORKOAL                654
#define MMODEL_TSURE_POKE_SPOINK                 655
#define MMODEL_TSURE_POKE_GRUMPIG                656
#define MMODEL_TSURE_POKE_SPINDA                 657
#define MMODEL_TSURE_POKE_TRAPINCH               658
#define MMODEL_TSURE_POKE_VIBRAVA                659
#define MMODEL_TSURE_POKE_FLYGON                 660
#define MMODEL_TSURE_POKE_CACNEA                 661
#define MMODEL_TSURE_POKE_CACTURNE               662
#define MMODEL_TSURE_POKE_SWABLU                 663
#define MMODEL_TSURE_POKE_ALTARIA                664
#define MMODEL_TSURE_POKE_ZANGOOSE               665
#define MMODEL_TSURE_POKE_SEVIPER                666
#define MMODEL_TSURE_POKE_LUNATONE               667
#define MMODEL_TSURE_POKE_SOLROCK                668
#define MMODEL_TSURE_POKE_BARBOACH               669
#define MMODEL_TSURE_POKE_WHISCASH               670
#define MMODEL_TSURE_POKE_CORPHISH               671
#define MMODEL_TSURE_POKE_CRAWDAUNT              672
#define MMODEL_TSURE_POKE_BALTOY                 673
#define MMODEL_TSURE_POKE_CLAYDOL                674
#define MMODEL_TSURE_POKE_LILEEP                 675
#define MMODEL_TSURE_POKE_CRADILY                676
#define MMODEL_TSURE_POKE_ANORITH                677
#define MMODEL_TSURE_POKE_ARMALDO                678
#define MMODEL_TSURE_POKE_FEEBAS                 679
#define MMODEL_TSURE_POKE_MILOTIC                680
#define MMODEL_TSURE_POKE_CASTFORM               681
#define MMODEL_TSURE_POKE_KECLEON                682
#define MMODEL_TSURE_POKE_SHUPPET                683
#define MMODEL_TSURE_POKE_BANETTE                684
#define MMODEL_TSURE_POKE_DUSKULL                685
#define MMODEL_TSURE_POKE_DUSCLOPS               686
#define MMODEL_TSURE_POKE_TROPIUS                687
#define MMODEL_TSURE_POKE_CHIMECHO               688
#define MMODEL_TSURE_POKE_ABSOL                  689
#define MMODEL_TSURE_POKE_WYNAUT                 690
#define MMODEL_TSURE_POKE_SNORUNT                691
#define MMODEL_TSURE_POKE_GLALIE                 692
#define MMODEL_TSURE_POKE_SPHEAL                 693
#define MMODEL_TSURE_POKE_SEALEO                 694
#define MMODEL_TSURE_POKE_WALREIN                695
#define MMODEL_TSURE_POKE_CLAMPERL               696
#define MMODEL_TSURE_POKE_HUNTAIL                697
#define MMODEL_TSURE_POKE_GOREBYSS               698
#define MMODEL_TSURE_POKE_RELICANTH              699
#define MMODEL_TSURE_POKE_LUVDISC                700
#define MMODEL_TSURE_POKE_BAGON                  701
#define MMODEL_TSURE_POKE_SHELGON                702
#define MMODEL_TSURE_POKE_SALAMENCE              703
#define MMODEL_TSURE_POKE_BELDUM                 704
#define MMODEL_TSURE_POKE_METANG                 705
#define MMODEL_TSURE_POKE_METAGROSS              706
#define MMODEL_TSURE_POKE_REGIROCK               707
#define MMODEL_TSURE_POKE_REGICE                 708
#define MMODEL_TSURE_POKE_REGISTEEL              709
#define MMODEL_TSURE_POKE_LATIAS                 710
#define MMODEL_TSURE_POKE_LATIOS                 711
#define MMODEL_TSURE_POKE_KYOGRE                 712
#define MMODEL_TSURE_POKE_GROUDON                713
#define MMODEL_TSURE_POKE_RAYQUAZA               714
#define MMODEL_TSURE_POKE_JIRACHI                715
#define MMODEL_TSURE_POKE_DEOXYS                 716
#define MMODEL_TSURE_POKE_DEOXYS_ATK             717
#define MMODEL_TSURE_POKE_DEOXYS_DEF             718
#define MMODEL_TSURE_POKE_DEOXYS_SPD             719
#define MMODEL_TSURE_POKE_TURTWIG                720
#define MMODEL_TSURE_POKE_GROTLE                 721
#define MMODEL_TSURE_POKE_TORTERRA               722
#define MMODEL_TSURE_POKE_CHIMCHAR               723
#define MMODEL_TSURE_POKE_MONFERNO               724
#define MMODEL_TSURE_POKE_INFERNAPE              725
#define MMODEL_TSURE_POKE_PIPLUP                 726
#define MMODEL_TSURE_POKE_PRINPLUP               727
#define MMODEL_TSURE_POKE_EMPOLEON               728
#define MMODEL_TSURE_POKE_STARLY                 729
#define MMODEL_TSURE_POKE_STARAVIA               730
#define MMODEL_TSURE_POKE_STARAPTOR              731
#define MMODEL_TSURE_POKE_BIDOOF                 732
#define MMODEL_TSURE_POKE_BIBAREL                733
#define MMODEL_TSURE_POKE_KRICKETOT              734
#define MMODEL_TSURE_POKE_KRICKETUNE             735
#define MMODEL_TSURE_POKE_SHINX                  736
#define MMODEL_TSURE_POKE_LUXIO                  737
#define MMODEL_TSURE_POKE_LUXRAY                 738
#define MMODEL_TSURE_POKE_BUDEW                  739
#define MMODEL_TSURE_POKE_ROSERADE               740
#define MMODEL_TSURE_POKE_CRANIDOS               741
#define MMODEL_TSURE_POKE_RAMPARDOS              742
#define MMODEL_TSURE_POKE_SHIELDON               743
#define MMODEL_TSURE_POKE_BASTIODON              744
#define MMODEL_TSURE_POKE_BURMY                  745
#define MMODEL_TSURE_POKE_BURMY_SANDY            746
#define MMODEL_TSURE_POKE_BURMY_TRASH            747
#define MMODEL_TSURE_POKE_WORMADAM               748
#define MMODEL_TSURE_POKE_WORMADAM_SANDY         749
#define MMODEL_TSURE_POKE_WORMADAM_TRASH         750
#define MMODEL_TSURE_POKE_MOTHIM                 751
#define MMODEL_TSURE_POKE_COMBEE                 752
#define MMODEL_TSURE_POKE_COMBEE_F               753
#define MMODEL_TSURE_POKE_VESPIQUEN              754
#define MMODEL_TSURE_POKE_PACHIRISU              755
#define MMODEL_TSURE_POKE_BUIZEL                 756
#define MMODEL_TSURE_POKE_FLOATZEL               757
#define MMODEL_TSURE_POKE_CHERUBI                758
#define MMODEL_TSURE_POKE_CHERRIM                759
#define MMODEL_TSURE_POKE_SHELLOS_WEST           760
#define MMODEL_TSURE_POKE_SHELLOS_EAST           761
#define MMODEL_TSURE_POKE_GASTRODON_WEST         762
#define MMODEL_TSURE_POKE_GASTRODON_EAST         763
#define MMODEL_TSURE_POKE_AMBIPOM                764
#define MMODEL_TSURE_POKE_DRIFLOON               765
#define MMODEL_TSURE_POKE_DRIFBLIM               766
#define MMODEL_TSURE_POKE_BUNEARY                767
#define MMODEL_TSURE_POKE_LOPUNNY                768
#define MMODEL_TSURE_POKE_MISMAGIUS              769
#define MMODEL_TSURE_POKE_HONCHKROW              770
#define MMODEL_TSURE_POKE_GLAMEOW                771
#define MMODEL_TSURE_POKE_PURUGLY                772
#define MMODEL_TSURE_POKE_CHINGLING              773
#define MMODEL_TSURE_POKE_STUNKY                 774
#define MMODEL_TSURE_POKE_SKUNTANK               775
#define MMODEL_TSURE_POKE_BRONZOR                776
#define MMODEL_TSURE_POKE_BRONZONG               777
#define MMODEL_TSURE_POKE_BONSLY                 778
#define MMODEL_TSURE_POKE_MIME_JR                779
#define MMODEL_TSURE_POKE_HAPPINY                780
#define MMODEL_TSURE_POKE_CHATOT                 781
#define MMODEL_TSURE_POKE_SPIRITOMB              782
#define MMODEL_TSURE_POKE_GIBLE                  783
#define MMODEL_TSURE_POKE_GIBLE_F                784
#define MMODEL_TSURE_POKE_GABITE                 785
#define MMODEL_TSURE_POKE_GABITE_F               786
#define MMODEL_TSURE_POKE_GARCHOMP               787
#define MMODEL_TSURE_POKE_GARCHOMP_F             788
#define MMODEL_TSURE_POKE_MUNCHLAX               789
#define MMODEL_TSURE_POKE_RIOLU                  790
#define MMODEL_TSURE_POKE_LUCARIO                791
#define MMODEL_TSURE_POKE_HIPPOPOTAS             792
#define MMODEL_TSURE_POKE_HIPPOPOTAS_F           793
#define MMODEL_TSURE_POKE_HIPPOWDON              794
#define MMODEL_TSURE_POKE_HIPPOWDON_F            795
#define MMODEL_TSURE_POKE_SKORUPI                796
#define MMODEL_TSURE_POKE_DRAPION                797
#define MMODEL_TSURE_POKE_CROAGUNK               798
#define MMODEL_TSURE_POKE_TOXICROAK              799
#define MMODEL_TSURE_POKE_CARNIVINE              800
#define MMODEL_TSURE_POKE_FINNEON                801
#define MMODEL_TSURE_POKE_LUMINEON               802
#define MMODEL_TSURE_POKE_MANTYKE                803
#define MMODEL_TSURE_POKE_SNOVER                 804
#define MMODEL_TSURE_POKE_ABOMASNOW              805
#define MMODEL_TSURE_POKE_WEAVILE                806
#define MMODEL_TSURE_POKE_MAGNEZONE              807
#define MMODEL_TSURE_POKE_LICKILICKY             808
#define MMODEL_TSURE_POKE_RHYPERIOR              809
#define MMODEL_TSURE_POKE_TANGROWTH              810
#define MMODEL_TSURE_POKE_ELECTIVIRE             811
#define MMODEL_TSURE_POKE_MAGMORTAR              812
#define MMODEL_TSURE_POKE_TOGEKISS               813
#define MMODEL_TSURE_POKE_YANMEGA                814
#define MMODEL_TSURE_POKE_LEAFEON                815
#define MMODEL_TSURE_POKE_GLACEON                816
#define MMODEL_TSURE_POKE_GLISCOR                817
#define MMODEL_TSURE_POKE_MAMOSWINE              818
#define MMODEL_TSURE_POKE_PORYGON_Z              819
#define MMODEL_TSURE_POKE_GALLADE                820
#define MMODEL_TSURE_POKE_PROBOPASS              821
#define MMODEL_TSURE_POKE_DUSKNOIR               822
#define MMODEL_TSURE_POKE_FROSLASS               823
#define MMODEL_TSURE_POKE_ROTOM                  824
#define MMODEL_TSURE_POKE_ROTOM_HEAT             825
#define MMODEL_TSURE_POKE_ROTOM_WASH             826
#define MMODEL_TSURE_POKE_ROTOM_FROST            827
#define MMODEL_TSURE_POKE_ROTOM_FAN              828
#define MMODEL_TSURE_POKE_ROTOM_MOW              829
#define MMODEL_TSURE_POKE_UXIE                   830
#define MMODEL_TSURE_POKE_MESPRIT                831
#define MMODEL_TSURE_POKE_AZELF                  832
#define MMODEL_TSURE_POKE_DIALGA                 833
#define MMODEL_TSURE_POKE_PALKIA                 834
#define MMODEL_TSURE_POKE_HEATRAN                835
#define MMODEL_TSURE_POKE_REGIGIGAS              836
#define MMODEL_TSURE_POKE_GIRATINA               837
#define MMODEL_TSURE_POKE_GIRATINA_ORIGIN        838
#define MMODEL_TSURE_POKE_CRESSELIA              839
#define MMODEL_TSURE_POKE_PHIONE                 840
#define MMODEL_TSURE_POKE_MANAPHY                841
#define MMODEL_TSURE_POKE_DARKRAI                842
#define MMODEL_TSURE_POKE_SHAYMIN                843
#define MMODEL_TSURE_POKE_SHAYMIN_SKY            844
#define MMODEL_TSURE_POKE_ARCEUS_NORMAL          845
#define MMODEL_TSURE_POKE_ARCEUS_FIGHTING        846
#define MMODEL_TSURE_POKE_ARCEUS_FLYING          847
#define MMODEL_TSURE_POKE_ARCEUS_POISON          848
#define MMODEL_TSURE_POKE_ARCEUS_GROUND          849
#define MMODEL_TSURE_POKE_ARCEUS_ROCK            850
#define MMODEL_TSURE_POKE_ARCEUS_BUG             851
#define MMODEL_TSURE_POKE_ARCEUS_GHOST           852
#define MMODEL_TSURE_POKE_ARCEUS_STEEL           853
#define MMODEL_TSURE_POKE_ARCEUS_MYSTERY         854
#define MMODEL_TSURE_POKE_ARCEUS_FIRE            855
#define MMODEL_TSURE_POKE_ARCEUS_WATER           856
#define MMODEL_TSURE_POKE_ARCEUS_GRASS           857
#define MMODEL_TSURE_POKE_ARCEUS_ELECTRIC        858
#define MMODEL_TSURE_POKE_ARCEUS_PSYCHIC         859
#define MMODEL_TSURE_POKE_ARCEUS_ICE             860
#define MMODEL_TSURE_POKE_ARCEUS_DRAGON          861
#define MMODEL_TSURE_POKE_ARCEUS_DARK            862

#endif //POKEHEARTGOLD_CONSTANTS_MMODEL_H
