#ifndef POKEHEARTGOLD_CONSTANTS_NPC_TRADE_H
#define POKEHEARTGOLD_CONSTANTS_NPC_TRADE_H

typedef enum NpcTradeNum {
    NPC_TRADE_ROCKY_ONIX,
    NPC_TRADE_MUSCLE_MACHOP,
    NPC_TRADE_BILLY_VOLTORB,
    NPC_TRADE_DORIS_DODRIO,
    NPC_TRADE_SPRINTS_RAPIDASH,
    NPC_TRADE_RUSTY_STEELIX,
    NPC_TRADE_SHUCKIE_SHUCKLE,
    NPC_TRADE_KENYA_SPEAROW,
    NPC_TRADE_MAGGIE_MAGNETON,
    NPC_TRADE_PAUL_XATU,
    NPC_TRADE_VOLTY_PIKACHU,
    NPC_TRADE_HORNLETTE_RHYHORN,
    NPC_TRADE_IRON_BELDUM,
    NPC_TRADE_MAX,
} NpcTradeNum;

// Used to index into NARC_msg_msg_0200_bin
#define NPC_TRADE_OT_NUM(tradeNum) (tradeNum + NPC_TRADE_MAX)

#endif // POKEHEARTGOLD_CONSTANTS_NPC_TRADE_H
