#ifndef POKEHEARTGOLD_CONSTANTS_PARTY_MENU_H
#define POKEHEARTGOLD_CONSTANTS_PARTY_MENU_H

#define PARTY_MENU_RESPONSE_OK              0
#define PARTY_MENU_RESPONSE_NOT_HERE        1
#define PARTY_MENU_RESPONSE_NEED_BADGE      2
#define PARTY_MENU_RESPONSE_HAVE_FOLLOWER   3
#define PARTY_MENU_RESPONSE_ALREADY_SURFING 4
#define PARTY_MENU_RESPONSE_NOT_NOW         5

#endif // POKEHEARTGOLD_CONSTANTS_PARTY_MENU_H
