#ifndef POKEHEARTGOLD_CONSTANTS_PLAYER_AVATAR_H
#define POKEHEARTGOLD_CONSTANTS_PLAYER_AVATAR_H

#define PLAYER_EVENT_NONE             0
#define PLAYER_EVENT_USED_STRENGTH    (1 << 0)
#define PLAYER_EVENT_USED_WATERFALL   (1 << 1)

enum PlayerMoveState {
    PLAYER_MOVE_STATE_NONE = 0,
    PLAYER_MOVE_STATE_START,
    PLAYER_MOVE_STATE_MOVING,
    PLAYER_MOVE_STATE_END,
};

enum AvatarMoveState {
    AVATAR_MOVE_STATE_NONE = 0,
    AVATAR_MOVE_STATE_MOVING,
    AVATAR_MOVE_STATE_TURNING,
};

#endif // POKEHEARTGOLD_CONSTANTS_PLAYER_AVATAR_H
