#ifndef POKEHEARTGOLD_CONSTANTS_POKEWALKER_COURSES_H
#define POKEHEARTGOLD_CONSTANTS_POKEWALKER_COURSES_H

#define WALKER_COURSE_REFRESHING_FIELD 0
#define WALKER_COURSE_NOISY_FOREST     1
#define WALKER_COURSE_RUGGED_ROAD      2
#define WALKER_COURSE_BEAUTIFUL_BEACH  3
#define WALKER_COURSE_SUBURBAN_AREA    4
#define WALKER_COURSE_DIM_CAVE         5
#define WALKER_COURSE_BLUE_LAKE        6
#define WALKER_COURSE_TOWN_OUTSKIRTS   7
#define WALKER_COURSE_HOENN_FIELD      8
#define WALKER_COURSE_WARM_BEACH       9
#define WALKER_COURSE_VOLCANO_PATH     10
#define WALKER_COURSE_TREEHOUSE        11
#define WALKER_COURSE_SCARY_CAVE       12
#define WALKER_COURSE_SINNOH_FIELD     13
#define WALKER_COURSE_ICY_MOUNTAIN_RD_ 14
#define WALKER_COURSE_BIG_FOREST       15
#define WALKER_COURSE_WHITE_LAKE       16
#define WALKER_COURSE_STORMY_BEACH     17
#define WALKER_COURSE_RESORT           18
#define WALKER_COURSE_QUIET_CAVE       19
#define WALKER_COURSE_BEYOND_THE_SEA   20
#define WALKER_COURSE_NIGHT_SKY_S_EDGE 21
#define WALKER_COURSE_YELLOW_FOREST    22
#define WALKER_COURSE_RALLY            23
#define WALKER_COURSE_SIGHTSEEING      24
#define WALKER_COURSE_WINNER_S_PATH    25
#define WALKER_COURSE_AMITY_MEADOW     26
#define WALKER_COURSE_MAX              27

#endif // POKEHEARTGOLD_CONSTANTS_POKEWALKER_COURSES_H
