#ifndef POKEHEARTGOLD_CONSTANTS_RADIO_STATION_H
#define POKEHEARTGOLD_CONSTANTS_RADIO_STATION_H

#define RADIO_STATION_POKEMON_MUSIC          0
#define RADIO_STATION_POKEMON_TALK           1
#define RADIO_STATION_POKEMON_SEARCH_PARTY   2
#define RADIO_STATION_SERIAL_RADIO_DRAMA     3
#define RADIO_STATION_BUENAS_PASSWORD        4
#define RADIO_STATION_TRAINER_PROFILES       5
#define RADIO_STATION_THAT_TOWN_THESE_PEOPLE 6
#define RADIO_STATION_POKE_FLUTE             7
#define RADIO_STATION_UNOWN                  8
#define RADIO_STATION_TEAM_ROCKET            9
#define RADIO_STATION_MAHOGANY_SIGNAL        10
#define RADIO_STATION_COMMERCIALS            11

#endif // POKEHEARTGOLD_CONSTANTS_RADIO_STATION_H
