#ifndef POKEHEARTGOLD_CONSTANTS_RANKING_H
#define POKEHEARTGOLD_CONSTANTS_RANKING_H

#define RANKINGS_SCOPE_GLOBAL 0
#define RANKINGS_SCOPE_GROUP  1

#define RANKINGS_PAGE_BATTLE_TOWER 0
#define RANKINGS_PAGE_POKEMON      1
#define RANKINGS_PAGE_CONTEST      2

#define RANKINGS_RECORD_BATTLE_TOWER_BEGIN           0
#define RANKINGS_RECORD_BATTLE_TOWER_SINGLE_WINS     0
#define RANKINGS_RECORD_BATTLE_TOWER_DOUBLE_WINS     1
#define RANKINGS_RECORD_BATTLE_TOWER_MULTI_NPC_WINS  2
#define RANKINGS_RECORD_BATTLE_TOWER_MULTI_COMM_WINS 3
#define RANKINGS_RECORD_BATTLE_TOWER_WIFI_WINS       4
#define RANKINGS_RECORD_BATTLE_TOWER_AVG_WIN_STREAK  5
#define RANKINGS_RECORD_BATTLE_TOWER_COUNT           6

#define RANKINGS_RECORD_POKEMON_BEGIN         6
#define RANKINGS_RECORD_POKEMON_MONS_DEFEATED 6
#define RANKINGS_RECORD_POKEMON_MONS_CAUGHT   7
#define RANKINGS_RECORD_POKEMON_MONS_HATCHED  8
#define RANKINGS_RECORD_POKEMON_MONS_FISHED   9
#define RANKINGS_RECORD_POKEMON_COUNT         4

#define RANKINGS_RECORD_CONTEST_BEGIN   10
#define RANKINGS_RECORD_CONTEST_WIN     10
#define RANKINGS_RECORD_CONTEST_ENTRY   11
#define RANKINGS_RECORD_CONTEST_RIBBONS 12
#define RANKINGS_RECORD_CONTEST_COUNT   3

#define RANKINGS_COUNT 13

#endif // POKEHEARTGOLD_CONSTANTS_RANKING_H
