#ifndef POKEHEARTGOLD_CONSTANTS_ROAMER_H
#define POKEHEARTGOLD_CONSTANTS_ROAMER_H

#define ROAMER_RAIKOU 0u
#define ROAMER_ENTEI  1u
#define ROAMER_LATIAS 2u
#define ROAMER_LATIOS 3u
#define ROAMER_MAX    4u

#define ROAMER_LOC_R29   0
#define ROAMER_LOC_R30   1
#define ROAMER_LOC_R31   2
#define ROAMER_LOC_R32   3
#define ROAMER_LOC_R33   4
#define ROAMER_LOC_R34   5
#define ROAMER_LOC_R35   6
#define ROAMER_LOC_R36   7
#define ROAMER_LOC_R37   8
#define ROAMER_LOC_R38   9
#define ROAMER_LOC_R39   10
#define ROAMER_LOC_R42   11
#define ROAMER_LOC_R43   12
#define ROAMER_LOC_R44   13
#define ROAMER_LOC_R45   14
#define ROAMER_LOC_R46   15
#define ROAMER_LOC_R01   16
#define ROAMER_LOC_R02   17
#define ROAMER_LOC_R03   18
#define ROAMER_LOC_R04   19
#define ROAMER_LOC_R05   20
#define ROAMER_LOC_R06   21
#define ROAMER_LOC_R07   22
#define ROAMER_LOC_R08   23
#define ROAMER_LOC_R09   24
#define ROAMER_LOC_R10   25
#define ROAMER_LOC_R11   26
#define ROAMER_LOC_R12   27
#define ROAMER_LOC_R13   28
#define ROAMER_LOC_R14   29
#define ROAMER_LOC_R15   30
#define ROAMER_LOC_R16   31
#define ROAMER_LOC_R17   32
#define ROAMER_LOC_R18   33
#define ROAMER_LOC_W19   34
#define ROAMER_LOC_W20   35
#define ROAMER_LOC_W21   36
#define ROAMER_LOC_R22   37
#define ROAMER_LOC_R24   38
#define ROAMER_LOC_R26   39
#define ROAMER_LOC_R28   40
#define ROAMER_LOC_COUNT 41

#define ROAMER_LOC_JOHTO_START (ROAMER_LOC_R29)
#define ROAMER_LOC_JOHTO_END   (ROAMER_LOC_R46)
#define ROAMER_LOC_JOHTO_COUNT (ROAMER_LOC_JOHTO_END - ROAMER_LOC_JOHTO_START + 1)

#define ROAMER_LOC_KANTO_START (ROAMER_LOC_R01)
#define ROAMER_LOC_KANTO_END   (ROAMER_LOC_R28)
#define ROAMER_LOC_KANTO_COUNT (ROAMER_LOC_KANTO_END - ROAMER_LOC_KANTO_START + 1)

#endif // POKEHEARTGOLD_CONSTANTS_ROAMER_H
