#ifndef GUARD_POKEHEARTGOLD_CONSTANTS_SAFARI_H
#define GUARD_POKEHEARTGOLD_CONSTANTS_SAFARI_H

#define SAFARI_ZONE_MAX_OBJECTS       30
#define SAFARI_ZONE_AREA_SET_COLS     3
#define SAFARI_ZONE_AREA_SET_ROWS     2
#define SAFARI_ZONE_MAX_AREAS_PER_SET (SAFARI_ZONE_AREA_SET_COLS * SAFARI_ZONE_AREA_SET_ROWS)
#define SAFARI_ZONE_MAX_AREA_SETS     2

#define SAFARI_ZONE_AREA_PLAINS      0
#define SAFARI_ZONE_AREA_MEADOW      1
#define SAFARI_ZONE_AREA_SAVANNAH    2
#define SAFARI_ZONE_AREA_PEAK        3
#define SAFARI_ZONE_AREA_ROCKY_BEACH 4
#define SAFARI_ZONE_AREA_WETLAND     5
#define SAFARI_ZONE_AREA_FOREST      6
#define SAFARI_ZONE_AREA_SWAMP       7
#define SAFARI_ZONE_AREA_MARSHLAND   8
#define SAFARI_ZONE_AREA_WASTELAND   9
#define SAFARI_ZONE_AREA_MOUNTAIN    10
#define SAFARI_ZONE_AREA_DESERT      11
#define NUM_SAFARI_ZONE_AREAS        12

#define SAFARI_ZONE_OBJECT_TYPE_NONE   0
#define SAFARI_ZONE_OBJECT_TYPE_PLAINS 1
#define SAFARI_ZONE_OBJECT_TYPE_FOREST 2
#define SAFARI_ZONE_OBJECT_TYPE_PEAK   3
#define SAFARI_ZONE_OBJECT_TYPE_WATER  4

#define SAFARI_ZONE_OBJECTID_SHRUBBERY    0
#define SAFARI_ZONE_OBJECTID_RED_FLOWER   1
#define SAFARI_ZONE_OBJECTID_WHITE_FLOWER 2
#define SAFARI_ZONE_OBJECTID_TREE         3
#define SAFARI_ZONE_OBJECTID_STUMP        4
#define SAFARI_ZONE_OBJECTID_BRANCHES     5
#define SAFARI_ZONE_OBJECTID_SMALL_ROCK   6
#define SAFARI_ZONE_OBJECTID_BIG_ROCK     7
#define SAFARI_ZONE_OBJECTID_MOSSY_ROCK   8
#define SAFARI_ZONE_OBJECTID_PUDDLE       9
#define SAFARI_ZONE_OBJECTID_FOUNTAIN     10
#define SAFARI_ZONE_OBJECTID_WATER_HOLE   11
#define SAFARI_ZONE_OBJECTID_BENCH        12
#define SAFARI_ZONE_OBJECTID_SHORT_FENCE1 13
#define SAFARI_ZONE_OBJECTID_SHORT_FENCE2 14
#define SAFARI_ZONE_OBJECTID_LONG_FENCE1  15
#define SAFARI_ZONE_OBJECTID_LONG_FENCE2  16
#define SAFARI_ZONE_OBJECTID_SIGNBOARD    17
#define SAFARI_ZONE_OBJECTID_YOUR_STATUE  18
#define SAFARI_ZONE_OBJECTID_YOUR_FLAG    19
#define SAFARI_ZONE_OBJECTID_OUTSIDE_LAMP 20
#define SAFARI_ZONE_OBJECTID_GUIDEPOST_R_ 21
#define SAFARI_ZONE_OBJECTID_GUIDEPOST_L_ 22
#define SAFARI_ZONE_OBJECTID_TRASH_CAN    23
#define NUM_SAFARI_ZONE_OBJECT_IDS        24

#define NUM_ENCOUNTERS_SAFARI 10

#endif // GUARD_POKEHEARTGOLD_CONSTANTS_SAFARI_H
