#ifndef POKEHEARTGOLD_CONSTANTS_SEALS_H
#define POKEHEARTGOLD_CONSTANTS_SEALS_H

#define SEAL_NONE                                        0u
#define SEAL_HEART_A                                     1u
#define SEAL_HEART_B                                     2u
#define SEAL_HEART_C                                     3u
#define SEAL_HEART_D                                     4u
#define SEAL_HEART_E                                     5u
#define SEAL_HEART_F                                     6u
#define SEAL_STAR_A                                      7u
#define SEAL_STAR_B                                      8u
#define SEAL_STAR_C                                      9u
#define SEAL_STAR_D                                     10u
#define SEAL_STAR_E                                     11u
#define SEAL_STAR_F                                     12u
#define SEAL_LINE_A                                     13u
#define SEAL_LINE_B                                     14u
#define SEAL_LINE_C                                     15u
#define SEAL_LINE_D                                     16u
#define SEAL_SMOKE_A                                    17u
#define SEAL_SMOKE_B                                    18u
#define SEAL_SMOKE_C                                    19u
#define SEAL_SMOKE_D                                    20u
#define SEAL_ELE_A                                      21u
#define SEAL_ELE_B                                      22u
#define SEAL_ELE_C                                      23u
#define SEAL_ELE_D                                      24u
#define SEAL_FOAMY_A                                    25u
#define SEAL_FOAMY_B                                    26u
#define SEAL_FOAMY_C                                    27u
#define SEAL_FOAMY_D                                    28u
#define SEAL_FIRE_A                                     29u
#define SEAL_FIRE_B                                     30u
#define SEAL_FIRE_C                                     31u
#define SEAL_FIRE_D                                     32u
#define SEAL_PARTY_A                                    33u
#define SEAL_PARTY_B                                    34u
#define SEAL_PARTY_C                                    35u
#define SEAL_PARTY_D                                    36u
#define SEAL_FLORA_A                                    37u
#define SEAL_FLORA_B                                    38u
#define SEAL_FLORA_C                                    39u
#define SEAL_FLORA_D                                    40u
#define SEAL_FLORA_E                                    41u
#define SEAL_FLORA_F                                    42u
#define SEAL_SONG_A                                     43u
#define SEAL_SONG_B                                     44u
#define SEAL_SONG_C                                     45u
#define SEAL_SONG_D                                     46u
#define SEAL_SONG_E                                     47u
#define SEAL_SONG_F                                     48u
#define SEAL_SONG_G                                     49u
#define SEAL_A                                          50u
#define SEAL_B                                          51u
#define SEAL_C                                          52u
#define SEAL_D                                          53u
#define SEAL_E                                          54u
#define SEAL_F                                          55u
#define SEAL_G                                          56u
#define SEAL_H                                          57u
#define SEAL_I                                          58u
#define SEAL_J                                          59u
#define SEAL_K                                          60u
#define SEAL_L                                          61u
#define SEAL_M                                          62u
#define SEAL_N                                          63u
#define SEAL_O                                          64u
#define SEAL_P                                          65u
#define SEAL_Q                                          66u
#define SEAL_R                                          67u
#define SEAL_S                                          68u
#define SEAL_T                                          69u
#define SEAL_U                                          70u
#define SEAL_V                                          71u
#define SEAL_W                                          72u
#define SEAL_X                                          73u
#define SEAL_Y                                          74u
#define SEAL_Z                                          75u
#define SEAL_SHOCK                                      76u
#define SEAL_MYSTERY                                    77u
#define SEAL_LIQUID                                     78u
#define SEAL_BURST                                      79u
#define SEAL_TWINKLE                                    80u

#define SEAL_MIN SEAL_HEART_A
#define SEAL_MAX SEAL_TWINKLE

#define MAX_SEALS_ON_CAPSULE         8
#define MAX_CAPSULES                12

#endif //POKEHEARTGOLD_CONSTANTS_SEALS_H
