#ifndef POKEHEARTGOLD_CONSTANTS_SEALS_H
#define POKEHEARTGOLD_CONSTANTS_SEALS_H

#define SEAL_NONE    0
#define SEAL_HEART_A 1
#define SEAL_HEART_B 2
#define SEAL_HEART_C 3
#define SEAL_HEART_D 4
#define SEAL_HEART_E 5
#define SEAL_HEART_F 6
#define SEAL_STAR_A  7
#define SEAL_STAR_B  8
#define SEAL_STAR_C  9
#define SEAL_STAR_D  10
#define SEAL_STAR_E  11
#define SEAL_STAR_F  12
#define SEAL_LINE_A  13
#define SEAL_LINE_B  14
#define SEAL_LINE_C  15
#define SEAL_LINE_D  16
#define SEAL_SMOKE_A 17
#define SEAL_SMOKE_B 18
#define SEAL_SMOKE_C 19
#define SEAL_SMOKE_D 20
#define SEAL_ELE_A   21
#define SEAL_ELE_B   22
#define SEAL_ELE_C   23
#define SEAL_ELE_D   24
#define SEAL_FOAMY_A 25
#define SEAL_FOAMY_B 26
#define SEAL_FOAMY_C 27
#define SEAL_FOAMY_D 28
#define SEAL_FIRE_A  29
#define SEAL_FIRE_B  30
#define SEAL_FIRE_C  31
#define SEAL_FIRE_D  32
#define SEAL_PARTY_A 33
#define SEAL_PARTY_B 34
#define SEAL_PARTY_C 35
#define SEAL_PARTY_D 36
#define SEAL_FLORA_A 37
#define SEAL_FLORA_B 38
#define SEAL_FLORA_C 39
#define SEAL_FLORA_D 40
#define SEAL_FLORA_E 41
#define SEAL_FLORA_F 42
#define SEAL_SONG_A  43
#define SEAL_SONG_B  44
#define SEAL_SONG_C  45
#define SEAL_SONG_D  46
#define SEAL_SONG_E  47
#define SEAL_SONG_F  48
#define SEAL_SONG_G  49
#define SEAL_A       50
#define SEAL_B       51
#define SEAL_C       52
#define SEAL_D       53
#define SEAL_E       54
#define SEAL_F       55
#define SEAL_G       56
#define SEAL_H       57
#define SEAL_I       58
#define SEAL_J       59
#define SEAL_K       60
#define SEAL_L       61
#define SEAL_M       62
#define SEAL_N       63
#define SEAL_O       64
#define SEAL_P       65
#define SEAL_Q       66
#define SEAL_R       67
#define SEAL_S       68
#define SEAL_T       69
#define SEAL_U       70
#define SEAL_V       71
#define SEAL_W       72
#define SEAL_X       73
#define SEAL_Y       74
#define SEAL_Z       75
#define SEAL_SHOCK   76
#define SEAL_MYSTERY 77
#define SEAL_LIQUID  78
#define SEAL_BURST   79
#define SEAL_TWINKLE 80

#define SEAL_MIN SEAL_HEART_A
#define SEAL_MAX SEAL_TWINKLE

#define MAX_SEALS_ON_CAPSULE 8
#define MAX_CAPSULES         12
#define SEAL_INVENTORY_QMAX  99 // slot capacity for a given seal

#endif // POKEHEARTGOLD_CONSTANTS_SEALS_H
