#ifndef POKEHEARTGOLD_CONSTANTS_SPAWNS_H
#define POKEHEARTGOLD_CONSTANTS_SPAWNS_H

#define SPAWN_NONE         0
#define SPAWN_NEW_BARK     1
#define SPAWN_CHERRYGROVE  2
#define SPAWN_VIOLET       3
#define SPAWN_AZALEA       4
#define SPAWN_GOLDENROD    5
#define SPAWN_ECRUTEAK     6
#define SPAWN_OLIVINE      7
#define SPAWN_CIANWOOD     8
#define SPAWN_MAHOGANY     9
#define SPAWN_LAKE_OF_RAGE 10
#define SPAWN_BLACKTHORN   11
#define SPAWN_MT_SILVER    12
#define SPAWN_PALLET       13
#define SPAWN_VIRIDIAN     14
#define SPAWN_PEWTER       15
#define SPAWN_CERULEAN     16
#define SPAWN_LAVENDER     17
#define SPAWN_VERMILION    18
#define SPAWN_CELADON      19
#define SPAWN_FUCHSIA      20
#define SPAWN_CINNABAR     21
#define SPAWN_INDIGO       22
#define SPAWN_SAFFRON      23
#define SPAWN_SAFARI       24
#define SPAWN_FRONTIER     25
#define SPAWN_POKEATHLON   26
#define SPAWN_VICTORY_ROAD 27
#define SPAWN_UNION_CAVE   28
#define SPAWN_MT_MOON      29
#define SPAWN_ROCK_TUNNEL  30

#endif // POKEHEARTGOLD_CONSTANTS_SPAWNS_H
