#ifndef POKEHEARTGOLD_CONSTANTS_SPRITES_H
#define POKEHEARTGOLD_CONSTANTS_SPRITES_H

#define SPRITE_HERO                                0
#define SPRITE_BABYBOY1                            1
#define SPRITE_BABYGIRL1                           2
#define SPRITE_BOY1                                3
#define SPRITE_BOY2                                4
#define SPRITE_BOY3                                5
#define SPRITE_GIRL1                               6
#define SPRITE_GIRL2                               7
#define SPRITE_GIRL3                               8
#define SPRITE_MAN1                                9
#define SPRITE_MAN2                               10
#define SPRITE_MAN3                               11
#define SPRITE_WOMAN1                             12
#define SPRITE_WOMAN2                             13
#define SPRITE_WOMAN3                             14
#define SPRITE_MIDDLEMAN1                         15
#define SPRITE_MIDDLEWOMAN1                       16
#define SPRITE_OLDMAN1                            17
#define SPRITE_OLDWOMAN1                          18
#define SPRITE_BIGMAN                             19
#define SPRITE_MOUNT                              20
#define SPRITE_CYCLEHERO                          21
#define SPRITE_REPORTER                           22
#define SPRITE_CAMERAMAN                          23
#define SPRITE_SHOPM1                             24
#define SPRITE_SHOPW1                             25
#define SPRITE_ASSISTANTM                         29
#define SPRITE_ASSISTANTW                         30
#define SPRITE_BADMAN                             31
#define SPRITE_SKIERW                             33
#define SPRITE_POLICEMAN                          34
#define SPRITE_IDOL                               35
#define SPRITE_GENTLEMAN                          36
#define SPRITE_LADY                               37
#define SPRITE_CYCLEM                             38
#define SPRITE_CYCLEW                             39
#define SPRITE_WORKMAN                            40
#define SPRITE_FARMER                             41
#define SPRITE_COWGIRL                            42
#define SPRITE_CLOWN                              43
#define SPRITE_ARTIST                             44
#define SPRITE_SPORTSMAN                          45
#define SPRITE_EXPLORE                            50
#define SPRITE_FIGHTER                            51
#define SPRITE_CAMPBOY                            52
#define SPRITE_PICNICGIRL                         53
#define SPRITE_FISHING                            54
#define SPRITE_AMBRELLA                           55
#define SPRITE_SEAMAN                             56
#define SPRITE_WAITER                             59
#define SPRITE_WAITRESS                           60
#define SPRITE_GORGGEOUSM                         62
#define SPRITE_GORGGEOUSW                         63
#define SPRITE_MAN5                               68
#define SPRITE_WOMAN5                             69
#define SPRITE_MYSTERY                            70
#define SPRITE_PIKACHU                            71
#define SPRITE_ROCK                               84
#define SPRITE_BREAKROCK                          85
#define SPRITE_TREE                               86
#define SPRITE_MONSTARBALL                        87
#define SPRITE_HEROINE                            97
#define SPRITE_CYCLEHEROINE                       98
#define SPRITE_DOCTOR                             99
#define SPRITE_LEADER1                           126
#define SPRITE_LEADER2                           127
#define SPRITE_LEADER3                           128
#define SPRITE_LEADER4                           129
#define SPRITE_LEADER5                           130
#define SPRITE_LEADER6                           131
#define SPRITE_LEADER7                           132
#define SPRITE_LEADER8                           133
#define SPRITE_SEVEN1                            141
#define SPRITE_SEVEN2                            142
#define SPRITE_SEVEN3                            143
#define SPRITE_SEVEN4                            144
#define SPRITE_SEVEN5                            145
#define SPRITE_GSBOY1                            146
#define SPRITE_GSRIVEL                           148
#define SPRITE_SUNGLASSES                        168
#define SPRITE_TOWERBOSS                         169
#define SPRITE_MAID                              175
#define SPRITE_SPHERO                            176
#define SPRITE_SPHEROINE                         177
#define SPRITE_SWIMHERO                          178
#define SPRITE_SWIMHEROINE                       179
#define SPRITE_WATERHERO                         180
#define SPRITE_WATERHEROINE                      181
#define SPRITE_BABYBOY1_2                        183
#define SPRITE_FISHINGHERO                       188
#define SPRITE_FISH_HEROINE                      189
#define SPRITE_DELIVERY                          193
#define SPRITE_POKEHERO                          196
#define SPRITE_POKEHEROINE                       197
#define SPRITE_SAVEHERO                          198
#define SPRITE_SAVEHEROINE                       199
#define SPRITE_BANZAIHERO                        200
#define SPRITE_BANZAIHEROINE                     201
#define SPRITE_POKEWALL                          210
#define SPRITE_RED                               211
#define SPRITE_THIEF                             218
#define SPRITE_ITAKO                             219
#define SPRITE_BOZU                              220
#define SPRITE_ROCKETW                           221
#define SPRITE_ROCKETM                           222
#define SPRITE_RKANBUW                           223
#define SPRITE_RKANBUM                           224
#define SPRITE_BOARDER                           225
#define SPRITE_FIRE                              227
#define SPRITE_GANG                              229
#define SPRITE_DANCER                            232
#define SPRITE_GANTETSU                          233
#define SPRITE_MONO_PIP                          234
#define SPRITE_MASAKI                            235
#define SPRITE_CAPTAIN                           236
#define SPRITE_RGYARADOSU                        237
#define SPRITE_HERO_2                            238
#define SPRITE_HEROINE_2                         239
#define SPRITE_LADDERHERO                        248
#define SPRITE_LADDERHEROINE                     249
#define SPRITE_ITAKO_                            250
#define SPRITE_BABYBOY1_3                        251
#define SPRITE_BABYBOY1_4                        252
#define SPRITE_BABYBOY1_5                        253
#define SPRITE_BABYBOY1_6                        254
#define SPRITE_BABYBOY1_7                        255
#define SPRITE_BABYBOY1_8                        256
#define SPRITE_BABYBOY1_9                        257
#define SPRITE_RHERO                             258
#define SPRITE_RHEROINE                          259
#define SPRITE_RBANZAIHERO                       260
#define SPRITE_RBANZAIINE                        261
#define SPRITE_BONGURI                           262
#define SPRITE_BONGURI_R                         263
#define SPRITE_BONGURI_Y                         264
#define SPRITE_BONGURI_B                         265
#define SPRITE_BONGURI_G                         266
#define SPRITE_BONGURI_P                         267
#define SPRITE_BONGURI_W                         268
#define SPRITE_BONGURI_BK                        269
#define SPRITE_BONMI_R                           270
#define SPRITE_BONMI_Y                           271
#define SPRITE_BONMI_B                           272
#define SPRITE_BONMI_G                           273
#define SPRITE_BONMI_P                           274
#define SPRITE_BONMI_W                           275
#define SPRITE_BONMI_BK                          276
#define SPRITE_BRAINS1                           277
#define SPRITE_BRAINS2                           278
#define SPRITE_BRAINS3                           279
#define SPRITE_BRAINS4                           280
#define SPRITE_PRINCESS                          281
#define SPRITE_BFSM                              282
#define SPRITE_BFSW1                             283
#define SPRITE_BFSW2                             284
#define SPRITE_WIFISM                            285
#define SPRITE_WIFISF                            286
#define SPRITE_AJI_PERU                          287
#define SPRITE_BABYBOY1_10                       288
#define SPRITE_BABYBOY1_11                       289
#define SPRITE_LEAG_DOOR2                        290
#define SPRITE_BABYBOY1_12                       291
#define SPRITE_BABYBOY1_13                       292
#define SPRITE_RKANBUM2                          293
#define SPRITE_RKANBUM3                          294
#define SPRITE_PL_BOY01C                         295
#define SPRITE_PL_GIRL01C                        296
#define SPRITE_SAVERHERO                         297
#define SPRITE_SAVERHEROINE                      298
#define SPRITE_DELIVERY2                         299
#define SPRITE_GSBABYBOY1                        315
#define SPRITE_GSBABYGIRL1                       316
#define SPRITE_GSBOY2                            317
#define SPRITE_GSBOY3                            318
#define SPRITE_GSGIRL1                           319
#define SPRITE_GSGIRL2                           320
#define SPRITE_GSGIRL3                           321
#define SPRITE_GSMAN1                            322
#define SPRITE_GSMAN2                            323
#define SPRITE_GSMAN3                            324
#define SPRITE_GSWOMAN1                          325
#define SPRITE_GSWOMAN2                          326
#define SPRITE_GSWOMAN3                          327
#define SPRITE_GSMIDDLEMAN1                      328
#define SPRITE_MIDDLEWOMAN1_2                    329
#define SPRITE_GSOLDMAN1                         330
#define SPRITE_GSOLDWOMAN1                       331
#define SPRITE_GSBIGMAN                          332
#define SPRITE_MOUNT_2                           333
#define SPRITE_SHOPM1_2                          334
#define SPRITE_PCWOMAN1                          335
#define SPRITE_PCWOMAN2                          336
#define SPRITE_PCWOMAN3                          337
#define SPRITE_GSASSISTANTM                      338
#define SPRITE_GSGENTLEMAN                       341
#define SPRITE_GSSWIMMERM                        342
#define SPRITE_GSSWIMMERW                        343
#define SPRITE_GSFIGHTER                         344
#define SPRITE_CAMPBOY_2                         345
#define SPRITE_PICNICGIRL_2                      346
#define SPRITE_FISHING_2                         347
#define SPRITE_SEAMAN_2                          348
#define SPRITE_STOP                              349
#define SPRITE_GTOROPHY                          350
#define SPRITE_MYSTERY_2                         351
#define SPRITE_GSLEADER1                         352
#define SPRITE_GSLEADER2                         353
#define SPRITE_GSLEADER3                         354
#define SPRITE_GSLEADER4                         355
#define SPRITE_GSLEADER5                         356
#define SPRITE_GSLEADER6                         357
#define SPRITE_GSLEADER7                         358
#define SPRITE_GSLEADER8                         359
#define SPRITE_GSBIGFOUR1                        360
#define SPRITE_GSBIGFOUR2                        361
#define SPRITE_GSBIGFOUR3                        362
#define SPRITE_GSBIGFOUR4                        363
#define SPRITE_WATARU                            364
#define SPRITE_GSMAMA                            365
#define SPRITE_OOKIDO                            366
#define SPRITE_GSDSBOY                           367
#define SPRITE_GSLEADER9                         368
#define SPRITE_GSLEADER10                        369
#define SPRITE_GSLEADER11                        370
#define SPRITE_GSLEADER12                        371
#define SPRITE_GSLEADER13                        372
#define SPRITE_GSLEADER14                        373
#define SPRITE_GSLEADER15                        374
#define SPRITE_GSLEADER16                        375
#define SPRITE_STOROPHY                          376
#define SPRITE_MANIA                             377
#define SPRITE_JUGGRER                           378
#define SPRITE_BTOROPHY                          379
#define SPRITE_JUPETTA                           380
#define SPRITE_USOKKY                            381
#define SPRITE_MINAKI                            382
#define SPRITE_THLONOWNER                        383
#define SPRITE_INSTRUCTOR                        384
#define SPRITE_SAKAKI                            385
#define SPRITE_SUIT                              386
#define SPRITE_CHOUROU                           387
#define SPRITE_KURUMI                            389
#define SPRITE_RAPURASU                          390
#define SPRITE_NANAMI                            392
#define SPRITE_REDMAMA                           393
#define SPRITE_COUNTERM                          394
#define SPRITE_KABIGON                           395
#define SPRITE_MEDAL                             396
#define SPRITE_SCROLL                            397
#define SPRITE_SIGNSHOES                         398
#define SPRITE_SIGNCLOTHES                       399
#define SPRITE_SIGNFLAG                          400
#define SPRITE_SIGNPOKEGEAR                      401
#define SPRITE_SIGNBALL                          402
#define SPRITE_STATUEHERO                        403
#define SPRITE_STATUEHEROINE                     404
#define SPRITE_ICE                               406
#define SPRITE_PKTHHERO                          407
#define SPRITE_PKTHHEROINE                       408
#define SPRITE_ROTOMF                            409
#define SPRITE_ROTOMS                            410
#define SPRITE_ROTOMI                            411
#define SPRITE_ROTOMW                            412
#define SPRITE_ROTOMG                            413
#define SPRITE_YADON                             414
#define SPRITE_TSURE_POKE                        415
#define SPRITE_TSURE_POKE_2                      416
#define SPRITE_TSURE_POKE_3                      417
#define SPRITE_TSURE_POKE_4                      418
#define SPRITE_TSURE_POKE_5                      419
#define SPRITE_TSURE_POKE_6                      420
#define SPRITE_DAIGO                             421
#define SPRITE_CHAMPION                          422
#define SPRITE_SHAKEHERO                         423
#define SPRITE_SHAKEHEROINE                      424
#define SPRITE_HOU_OBJ01                         425
#define SPRITE_LUG_OBJ01                         426
#define SPRITE_GSWOMAN6                          427
#define SPRITE_TSURE_POKE_7                      428
#define SPRITE_TSURE_POKE_8                      429
#define SPRITE_TSURE_POKE_9                      430
#define SPRITE_TSURE_POKE_10                     431
#define SPRITE_TSURE_POKE_11                     432
#define SPRITE_TSURE_POKE_12                     433
#define SPRITE_TSURE_POKE_13                     434
#define SPRITE_TSURE_POKE_14                     435
#define SPRITE_TSURE_POKE_15                     436
#define SPRITE_TSURE_POKE_16                     437
#define SPRITE_TSURE_POKE_17                     438
#define SPRITE_TSURE_POKE_18                     439
#define SPRITE_TSURE_POKE_19                     440
#define SPRITE_TSURE_POKE_20                     441
#define SPRITE_TSURE_POKE_21                     442
#define SPRITE_TSURE_POKE_22                     443
#define SPRITE_TSURE_POKE_23                     444
#define SPRITE_TSURE_POKE_24                     445
#define SPRITE_TSURE_POKE_25                     446
#define SPRITE_TSURE_POKE_26                     447
#define SPRITE_TSURE_POKE_27                     448
#define SPRITE_TSURE_POKE_28                     449
#define SPRITE_TSURE_POKE_29                     450
#define SPRITE_TSURE_POKE_30                     451
#define SPRITE_TSURE_POKE_31                     452
#define SPRITE_TSURE_POKE_32                     453
#define SPRITE_TSURE_POKE_33                     454
#define SPRITE_TSURE_POKE_34                     455
#define SPRITE_TSURE_POKE_35                     456
#define SPRITE_TSURE_POKE_36                     457
#define SPRITE_TSURE_POKE_37                     458
#define SPRITE_TSURE_POKE_38                     459
#define SPRITE_TSURE_POKE_39                     460
#define SPRITE_TSURE_POKE_40                     461
#define SPRITE_TSURE_POKE_41                     462
#define SPRITE_TSURE_POKE_42                     463
#define SPRITE_TSURE_POKE_43                     464
#define SPRITE_TSURE_POKE_44                     465
#define SPRITE_TSURE_POKE_45                     466
#define SPRITE_TSURE_POKE_46                     467
#define SPRITE_TSURE_POKE_47                     468
#define SPRITE_TSURE_POKE_48                     469
#define SPRITE_TSURE_POKE_49                     470
#define SPRITE_TSURE_POKE_50                     471
#define SPRITE_TSURE_POKE_51                     472
#define SPRITE_TSURE_POKE_52                     473
#define SPRITE_TSURE_POKE_53                     474
#define SPRITE_TSURE_POKE_54                     475
#define SPRITE_TSURE_POKE_55                     476
#define SPRITE_TSURE_POKE_56                     477
#define SPRITE_TSURE_POKE_57                     478
#define SPRITE_TSURE_POKE_58                     479
#define SPRITE_TSURE_POKE_59                     480
#define SPRITE_TSURE_POKE_60                     481
#define SPRITE_TSURE_POKE_61                     482
#define SPRITE_TSURE_POKE_62                     483
#define SPRITE_TSURE_POKE_63                     484
#define SPRITE_TSURE_POKE_64                     485
#define SPRITE_TSURE_POKE_65                     486
#define SPRITE_TSURE_POKE_66                     487
#define SPRITE_TSURE_POKE_67                     488
#define SPRITE_TSURE_POKE_68                     489
#define SPRITE_TSURE_POKE_69                     490
#define SPRITE_TSURE_POKE_70                     491
#define SPRITE_TSURE_POKE_71                     492
#define SPRITE_TSURE_POKE_72                     493
#define SPRITE_TSURE_POKE_73                     494
#define SPRITE_TSURE_POKE_74                     495
#define SPRITE_TSURE_POKE_75                     496
#define SPRITE_TSURE_POKE_76                     497
#define SPRITE_TSURE_POKE_77                     498
#define SPRITE_TSURE_POKE_78                     499
#define SPRITE_TSURE_POKE_79                     500
#define SPRITE_TSURE_POKE_80                     501
#define SPRITE_TSURE_POKE_81                     502
#define SPRITE_TSURE_POKE_82                     503
#define SPRITE_TSURE_POKE_83                     504
#define SPRITE_TSURE_POKE_84                     505
#define SPRITE_TSURE_POKE_85                     506
#define SPRITE_TSURE_POKE_86                     507
#define SPRITE_TSURE_POKE_87                     508
#define SPRITE_TSURE_POKE_88                     509
#define SPRITE_TSURE_POKE_89                     510
#define SPRITE_TSURE_POKE_90                     511
#define SPRITE_TSURE_POKE_91                     512
#define SPRITE_TSURE_POKE_92                     513
#define SPRITE_TSURE_POKE_93                     514
#define SPRITE_TSURE_POKE_94                     515
#define SPRITE_TSURE_POKE_95                     516
#define SPRITE_TSURE_POKE_96                     517
#define SPRITE_TSURE_POKE_97                     518
#define SPRITE_TSURE_POKE_98                     519
#define SPRITE_TSURE_POKE_99                     520
#define SPRITE_TSURE_POKE_100                    521
#define SPRITE_TSURE_POKE_101                    522
#define SPRITE_TSURE_POKE_102                    523
#define SPRITE_TSURE_POKE_103                    524
#define SPRITE_TSURE_POKE_104                    525
#define SPRITE_TSURE_POKE_105                    526
#define SPRITE_TSURE_POKE_106                    527
#define SPRITE_TSURE_POKE_107                    528
#define SPRITE_TSURE_POKE_108                    529
#define SPRITE_TSURE_POKE_109                    530
#define SPRITE_TSURE_POKE_110                    531
#define SPRITE_TSURE_POKE_111                    532
#define SPRITE_TSURE_POKE_112                    533
#define SPRITE_TSURE_POKE_113                    534
#define SPRITE_TSURE_POKE_114                    535
#define SPRITE_TSURE_POKE_115                    536
#define SPRITE_TSURE_POKE_116                    537
#define SPRITE_TSURE_POKE_117                    538
#define SPRITE_TSURE_POKE_118                    539
#define SPRITE_TSURE_POKE_119                    540
#define SPRITE_TSURE_POKE_120                    541
#define SPRITE_TSURE_POKE_121                    542
#define SPRITE_TSURE_POKE_122                    543
#define SPRITE_TSURE_POKE_123                    544
#define SPRITE_TSURE_POKE_124                    545
#define SPRITE_TSURE_POKE_125                    546
#define SPRITE_TSURE_POKE_126                    547
#define SPRITE_TSURE_POKE_127                    548
#define SPRITE_TSURE_POKE_128                    549
#define SPRITE_TSURE_POKE_129                    550
#define SPRITE_TSURE_POKE_130                    551
#define SPRITE_TSURE_POKE_131                    552
#define SPRITE_TSURE_POKE_132                    553
#define SPRITE_TSURE_POKE_133                    554
#define SPRITE_TSURE_POKE_134                    555
#define SPRITE_TSURE_POKE_135                    556
#define SPRITE_TSURE_POKE_136                    557
#define SPRITE_TSURE_POKE_137                    558
#define SPRITE_TSURE_POKE_138                    559
#define SPRITE_TSURE_POKE_139                    560
#define SPRITE_TSURE_POKE_140                    561
#define SPRITE_TSURE_POKE_141                    562
#define SPRITE_TSURE_POKE_142                    563
#define SPRITE_TSURE_POKE_143                    564
#define SPRITE_TSURE_POKE_144                    565
#define SPRITE_TSURE_POKE_145                    566
#define SPRITE_TSURE_POKE_146                    567
#define SPRITE_TSURE_POKE_147                    568
#define SPRITE_TSURE_POKE_148                    569
#define SPRITE_TSURE_POKE_149                    570
#define SPRITE_TSURE_POKE_150                    571
#define SPRITE_TSURE_POKE_151                    572
#define SPRITE_TSURE_POKE_152                    573
#define SPRITE_TSURE_POKE_153                    574
#define SPRITE_TSURE_POKE_154                    575
#define SPRITE_TSURE_POKE_155                    576
#define SPRITE_TSURE_POKE_156                    577
#define SPRITE_TSURE_POKE_157                    578
#define SPRITE_TSURE_POKE_158                    579
#define SPRITE_TSURE_POKE_159                    580
#define SPRITE_TSURE_POKE_160                    581
#define SPRITE_TSURE_POKE_161                    582
#define SPRITE_TSURE_POKE_162                    583
#define SPRITE_TSURE_POKE_163                    584
#define SPRITE_TSURE_POKE_164                    585
#define SPRITE_TSURE_POKE_165                    586
#define SPRITE_TSURE_POKE_166                    587
#define SPRITE_TSURE_POKE_167                    588
#define SPRITE_TSURE_POKE_168                    589
#define SPRITE_TSURE_POKE_169                    590
#define SPRITE_TSURE_POKE_170                    591
#define SPRITE_TSURE_POKE_171                    592
#define SPRITE_TSURE_POKE_172                    593
#define SPRITE_TSURE_POKE_173                    594
#define SPRITE_TSURE_POKE_174                    595
#define SPRITE_TSURE_POKE_175                    596
#define SPRITE_TSURE_POKE_176                    597
#define SPRITE_TSURE_POKE_177                    598
#define SPRITE_TSURE_POKE_178                    599
#define SPRITE_TSURE_POKE_179                    600
#define SPRITE_TSURE_POKE_180                    601
#define SPRITE_TSURE_POKE_181                    602
#define SPRITE_TSURE_POKE_182                    603
#define SPRITE_TSURE_POKE_183                    604
#define SPRITE_TSURE_POKE_184                    605
#define SPRITE_TSURE_POKE_185                    606
#define SPRITE_TSURE_POKE_186                    607
#define SPRITE_TSURE_POKE_187                    608
#define SPRITE_TSURE_POKE_188                    609
#define SPRITE_TSURE_POKE_189                    610
#define SPRITE_TSURE_POKE_190                    611
#define SPRITE_TSURE_POKE_191                    612
#define SPRITE_TSURE_POKE_192                    613
#define SPRITE_TSURE_POKE_193                    614
#define SPRITE_TSURE_POKE_194                    615
#define SPRITE_TSURE_POKE_195                    616
#define SPRITE_TSURE_POKE_196                    617
#define SPRITE_TSURE_POKE_197                    618
#define SPRITE_TSURE_POKE_198                    619
#define SPRITE_TSURE_POKE_199                    620
#define SPRITE_TSURE_POKE_200                    621
#define SPRITE_TSURE_POKE_201                    622
#define SPRITE_TSURE_POKE_202                    623
#define SPRITE_TSURE_POKE_203                    624
#define SPRITE_TSURE_POKE_204                    625
#define SPRITE_TSURE_POKE_205                    626
#define SPRITE_TSURE_POKE_206                    627
#define SPRITE_TSURE_POKE_207                    628
#define SPRITE_TSURE_POKE_208                    629
#define SPRITE_TSURE_POKE_209                    630
#define SPRITE_TSURE_POKE_210                    631
#define SPRITE_TSURE_POKE_211                    632
#define SPRITE_TSURE_POKE_212                    633
#define SPRITE_TSURE_POKE_213                    634
#define SPRITE_TSURE_POKE_214                    635
#define SPRITE_TSURE_POKE_215                    636
#define SPRITE_TSURE_POKE_216                    637
#define SPRITE_TSURE_POKE_217                    638
#define SPRITE_TSURE_POKE_218                    639
#define SPRITE_TSURE_POKE_219                    640
#define SPRITE_TSURE_POKE_220                    641
#define SPRITE_TSURE_POKE_221                    642
#define SPRITE_TSURE_POKE_222                    643
#define SPRITE_TSURE_POKE_223                    644
#define SPRITE_TSURE_POKE_224                    645
#define SPRITE_TSURE_POKE_225                    646
#define SPRITE_TSURE_POKE_226                    647
#define SPRITE_TSURE_POKE_227                    648
#define SPRITE_TSURE_POKE_228                    649
#define SPRITE_TSURE_POKE_229                    650
#define SPRITE_TSURE_POKE_230                    651
#define SPRITE_TSURE_POKE_231                    652
#define SPRITE_TSURE_POKE_232                    653
#define SPRITE_TSURE_POKE_233                    654
#define SPRITE_TSURE_POKE_234                    655
#define SPRITE_TSURE_POKE_235                    656
#define SPRITE_TSURE_POKE_236                    657
#define SPRITE_TSURE_POKE_237                    658
#define SPRITE_TSURE_POKE_238                    659
#define SPRITE_TSURE_POKE_239                    660
#define SPRITE_TSURE_POKE_240                    661
#define SPRITE_TSURE_POKE_241                    662
#define SPRITE_TSURE_POKE_242                    663
#define SPRITE_TSURE_POKE_243                    664
#define SPRITE_TSURE_POKE_244                    665
#define SPRITE_TSURE_POKE_245                    666
#define SPRITE_TSURE_POKE_246                    667
#define SPRITE_TSURE_POKE_247                    668
#define SPRITE_TSURE_POKE_248                    669
#define SPRITE_TSURE_POKE_249                    670
#define SPRITE_TSURE_POKE_250                    671
#define SPRITE_TSURE_POKE_251                    672
#define SPRITE_TSURE_POKE_252                    673
#define SPRITE_TSURE_POKE_253                    674
#define SPRITE_TSURE_POKE_254                    675
#define SPRITE_TSURE_POKE_255                    676
#define SPRITE_TSURE_POKE_256                    677
#define SPRITE_TSURE_POKE_257                    678
#define SPRITE_TSURE_POKE_258                    679
#define SPRITE_TSURE_POKE_259                    680
#define SPRITE_TSURE_POKE_260                    681
#define SPRITE_TSURE_POKE_261                    682
#define SPRITE_TSURE_POKE_262                    683
#define SPRITE_TSURE_POKE_263                    684
#define SPRITE_TSURE_POKE_264                    685
#define SPRITE_TSURE_POKE_265                    686
#define SPRITE_TSURE_POKE_266                    687
#define SPRITE_TSURE_POKE_267                    688
#define SPRITE_TSURE_POKE_268                    689
#define SPRITE_TSURE_POKE_269                    690
#define SPRITE_TSURE_POKE_270                    691
#define SPRITE_TSURE_POKE_271                    692
#define SPRITE_TSURE_POKE_272                    693
#define SPRITE_TSURE_POKE_273                    694
#define SPRITE_TSURE_POKE_274                    695
#define SPRITE_TSURE_POKE_275                    696
#define SPRITE_TSURE_POKE_276                    697
#define SPRITE_TSURE_POKE_277                    698
#define SPRITE_TSURE_POKE_278                    699
#define SPRITE_TSURE_POKE_279                    700
#define SPRITE_TSURE_POKE_280                    701
#define SPRITE_TSURE_POKE_281                    702
#define SPRITE_TSURE_POKE_282                    703
#define SPRITE_TSURE_POKE_283                    704
#define SPRITE_TSURE_POKE_284                    705
#define SPRITE_TSURE_POKE_285                    706
#define SPRITE_TSURE_POKE_286                    707
#define SPRITE_TSURE_POKE_287                    708
#define SPRITE_TSURE_POKE_288                    709
#define SPRITE_TSURE_POKE_289                    710
#define SPRITE_TSURE_POKE_290                    711
#define SPRITE_TSURE_POKE_291                    712
#define SPRITE_TSURE_POKE_292                    713
#define SPRITE_TSURE_POKE_293                    714
#define SPRITE_TSURE_POKE_294                    715
#define SPRITE_TSURE_POKE_295                    716
#define SPRITE_TSURE_POKE_296                    717
#define SPRITE_TSURE_POKE_297                    718
#define SPRITE_TSURE_POKE_298                    719
#define SPRITE_TSURE_POKE_299                    720
#define SPRITE_TSURE_POKE_300                    721
#define SPRITE_TSURE_POKE_301                    722
#define SPRITE_TSURE_POKE_302                    723
#define SPRITE_TSURE_POKE_303                    724
#define SPRITE_TSURE_POKE_304                    725
#define SPRITE_TSURE_POKE_305                    726
#define SPRITE_TSURE_POKE_306                    727
#define SPRITE_TSURE_POKE_307                    728
#define SPRITE_TSURE_POKE_308                    729
#define SPRITE_TSURE_POKE_309                    730
#define SPRITE_TSURE_POKE_310                    731
#define SPRITE_TSURE_POKE_311                    732
#define SPRITE_TSURE_POKE_312                    733
#define SPRITE_TSURE_POKE_313                    734
#define SPRITE_TSURE_POKE_314                    735
#define SPRITE_TSURE_POKE_315                    736
#define SPRITE_TSURE_POKE_316                    737
#define SPRITE_TSURE_POKE_317                    738
#define SPRITE_TSURE_POKE_318                    739
#define SPRITE_TSURE_POKE_319                    740
#define SPRITE_TSURE_POKE_320                    741
#define SPRITE_TSURE_POKE_321                    742
#define SPRITE_TSURE_POKE_322                    743
#define SPRITE_TSURE_POKE_323                    744
#define SPRITE_TSURE_POKE_324                    745
#define SPRITE_TSURE_POKE_325                    746
#define SPRITE_TSURE_POKE_326                    747
#define SPRITE_TSURE_POKE_327                    748
#define SPRITE_TSURE_POKE_328                    749
#define SPRITE_TSURE_POKE_329                    750
#define SPRITE_TSURE_POKE_330                    751
#define SPRITE_TSURE_POKE_331                    752
#define SPRITE_TSURE_POKE_332                    753
#define SPRITE_TSURE_POKE_333                    754
#define SPRITE_TSURE_POKE_334                    755
#define SPRITE_TSURE_POKE_335                    756
#define SPRITE_TSURE_POKE_336                    757
#define SPRITE_TSURE_POKE_337                    758
#define SPRITE_TSURE_POKE_338                    759
#define SPRITE_TSURE_POKE_339                    760
#define SPRITE_TSURE_POKE_340                    761
#define SPRITE_TSURE_POKE_341                    762
#define SPRITE_TSURE_POKE_342                    763
#define SPRITE_TSURE_POKE_343                    764
#define SPRITE_TSURE_POKE_344                    765
#define SPRITE_TSURE_POKE_345                    766
#define SPRITE_TSURE_POKE_346                    767
#define SPRITE_TSURE_POKE_347                    768
#define SPRITE_TSURE_POKE_348                    769
#define SPRITE_TSURE_POKE_349                    770
#define SPRITE_TSURE_POKE_350                    771
#define SPRITE_TSURE_POKE_351                    772
#define SPRITE_TSURE_POKE_352                    773
#define SPRITE_TSURE_POKE_353                    774
#define SPRITE_TSURE_POKE_354                    775
#define SPRITE_TSURE_POKE_355                    776
#define SPRITE_TSURE_POKE_356                    777
#define SPRITE_TSURE_POKE_357                    778
#define SPRITE_TSURE_POKE_358                    779
#define SPRITE_TSURE_POKE_359                    780
#define SPRITE_TSURE_POKE_360                    781
#define SPRITE_TSURE_POKE_361                    782
#define SPRITE_TSURE_POKE_362                    783
#define SPRITE_TSURE_POKE_363                    784
#define SPRITE_TSURE_POKE_364                    785
#define SPRITE_TSURE_POKE_365                    786
#define SPRITE_TSURE_POKE_366                    787
#define SPRITE_TSURE_POKE_367                    788
#define SPRITE_TSURE_POKE_368                    789
#define SPRITE_TSURE_POKE_369                    790
#define SPRITE_TSURE_POKE_370                    791
#define SPRITE_TSURE_POKE_371                    792
#define SPRITE_TSURE_POKE_372                    793
#define SPRITE_TSURE_POKE_373                    794
#define SPRITE_TSURE_POKE_374                    795
#define SPRITE_TSURE_POKE_375                    796
#define SPRITE_TSURE_POKE_376                    797
#define SPRITE_TSURE_POKE_377                    798
#define SPRITE_TSURE_POKE_378                    799
#define SPRITE_TSURE_POKE_379                    800
#define SPRITE_TSURE_POKE_380                    801
#define SPRITE_TSURE_POKE_381                    802
#define SPRITE_TSURE_POKE_382                    803
#define SPRITE_TSURE_POKE_383                    804
#define SPRITE_TSURE_POKE_384                    805
#define SPRITE_TSURE_POKE_385                    806
#define SPRITE_TSURE_POKE_386                    807
#define SPRITE_TSURE_POKE_387                    808
#define SPRITE_TSURE_POKE_388                    809
#define SPRITE_TSURE_POKE_389                    810
#define SPRITE_TSURE_POKE_390                    811
#define SPRITE_TSURE_POKE_391                    812
#define SPRITE_TSURE_POKE_392                    813
#define SPRITE_TSURE_POKE_393                    814
#define SPRITE_TSURE_POKE_394                    815
#define SPRITE_TSURE_POKE_395                    816
#define SPRITE_TSURE_POKE_396                    817
#define SPRITE_TSURE_POKE_397                    818
#define SPRITE_TSURE_POKE_398                    819
#define SPRITE_TSURE_POKE_399                    820
#define SPRITE_TSURE_POKE_400                    821
#define SPRITE_TSURE_POKE_401                    822
#define SPRITE_TSURE_POKE_402                    823
#define SPRITE_TSURE_POKE_403                    824
#define SPRITE_TSURE_POKE_404                    825
#define SPRITE_TSURE_POKE_405                    826
#define SPRITE_TSURE_POKE_406                    827
#define SPRITE_TSURE_POKE_407                    828
#define SPRITE_TSURE_POKE_408                    829
#define SPRITE_TSURE_POKE_409                    830
#define SPRITE_TSURE_POKE_410                    831
#define SPRITE_TSURE_POKE_411                    832
#define SPRITE_TSURE_POKE_412                    833
#define SPRITE_TSURE_POKE_413                    834
#define SPRITE_TSURE_POKE_414                    835
#define SPRITE_TSURE_POKE_415                    836
#define SPRITE_TSURE_POKE_416                    837
#define SPRITE_TSURE_POKE_417                    838
#define SPRITE_TSURE_POKE_418                    839
#define SPRITE_TSURE_POKE_419                    840
#define SPRITE_TSURE_POKE_420                    841
#define SPRITE_TSURE_POKE_421                    842
#define SPRITE_TSURE_POKE_422                    843
#define SPRITE_TSURE_POKE_423                    844
#define SPRITE_TSURE_POKE_424                    845
#define SPRITE_TSURE_POKE_425                    846
#define SPRITE_TSURE_POKE_426                    847
#define SPRITE_TSURE_POKE_427                    848
#define SPRITE_TSURE_POKE_428                    849
#define SPRITE_TSURE_POKE_429                    850
#define SPRITE_TSURE_POKE_430                    851
#define SPRITE_TSURE_POKE_431                    852
#define SPRITE_TSURE_POKE_432                    853
#define SPRITE_TSURE_POKE_433                    854
#define SPRITE_TSURE_POKE_434                    855
#define SPRITE_TSURE_POKE_435                    856
#define SPRITE_TSURE_POKE_436                    857
#define SPRITE_TSURE_POKE_437                    858
#define SPRITE_TSURE_POKE_438                    859
#define SPRITE_TSURE_POKE_439                    860
#define SPRITE_TSURE_POKE_440                    861
#define SPRITE_TSURE_POKE_441                    862
#define SPRITE_TSURE_POKE_442                    863
#define SPRITE_TSURE_POKE_443                    864
#define SPRITE_TSURE_POKE_444                    865
#define SPRITE_TSURE_POKE_445                    866
#define SPRITE_TSURE_POKE_446                    867
#define SPRITE_TSURE_POKE_447                    868
#define SPRITE_TSURE_POKE_448                    869
#define SPRITE_TSURE_POKE_449                    870
#define SPRITE_TSURE_POKE_450                    871
#define SPRITE_TSURE_POKE_451                    872
#define SPRITE_TSURE_POKE_452                    873
#define SPRITE_TSURE_POKE_453                    874
#define SPRITE_TSURE_POKE_454                    875
#define SPRITE_TSURE_POKE_455                    876
#define SPRITE_TSURE_POKE_456                    877
#define SPRITE_TSURE_POKE_457                    878
#define SPRITE_TSURE_POKE_458                    879
#define SPRITE_TSURE_POKE_459                    880
#define SPRITE_TSURE_POKE_460                    881
#define SPRITE_TSURE_POKE_461                    882
#define SPRITE_TSURE_POKE_462                    883
#define SPRITE_TSURE_POKE_463                    884
#define SPRITE_TSURE_POKE_464                    885
#define SPRITE_TSURE_POKE_465                    886
#define SPRITE_TSURE_POKE_466                    887
#define SPRITE_TSURE_POKE_467                    888
#define SPRITE_TSURE_POKE_468                    889
#define SPRITE_TSURE_POKE_469                    890
#define SPRITE_TSURE_POKE_470                    891
#define SPRITE_TSURE_POKE_471                    892
#define SPRITE_TSURE_POKE_472                    893
#define SPRITE_TSURE_POKE_473                    894
#define SPRITE_TSURE_POKE_474                    895
#define SPRITE_TSURE_POKE_475                    896
#define SPRITE_TSURE_POKE_476                    897
#define SPRITE_TSURE_POKE_477                    898
#define SPRITE_TSURE_POKE_478                    899
#define SPRITE_TSURE_POKE_479                    900
#define SPRITE_TSURE_POKE_480                    901
#define SPRITE_TSURE_POKE_481                    902
#define SPRITE_TSURE_POKE_482                    903
#define SPRITE_TSURE_POKE_483                    904
#define SPRITE_TSURE_POKE_484                    905
#define SPRITE_TSURE_POKE_485                    906
#define SPRITE_TSURE_POKE_486                    907
#define SPRITE_TSURE_POKE_487                    908
#define SPRITE_TSURE_POKE_488                    909
#define SPRITE_TSURE_POKE_489                    910
#define SPRITE_TSURE_POKE_490                    911
#define SPRITE_TSURE_POKE_491                    912
#define SPRITE_TSURE_POKE_492                    913
#define SPRITE_TSURE_POKE_493                    914
#define SPRITE_TSURE_POKE_494                    915
#define SPRITE_TSURE_POKE_495                    916
#define SPRITE_TSURE_POKE_496                    917
#define SPRITE_TSURE_POKE_497                    918
#define SPRITE_TSURE_POKE_498                    919
#define SPRITE_TSURE_POKE_499                    920
#define SPRITE_TSURE_POKE_500                    921
#define SPRITE_TSURE_POKE_501                    922
#define SPRITE_TSURE_POKE_502                    923
#define SPRITE_TSURE_POKE_503                    924
#define SPRITE_TSURE_POKE_504                    925
#define SPRITE_TSURE_POKE_505                    926
#define SPRITE_TSURE_POKE_506                    927
#define SPRITE_TSURE_POKE_507                    928
#define SPRITE_TSURE_POKE_508                    929
#define SPRITE_TSURE_POKE_509                    930
#define SPRITE_TSURE_POKE_510                    931
#define SPRITE_TSURE_POKE_511                    932
#define SPRITE_TSURE_POKE_512                    933
#define SPRITE_TSURE_POKE_513                    934
#define SPRITE_TSURE_POKE_514                    935
#define SPRITE_TSURE_POKE_515                    936
#define SPRITE_TSURE_POKE_516                    937
#define SPRITE_TSURE_POKE_517                    938
#define SPRITE_TSURE_POKE_518                    939
#define SPRITE_TSURE_POKE_519                    940
#define SPRITE_TSURE_POKE_520                    941
#define SPRITE_TSURE_POKE_521                    942
#define SPRITE_TSURE_POKE_522                    943
#define SPRITE_TSURE_POKE_523                    944
#define SPRITE_TSURE_POKE_524                    945
#define SPRITE_TSURE_POKE_525                    946
#define SPRITE_TSURE_POKE_526                    947
#define SPRITE_TSURE_POKE_527                    948
#define SPRITE_TSURE_POKE_528                    949
#define SPRITE_TSURE_POKE_529                    950
#define SPRITE_TSURE_POKE_530                    951
#define SPRITE_TSURE_POKE_531                    952
#define SPRITE_TSURE_POKE_532                    953
#define SPRITE_TSURE_POKE_533                    954
#define SPRITE_TSURE_POKE_534                    955
#define SPRITE_TSURE_POKE_535                    956
#define SPRITE_TSURE_POKE_536                    957
#define SPRITE_TSURE_POKE_537                    958
#define SPRITE_TSURE_POKE_538                    959
#define SPRITE_TSURE_POKE_539                    960
#define SPRITE_TSURE_POKE_540                    961
#define SPRITE_TSURE_POKE_541                    962
#define SPRITE_TSURE_POKE_542                    963
#define SPRITE_TSURE_POKE_543                    964
#define SPRITE_TSURE_POKE_544                    965
#define SPRITE_TSURE_POKE_545                    966
#define SPRITE_TSURE_POKE_546                    967
#define SPRITE_TSURE_POKE_547                    968
#define SPRITE_TSURE_POKE_548                    969
#define SPRITE_TSURE_POKE_549                    970
#define SPRITE_TSURE_POKE_550                    971
#define SPRITE_TSURE_POKE_551                    972
#define SPRITE_TSURE_POKE_552                    973
#define SPRITE_TSURE_POKE_553                    974
#define SPRITE_TSURE_POKE_554                    975
#define SPRITE_TSURE_POKE_555                    976
#define SPRITE_TSURE_POKE_556                    977
#define SPRITE_TSURE_POKE_557                    978
#define SPRITE_TSURE_POKE_558                    979
#define SPRITE_TSURE_POKE_559                    980
#define SPRITE_TSURE_POKE_560                    981
#define SPRITE_TSURE_POKE_561                    982
#define SPRITE_TSURE_POKE_562                    983
#define SPRITE_TSURE_POKE_563                    984
#define SPRITE_TSURE_POKE_564                    985
#define SPRITE_TSURE_POKE_565                    986
#define SPRITE_TSURE_POKE_566                    987
#define SPRITE_TSURE_POKE_567                    988
#define SPRITE_TSURE_POKE_568                    989
#define SPRITE_TSURE_POKE_569                    990
#define SPRITE_TSURE_POKE_570                    991
#define SPRITE_TSURE_POKE_571                    992
#define SPRITE_TSURE_POKE_572                    993
#define SPRITE_TSURE_POKE_573                    994
#define SPRITE_TSURE_POKE_574                    995
#define SPRITE_TSURE_POKE_575                    996
#define SPRITE_TSURE_POKE_576                    997
#define SPRITE_TSURE_POKE_577                    998
#define SPRITE_TSURE_POKE_578                    999
#define SPRITE_TSURE_POKE_579                    1000
#define SPRITE_TSURE_POKE_580                    1001
#define SPRITE_TSURE_POKE_581                    1002
#define SPRITE_TSURE_POKE_582                    1003
#define SPRITE_TSURE_POKE_583                    1004
#define SPRITE_TSURE_POKE_584                    1005
#define SPRITE_TSURE_POKE_585                    1006
#define SPRITE_TSURE_POKE_586                    1007
#define SPRITE_TSURE_POKE_587                    1008
#define SPRITE_TSURE_POKE_588                    1009
#define SPRITE_TSURE_POKE_589                    1010
#define SPRITE_TSURE_POKE_590                    1011
#define SPRITE_TSURE_POKE_591                    1012
#define SPRITE_TSURE_POKE_592                    1013
#define SPRITE_TSURE_POKE_593                    1014
#define SPRITE_TSURE_POKE_594                    1015
#define SPRITE_TSURE_POKE_595                    1016
#define SPRITE_TSURE_POKE_596                    1017
#define SPRITE_TSURE_POKE_597                    1018
#define SPRITE_TSURE_POKE_598                    1019
#define SPRITE_TSURE_POKE_599                    1020
#define SPRITE_TSURE_POKE_600                    1021
#define SPRITE_TSURE_POKE_601                    1022
#define SPRITE_TSURE_POKE_602                    1023
#define SPRITE_TSURE_POKE_603                    1024
#define SPRITE_TSURE_POKE_604                    1025
#define SPRITE_TSURE_POKE_605                    1026
#define SPRITE_TSURE_POKE_606                    1027
#define SPRITE_TSURE_POKE_607                    1028
#define SPRITE_TSURE_POKE_608                    1029
#define SPRITE_TSURE_POKE_609                    1030
#define SPRITE_TSURE_POKE_610                    1031
#define SPRITE_TSURE_POKE_611                    1032
#define SPRITE_TSURE_POKE_612                    1033
#define SPRITE_TSURE_POKE_613                    1034
#define SPRITE_TSURE_POKE_614                    1035
#define SPRITE_TSURE_POKE_615                    1036
#define SPRITE_TSURE_POKE_616                    1037
#define SPRITE_TSURE_POKE_617                    1038
#define SPRITE_TSURE_POKE_618                    1039
#define SPRITE_TSURE_POKE_619                    1040
#define SPRITE_TSURE_POKE_620                    1041
#define SPRITE_TSURE_POKE_621                    1042
#define SPRITE_TSURE_POKE_622                    1043
#define SPRITE_TSURE_POKE_623                    1044
#define SPRITE_TSURE_POKE_624                    1045
#define SPRITE_TSURE_POKE_625                    1046
#define SPRITE_TSURE_POKE_626                    1047
#define SPRITE_TSURE_POKE_627                    1048
#define SPRITE_TSURE_POKE_628                    1049
#define SPRITE_BABYBOY1_14                       8192

#define SPRITE_VAR_0                              100
#define SPRITE_VAR_1                              101
#define SPRITE_VAR_2                              102
#define SPRITE_VAR_3                              103
#define SPRITE_VAR_4                              104
#define SPRITE_VAR_5                              105
#define SPRITE_VAR_6                              106
#define SPRITE_VAR_7                              107
#define SPRITE_VAR_8                              108
#define SPRITE_VAR_9                              109
#define SPRITE_VAR_10                             110
#define SPRITE_VAR_11                             111
#define SPRITE_VAR_12                             112
#define SPRITE_VAR_13                             113
#define SPRITE_VAR_14                             114
#define SPRITE_VAR_15                             115

#endif //POKEHEARTGOLD_CONSTANTS_SPRITES_H
