#ifndef POKEHEARTGOLD_CONSTANTS_SPRITES_H
#define POKEHEARTGOLD_CONSTANTS_SPRITES_H

#define SPRITE_HERO                                0
#define SPRITE_BABYBOY1                            1
#define SPRITE_BABYGIRL1                           2
#define SPRITE_BOY1                                3
#define SPRITE_BOY2                                4
#define SPRITE_BOY3                                5
#define SPRITE_GIRL1                               6
#define SPRITE_GIRL2                               7
#define SPRITE_GIRL3                               8
#define SPRITE_MAN1                                9
#define SPRITE_MAN2                               10
#define SPRITE_MAN3                               11
#define SPRITE_WOMAN1                             12
#define SPRITE_WOMAN2                             13
#define SPRITE_WOMAN3                             14
#define SPRITE_MIDDLEMAN1                         15
#define SPRITE_MIDDLEWOMAN1                       16
#define SPRITE_OLDMAN1                            17
#define SPRITE_OLDWOMAN1                          18
#define SPRITE_BIGMAN                             19
#define SPRITE_MOUNT                              20
#define SPRITE_CYCLEHERO                          21
#define SPRITE_REPORTER                           22
#define SPRITE_CAMERAMAN                          23
#define SPRITE_SHOPM1                             24
#define SPRITE_SHOPW1                             25
#define SPRITE_ASSISTANTM                         29
#define SPRITE_ASSISTANTW                         30
#define SPRITE_BADMAN                             31
#define SPRITE_SKIERW                             33
#define SPRITE_POLICEMAN                          34
#define SPRITE_IDOL                               35
#define SPRITE_GENTLEMAN                          36
#define SPRITE_LADY                               37
#define SPRITE_CYCLEM                             38
#define SPRITE_CYCLEW                             39
#define SPRITE_WORKMAN                            40
#define SPRITE_FARMER                             41
#define SPRITE_COWGIRL                            42
#define SPRITE_CLOWN                              43
#define SPRITE_ARTIST                             44
#define SPRITE_SPORTSMAN                          45
#define SPRITE_EXPLORE                            50
#define SPRITE_FIGHTER                            51
#define SPRITE_CAMPBOY                            52
#define SPRITE_PICNICGIRL                         53
#define SPRITE_FISHING                            54
#define SPRITE_AMBRELLA                           55
#define SPRITE_SEAMAN                             56
#define SPRITE_WAITER                             59
#define SPRITE_WAITRESS                           60
#define SPRITE_GORGGEOUSM                         62
#define SPRITE_GORGGEOUSW                         63
#define SPRITE_MAN5                               68
#define SPRITE_WOMAN5                             69
#define SPRITE_MYSTERY                            70
#define SPRITE_PIKACHU                            71
#define SPRITE_ROCK                               84
#define SPRITE_BREAKROCK                          85
#define SPRITE_TREE                               86
#define SPRITE_MONSTARBALL                        87
#define SPRITE_HEROINE                            97
#define SPRITE_CYCLEHEROINE                       98
#define SPRITE_DOCTOR                             99
#define SPRITE_LEADER1                           126
#define SPRITE_LEADER2                           127
#define SPRITE_LEADER3                           128
#define SPRITE_LEADER4                           129
#define SPRITE_LEADER5                           130
#define SPRITE_LEADER6                           131
#define SPRITE_LEADER7                           132
#define SPRITE_LEADER8                           133
#define SPRITE_SEVEN1                            141
#define SPRITE_SEVEN2                            142
#define SPRITE_SEVEN3                            143
#define SPRITE_SEVEN4                            144
#define SPRITE_SEVEN5                            145
#define SPRITE_GSBOY1                            146
#define SPRITE_GSRIVEL                           148
#define SPRITE_SUNGLASSES                        168
#define SPRITE_TOWERBOSS                         169
#define SPRITE_MAID                              175
#define SPRITE_SPHERO                            176
#define SPRITE_SPHEROINE                         177
#define SPRITE_SWIMHERO                          178
#define SPRITE_SWIMHEROINE                       179
#define SPRITE_WATERHERO                         180
#define SPRITE_WATERHEROINE                      181
#define SPRITE_BABYBOY1_2                        183
#define SPRITE_FISHINGHERO                       188
#define SPRITE_FISH_HEROINE                      189
#define SPRITE_DELIVERY                          193
#define SPRITE_POKEHERO                          196
#define SPRITE_POKEHEROINE                       197
#define SPRITE_SAVEHERO                          198
#define SPRITE_SAVEHEROINE                       199
#define SPRITE_BANZAIHERO                        200
#define SPRITE_BANZAIHEROINE                     201
#define SPRITE_POKEWALL                          210
#define SPRITE_RED                               211
#define SPRITE_THIEF                             218
#define SPRITE_ITAKO                             219
#define SPRITE_BOZU                              220
#define SPRITE_ROCKETW                           221
#define SPRITE_ROCKETM                           222
#define SPRITE_RKANBUW                           223
#define SPRITE_RKANBUM                           224
#define SPRITE_BOARDER                           225
#define SPRITE_FIRE                              227
#define SPRITE_GANG                              229
#define SPRITE_DANCER                            232
#define SPRITE_GANTETSU                          233
#define SPRITE_MONO_PIP                          234
#define SPRITE_MASAKI                            235
#define SPRITE_CAPTAIN                           236
#define SPRITE_RGYARADOSU                        237
#define SPRITE_HERO_2                            238
#define SPRITE_HEROINE_2                         239
#define SPRITE_LADDERHERO                        248
#define SPRITE_LADDERHEROINE                     249
#define SPRITE_ITAKO_                            250
#define SPRITE_BABYBOY1_3                        251
#define SPRITE_BABYBOY1_4                        252
#define SPRITE_BABYBOY1_5                        253
#define SPRITE_BABYBOY1_6                        254
#define SPRITE_BABYBOY1_7                        255
#define SPRITE_BABYBOY1_8                        256
#define SPRITE_BABYBOY1_9                        257
#define SPRITE_RHERO                             258
#define SPRITE_RHEROINE                          259
#define SPRITE_RBANZAIHERO                       260
#define SPRITE_RBANZAIINE                        261
#define SPRITE_BONGURI                           262
#define SPRITE_BONGURI_R                         263
#define SPRITE_BONGURI_Y                         264
#define SPRITE_BONGURI_B                         265
#define SPRITE_BONGURI_G                         266
#define SPRITE_BONGURI_P                         267
#define SPRITE_BONGURI_W                         268
#define SPRITE_BONGURI_BK                        269
#define SPRITE_BONMI_R                           270
#define SPRITE_BONMI_Y                           271
#define SPRITE_BONMI_B                           272
#define SPRITE_BONMI_G                           273
#define SPRITE_BONMI_P                           274
#define SPRITE_BONMI_W                           275
#define SPRITE_BONMI_BK                          276
#define SPRITE_BRAINS1                           277
#define SPRITE_BRAINS2                           278
#define SPRITE_BRAINS3                           279
#define SPRITE_BRAINS4                           280
#define SPRITE_PRINCESS                          281
#define SPRITE_BFSM                              282
#define SPRITE_BFSW1                             283
#define SPRITE_BFSW2                             284
#define SPRITE_WIFISM                            285
#define SPRITE_WIFISF                            286
#define SPRITE_AJI_PERU                          287
#define SPRITE_BABYBOY1_10                       288
#define SPRITE_BABYBOY1_11                       289
#define SPRITE_LEAG_DOOR2                        290
#define SPRITE_BABYBOY1_12                       291
#define SPRITE_BABYBOY1_13                       292
#define SPRITE_RKANBUM2                          293
#define SPRITE_RKANBUM3                          294
#define SPRITE_PL_BOY01C                         295
#define SPRITE_PL_GIRL01C                        296
#define SPRITE_SAVERHERO                         297
#define SPRITE_SAVERHEROINE                      298
#define SPRITE_DELIVERY2                         299
#define SPRITE_GSBABYBOY1                        315
#define SPRITE_GSBABYGIRL1                       316
#define SPRITE_GSBOY2                            317
#define SPRITE_GSBOY3                            318
#define SPRITE_GSGIRL1                           319
#define SPRITE_GSGIRL2                           320
#define SPRITE_GSGIRL3                           321
#define SPRITE_GSMAN1                            322
#define SPRITE_GSMAN2                            323
#define SPRITE_GSMAN3                            324
#define SPRITE_GSWOMAN1                          325
#define SPRITE_GSWOMAN2                          326
#define SPRITE_GSWOMAN3                          327
#define SPRITE_GSMIDDLEMAN1                      328
#define SPRITE_MIDDLEWOMAN1_2                    329
#define SPRITE_GSOLDMAN1                         330
#define SPRITE_GSOLDWOMAN1                       331
#define SPRITE_GSBIGMAN                          332
#define SPRITE_MOUNT_2                           333
#define SPRITE_SHOPM1_2                          334
#define SPRITE_PCWOMAN1                          335
#define SPRITE_PCWOMAN2                          336
#define SPRITE_PCWOMAN3                          337
#define SPRITE_GSASSISTANTM                      338
#define SPRITE_GSGENTLEMAN                       341
#define SPRITE_GSSWIMMERM                        342
#define SPRITE_GSSWIMMERW                        343
#define SPRITE_GSFIGHTER                         344
#define SPRITE_CAMPBOY_2                         345
#define SPRITE_PICNICGIRL_2                      346
#define SPRITE_FISHING_2                         347
#define SPRITE_SEAMAN_2                          348
#define SPRITE_STOP                              349
#define SPRITE_GTOROPHY                          350
#define SPRITE_MYSTERY_2                         351
#define SPRITE_GSLEADER1                         352
#define SPRITE_GSLEADER2                         353
#define SPRITE_GSLEADER3                         354
#define SPRITE_GSLEADER4                         355
#define SPRITE_GSLEADER5                         356
#define SPRITE_GSLEADER6                         357
#define SPRITE_GSLEADER7                         358
#define SPRITE_GSLEADER8                         359
#define SPRITE_GSBIGFOUR1                        360
#define SPRITE_GSBIGFOUR2                        361
#define SPRITE_GSBIGFOUR3                        362
#define SPRITE_GSBIGFOUR4                        363
#define SPRITE_WATARU                            364
#define SPRITE_GSMAMA                            365
#define SPRITE_OOKIDO                            366
#define SPRITE_GSDSBOY                           367
#define SPRITE_GSLEADER9                         368
#define SPRITE_GSLEADER10                        369
#define SPRITE_GSLEADER11                        370
#define SPRITE_GSLEADER12                        371
#define SPRITE_GSLEADER13                        372
#define SPRITE_GSLEADER14                        373
#define SPRITE_GSLEADER15                        374
#define SPRITE_GSLEADER16                        375
#define SPRITE_STOROPHY                          376
#define SPRITE_MANIA                             377
#define SPRITE_JUGGRER                           378
#define SPRITE_BTOROPHY                          379
#define SPRITE_JUPETTA                           380
#define SPRITE_USOKKY                            381
#define SPRITE_MINAKI                            382
#define SPRITE_THLONOWNER                        383
#define SPRITE_INSTRUCTOR                        384
#define SPRITE_SAKAKI                            385
#define SPRITE_SUIT                              386
#define SPRITE_CHOUROU                           387
#define SPRITE_KURUMI                            389
#define SPRITE_RAPURASU                          390
#define SPRITE_NANAMI                            392
#define SPRITE_REDMAMA                           393
#define SPRITE_COUNTERM                          394
#define SPRITE_KABIGON                           395
#define SPRITE_MEDAL                             396
#define SPRITE_SCROLL                            397
#define SPRITE_SIGNSHOES                         398
#define SPRITE_SIGNCLOTHES                       399
#define SPRITE_SIGNFLAG                          400
#define SPRITE_SIGNPOKEGEAR                      401
#define SPRITE_SIGNBALL                          402
#define SPRITE_STATUEHERO                        403
#define SPRITE_STATUEHEROINE                     404
#define SPRITE_ICE                               406
#define SPRITE_PKTHHERO                          407
#define SPRITE_PKTHHEROINE                       408
#define SPRITE_ROTOMF                            409
#define SPRITE_ROTOMS                            410
#define SPRITE_ROTOMI                            411
#define SPRITE_ROTOMW                            412
#define SPRITE_ROTOMG                            413
#define SPRITE_YADON                             414
#define SPRITE_TSURE_POKE                        415
#define SPRITE_TSURE_POKE_2                      416
#define SPRITE_TSURE_POKE_3                      417
#define SPRITE_TSURE_POKE_4                      418
#define SPRITE_TSURE_POKE_5                      419
#define SPRITE_TSURE_POKE_6                      420
#define SPRITE_DAIGO                             421
#define SPRITE_CHAMPION                          422
#define SPRITE_SHAKEHERO                         423
#define SPRITE_SHAKEHEROINE                      424
#define SPRITE_HOU_OBJ01                         425
#define SPRITE_LUG_OBJ01                         426
#define SPRITE_GSWOMAN6                          427
#define SPRITE_TSURE_POKE_BULBASAUR              428
#define SPRITE_TSURE_POKE_IVYSAUR                429
#define SPRITE_TSURE_POKE_VENUSAUR               430
#define SPRITE_TSURE_POKE_VENUSAUR_F             431
#define SPRITE_TSURE_POKE_CHARMANDER             432
#define SPRITE_TSURE_POKE_CHARMELEON             433
#define SPRITE_TSURE_POKE_CHARIZARD              434
#define SPRITE_TSURE_POKE_SQUIRTLE               435
#define SPRITE_TSURE_POKE_WARTORTLE              436
#define SPRITE_TSURE_POKE_BLASTOISE              437
#define SPRITE_TSURE_POKE_CATERPIE               438
#define SPRITE_TSURE_POKE_METAPOD                439
#define SPRITE_TSURE_POKE_BUTTERFREE             440
#define SPRITE_TSURE_POKE_WEEDLE                 441
#define SPRITE_TSURE_POKE_KAKUNA                 442
#define SPRITE_TSURE_POKE_BEEDRILL               443
#define SPRITE_TSURE_POKE_PIDGEY                 444
#define SPRITE_TSURE_POKE_PIDGEOTTO              445
#define SPRITE_TSURE_POKE_PIDGEOT                446
#define SPRITE_TSURE_POKE_RATTATA                447
#define SPRITE_TSURE_POKE_RATICATE               448
#define SPRITE_TSURE_POKE_SPEAROW                449
#define SPRITE_TSURE_POKE_FEAROW                 450
#define SPRITE_TSURE_POKE_EKANS                  451
#define SPRITE_TSURE_POKE_ARBOK                  452
#define SPRITE_TSURE_POKE_PIKACHU                453
#define SPRITE_TSURE_POKE_PIKACHU_F              454
#define SPRITE_TSURE_POKE_RAICHU                 455
#define SPRITE_TSURE_POKE_SANDSHREW              456
#define SPRITE_TSURE_POKE_SANDSLASH              457
#define SPRITE_TSURE_POKE_NIDORAN_F              458
#define SPRITE_TSURE_POKE_NIDORINA               459
#define SPRITE_TSURE_POKE_NIDOQUEEN              460
#define SPRITE_TSURE_POKE_NIDORAN_M              461
#define SPRITE_TSURE_POKE_NIDORINO               462
#define SPRITE_TSURE_POKE_NIDOKING               463
#define SPRITE_TSURE_POKE_CLEFAIRY               464
#define SPRITE_TSURE_POKE_CLEFABLE               465
#define SPRITE_TSURE_POKE_VULPIX                 466
#define SPRITE_TSURE_POKE_NINETALES              467
#define SPRITE_TSURE_POKE_JIGGLYPUFF             468
#define SPRITE_TSURE_POKE_WIGGLYTUFF             469
#define SPRITE_TSURE_POKE_ZUBAT                  470
#define SPRITE_TSURE_POKE_GOLBAT                 471
#define SPRITE_TSURE_POKE_ODDISH                 472
#define SPRITE_TSURE_POKE_GLOOM                  473
#define SPRITE_TSURE_POKE_VILEPLUME              474
#define SPRITE_TSURE_POKE_PARAS                  475
#define SPRITE_TSURE_POKE_PARASECT               476
#define SPRITE_TSURE_POKE_VENONAT                477
#define SPRITE_TSURE_POKE_VENOMOTH               478
#define SPRITE_TSURE_POKE_DIGLETT                479
#define SPRITE_TSURE_POKE_DUGTRIO                480
#define SPRITE_TSURE_POKE_MEOWTH                 481
#define SPRITE_TSURE_POKE_PERSIAN                482
#define SPRITE_TSURE_POKE_PSYDUCK                483
#define SPRITE_TSURE_POKE_GOLDUCK                484
#define SPRITE_TSURE_POKE_MANKEY                 485
#define SPRITE_TSURE_POKE_PRIMEAPE               486
#define SPRITE_TSURE_POKE_GROWLITHE              487
#define SPRITE_TSURE_POKE_ARCANINE               488
#define SPRITE_TSURE_POKE_POLIWAG                489
#define SPRITE_TSURE_POKE_POLIWHIRL              490
#define SPRITE_TSURE_POKE_POLIWRATH              491
#define SPRITE_TSURE_POKE_ABRA                   492
#define SPRITE_TSURE_POKE_KADABRA                493
#define SPRITE_TSURE_POKE_ALAKAZAM               494
#define SPRITE_TSURE_POKE_MACHOP                 495
#define SPRITE_TSURE_POKE_MACHOKE                496
#define SPRITE_TSURE_POKE_MACHAMP                497
#define SPRITE_TSURE_POKE_BELLSPROUT             498
#define SPRITE_TSURE_POKE_WEEPINBELL             499
#define SPRITE_TSURE_POKE_VICTREEBEL             500
#define SPRITE_TSURE_POKE_TENTACOOL              501
#define SPRITE_TSURE_POKE_TENTACRUEL             502
#define SPRITE_TSURE_POKE_GEODUDE                503
#define SPRITE_TSURE_POKE_GRAVELER               504
#define SPRITE_TSURE_POKE_GOLEM                  505
#define SPRITE_TSURE_POKE_PONYTA                 506
#define SPRITE_TSURE_POKE_RAPIDASH               507
#define SPRITE_TSURE_POKE_SLOWPOKE               508
#define SPRITE_TSURE_POKE_SLOWBRO                509
#define SPRITE_TSURE_POKE_MAGNEMITE              510
#define SPRITE_TSURE_POKE_MAGNETON               511
#define SPRITE_TSURE_POKE_FARFETCHD              512
#define SPRITE_TSURE_POKE_DODUO                  513
#define SPRITE_TSURE_POKE_DODRIO                 514
#define SPRITE_TSURE_POKE_SEEL                   515
#define SPRITE_TSURE_POKE_DEWGONG                516
#define SPRITE_TSURE_POKE_GRIMER                 517
#define SPRITE_TSURE_POKE_MUK                    518
#define SPRITE_TSURE_POKE_SHELLDER               519
#define SPRITE_TSURE_POKE_CLOYSTER               520
#define SPRITE_TSURE_POKE_GASTLY                 521
#define SPRITE_TSURE_POKE_HAUNTER                522
#define SPRITE_TSURE_POKE_GENGAR                 523
#define SPRITE_TSURE_POKE_ONIX                   524
#define SPRITE_TSURE_POKE_DROWZEE                525
#define SPRITE_TSURE_POKE_HYPNO                  526
#define SPRITE_TSURE_POKE_KRABBY                 527
#define SPRITE_TSURE_POKE_KINGLER                528
#define SPRITE_TSURE_POKE_VOLTORB                529
#define SPRITE_TSURE_POKE_ELECTRODE              530
#define SPRITE_TSURE_POKE_EXEGGCUTE              531
#define SPRITE_TSURE_POKE_EXEGGUTOR              532
#define SPRITE_TSURE_POKE_CUBONE                 533
#define SPRITE_TSURE_POKE_MAROWAK                534
#define SPRITE_TSURE_POKE_HITMONLEE              535
#define SPRITE_TSURE_POKE_HITMONCHAN             536
#define SPRITE_TSURE_POKE_LICKITUNG              537
#define SPRITE_TSURE_POKE_KOFFING                538
#define SPRITE_TSURE_POKE_WEEZING                539
#define SPRITE_TSURE_POKE_RHYHORN                540
#define SPRITE_TSURE_POKE_RHYDON                 541
#define SPRITE_TSURE_POKE_CHANSEY                542
#define SPRITE_TSURE_POKE_TANGELA                543
#define SPRITE_TSURE_POKE_KANGASKHAN             544
#define SPRITE_TSURE_POKE_HORSEA                 545
#define SPRITE_TSURE_POKE_SEADRA                 546
#define SPRITE_TSURE_POKE_GOLDEEN                547
#define SPRITE_TSURE_POKE_SEAKING                548
#define SPRITE_TSURE_POKE_STARYU                 549
#define SPRITE_TSURE_POKE_STARMIE                550
#define SPRITE_TSURE_POKE_MR_MIME                551
#define SPRITE_TSURE_POKE_SCYTHER                552
#define SPRITE_TSURE_POKE_JYNX                   553
#define SPRITE_TSURE_POKE_ELECTABUZZ             554
#define SPRITE_TSURE_POKE_MAGMAR                 555
#define SPRITE_TSURE_POKE_PINSIR                 556
#define SPRITE_TSURE_POKE_TAUROS                 557
#define SPRITE_TSURE_POKE_MAGIKARP               558
#define SPRITE_TSURE_POKE_GYARADOS               559
#define SPRITE_TSURE_POKE_LAPRAS                 560
#define SPRITE_TSURE_POKE_DITTO                  561
#define SPRITE_TSURE_POKE_EEVEE                  562
#define SPRITE_TSURE_POKE_VAPOREON               563
#define SPRITE_TSURE_POKE_JOLTEON                564
#define SPRITE_TSURE_POKE_FLAREON                565
#define SPRITE_TSURE_POKE_PORYGON                566
#define SPRITE_TSURE_POKE_OMANYTE                567
#define SPRITE_TSURE_POKE_OMASTAR                568
#define SPRITE_TSURE_POKE_KABUTO                 569
#define SPRITE_TSURE_POKE_KABUTOPS               570
#define SPRITE_TSURE_POKE_AERODACTYL             571
#define SPRITE_TSURE_POKE_SNORLAX                572
#define SPRITE_TSURE_POKE_ARTICUNO               573
#define SPRITE_TSURE_POKE_ZAPDOS                 574
#define SPRITE_TSURE_POKE_MOLTRES                575
#define SPRITE_TSURE_POKE_DRATINI                576
#define SPRITE_TSURE_POKE_DRAGONAIR              577
#define SPRITE_TSURE_POKE_DRAGONITE              578
#define SPRITE_TSURE_POKE_MEWTWO                 579
#define SPRITE_TSURE_POKE_MEW                    580
#define SPRITE_TSURE_POKE_CHIKORITA              581
#define SPRITE_TSURE_POKE_BAYLEEF                582
#define SPRITE_TSURE_POKE_MEGANIUM               583
#define SPRITE_TSURE_POKE_MEGANIUM_F             584
#define SPRITE_TSURE_POKE_CYNDAQUIL              585
#define SPRITE_TSURE_POKE_QUILAVA                586
#define SPRITE_TSURE_POKE_TYPHLOSION             587
#define SPRITE_TSURE_POKE_TOTODILE               588
#define SPRITE_TSURE_POKE_CROCONAW               589
#define SPRITE_TSURE_POKE_FERALIGATR             590
#define SPRITE_TSURE_POKE_SENTRET                591
#define SPRITE_TSURE_POKE_FURRET                 592
#define SPRITE_TSURE_POKE_HOOTHOOT               593
#define SPRITE_TSURE_POKE_NOCTOWL                594
#define SPRITE_TSURE_POKE_LEDYBA                 595
#define SPRITE_TSURE_POKE_LEDIAN                 596
#define SPRITE_TSURE_POKE_SPINARAK               597
#define SPRITE_TSURE_POKE_ARIADOS                598
#define SPRITE_TSURE_POKE_CROBAT                 599
#define SPRITE_TSURE_POKE_CHINCHOU               600
#define SPRITE_TSURE_POKE_LANTURN                601
#define SPRITE_TSURE_POKE_PICHU                  602
#define SPRITE_TSURE_POKE_PICHU_SPIKY            603
#define SPRITE_TSURE_POKE_CLEFFA                 604
#define SPRITE_TSURE_POKE_IGGLYBUFF              605
#define SPRITE_TSURE_POKE_TOGEPI                 606
#define SPRITE_TSURE_POKE_TOGETIC                607
#define SPRITE_TSURE_POKE_NATU                   608
#define SPRITE_TSURE_POKE_XATU                   609
#define SPRITE_TSURE_POKE_MAREEP                 610
#define SPRITE_TSURE_POKE_FLAAFFY                611
#define SPRITE_TSURE_POKE_AMPHAROS               612
#define SPRITE_TSURE_POKE_BELLOSSOM              613
#define SPRITE_TSURE_POKE_MARILL                 614
#define SPRITE_TSURE_POKE_AZUMARILL              615
#define SPRITE_TSURE_POKE_SUDOWOODO              616
#define SPRITE_TSURE_POKE_POLITOED               617
#define SPRITE_TSURE_POKE_HOPPIP                 618
#define SPRITE_TSURE_POKE_SKIPLOOM               619
#define SPRITE_TSURE_POKE_JUMPLUFF               620
#define SPRITE_TSURE_POKE_AIPOM                  621
#define SPRITE_TSURE_POKE_SUNKERN                622
#define SPRITE_TSURE_POKE_SUNFLORA               623
#define SPRITE_TSURE_POKE_YANMA                  624
#define SPRITE_TSURE_POKE_WOOPER                 625
#define SPRITE_TSURE_POKE_QUAGSIRE               626
#define SPRITE_TSURE_POKE_ESPEON                 627
#define SPRITE_TSURE_POKE_UMBREON                628
#define SPRITE_TSURE_POKE_MURKROW                629
#define SPRITE_TSURE_POKE_SLOWKING               630
#define SPRITE_TSURE_POKE_MISDREAVUS             631
#define SPRITE_TSURE_POKE_UNOWN_A                632
#define SPRITE_TSURE_POKE_UNOWN_B                633
#define SPRITE_TSURE_POKE_UNOWN_C                634
#define SPRITE_TSURE_POKE_UNOWN_D                635
#define SPRITE_TSURE_POKE_UNOWN_E                636
#define SPRITE_TSURE_POKE_UNOWN_F                637
#define SPRITE_TSURE_POKE_UNOWN_G                638
#define SPRITE_TSURE_POKE_UNOWN_H                639
#define SPRITE_TSURE_POKE_UNOWN_I                640
#define SPRITE_TSURE_POKE_UNOWN_J                641
#define SPRITE_TSURE_POKE_UNOWN_K                642
#define SPRITE_TSURE_POKE_UNOWN_L                643
#define SPRITE_TSURE_POKE_UNOWN_M                644
#define SPRITE_TSURE_POKE_UNOWN_N                645
#define SPRITE_TSURE_POKE_UNOWN_O                646
#define SPRITE_TSURE_POKE_UNOWN_P                647
#define SPRITE_TSURE_POKE_UNOWN_Q                648
#define SPRITE_TSURE_POKE_UNOWN_R                649
#define SPRITE_TSURE_POKE_UNOWN_S                650
#define SPRITE_TSURE_POKE_UNOWN_T                651
#define SPRITE_TSURE_POKE_UNOWN_U                652
#define SPRITE_TSURE_POKE_UNOWN_V                653
#define SPRITE_TSURE_POKE_UNOWN_W                654
#define SPRITE_TSURE_POKE_UNOWN_X                655
#define SPRITE_TSURE_POKE_UNOWN_Y                656
#define SPRITE_TSURE_POKE_UNOWN_Z                657
#define SPRITE_TSURE_POKE_UNOWN_QMARK            658
#define SPRITE_TSURE_POKE_UNOWN_EXCL             659
#define SPRITE_TSURE_POKE_WOBBUFFET              660
#define SPRITE_TSURE_POKE_WOBBUFFET_F            661
#define SPRITE_TSURE_POKE_GIRAFARIG              662
#define SPRITE_TSURE_POKE_PINECO                 663
#define SPRITE_TSURE_POKE_FORRETRESS             664
#define SPRITE_TSURE_POKE_DUNSPARCE              665
#define SPRITE_TSURE_POKE_GLIGAR                 666
#define SPRITE_TSURE_POKE_STEELIX                667
#define SPRITE_TSURE_POKE_STEELIX_F              668
#define SPRITE_TSURE_POKE_SNUBBULL               669
#define SPRITE_TSURE_POKE_GRANBULL               670
#define SPRITE_TSURE_POKE_QWILFISH               671
#define SPRITE_TSURE_POKE_SCIZOR                 672
#define SPRITE_TSURE_POKE_SHUCKLE                673
#define SPRITE_TSURE_POKE_HERACROSS              674
#define SPRITE_TSURE_POKE_HERACROSS_F            675
#define SPRITE_TSURE_POKE_SNEASEL                676
#define SPRITE_TSURE_POKE_TEDDIURSA              677
#define SPRITE_TSURE_POKE_URSARING               678
#define SPRITE_TSURE_POKE_SLUGMA                 679
#define SPRITE_TSURE_POKE_MAGCARGO               680
#define SPRITE_TSURE_POKE_SWINUB                 681
#define SPRITE_TSURE_POKE_PILOSWINE              682
#define SPRITE_TSURE_POKE_CORSOLA                683
#define SPRITE_TSURE_POKE_REMORAID               684
#define SPRITE_TSURE_POKE_OCTILLERY              685
#define SPRITE_TSURE_POKE_DELIBIRD               686
#define SPRITE_TSURE_POKE_MANTINE                687
#define SPRITE_TSURE_POKE_SKARMORY               688
#define SPRITE_TSURE_POKE_HOUNDOUR               689
#define SPRITE_TSURE_POKE_HOUNDOOM               690
#define SPRITE_TSURE_POKE_KINGDRA                691
#define SPRITE_TSURE_POKE_PHANPY                 692
#define SPRITE_TSURE_POKE_DONPHAN                693
#define SPRITE_TSURE_POKE_PORYGON2               694
#define SPRITE_TSURE_POKE_STANTLER               695
#define SPRITE_TSURE_POKE_SMEARGLE               696
#define SPRITE_TSURE_POKE_TYROGUE                697
#define SPRITE_TSURE_POKE_HITMONTOP              698
#define SPRITE_TSURE_POKE_SMOOCHUM               699
#define SPRITE_TSURE_POKE_ELEKID                 700
#define SPRITE_TSURE_POKE_MAGBY                  701
#define SPRITE_TSURE_POKE_MILTANK                702
#define SPRITE_TSURE_POKE_BLISSEY                703
#define SPRITE_TSURE_POKE_RAIKOU                 704
#define SPRITE_TSURE_POKE_ENTEI                  705
#define SPRITE_TSURE_POKE_SUICUNE                706
#define SPRITE_TSURE_POKE_LARVITAR               707
#define SPRITE_TSURE_POKE_PUPITAR                708
#define SPRITE_TSURE_POKE_TYRANITAR              709
#define SPRITE_TSURE_POKE_LUGIA                  710
#define SPRITE_TSURE_POKE_HO_OH                  711
#define SPRITE_TSURE_POKE_CELEBI                 712
#define SPRITE_TSURE_POKE_TREECKO                713
#define SPRITE_TSURE_POKE_GROVYLE                714
#define SPRITE_TSURE_POKE_SCEPTILE               715
#define SPRITE_TSURE_POKE_TORCHIC                716
#define SPRITE_TSURE_POKE_COMBUSKEN              717
#define SPRITE_TSURE_POKE_BLAZIKEN               718
#define SPRITE_TSURE_POKE_MUDKIP                 719
#define SPRITE_TSURE_POKE_MARSHTOMP              720
#define SPRITE_TSURE_POKE_SWAMPERT               721
#define SPRITE_TSURE_POKE_POOCHYENA              722
#define SPRITE_TSURE_POKE_MIGHTYENA              723
#define SPRITE_TSURE_POKE_ZIGZAGOON              724
#define SPRITE_TSURE_POKE_LINOONE                725
#define SPRITE_TSURE_POKE_WURMPLE                726
#define SPRITE_TSURE_POKE_SILCOON                727
#define SPRITE_TSURE_POKE_BEAUTIFLY              728
#define SPRITE_TSURE_POKE_CASCOON                729
#define SPRITE_TSURE_POKE_DUSTOX                 730
#define SPRITE_TSURE_POKE_LOTAD                  731
#define SPRITE_TSURE_POKE_LOMBRE                 732
#define SPRITE_TSURE_POKE_LUDICOLO               733
#define SPRITE_TSURE_POKE_SEEDOT                 734
#define SPRITE_TSURE_POKE_NUZLEAF                735
#define SPRITE_TSURE_POKE_SHIFTRY                736
#define SPRITE_TSURE_POKE_TAILLOW                737
#define SPRITE_TSURE_POKE_SWELLOW                738
#define SPRITE_TSURE_POKE_WINGULL                739
#define SPRITE_TSURE_POKE_PELIPPER               740
#define SPRITE_TSURE_POKE_RALTS                  741
#define SPRITE_TSURE_POKE_KIRLIA                 742
#define SPRITE_TSURE_POKE_GARDEVOIR              743
#define SPRITE_TSURE_POKE_SURSKIT                744
#define SPRITE_TSURE_POKE_MASQUERAIN             745
#define SPRITE_TSURE_POKE_SHROOMISH              746
#define SPRITE_TSURE_POKE_BRELOOM                747
#define SPRITE_TSURE_POKE_SLAKOTH                748
#define SPRITE_TSURE_POKE_VIGOROTH               749
#define SPRITE_TSURE_POKE_SLAKING                750
#define SPRITE_TSURE_POKE_NINCADA                751
#define SPRITE_TSURE_POKE_NINJASK                752
#define SPRITE_TSURE_POKE_SHEDINJA               753
#define SPRITE_TSURE_POKE_WHISMUR                754
#define SPRITE_TSURE_POKE_LOUDRED                755
#define SPRITE_TSURE_POKE_EXPLOUD                756
#define SPRITE_TSURE_POKE_MAKUHITA               757
#define SPRITE_TSURE_POKE_HARIYAMA               758
#define SPRITE_TSURE_POKE_AZURILL                759
#define SPRITE_TSURE_POKE_NOSEPASS               760
#define SPRITE_TSURE_POKE_SKITTY                 761
#define SPRITE_TSURE_POKE_DELCATTY               762
#define SPRITE_TSURE_POKE_SABLEYE                763
#define SPRITE_TSURE_POKE_MAWILE                 764
#define SPRITE_TSURE_POKE_ARON                   765
#define SPRITE_TSURE_POKE_LAIRON                 766
#define SPRITE_TSURE_POKE_AGGRON                 767
#define SPRITE_TSURE_POKE_MEDITITE               768
#define SPRITE_TSURE_POKE_MEDICHAM               769
#define SPRITE_TSURE_POKE_ELECTRIKE              770
#define SPRITE_TSURE_POKE_MANECTRIC              771
#define SPRITE_TSURE_POKE_PLUSLE                 772
#define SPRITE_TSURE_POKE_MINUN                  773
#define SPRITE_TSURE_POKE_VOLBEAT                774
#define SPRITE_TSURE_POKE_ILLUMISE               775
#define SPRITE_TSURE_POKE_ROSELIA                776
#define SPRITE_TSURE_POKE_GULPIN                 777
#define SPRITE_TSURE_POKE_SWALOT                 778
#define SPRITE_TSURE_POKE_CARVANHA               779
#define SPRITE_TSURE_POKE_SHARPEDO               780
#define SPRITE_TSURE_POKE_WAILMER                781
#define SPRITE_TSURE_POKE_WAILORD                782
#define SPRITE_TSURE_POKE_NUMEL                  783
#define SPRITE_TSURE_POKE_CAMERUPT               784
#define SPRITE_TSURE_POKE_TORKOAL                785
#define SPRITE_TSURE_POKE_SPOINK                 786
#define SPRITE_TSURE_POKE_GRUMPIG                787
#define SPRITE_TSURE_POKE_SPINDA                 788
#define SPRITE_TSURE_POKE_TRAPINCH               789
#define SPRITE_TSURE_POKE_VIBRAVA                790
#define SPRITE_TSURE_POKE_FLYGON                 791
#define SPRITE_TSURE_POKE_CACNEA                 792
#define SPRITE_TSURE_POKE_CACTURNE               793
#define SPRITE_TSURE_POKE_SWABLU                 794
#define SPRITE_TSURE_POKE_ALTARIA                795
#define SPRITE_TSURE_POKE_ZANGOOSE               796
#define SPRITE_TSURE_POKE_SEVIPER                797
#define SPRITE_TSURE_POKE_LUNATONE               798
#define SPRITE_TSURE_POKE_SOLROCK                799
#define SPRITE_TSURE_POKE_BARBOACH               800
#define SPRITE_TSURE_POKE_WHISCASH               801
#define SPRITE_TSURE_POKE_CORPHISH               802
#define SPRITE_TSURE_POKE_CRAWDAUNT              803
#define SPRITE_TSURE_POKE_BALTOY                 804
#define SPRITE_TSURE_POKE_CLAYDOL                805
#define SPRITE_TSURE_POKE_LILEEP                 806
#define SPRITE_TSURE_POKE_CRADILY                807
#define SPRITE_TSURE_POKE_ANORITH                808
#define SPRITE_TSURE_POKE_ARMALDO                809
#define SPRITE_TSURE_POKE_FEEBAS                 810
#define SPRITE_TSURE_POKE_MILOTIC                811
#define SPRITE_TSURE_POKE_CASTFORM               812
#define SPRITE_TSURE_POKE_KECLEON                813
#define SPRITE_TSURE_POKE_SHUPPET                814
#define SPRITE_TSURE_POKE_BANETTE                815
#define SPRITE_TSURE_POKE_DUSKULL                816
#define SPRITE_TSURE_POKE_DUSCLOPS               817
#define SPRITE_TSURE_POKE_TROPIUS                818
#define SPRITE_TSURE_POKE_CHIMECHO               819
#define SPRITE_TSURE_POKE_ABSOL                  820
#define SPRITE_TSURE_POKE_WYNAUT                 821
#define SPRITE_TSURE_POKE_SNORUNT                822
#define SPRITE_TSURE_POKE_GLALIE                 823
#define SPRITE_TSURE_POKE_SPHEAL                 824
#define SPRITE_TSURE_POKE_SEALEO                 825
#define SPRITE_TSURE_POKE_WALREIN                826
#define SPRITE_TSURE_POKE_CLAMPERL               827
#define SPRITE_TSURE_POKE_HUNTAIL                828
#define SPRITE_TSURE_POKE_GOREBYSS               829
#define SPRITE_TSURE_POKE_RELICANTH              830
#define SPRITE_TSURE_POKE_LUVDISC                831
#define SPRITE_TSURE_POKE_BAGON                  832
#define SPRITE_TSURE_POKE_SHELGON                833
#define SPRITE_TSURE_POKE_SALAMENCE              834
#define SPRITE_TSURE_POKE_BELDUM                 835
#define SPRITE_TSURE_POKE_METANG                 836
#define SPRITE_TSURE_POKE_METAGROSS              837
#define SPRITE_TSURE_POKE_REGIROCK               838
#define SPRITE_TSURE_POKE_REGICE                 839
#define SPRITE_TSURE_POKE_REGISTEEL              840
#define SPRITE_TSURE_POKE_LATIAS                 841
#define SPRITE_TSURE_POKE_LATIOS                 842
#define SPRITE_TSURE_POKE_KYOGRE                 843
#define SPRITE_TSURE_POKE_GROUDON                844
#define SPRITE_TSURE_POKE_RAYQUAZA               845
#define SPRITE_TSURE_POKE_JIRACHI                846
#define SPRITE_TSURE_POKE_DEOXYS                 847
#define SPRITE_TSURE_POKE_DEOXYS_ATK             848
#define SPRITE_TSURE_POKE_DEOXYS_DEF             849
#define SPRITE_TSURE_POKE_DEOXYS_SPD             850
#define SPRITE_TSURE_POKE_TURTWIG                851
#define SPRITE_TSURE_POKE_GROTLE                 852
#define SPRITE_TSURE_POKE_TORTERRA               853
#define SPRITE_TSURE_POKE_CHIMCHAR               854
#define SPRITE_TSURE_POKE_MONFERNO               855
#define SPRITE_TSURE_POKE_INFERNAPE              856
#define SPRITE_TSURE_POKE_PIPLUP                 857
#define SPRITE_TSURE_POKE_PRINPLUP               858
#define SPRITE_TSURE_POKE_EMPOLEON               859
#define SPRITE_TSURE_POKE_STARLY                 860
#define SPRITE_TSURE_POKE_STARAVIA               861
#define SPRITE_TSURE_POKE_STARAPTOR              862
#define SPRITE_TSURE_POKE_BIDOOF                 863
#define SPRITE_TSURE_POKE_BIBAREL                864
#define SPRITE_TSURE_POKE_KRICKETOT              865
#define SPRITE_TSURE_POKE_KRICKETUNE             866
#define SPRITE_TSURE_POKE_SHINX                  867
#define SPRITE_TSURE_POKE_LUXIO                  868
#define SPRITE_TSURE_POKE_LUXRAY                 869
#define SPRITE_TSURE_POKE_BUDEW                  870
#define SPRITE_TSURE_POKE_ROSERADE               871
#define SPRITE_TSURE_POKE_CRANIDOS               872
#define SPRITE_TSURE_POKE_RAMPARDOS              873
#define SPRITE_TSURE_POKE_SHIELDON               874
#define SPRITE_TSURE_POKE_BASTIODON              875
#define SPRITE_TSURE_POKE_BURMY                  876
#define SPRITE_TSURE_POKE_BURMY_SANDY            877
#define SPRITE_TSURE_POKE_BURMY_TRASH            878
#define SPRITE_TSURE_POKE_WORMADAM               879
#define SPRITE_TSURE_POKE_WORMADAM_SANDY         880
#define SPRITE_TSURE_POKE_WORMADAM_TRASH         881
#define SPRITE_TSURE_POKE_MOTHIM                 882
#define SPRITE_TSURE_POKE_COMBEE                 883
#define SPRITE_TSURE_POKE_COMBEE_F               884
#define SPRITE_TSURE_POKE_VESPIQUEN              885
#define SPRITE_TSURE_POKE_PACHIRISU              886
#define SPRITE_TSURE_POKE_BUIZEL                 887
#define SPRITE_TSURE_POKE_FLOATZEL               888
#define SPRITE_TSURE_POKE_CHERUBI                889
#define SPRITE_TSURE_POKE_CHERRIM                890
#define SPRITE_TSURE_POKE_SHELLOS_WEST           891
#define SPRITE_TSURE_POKE_SHELLOS_EAST           892
#define SPRITE_TSURE_POKE_GASTRODON_WEST         893
#define SPRITE_TSURE_POKE_GASTRODON_EAST         894
#define SPRITE_TSURE_POKE_AMBIPOM                895
#define SPRITE_TSURE_POKE_DRIFLOON               896
#define SPRITE_TSURE_POKE_DRIFBLIM               897
#define SPRITE_TSURE_POKE_BUNEARY                898
#define SPRITE_TSURE_POKE_LOPUNNY                899
#define SPRITE_TSURE_POKE_MISMAGIUS              900
#define SPRITE_TSURE_POKE_HONCHKROW              901
#define SPRITE_TSURE_POKE_GLAMEOW                902
#define SPRITE_TSURE_POKE_PURUGLY                903
#define SPRITE_TSURE_POKE_CHINGLING              904
#define SPRITE_TSURE_POKE_STUNKY                 905
#define SPRITE_TSURE_POKE_SKUNTANK               906
#define SPRITE_TSURE_POKE_BRONZOR                907
#define SPRITE_TSURE_POKE_BRONZONG               908
#define SPRITE_TSURE_POKE_BONSLY                 909
#define SPRITE_TSURE_POKE_MIME_JR                910
#define SPRITE_TSURE_POKE_HAPPINY                911
#define SPRITE_TSURE_POKE_CHATOT                 912
#define SPRITE_TSURE_POKE_SPIRITOMB              913
#define SPRITE_TSURE_POKE_GIBLE                  914
#define SPRITE_TSURE_POKE_GIBLE_F                915
#define SPRITE_TSURE_POKE_GABITE                 916
#define SPRITE_TSURE_POKE_GABITE_F               917
#define SPRITE_TSURE_POKE_GARCHOMP               918
#define SPRITE_TSURE_POKE_GARCHOMP_F             919
#define SPRITE_TSURE_POKE_MUNCHLAX               920
#define SPRITE_TSURE_POKE_RIOLU                  921
#define SPRITE_TSURE_POKE_LUCARIO                922
#define SPRITE_TSURE_POKE_HIPPOPOTAS             923
#define SPRITE_TSURE_POKE_HIPPOPOTAS_F           924
#define SPRITE_TSURE_POKE_HIPPOWDON              925
#define SPRITE_TSURE_POKE_HIPPOWDON_F            926
#define SPRITE_TSURE_POKE_SKORUPI                927
#define SPRITE_TSURE_POKE_DRAPION                928
#define SPRITE_TSURE_POKE_CROAGUNK               929
#define SPRITE_TSURE_POKE_TOXICROAK              930
#define SPRITE_TSURE_POKE_CARNIVINE              931
#define SPRITE_TSURE_POKE_FINNEON                932
#define SPRITE_TSURE_POKE_LUMINEON               933
#define SPRITE_TSURE_POKE_MANTYKE                934
#define SPRITE_TSURE_POKE_SNOVER                 935
#define SPRITE_TSURE_POKE_ABOMASNOW              936
#define SPRITE_TSURE_POKE_WEAVILE                937
#define SPRITE_TSURE_POKE_MAGNEZONE              938
#define SPRITE_TSURE_POKE_LICKILICKY             939
#define SPRITE_TSURE_POKE_RHYPERIOR              940
#define SPRITE_TSURE_POKE_TANGROWTH              941
#define SPRITE_TSURE_POKE_ELECTIVIRE             942
#define SPRITE_TSURE_POKE_MAGMORTAR              943
#define SPRITE_TSURE_POKE_TOGEKISS               944
#define SPRITE_TSURE_POKE_YANMEGA                945
#define SPRITE_TSURE_POKE_LEAFEON                946
#define SPRITE_TSURE_POKE_GLACEON                947
#define SPRITE_TSURE_POKE_GLISCOR                948
#define SPRITE_TSURE_POKE_MAMOSWINE              949
#define SPRITE_TSURE_POKE_PORYGON_Z              950
#define SPRITE_TSURE_POKE_GALLADE                951
#define SPRITE_TSURE_POKE_PROBOPASS              952
#define SPRITE_TSURE_POKE_DUSKNOIR               953
#define SPRITE_TSURE_POKE_FROSLASS               954
#define SPRITE_TSURE_POKE_ROTOM                  955
#define SPRITE_TSURE_POKE_ROTOM_HEAT             956
#define SPRITE_TSURE_POKE_ROTOM_WASH             957
#define SPRITE_TSURE_POKE_ROTOM_FROST            958
#define SPRITE_TSURE_POKE_ROTOM_FAN              959
#define SPRITE_TSURE_POKE_ROTOM_MOW              960
#define SPRITE_TSURE_POKE_UXIE                   961
#define SPRITE_TSURE_POKE_MESPRIT                962
#define SPRITE_TSURE_POKE_AZELF                  963
#define SPRITE_TSURE_POKE_DIALGA                 964
#define SPRITE_TSURE_POKE_PALKIA                 965
#define SPRITE_TSURE_POKE_HEATRAN                966
#define SPRITE_TSURE_POKE_REGIGIGAS              967
#define SPRITE_TSURE_POKE_GIRATINA               968
#define SPRITE_TSURE_POKE_GIRATINA_ORIGIN        969
#define SPRITE_TSURE_POKE_CRESSELIA              970
#define SPRITE_TSURE_POKE_PHIONE                 971
#define SPRITE_TSURE_POKE_MANAPHY                972
#define SPRITE_TSURE_POKE_DARKRAI                973
#define SPRITE_TSURE_POKE_SHAYMIN                974
#define SPRITE_TSURE_POKE_SHAYMIN_SKY            975
#define SPRITE_TSURE_POKE_ARCEUS_NORMAL          976
#define SPRITE_TSURE_POKE_ARCEUS_FIGHTING        977
#define SPRITE_TSURE_POKE_ARCEUS_FLYING          978
#define SPRITE_TSURE_POKE_ARCEUS_POISON          979
#define SPRITE_TSURE_POKE_ARCEUS_GROUND          980
#define SPRITE_TSURE_POKE_ARCEUS_ROCK            981
#define SPRITE_TSURE_POKE_ARCEUS_BUG             982
#define SPRITE_TSURE_POKE_ARCEUS_GHOST           983
#define SPRITE_TSURE_POKE_ARCEUS_STEEL           984
#define SPRITE_TSURE_POKE_ARCEUS_MYSTERY         985
#define SPRITE_TSURE_POKE_ARCEUS_FIRE            986
#define SPRITE_TSURE_POKE_ARCEUS_WATER           987
#define SPRITE_TSURE_POKE_ARCEUS_GRASS           988
#define SPRITE_TSURE_POKE_ARCEUS_ELECTRIC        989
#define SPRITE_TSURE_POKE_ARCEUS_PSYCHIC         990
#define SPRITE_TSURE_POKE_ARCEUS_ICE             991
#define SPRITE_TSURE_POKE_ARCEUS_DRAGON          992
#define SPRITE_TSURE_POKE_ARCEUS_DARK            993
#define SPRITE_TSURE_POKE_STATIC_BUTTERFREE      994
#define SPRITE_TSURE_POKE_STATIC_PIDGEY          995
#define SPRITE_TSURE_POKE_STATIC_RATTATA         996
#define SPRITE_TSURE_POKE_STATIC_SPEAROW         997
#define SPRITE_TSURE_POKE_STATIC_FEAROW          998
#define SPRITE_TSURE_POKE_STATIC_PIKACHU         999
#define SPRITE_TSURE_POKE_STATIC_NIDORAN_F      1000
#define SPRITE_TSURE_POKE_STATIC_NIDORAN_M      1001
#define SPRITE_TSURE_POKE_STATIC_NIDORINO       1002
#define SPRITE_TSURE_POKE_STATIC_CLEFAIRY       1003
#define SPRITE_TSURE_POKE_STATIC_JIGGLYPUFF     1004
#define SPRITE_TSURE_POKE_STATIC_ZUBAT          1005
#define SPRITE_TSURE_POKE_STATIC_ODDISH         1006
#define SPRITE_TSURE_POKE_STATIC_DIGLETT        1007
#define SPRITE_TSURE_POKE_STATIC_MEOWTH         1008
#define SPRITE_TSURE_POKE_STATIC_PERSIAN        1009
#define SPRITE_TSURE_POKE_STATIC_PSYDUCK        1010
#define SPRITE_TSURE_POKE_STATIC_POLIWRATH      1011
#define SPRITE_TSURE_POKE_STATIC_ABRA           1012
#define SPRITE_TSURE_POKE_STATIC_MACHOP         1013
#define SPRITE_TSURE_POKE_STATIC_MACHOKE        1014
#define SPRITE_TSURE_POKE_STATIC_SLOWPOKE       1015
#define SPRITE_TSURE_POKE_STATIC_SLOWBRO        1016
#define SPRITE_TSURE_POKE_STATIC_FARFETCHD      1017
#define SPRITE_TSURE_POKE_STATIC_DODRIO         1018
#define SPRITE_TSURE_POKE_STATIC_ELECTRODE      1019
#define SPRITE_TSURE_POKE_STATIC_RHYDON         1020
#define SPRITE_TSURE_POKE_STATIC_CHANSEY        1021
#define SPRITE_TSURE_POKE_STATIC_KANGASKHAN     1022
#define SPRITE_TSURE_POKE_STATIC_LAPRAS         1023
#define SPRITE_TSURE_POKE_STATIC_ARTICUNO       1024
#define SPRITE_TSURE_POKE_STATIC_ZAPDOS         1025
#define SPRITE_TSURE_POKE_STATIC_MOLTRES        1026
#define SPRITE_TSURE_POKE_STATIC_DRATINI        1027
#define SPRITE_TSURE_POKE_STATIC_DRAGONITE      1028
#define SPRITE_TSURE_POKE_STATIC_MEWTWO         1029
#define SPRITE_TSURE_POKE_STATIC_BAYLEEF        1030
#define SPRITE_TSURE_POKE_STATIC_AMPHAROS       1031
#define SPRITE_TSURE_POKE_STATIC_MARILL         1032
#define SPRITE_TSURE_POKE_STATIC_AIPOM          1033
#define SPRITE_TSURE_POKE_STATIC_MURKROW        1034
#define SPRITE_TSURE_POKE_STATIC_MILTANK        1035
#define SPRITE_TSURE_POKE_STATIC_BLISSEY        1036
#define SPRITE_TSURE_POKE_STATIC_RAIKOU         1037
#define SPRITE_TSURE_POKE_STATIC_ENTEI          1038
#define SPRITE_TSURE_POKE_STATIC_SUICUNE        1039
#define SPRITE_TSURE_POKE_STATIC_CELEBI         1040
#define SPRITE_TSURE_POKE_STATIC_LATIAS         1041
#define SPRITE_TSURE_POKE_STATIC_LATIOS         1042
#define SPRITE_TSURE_POKE_STATIC_KYOGRE         1043
#define SPRITE_TSURE_POKE_STATIC_GROUDON        1044
#define SPRITE_TSURE_POKE_STATIC_RAYQUAZA       1045
#define SPRITE_TSURE_POKE_STATIC_PICHU_SPIKY    1046
#define SPRITE_TSURE_POKE_STATIC_MEGANIUM       1047
#define SPRITE_TSURE_POKE_STATIC_TYPHLOSION     1048
#define SPRITE_TSURE_POKE_STATIC_FERALIGATR     1049
#define SPRITE_CAMERA_FOCUS                     8192

#define SPRITE_VAR_0                              100
#define SPRITE_VAR_1                              101
#define SPRITE_VAR_2                              102
#define SPRITE_VAR_3                              103
#define SPRITE_VAR_4                              104
#define SPRITE_VAR_5                              105
#define SPRITE_VAR_6                              106
#define SPRITE_VAR_7                              107
#define SPRITE_VAR_8                              108
#define SPRITE_VAR_9                              109
#define SPRITE_VAR_10                             110
#define SPRITE_VAR_11                             111
#define SPRITE_VAR_12                             112
#define SPRITE_VAR_13                             113
#define SPRITE_VAR_14                             114
#define SPRITE_VAR_15                             115

#endif //POKEHEARTGOLD_CONSTANTS_SPRITES_H
