#ifndef POKEHEARTGOLD_CONSTANTS_START_MENU_ICONS_H
#define POKEHEARTGOLD_CONSTANTS_START_MENU_ICONS_H

#define START_MENU_ICON_UNLOCK_BAG            0
#define START_MENU_ICON_UNLOCK_TRAINER_CARD   1
#define START_MENU_ICON_UNLOCK_SAVE_BUTTON    2
#define START_MENU_ICON_UNLOCK_OPTIONS_BUTTON 3

#endif // POKEHEARTGOLD_CONSTANTS_START_MENU_ICONS_H
