#ifndef GUARD_POKEHEARTGOLD_CONSTANTS_TIME_H
#define GUARD_POKEHEARTGOLD_CONSTANTS_TIME_H

#ifdef PM_ASM

#define RTC_WEEK_SUNDAY    0
#define RTC_WEEK_MONDAY    1
#define RTC_WEEK_TUESDAY   2
#define RTC_WEEK_WEDNESDAY 3
#define RTC_WEEK_THURSDAY  4
#define RTC_WEEK_FRIDAY    5
#define RTC_WEEK_SATURDAY  6

#define RTC_TIMEOFDAY_MORN 0
#define RTC_TIMEOFDAY_DAY  1
#define RTC_TIMEOFDAY_EVE  2
#define RTC_TIMEOFDAY_NITE 3
#define RTC_TIMEOFDAY_LATE 4

#endif // PM_ASM

#endif // GUARD_POKEHEARTGOLD_CONSTANTS_TIME_H
