#ifndef POKEHEARTGOLD_CONSTANTS_TRAINERS_H
#define POKEHEARTGOLD_CONSTANTS_TRAINERS_H

#define TRAINER_NONE                        0
#define FIRST_TRAINER_INDEX                 1
#define TRAINER_RIVAL_SILVER                1
#define TRAINER_RIVAL_SILVER_2              2
#define TRAINER_RIVAL_SILVER_3              3
#define TRAINER_BUG_CATCHER_WADE            4
#define TRAINER_BEAUTY_VICTORIA             5
#define TRAINER_POLICEMAN_KEITH             6
#define TRAINER_JUGGLER_IRWIN               7
#define TRAINER_YOUNGSTER_JOEY              8
#define TRAINER_SWIMMER_F_ELAINE            9
#define TRAINER_TWINS_AMY_AND_MIMI          10
#define TRAINER_KIMONO_GIRL_MICKEY          11
#define TRAINER_TEAM_ROCKET_GRUNT           12
#define TRAINER_TEAM_ROCKET_F_GRUNT         13
#define TRAINER_BURGLAR_DUNCAN              14
#define TRAINER_FIREBREATHER_OTIS           15
#define TRAINER_SWIMMER_M_SIMON             16
#define TRAINER_BLACK_BELT_KENJI            17
#define TRAINER_FISHERMAN_JUSTIN            18
#define TRAINER_BIKER_MICKEY                19
#define TRAINER_LEADER_FALKNER_FALKNER      20
#define TRAINER_LEADER_BUGSY_BUGSY          21
#define TRAINER_LASS_CARRIE                 22
#define TRAINER_POKE_MANIAC_LARRY           23
#define TRAINER_SCHOOL_KID_M_ALAN           24
#define TRAINER_HIKER_RUSSEL                25
#define TRAINER_CAMPER_ROLAND               26
#define TRAINER_PICNICKER_LIZ               27
#define TRAINER_ACE_TRAINER_M_JAKE          28
#define TRAINER_BIRD_KEEPER_GS_ROD          29
#define TRAINER_LEADER_WHITNEY              30
#define TRAINER_LEADER_MORTY_MORTY          31
#define TRAINER_LEADER_PRYCE_PRYCE          32
#define TRAINER_LEADER_JASMINE_JASMINE      33
#define TRAINER_LEADER_CHUCK_CHUCK          34
#define TRAINER_LEADER_CLAIR_CLAIR          35
#define TRAINER_ACE_TRAINER_F_JOYCE         36
#define TRAINER_GENTLEMAN_PRESTON           37
#define TRAINER_TEACHER_COLETTE             38
#define TRAINER_SAILOR_EUGENE               39
#define TRAINER_SUPER_NERD_MICKEY           40
#define TRAINER_GUITARIST_CLYDE             41
#define TRAINER_PSYCHIC_M_NATHAN            42
#define TRAINER_SAGE_CHOW                   43
#define TRAINER_POKEFAN_M_DEREK             44
#define TRAINER_POKEFAN_RUTH                45
#define TRAINER_MEDIUM_MARTHA               46
#define TRAINER_YOUNGSTER_MIKEY             47
#define TRAINER_BUG_CATCHER_ROB             48
#define TRAINER_YOUNGSTER_ALBERT            49
#define TRAINER_BIRD_KEEPER_GS_ABE          50
#define TRAINER_SAGE_NICO                   51
#define TRAINER_SAGE_EDMOND                 52
#define TRAINER_SAGE_JIN                    53
#define TRAINER_SAGE_TROY                   54
#define TRAINER_SAGE_NEAL                   55
#define TRAINER_YOUNGSTER_GORDON            56
#define TRAINER_FISHERMAN_RALPH             57
#define TRAINER_FISHERMAN_ARNOLD            58
#define TRAINER_FISHERMAN_KYLE              59
#define TRAINER_FISHERMAN_HENRY             60
#define TRAINER_HIKER_ANTHONY               61
#define TRAINER_YOUNGSTER_SAMUEL            62
#define TRAINER_TEAM_ROCKET_MICKEY          63
#define TRAINER_YOUNGSTER_IAN               64
#define TRAINER_PICNICKER_GINA              65
#define TRAINER_CAMPER_TODD                 66
#define TRAINER_BUG_CATCHER_BENNY           67
#define TRAINER_BUG_CATCHER_AL              68
#define TRAINER_BUG_CATCHER_JOSH            69
#define TRAINER_BEAUTY_SAMANTHA             70
#define TRAINER_LASS_CATHY                  71
#define TRAINER_BIRD_KEEPER_GS_BRYAN        72
#define TRAINER_BIRD_KEEPER_GS_THEO         73
#define TRAINER_CAMPER_IVAN                 74
#define TRAINER_CAMPER_ELLIOT               75
#define TRAINER_PICNICKER_BROOKE            76
#define TRAINER_PICNICKER_KIM               77
#define TRAINER_BUG_CATCHER_ARNIE           78
#define TRAINER_BUG_CATCHER_KEN             79
#define TRAINER_POLICEMAN_DIRK              80
#define TRAINER_TWINS_TORI_AND_TIL          81
#define TRAINER_BIRD_KEEPER_GS_TOBY         82
#define TRAINER_PICNICKER_CINDY             83
#define TRAINER_CAMPER_BARRY                84
#define TRAINER_SWIMMER_F_PAULA             85
#define TRAINER_SWIMMER_M_RANDALL           86
#define TRAINER_SAGE_MICKEY                 87
#define TRAINER_SAGE_MICKEY_2               88
#define TRAINER_MEDIUM_GRACE                89
#define TRAINER_SWIMMER_F_KAYLEE            90
#define TRAINER_SWIMMER_F_SUSIE             91
#define TRAINER_SWIMMER_F_DENISE            92
#define TRAINER_SWIMMER_F_KARA              93
#define TRAINER_SWIMMER_F_WENDY             94
#define TRAINER_SWIMMER_M_CHARLIE           95
#define TRAINER_SWIMMER_M_GEORGE            96
#define TRAINER_SWIMMER_M_BERKE             97
#define TRAINER_SWIMMER_M_RONALD            98
#define TRAINER_SWIMMER_M_MATTHEW           99
#define TRAINER_HIKER_ANTHONY_2             100
#define TRAINER_TEAM_ROCKET_GRUNT_2         101
#define TRAINER_ACE_TRAINER_M_GAVEN         102
#define TRAINER_ACE_TRAINER_M_BLAKE         103
#define TRAINER_ACE_TRAINER_M_BRIAN         104
#define TRAINER_ACE_TRAINER_M_MICKEY        105
#define TRAINER_ACE_TRAINER_M_MICKEY_2      106
#define TRAINER_ACE_TRAINER_M_MICKEY_3      107
#define TRAINER_ACE_TRAINER_M_RYAN          108
#define TRAINER_ACE_TRAINER_M_ALTON         109
#define TRAINER_ACE_TRAINER_M_PAULO         110
#define TRAINER_ACE_TRAINER_M_MIKE          111
#define TRAINER_ACE_TRAINER_M_CODY          112
#define TRAINER_ACE_TRAINER_F_JAMIE         113
#define TRAINER_ACE_TRAINER_F_REENA         114
#define TRAINER_ACE_TRAINER_F_MEGAN         115
#define TRAINER_ACE_TRAINER_F_LOIS          116
#define TRAINER_ACE_TRAINER_F_LOLA          117
#define TRAINER_ACE_TRAINER_F_KATE          118
#define TRAINER_ACE_TRAINER_F_FRAN          119
#define TRAINER_ACE_TRAINER_F_IRENE         120
#define TRAINER_ACE_TRAINER_F_KELLY         121
#define TRAINER_FISHERMAN_MARVIN            122
#define TRAINER_FISHERMAN_TULLY             123
#define TRAINER_FISHERMAN_WILTON            124
#define TRAINER_FISHERMAN_EDGAR             125
#define TRAINER_FISHERMAN_ANDRE             126
#define TRAINER_FISHERMAN_RAYMOND           127
#define TRAINER_FISHERMAN_JONAH             128
#define TRAINER_POKE_MANIAC_SHANE           129
#define TRAINER_POKE_MANIAC_BECKETT         130
#define TRAINER_POKE_MANIAC_BRENT           131
#define TRAINER_POKE_MANIAC_RON             132
#define TRAINER_POKE_MANIAC_MORGAN          133
#define TRAINER_HIKER_BENJAMIN              134
#define TRAINER_SCHOOL_KID_M_JOHNNY         135
#define TRAINER_LASS_LINDA                  136
#define TRAINER_BIRD_KEEPER_GS_VANCE        137
#define TRAINER_CAMPER_MICKEY               138
#define TRAINER_PICNICKER_DEBRA             139
#define TRAINER_BUG_CATCHER_DOUG            140
#define TRAINER_CAMPER_MICKEY_2             141
#define TRAINER_PICNICKER_GINA_2            142
#define TRAINER_HIKER_ERIK                  143
#define TRAINER_HIKER_MICHAEL               144
#define TRAINER_HIKER_PARRY                 145
#define TRAINER_HIKER_TIMOTHY               146
#define TRAINER_CAMPER_TED                  147
#define TRAINER_CAMPER_LLOYD                148
#define TRAINER_CAMPER_DEAN                 149
#define TRAINER_CAMPER_SID                  150
#define TRAINER_PICNICKER_ERIN              151
#define TRAINER_PICNICKER_HOPE              152
#define TRAINER_PICNICKER_SHARON            153
#define TRAINER_HIKER_BAILEY                154
#define TRAINER_HIKER_ANTHONY_3             155
#define TRAINER_BLACK_BELT_YOSHI            156
#define TRAINER_BLACK_BELT_LAO              157
#define TRAINER_BLACK_BELT_KIYO             158
#define TRAINER_BLACK_BELT_LUNG             159
#define TRAINER_KIMONO_GIRL_NAOKO           160
#define TRAINER_KIMONO_GIRL_SAYO            161
#define TRAINER_KIMONO_GIRL_ZUKI            162
#define TRAINER_KIMONO_GIRL_KUNI            163
#define TRAINER_KIMONO_GIRL_MIKI            164
#define TRAINER_SWIMMER_F_MICKEY            165
#define TRAINER_SWIMMER_F_MICKEY_2          166
#define TRAINER_SWIMMER_F_MICKEY_3          167
#define TRAINER_SWIMMER_M_MICKEY            168
#define TRAINER_SWIMMER_M_MICKEY_2          169
#define TRAINER_SWIMMER_M_MICKEY_3          170
#define TRAINER_SWIMMER_M_MICKEY_4          171
#define TRAINER_POKE_MANIAC_BRENT_2         172
#define TRAINER_POKE_MANIAC_BRENT_3         173
#define TRAINER_BIKER_MICKEY_2              174
#define TRAINER_MEDIUM_BETHANY              175
#define TRAINER_MEDIUM_MARGARET             176
#define TRAINER_MEDIUM_ETHEL                177
#define TRAINER_SCHOOL_KID_M_JACK           178
#define TRAINER_SCHOOL_KID_M_KIPP           179
#define TRAINER_BEAUTY_MICKEY               180
#define TRAINER_POKEFAN_M_WILLIAM           181
#define TRAINER_POKEFAN_BEVERLY             182
#define TRAINER_LASS_ALICE                  183
#define TRAINER_LASS_KRISE                  184
#define TRAINER_TEAM_ROCKET_GRUNT_3         185
#define TRAINER_TEAM_ROCKET_GRUNT_4         186
#define TRAINER_TEAM_ROCKET_GRUNT_5         187
#define TRAINER_TEAM_ROCKET_GRUNT_6         188
#define TRAINER_TEAM_ROCKET_GRUNT_7         189
#define TRAINER_TEAM_ROCKET_GRUNT_8         190
#define TRAINER_TEAM_ROCKET_GRUNT_9         191
#define TRAINER_TEAM_ROCKET_GRUNT_10        192
#define TRAINER_TEAM_ROCKET_GRUNT_11        193
#define TRAINER_TEAM_ROCKET_MICKEY_2        194
#define TRAINER_TEAM_ROCKET_GRUNT_12        195
#define TRAINER_TEAM_ROCKET_GRUNT_13        196
#define TRAINER_TEAM_ROCKET_GRUNT_14        197
#define TRAINER_TEAM_ROCKET_F_GRUNT_2       198
#define TRAINER_TEAM_ROCKET_F_GRUNT_3       199
#define TRAINER_TEAM_ROCKET_F_GRUNT_4       200
#define TRAINER_POKE_MANIAC_ANDREW          201
#define TRAINER_POKE_MANIAC_CALVIN          202
#define TRAINER_HIKER_PHILLIP               203
#define TRAINER_HIKER_LEONARD               204
#define TRAINER_ACE_TRAINER_M_NICK          205
#define TRAINER_ACE_TRAINER_F_GWEN          206
#define TRAINER_BEAUTY_MICKEY_2             207
#define TRAINER_BEAUTY_MICKEY_3             208
#define TRAINER_BEAUTY_CASSIE               209
#define TRAINER_BEAUTY_CAROLINE             210
#define TRAINER_SAILOR_HUEY                 211
#define TRAINER_SAILOR_TERRELL              212
#define TRAINER_SAILOR_KENT                 213
#define TRAINER_SAILOR_ROBERTO              214
#define TRAINER_LASS_CONNIE                 215
#define TRAINER_TEAM_ROCKET_GRUNT_15        216
#define TRAINER_BIRD_KEEPER_GS_DENIS        217
#define TRAINER_TEAM_ROCKET_GRUNT_16        218
#define TRAINER_TEAM_ROCKET_GRUNT_17        219
#define TRAINER_TEAM_ROCKET_GRUNT_18        220
#define TRAINER_TEAM_ROCKET_MICKEY_3        221
#define TRAINER_TEAM_ROCKET_GRUNT_19        222
#define TRAINER_TEAM_ROCKET_GRUNT_20        223
#define TRAINER_TEAM_ROCKET_GRUNT_21        224
#define TRAINER_TEAM_ROCKET_MICKEY_4        225
#define TRAINER_TEAM_ROCKET_MICKEY_5        226
#define TRAINER_TEAM_ROCKET_GRUNT_22        227
#define TRAINER_TEAM_ROCKET_GRUNT_23        228
#define TRAINER_TEAM_ROCKET_MICKEY_6        229
#define TRAINER_PSYCHIC_M_FRANKLIN          230
#define TRAINER_GENTLEMAN_EDWARD            231
#define TRAINER_GUITARIST_VINCENT           232
#define TRAINER_SUPER_NERD_ERIC             233
#define TRAINER_HIKER_EOIN                  234
#define TRAINER_HIKER_NOLAND                235
#define TRAINER_ACE_TRAINER_M_SHAYE         236
#define TRAINER_ACE_TRAINER_F_CAROL         237
#define TRAINER_SAILOR_STANLY               238
#define TRAINER_SAILOR_JEFF                 239
#define TRAINER_SAILOR_GARRETT              240
#define TRAINER_SAILOR_KENNETH              241
#define TRAINER_JUGGLER_FRITZ               242
#define TRAINER_SWIMMER_F_KATIE             243
#define TRAINER_CHAMPION_LANCE              244
#define TRAINER_ELITE_FOUR_WILL_WILL        245
#define TRAINER_ELITE_FOUR_KAREN_KAREN      246
#define TRAINER_ELITE_FOUR_KOGA_KOGA        247
#define TRAINER_BUG_CATCHER_ED              248
#define TRAINER_BUG_CATCHER_DON             249
#define TRAINER_BLACK_BELT_KENJI_2          250
#define TRAINER_BLACK_BELT_NOB              251
#define TRAINER_SWIMMER_M_HAROLD            252
#define TRAINER_LEADER_BROCK_BROCK          253
#define TRAINER_LEADER_MISTY_MISTY          254
#define TRAINER_LEADER_LT_SURGE_LT__SURGE   255
#define TRAINER_LEADER_ERIKA_ERIKA          256
#define TRAINER_LEADER_JANINE_JANINE        257
#define TRAINER_LEADER_SABRINA_SABRINA      258
#define TRAINER_LEADER_BLAINE_BLAINE        259
#define TRAINER_PKMN_TRAINER_RED_RED        260
#define TRAINER_LEADER_BLUE_BLUE            261
#define TRAINER_TEAM_ROCKET_MICKEY_7        262
#define TRAINER_RIVAL_SILVER_4              263
#define TRAINER_RIVAL_SILVER_5              264
#define TRAINER_RIVAL_SILVER_6              265
#define TRAINER_RIVAL_SILVER_7              266
#define TRAINER_RIVAL_SILVER_8              267
#define TRAINER_RIVAL_SILVER_9              268
#define TRAINER_RIVAL_SILVER_10             269
#define TRAINER_RIVAL_SILVER_11             270
#define TRAINER_RIVAL_SILVER_12             271
#define TRAINER_RIVAL_SILVER_13             272
#define TRAINER_SWIMMER_M_MICKEY_5          273
#define TRAINER_CAMPER_TODD_2               274
#define TRAINER_CAMPER_TODD_3               275
#define TRAINER_PICNICKER_LIZ_2             276
#define TRAINER_PICNICKER_LIZ_3             277
#define TRAINER_BLACK_BELT_KENJI_3          278
#define TRAINER_YOUNGSTER_JOEY_2            279
#define TRAINER_YOUNGSTER_JOEY_3            280
#define TRAINER_FIREBREATHER_RICHARD        281
#define TRAINER_FIREBREATHER_NED            282
#define TRAINER_BURGLAR_ORSON               283
#define TRAINER_BURGLAR_COREY               284
#define TRAINER_RIVAL_SILVER_14             285
#define TRAINER_RIVAL_SILVER_15             286
#define TRAINER_RIVAL_SILVER_16             287
#define TRAINER_RIVAL_SILVER_17             288
#define TRAINER_RIVAL_SILVER_18             289
#define TRAINER_ELDER_LI                    290
#define TRAINER_SWIMMER_F_DEBBIE            291
#define TRAINER_SWIMMER_F_MICKEY_4          292
#define TRAINER_SWIMMER_F_NICOLE            293
#define TRAINER_SWIMMER_F_LORI              294
#define TRAINER_SWIMMER_F_MICKEY_5          295
#define TRAINER_SWIMMER_F_NIKKI             296
#define TRAINER_SWIMMER_F_DIANA             297
#define TRAINER_SWIMMER_F_BRIANA            298
#define TRAINER_BIRD_KEEPER_GS_HANK         299
#define TRAINER_BIRD_KEEPER_GS_ROY          300
#define TRAINER_BIRD_KEEPER_GS_BORIS        301
#define TRAINER_BIRD_KEEPER_GS_BOB          302
#define TRAINER_BIRD_KEEPER_GS_JOSE         303
#define TRAINER_CAMPER_MICKEY_3             304
#define TRAINER_CAMPER_MICKEY_4             305
#define TRAINER_CAMPER_MICKEY_5             306
#define TRAINER_CAMPER_MICKEY_6             307
#define TRAINER_CAMPER_JERRY                308
#define TRAINER_BIKER_DWAYNE                309
#define TRAINER_BIKER_HARRIS                310
#define TRAINER_BIKER_ZEKE                  311
#define TRAINER_BIKER_CHARLES               312
#define TRAINER_BIKER_REESE                 313
#define TRAINER_BIKER_JOEL                  314
#define TRAINER_BIKER_GLENN                 315
#define TRAINER_PSYCHIC_M_HERMAN            316
#define TRAINER_PSYCHIC_M_FIDEL             317
#define TRAINER_FIREBREATHER_BURT           318
#define TRAINER_FIREBREATHER_BILL           319
#define TRAINER_FISHERMAN_MARTIN            320
#define TRAINER_FISHERMAN_STEPHEN           321
#define TRAINER_FISHERMAN_BARNEY            322
#define TRAINER_FISHERMAN_TULLY_2           323
#define TRAINER_FISHERMAN_TULLY_3           324
#define TRAINER_FISHERMAN_WILTON_2          325
#define TRAINER_TWINS_JO_AND_ZOE            326
#define TRAINER_SCHOOL_KID_M_DANNY          327
#define TRAINER_SCHOOL_KID_M_TOMMY          328
#define TRAINER_SCHOOL_KID_M_DUDLEY         329
#define TRAINER_SCHOOL_KID_M_JOE            330
#define TRAINER_SCHOOL_KID_M_BILLY          331
#define TRAINER_PICNICKER_HEIDI             332
#define TRAINER_PICNICKER_EDNA              333
#define TRAINER_PICNICKER_GINA_3            334
#define TRAINER_PICNICKER_ERIN_2            335
#define TRAINER_PICNICKER_TANYA             336
#define TRAINER_GENTLEMAN_GREGORY           337
#define TRAINER_GENTLEMAN_MICKEY            338
#define TRAINER_BLACK_BELT_WAI              339
#define TRAINER_BEAUTY_MICKEY_4             340
#define TRAINER_BEAUTY_MICKEY_5             341
#define TRAINER_BEAUTY_MICKEY_6             342
#define TRAINER_BEAUTY_MICKEY_7             343
#define TRAINER_BEAUTY_MICKEY_8             344
#define TRAINER_BEAUTY_MICKEY_9             345
#define TRAINER_BEAUTY_JULIA                346
#define TRAINER_BEAUTY_MICKEY_10            347
#define TRAINER_POKEFAN_M_ROBERT            348
#define TRAINER_POKEFAN_M_JOSHUA            349
#define TRAINER_POKEFAN_M_CARTER            350
#define TRAINER_POKEFAN_M_TREVOR            351
#define TRAINER_POKEFAN_GEORGIA             352
#define TRAINER_TEAM_ROCKET_GRUNT_24        353
#define TRAINER_LASS_LAURA                  354
#define TRAINER_LASS_SHANNON                355
#define TRAINER_LASS_MICHELLE               356
#define TRAINER_HIKER_CLARKE                357
#define TRAINER_HIKER_KENNY                 358
#define TRAINER_HIKER_JIM                   359
#define TRAINER_BUG_CATCHER_ARNIE_2         360
#define TRAINER_ACE_TRAINER_M_KEVIN         361
#define TRAINER_ACE_TRAINER_F_QUINN         362
#define TRAINER_ACE_TRAINER_F_EMMA          363
#define TRAINER_SUPER_NERD_SAM              364
#define TRAINER_SUPER_NERD_TYRONE           365
#define TRAINER_SUPER_NERD_PAT              366
#define TRAINER_SUPER_NERD_SHAWN            367
#define TRAINER_MEDIUM_REBECCA              368
#define TRAINER_MEDIUM_DARCY                369
#define TRAINER_SWIMMER_M_JEROME            370
#define TRAINER_SWIMMER_M_TUCKER            371
#define TRAINER_SWIMMER_M_MICKEY_6          372
#define TRAINER_SWIMMER_M_FRANKIE           373
#define TRAINER_SWIMMER_M_TYSON             374
#define TRAINER_SWIMMER_M_MICKEY_7          375
#define TRAINER_SWIMMER_M_MICKEY_8          376
#define TRAINER_SWIMMER_M_PARKER            377
#define TRAINER_YOUNGSTER_WARREN            378
#define TRAINER_YOUNGSTER_JIMMY             379
#define TRAINER_YOUNGSTER_OWEN              380
#define TRAINER_YOUNGSTER_JASON             381
#define TRAINER_TEACHER_HILLARY             382
#define TRAINER_BIRD_KEEPER_GS_PETER        383
#define TRAINER_HIKER_DANIEL                384
#define TRAINER_TWINS_DARA_AND_DIA          385
#define TRAINER_PSYCHIC_M_GREG              386
#define TRAINER_TWINS_AMY_AND_MIMI_2        387
#define TRAINER_FIREBREATHER_WALT           388
#define TRAINER_PSYCHIC_M_NELSON            389
#define TRAINER_FIREBREATHER_RAY            390
#define TRAINER_POKE_MANIAC_ISSAC           391
#define TRAINER_POKE_MANIAC_DONALD          392
#define TRAINER_SUPER_NERD_TERU             393
#define TRAINER_ACE_TRAINER_M_MICKEY_4      394
#define TRAINER_PSYCHIC_M_MARK              395
#define TRAINER_JUGGLER_HORTON              396
#define TRAINER_SCHOOL_KID_M_CHAD           397
#define TRAINER_BEAUTY_VALERIE              398
#define TRAINER_FIREBREATHER_LYLE           399
#define TRAINER_LASS_DANA                   400
#define TRAINER_GENTLEMAN_ALFRED            401
#define TRAINER_PICNICKER_TIFFANY           402
#define TRAINER_CAMPER_SPENCER              403
#define TRAINER_TEAM_ROCKET_F_GRUNT_5       404
#define TRAINER_PSYCHIC_M_PHIL              405
#define TRAINER_POKE_MANIAC_ZACH            406
#define TRAINER_ACE_TRAINER_M_ALLEN         407
#define TRAINER_ACE_TRAINER_F_CYBIL         408
#define TRAINER_POKEFAN_M_BRANDON           409
#define TRAINER_SAILOR_HARRY                410
#define TRAINER_PSYCHIC_M_VERNON            411
#define TRAINER_PSYCHIC_M_ELI               412
#define TRAINER_FISHERMAN_SCOTT             413
#define TRAINER_BIRD_KEEPER_GS_JOSE_2       414
#define TRAINER_PSYCHIC_M_JARED             415
#define TRAINER_TWINS_JO_AND_ZOE_2          416
#define TRAINER_ACE_TRAINER_F_JENN          417
#define TRAINER_ELITE_FOUR_BRUNO_BRUNO      418
#define TRAINER_LASS_ELLEN                  419
#define TRAINER_BIRD_KEEPER_GS_PERRY        420
#define TRAINER_BIRD_KEEPER_GS_BRET         421
#define TRAINER_PSYCHIC_M_RODNEY            422
#define TRAINER_POKEFAN_M_JEREMY            423
#define TRAINER_POKEFAN_M_COLIN             424
#define TRAINER_TWINS_MEG_AND_PEG           425
#define TRAINER_TWINS_MEG_AND_PEG_2         426
#define TRAINER_TEACHER_SHIRLEY             427
#define TRAINER_SCHOOL_KID_M_NATE           428
#define TRAINER_SCHOOL_KID_M_RICKY          429
#define TRAINER_SCHOOL_KID_M_JACK_2         430
#define TRAINER_SCHOOL_KID_M_JACK_3         431
#define TRAINER_SCHOOL_KID_M_ALAN_2         432
#define TRAINER_SCHOOL_KID_M_ALAN_3         433
#define TRAINER_SCHOOL_KID_M_CHAD_2         434
#define TRAINER_SCHOOL_KID_M_CHAD_3         435
#define TRAINER_POKEFAN_BEVERLY_2           436
#define TRAINER_POKEFAN_BEVERLY_3           437
#define TRAINER_POKEFAN_M_DEREK_2           438
#define TRAINER_POKEFAN_M_DEREK_3           439
#define TRAINER_SAILOR_HUEY_2               440
#define TRAINER_SAILOR_HUEY_3               441
#define TRAINER_LASS_MICKEY                 442
#define TRAINER_LASS_MICKEY_2               443
#define TRAINER_ACE_TRAINER_F_REENA_2       444
#define TRAINER_ACE_TRAINER_F_REENA_3       445
#define TRAINER_BIRD_KEEPER_GS_JOSE_3       446
#define TRAINER_BIRD_KEEPER_GS_VANCE_2      447
#define TRAINER_BIRD_KEEPER_GS_VANCE_3      448
#define TRAINER_BUG_CATCHER_ARNIE_3         449
#define TRAINER_FISHERMAN_WILTON_3          450
#define TRAINER_HIKER_PARRY_2               451
#define TRAINER_HIKER_PARRY_3               452
#define TRAINER_PICNICKER_ERIN_3            453
#define TRAINER_JUGGLER_IRWIN_2             454
#define TRAINER_JUGGLER_IRWIN_3             455
#define TRAINER_ACE_TRAINER_M_GAVEN_2       456
#define TRAINER_ACE_TRAINER_M_GAVEN_3       457
#define TRAINER_ACE_TRAINER_F_JAMIE_2       458
#define TRAINER_ACE_TRAINER_F_JAMIE_3       459
#define TRAINER_BUG_CATCHER_WADE_2          460
#define TRAINER_BUG_CATCHER_WADE_3          461
#define TRAINER_FISHERMAN_RALPH_2           462
#define TRAINER_FISHERMAN_RALPH_3           463
#define TRAINER_LASS_DANA_2                 464
#define TRAINER_LASS_DANA_3                 465
#define TRAINER_PICNICKER_TIFFANY_2         466
#define TRAINER_PICNICKER_TIFFANY_3         467
#define TRAINER_SCIENTIST_GS_ROSS           468
#define TRAINER_SCIENTIST_GS_MITCH          469
#define TRAINER_SCIENTIST_GS_GREGG          470
#define TRAINER_SCIENTIST_GS_GARETT         471
#define TRAINER_SCIENTIST_GS_TRENTON        472
#define TRAINER_SUPER_NERD_MICKEY_2         473
#define TRAINER_SUPER_NERD_MICKEY_3         474
#define TRAINER_SUPER_NERD_MICKEY_4         475
#define TRAINER_SUPER_NERD_MICKEY_5         476
#define TRAINER_SUPER_NERD_MICKEY_6         477
#define TRAINER_EXECUTIVE_ARIANA_ARIANA     478
#define TRAINER_EXECUTIVE_ARIANA_ARIANA_2   479
#define TRAINER_SKIER_DIANA                 480
#define TRAINER_SKIER_JILL                  481
#define TRAINER_BOARDER_DEANDRE             482
#define TRAINER_BOARDER_PATTON              483
#define TRAINER_BOARDER_GERARDO             484
#define TRAINER_EXECUTIVE_ARCHER_ARCHER     485
#define TRAINER_EXECUTIVE_PROTON_PROTON     486
#define TRAINER_EXECUTIVE_PETREL_PETREL     487
#define TRAINER_EXECUTIVE_PETREL_PETREL_2   488
#define TRAINER_RIVAL_SILVER_19             489
#define TRAINER_RIVAL_SILVER_20             490
#define TRAINER_RIVAL_SILVER_21             491
#define TRAINER_POKEFAN_M_ALEX              492
#define TRAINER_MEDIUM_EDITH                493
#define TRAINER_MEDIUM_GEORGINA             494
#define TRAINER_PASSERBY_BOY                495
#define TRAINER_PASSERBY_BOY_2              496
#define TRAINER_PASSERBY_BOY_3              497
#define TRAINER_MYSTERY_MAN_EUSINE          498
#define TRAINER_TEAM_ROCKET_GRUNT_25        499
#define TRAINER_ACE_TRAINER_M_KOBE          500
#define TRAINER_ACE_TRAINER_F_PIPER         501
#define TRAINER_TWINS_CLEA_AND_GIL          502
#define TRAINER_SCHOOL_KID_M_JACK_4         503
#define TRAINER_SCHOOL_KID_M_MICKEY         504
#define TRAINER_SCHOOL_KID_M_ALAN_4         505
#define TRAINER_SCHOOL_KID_M_MICKEY_2       506
#define TRAINER_SCHOOL_KID_M_CHAD_4         507
#define TRAINER_SCHOOL_KID_M_MICKEY_3       508
#define TRAINER_SAILOR_HUEY_4               509
#define TRAINER_YOUNGSTER_JOEY_4            510
#define TRAINER_YOUNGSTER_MICKEY            511
#define TRAINER_BUG_CATCHER_WADE_4          512
#define TRAINER_BUG_CATCHER_ARNIE_4         513
#define TRAINER_BUG_CATCHER_MICKEY          514
#define TRAINER_FISHERMAN_RALPH_4           515
#define TRAINER_FISHERMAN_MICKEY            516
#define TRAINER_FISHERMAN_TULLY_4           517
#define TRAINER_PICNICKER_LIZ_4             518
#define TRAINER_PICNICKER_MICKEY            519
#define TRAINER_PICNICKER_GINA_4            520
#define TRAINER_PICNICKER_MICKEY_2          521
#define TRAINER_PICNICKER_TIFFANY_4         522
#define TRAINER_HIKER_ANTHONY_4             523
#define TRAINER_HIKER_MICKEY                524
#define TRAINER_CAMPER_TODD_4               525
#define TRAINER_CAMPER_MICKEY_7             526
#define TRAINER_JUGGLER_IRWIN_4             527
#define TRAINER_LASS_DANA_4                 528
#define TRAINER_LASS_MICKEY_3               529
#define TRAINER_POKE_MANIAC_BRENT_4         530
#define TRAINER_TWINS_MICKEY                531
#define TRAINER_BUG_CATCHER_MICKEY_2        532
#define TRAINER_BUG_CATCHER_WAYNE           533
#define TRAINER_BEAUTY_KIMBERLY             534
#define TRAINER_POKEFAN_MARIGOLD            535
#define TRAINER_CAMPER_BERTRAND             536
#define TRAINER_POKE_MANIAC_HARRISON        537
#define TRAINER_SUPER_NERD_HUGH             538
#define TRAINER_SUPER_NERD_MARKUS           539
#define TRAINER_POKEFAN_M_REX               540
#define TRAINER_POKEFAN_M_ANDY              541
#define TRAINER_SAGE_MICKEY_3               542
#define TRAINER_SAGE_MICKEY_4               543
#define TRAINER_SAGE_MICKEY_5               544
#define TRAINER_ACE_TRAINER_M_FRENCH        545
#define TRAINER_SCHOOL_KID_M_SHERMAN        546
#define TRAINER_HIKER_BRUCE                 547
#define TRAINER_BLACK_BELT_MANFORD          548
#define TRAINER_DOUBLE_TEAM_ZAC_AND_JEN     549
#define TRAINER_BLACK_BELT_ANDER            550
#define TRAINER_HIKER_DWIGHT                551
#define TRAINER_YOUNGSTER_REGIS             552
#define TRAINER_YOUNG_COUPLE_MOE_AND_LULU   553
#define TRAINER_GENTLEMAN_MILTON            554
#define TRAINER_BIRD_KEEPER_GS_JUSTIN       555
#define TRAINER_BIRD_KEEPER_GS_GAIL         556
#define TRAINER_YOUNG_COUPLE_VIC_AND_TARA   557
#define TRAINER_FISHERMAN_KYLER             558
#define TRAINER_YOUNG_COUPLE_TIM_AND_SUE    559
#define TRAINER_CAMPER_CLARK                560
#define TRAINER_CAMPER_TANNER               561
#define TRAINER_PICNICKER_PIPER             562
#define TRAINER_PICNICKER_GINGER            563
#define TRAINER_TEACHER_CLARICE             564
#define TRAINER_BIRD_KEEPER_GS_JOSH         565
#define TRAINER_SCHOOL_KID_M_CONNOR         566
#define TRAINER_SCHOOL_KID_M_TORIN          567
#define TRAINER_SCHOOL_KID_M_TRAVIS         568
#define TRAINER_TWINS_KAY_AND_TIA           569
#define TRAINER_POKEFAN_M_BOONE             570
#define TRAINER_POKEFAN_ELEANOR             571
#define TRAINER_BIKER_DALE                  572
#define TRAINER_BIKER_JACOB                 573
#define TRAINER_BIKER_AIDEN                 574
#define TRAINER_BIKER_DAN                   575
#define TRAINER_BIKER_THERON                576
#define TRAINER_BIKER_MARKEY                577
#define TRAINER_BIKER_TEDDY                 578
#define TRAINER_BIKER_ERNEST                579
#define TRAINER_CAMPER_PEDRO                580
#define TRAINER_PICNICKER_ADRIAN            581
#define TRAINER_PICNICKER_CHEYENNE          582
#define TRAINER_BIRD_KEEPER_GS_BERT         583
#define TRAINER_BIRD_KEEPER_GS_ERNIE        584
#define TRAINER_SWIMMER_M_ELMO              585
#define TRAINER_SWIMMER_M_LUIS              586
#define TRAINER_SWIMMER_F_LEONA             587
#define TRAINER_SWIMMER_F_MINA              588
#define TRAINER_FISHERMAN_MURPHY            589
#define TRAINER_FISHERMAN_LIAM              590
#define TRAINER_FISHERMAN_GIDEON            591
#define TRAINER_SWIMMER_F_CHELAN            592
#define TRAINER_SWIMMER_F_KENDRA            593
#define TRAINER_SWIMMER_M_ESTEBAN           594
#define TRAINER_SWIMMER_M_DUANE             595
#define TRAINER_BIRD_KEEPER_GS_KINSLEY      596
#define TRAINER_BIRD_KEEPER_GS_EASTON       597
#define TRAINER_TWINS_DAY_AND_DANI          598
#define TRAINER_CAMPER_VIRGIL               599
#define TRAINER_PICNICKER_SELINA            600
#define TRAINER_TEAM_ROCKET_GRUNT_26        601
#define TRAINER_BIRD_KEEPER_GS_JOSE_4       602
#define TRAINER_PICNICKER_ERIN_4            603
#define TRAINER_ACE_TRAINER_M_GAVEN_4       604
#define TRAINER_BLACK_BELT_KENJI_4          605
#define TRAINER_HIKER_PARRY_4               606
#define TRAINER_ACE_TRAINER_F_REENA_4       607
#define TRAINER_FISHERMAN_WILTON_4          608
#define TRAINER_ACE_TRAINER_F_JAMIE_4       609
#define TRAINER_POKEFAN_M_DEREK_4           610
#define TRAINER_POKEFAN_BEVERLY_4           611
#define TRAINER_BIRD_KEEPER_GS_VANCE_4      612
#define TRAINER_LASS_KRISE_2                613
#define TRAINER_LASS_KRISE_3                614
#define TRAINER_LASS_KRISE_4                615
#define TRAINER_YOUNGSTER_IAN_2             616
#define TRAINER_YOUNGSTER_IAN_3             617
#define TRAINER_YOUNGSTER_IAN_4             618
#define TRAINER_FIREBREATHER_WALT_2         619
#define TRAINER_FIREBREATHER_WALT_3         620
#define TRAINER_FIREBREATHER_WALT_4         621
#define TRAINER_BUG_CATCHER_DOUG_2          622
#define TRAINER_BUG_CATCHER_DOUG_3          623
#define TRAINER_BUG_CATCHER_DOUG_4          624
#define TRAINER_BUG_CATCHER_ROB_2           625
#define TRAINER_BUG_CATCHER_ROB_3           626
#define TRAINER_BUG_CATCHER_ROB_4           627
#define TRAINER_BIKER_REESE_2               628
#define TRAINER_BIKER_REESE_3               629
#define TRAINER_BIKER_REESE_4               630
#define TRAINER_BIKER_AIDEN_2               631
#define TRAINER_BIKER_AIDEN_3               632
#define TRAINER_BIKER_AIDEN_4               633
#define TRAINER_BIKER_ERNEST_2              634
#define TRAINER_BIKER_ERNEST_3              635
#define TRAINER_BIKER_ERNEST_4              636
#define TRAINER_TEACHER_HILLARY_2           637
#define TRAINER_TEACHER_HILLARY_3           638
#define TRAINER_TEACHER_HILLARY_4           639
#define TRAINER_SCHOOL_KID_M_BILLY_2        640
#define TRAINER_SCHOOL_KID_M_BILLY_3        641
#define TRAINER_SCHOOL_KID_M_BILLY_4        642
#define TRAINER_TWINS_KAY_AND_TIA_2         643
#define TRAINER_TWINS_KAY_AND_TIA_3         644
#define TRAINER_TWINS_KAY_AND_TIA_4         645
#define TRAINER_BIRD_KEEPER_GS_JOSH_2       646
#define TRAINER_BIRD_KEEPER_GS_JOSH_3       647
#define TRAINER_BIRD_KEEPER_GS_JOSH_4       648
#define TRAINER_SCHOOL_KID_M_TORIN_2        649
#define TRAINER_SCHOOL_KID_M_TORIN_3        650
#define TRAINER_SCHOOL_KID_M_TORIN_4        651
#define TRAINER_YOUNG_COUPLE_TIM_AND_SUE_2  652
#define TRAINER_YOUNG_COUPLE_TIM_AND_SUE_3  653
#define TRAINER_YOUNG_COUPLE_TIM_AND_SUE_4  654
#define TRAINER_HIKER_KENNY_2               655
#define TRAINER_HIKER_KENNY_3               656
#define TRAINER_HIKER_KENNY_4               657
#define TRAINER_CAMPER_TANNER_2             658
#define TRAINER_CAMPER_TANNER_3             659
#define TRAINER_CAMPER_TANNER_4             660
#define TRAINER_FISHERMAN_KYLE_2            661
#define TRAINER_FISHERMAN_KYLE_3            662
#define TRAINER_FISHERMAN_KYLE_4            663
#define TRAINER_FISHERMAN_KYLER_2           664
#define TRAINER_FISHERMAN_KYLER_3           665
#define TRAINER_FISHERMAN_KYLER_4           666
#define TRAINER_PKMN_TRAINER_CHERYL_CHERYL  667
#define TRAINER_PKMN_TRAINER_BUCK_MARLEY    668
#define TRAINER_PKMN_TRAINER_MARLEY_MIRA    669
#define TRAINER_PKMN_TRAINER_RILEY_RILEY    670
#define TRAINER_PKMN_TRAINER_MIRA_BUCK      671
#define TRAINER_GENTLEMAN_ALFRED_2          672
#define TRAINER_GENTLEMAN_ALFRED_3          673
#define TRAINER_GENTLEMAN_ALFRED_4          674
#define TRAINER_PKMN_TRAINER_LANCE_LANCE    675
#define TRAINER_SAILOR_PARKER               676
#define TRAINER_SAILOR_EDDIE                677
#define TRAINER_SWIMMER_F_JOY               678
#define TRAINER_BEAUTY_CALLIE               679
#define TRAINER_BEAUTY_KASSANDRA            680
#define TRAINER_ACE_TRAINER_M_ARABELLA      681
#define TRAINER_ACE_TRAINER_M_BONITA        682
#define TRAINER_ACE_TRAINER_F_SALMA         683
#define TRAINER_DOUBLE_TEAM_ELAN_AND_IDA    684
#define TRAINER_HIKER_EDWIN                 685
#define TRAINER_BOARDER_BRYCE               686
#define TRAINER_BOARDER_SHAUN               687
#define TRAINER_SKIER_CADY                  688
#define TRAINER_SUPER_NERD_CARY             689
#define TRAINER_SUPER_NERD_WALDO            690
#define TRAINER_SUPER_NERD_MERLE            691
#define TRAINER_SCIENTIST_GS_LOWELL         692
#define TRAINER_SCIENTIST_GS_LINDEN         693
#define TRAINER_SCIENTIST_GS_DANIEL         694
#define TRAINER_BUG_CATCHER_DANE            695
#define TRAINER_BUG_CATCHER_DION            696
#define TRAINER_BUG_CATCHER_STACEY          697
#define TRAINER_BUG_CATCHER_ELLIS           698
#define TRAINER_BUG_CATCHER_ABNER           699
#define TRAINER_ROCKET_BOSS_GIOVANNI        700
#define TRAINER_CHAMPION_LANCE_2            701
#define TRAINER_ELITE_FOUR_WILL_WILL_2      702
#define TRAINER_ELITE_FOUR_KOGA_KOGA_2      703
#define TRAINER_ELITE_FOUR_BRUNO_BRUNO_2    704
#define TRAINER_ELITE_FOUR_KAREN_KAREN_2    705
#define TRAINER_EXECUTIVE_PROTON_PROTON_2   706
#define TRAINER_TOWER_TYCOON_PALMER         707
#define TRAINER_HALL_MATRON_ARGENTA         708
#define TRAINER_FACTORY_HEAD_THORTON        709
#define TRAINER_ARCADE_STAR_DAHLIA          710
#define TRAINER_CASTLE_VALET_DARACH         711
#define TRAINER_LEADER_FALKNER_FALKNER_2    712
#define TRAINER_LEADER_BUGSY_BUGSY_2        713
#define TRAINER_LEADER_WHITNEY_2            714
#define TRAINER_LEADER_MORTY_MORTY_2        715
#define TRAINER_LEADER_PRYCE_PRYCE_2        716
#define TRAINER_LEADER_JASMINE_JASMINE_2    717
#define TRAINER_LEADER_CHUCK_CHUCK_2        718
#define TRAINER_LEADER_CLAIR_CLAIR_2        719
#define TRAINER_LEADER_BROCK_BROCK_2        720
#define TRAINER_LEADER_MISTY_MISTY_2        721
#define TRAINER_LEADER_LT_SURGE_LT__SURGE_2 722
#define TRAINER_LEADER_ERIKA_ERIKA_2        723
#define TRAINER_LEADER_JANINE_JANINE_2      724
#define TRAINER_LEADER_SABRINA_SABRINA_2    725
#define TRAINER_LEADER_BLAINE_BLAINE_2      726
#define TRAINER_LEADER_BLUE_BLUE_2          727
#define TRAINER_BEAUTY_CHARLOTTE            728
#define TRAINER_YOUNG_COUPLE_DUFF_AND_EDA   729
#define TRAINER_DOUBLE_TEAM_THOM_AND_KAE    730
#define TRAINER_HIKER_DEVIN                 731
#define TRAINER_CAMPER_GRANT                732
#define TRAINER_CHAMPION_LANCE_3            733
#define TRAINER_LEADER_CLAIR_CLAIR_3        734
#define TRAINER_PARTNER_RIVAL_1             735
#define TRAINER_PARTNER_RIVAL_2             736
#define TRAINER_PARTNER_RIVAL_3             737

#define LAST_TRAINER_INDEX 740

// Pokemon gender and ability override flags
#define TRPOKE_GENDER_OVERRIDE_OFF    0
#define TRPOKE_GENDER_OVERRIDE_MALE   1
#define TRPOKE_GENDER_OVERRIDE_FEMALE 2

#define TRPOKE_ABILITY_OVERRIDE_OFF    0
#define TRPOKE_ABILITY_OVERRIDE_FIRST  1
#define TRPOKE_ABILITY_OVERRIDE_SECOND 2

// Indices identifying messages in trtbl.narc.
// For use with GetTrainerMessageByIdPair and
// TrainerMessageWithIdPairExists.

#define TRTYPE_MOVES_F (0)
#define TRTYPE_ITEM_F  (1)

#define TRTYPE_MON            ((0 << TRTYPE_MOVES_F) | (0 << TRTYPE_ITEM_F))
#define TRTYPE_MON_MOVES      ((1 << TRTYPE_MOVES_F) | (0 << TRTYPE_ITEM_F))
#define TRTYPE_MON_ITEM       ((0 << TRTYPE_MOVES_F) | (1 << TRTYPE_ITEM_F))
#define TRTYPE_MON_ITEM_MOVES ((1 << TRTYPE_MOVES_F) | (1 << TRTYPE_ITEM_F))

// Before the battle starts (interact, trainer eye)
#define TRMSG_INTRO 0
// When the NPC loses
#define TRMSG_LOSE 1
// After the trainer is defeated (interact)
#define TRMSG_AFTER 2
// These are for double-battle trainer classes.
// One member gets the _1 IDs, the other gets
// the _2 IDs.
#define TRMSG_DBL_INTRO_1 3
#define TRMSG_DBL_LOSE_1  4
#define TRMSG_DBL_AFTER_1 5
// If the player tries to start the double
// battle with only one usable party member,
// a double trainer will refuse to engage.
// This message, along with TRMSG_DBL_1POKE_2,
// accompanies this refusal.
#define TRMSG_DBL_1POKE_1 6
#define TRMSG_DBL_INTRO_2 7
#define TRMSG_DBL_LOSE_2  8
#define TRMSG_DBL_AFTER_2 9
#define TRMSG_DBL_1POKE_2 10
// 11-14 are unused.
#define TRMSG_LAST_POKE      15
#define TRMSG_LAST_POKE_HALF 16
// The texts change when it's a phone trainer.
#define TRMSG_PHONE_REMATCH_INTRO       17
#define TRMSG_PHONE_REMATCH_DBL_INTRO_1 18
#define TRMSG_PHONE_REMATCH_DBL_INTRO_2 19
#define TRMSG_WIN                       20

#endif // POKEHEARTGOLD_CONSTANTS_TRAINERS_H
