#ifndef POKEHEARTGOLD_CONSTANTS_TRAINER_DATA_H
#define POKEHEARTGOLD_CONSTANTS_TRAINER_DATA_H

typedef enum TrainerAttr {
    TRATTR_TYPE,
    TRATTR_CLASS,
    TRATTR_UNK2,
    TRATTR_NPOKE,
    TRATTR_ITEM1,
    TRATTR_ITEM2,
    TRATTR_ITEM3,
    TRATTR_ITEM4,
    TRATTR_AIFLAGS,
    TRATTR_DOUBLEBTL,
} TrainerAttr;

typedef enum TrainerGender {
    TRAINER_MALE,
    TRAINER_FEMALE,
    TRAINER_DOUBLE,
} TrainerGender;

#endif // POKEHEARTGOLD_CONSTANTS_TRAINER_DATA_H
