#ifndef POKEHEARTGOLD_CONSTANTS_VARS_H
#define POKEHEARTGOLD_CONSTANTS_VARS_H

#define NUM_VARS            368
#define VAR_BASE         0x4000
#define SPECIAL_VAR_BASE 0x8000

#endif //POKEHEARTGOLD_CONSTANTS_VARS_H
