#ifndef GUARD_POKEHEARTGOLD_FIELD_ENCOUNTER_CHECK_H
#define GUARD_POKEHEARTGOLD_FIELD_ENCOUNTER_CHECK_H

#include "field_system.h"

BOOL ov02_02246C8C(FieldSystem *fieldSystem);

#endif // GUARD_POKEHEARTGOLD_FIELD_ENCOUNTER_CHECK_H
