if get_option('version') == 'heartgold'
    zukan_hw_files = copy_gen.process(files(
        'zukan_hw_data_0.bin', 
        'zukan_hw_data_1_gold.bin'
    ))
    zukan_hw_order = files('zukan_hw_gold.order')
elif get_option('version') == 'soulsilver'
    zukan_hw_files = copy_gen.process(files(
        'zukan_hw_data_0.bin', 
        'zukan_hw_data_1_silver.bin'
    ))
    zukan_hw_order = files('zukan_hw_silver.order')
endif