
zukan_hw_files_hg = copy_gen.process(files(
    'zukan_hw_data_0.bin', 
    'zukan_hw_data_1_gold.bin'
))
zukan_hw_order_hg = files('zukan_hw_gold.order')

zukan_hw_files_ss = copy_gen.process(files(
    'zukan_hw_data_0.bin', 
    'zukan_hw_data_1_silver.bin'
))
zukan_hw_order_ss = files('zukan_hw_silver.order')
