#ifndef NNSYS_G3D_BINRES_RES_STRUCT_ACCESSOR_H
#define NNSYS_G3D_BINRES_RES_STRUCT_ACCESSOR_H

NNSG3dResMdlSet* NNS_G3dGetMdlSet(const NNSG3dResFileHeader* header);
NNSG3dResTex* NNS_G3dGetTex(const NNSG3dResFileHeader* header);

#endif //NNSYS_G3D_BINRES_RES_STRUCT_ACCESSOR_H
