pokefoot_nclr = copy_gen.process(files(
    'pokefoot_00000000.NCLR',
))

pokefoot_nanr_lz = lz_gen.process(files(
    'pokefoot_00000001.NANR'
))

pokefoot_ncer_lz = lz_gen.process(files(
    'pokefoot_00000002.NCER'
))

pokefoot_ncgr_lz = ncgr_lz_gen.process(files(
    'pokefoot_00000003.png',
    'pokefoot_00000004.png',
    'pokefoot_00000005.png',
    'pokefoot_00000006.png',
    'pokefoot_00000007.png',
    'pokefoot_00000008.png',
    'pokefoot_00000009.png',
    'pokefoot_00000010.png',
    'pokefoot_00000011.png',
    'pokefoot_00000012.png',
    'pokefoot_00000013.png',
    'pokefoot_00000014.png',
    'pokefoot_00000015.png',
    'pokefoot_00000016.png',
    'pokefoot_00000017.png',
    'pokefoot_00000018.png',
    'pokefoot_00000019.png',
    'pokefoot_00000020.png',
    'pokefoot_00000021.png',
    'pokefoot_00000022.png',
    'pokefoot_00000023.png',
    'pokefoot_00000024.png',
    'pokefoot_00000025.png',
    'pokefoot_00000026.png',
    'pokefoot_00000027.png',
    'pokefoot_00000028.png',
    'pokefoot_00000029.png',
    'pokefoot_00000030.png',
    'pokefoot_00000031.png',
    'pokefoot_00000032.png',
    'pokefoot_00000033.png',
    'pokefoot_00000034.png',
    'pokefoot_00000035.png',
    'pokefoot_00000036.png',
    'pokefoot_00000037.png',
    'pokefoot_00000038.png',
    'pokefoot_00000039.png',
    'pokefoot_00000040.png',
    'pokefoot_00000041.png',
    'pokefoot_00000042.png',
    'pokefoot_00000043.png',
    'pokefoot_00000044.png',
    'pokefoot_00000045.png',
    'pokefoot_00000046.png',
    'pokefoot_00000047.png',
    'pokefoot_00000048.png',
    'pokefoot_00000049.png',
    'pokefoot_00000050.png',
    'pokefoot_00000051.png',
    'pokefoot_00000052.png',
    'pokefoot_00000053.png',
    'pokefoot_00000054.png',
    'pokefoot_00000055.png',
    'pokefoot_00000056.png',
    'pokefoot_00000057.png',
    'pokefoot_00000058.png',
    'pokefoot_00000059.png',
    'pokefoot_00000060.png',
    'pokefoot_00000061.png',
    'pokefoot_00000062.png',
    'pokefoot_00000063.png',
    'pokefoot_00000064.png',
    'pokefoot_00000065.png',
    'pokefoot_00000066.png',
    'pokefoot_00000067.png',
    'pokefoot_00000068.png',
    'pokefoot_00000069.png',
    'pokefoot_00000070.png',
    'pokefoot_00000071.png',
    'pokefoot_00000072.png',
    'pokefoot_00000073.png',
    'pokefoot_00000074.png',
    'pokefoot_00000075.png',
    'pokefoot_00000076.png',
    'pokefoot_00000077.png',
    'pokefoot_00000078.png',
    'pokefoot_00000079.png',
    'pokefoot_00000080.png',
    'pokefoot_00000081.png',
    'pokefoot_00000082.png',
    'pokefoot_00000083.png',
    'pokefoot_00000084.png',
    'pokefoot_00000085.png',
    'pokefoot_00000086.png',
    'pokefoot_00000087.png',
    'pokefoot_00000088.png',
    'pokefoot_00000089.png',
    'pokefoot_00000090.png',
    'pokefoot_00000091.png',
    'pokefoot_00000092.png',
    'pokefoot_00000093.png',
    'pokefoot_00000094.png',
    'pokefoot_00000095.png',
    'pokefoot_00000096.png',
    'pokefoot_00000097.png',
    'pokefoot_00000098.png',
    'pokefoot_00000099.png',
    'pokefoot_00000100.png',
    'pokefoot_00000101.png',
    'pokefoot_00000102.png',
    'pokefoot_00000103.png',
    'pokefoot_00000104.png',
    'pokefoot_00000105.png',
    'pokefoot_00000106.png',
    'pokefoot_00000107.png',
    'pokefoot_00000108.png',
    'pokefoot_00000109.png',
    'pokefoot_00000110.png',
    'pokefoot_00000111.png',
    'pokefoot_00000112.png',
    'pokefoot_00000113.png',
    'pokefoot_00000114.png',
    'pokefoot_00000115.png',
    'pokefoot_00000116.png',
    'pokefoot_00000117.png',
    'pokefoot_00000118.png',
    'pokefoot_00000119.png',
    'pokefoot_00000120.png',
    'pokefoot_00000121.png',
    'pokefoot_00000122.png',
    'pokefoot_00000123.png',
    'pokefoot_00000124.png',
    'pokefoot_00000125.png',
    'pokefoot_00000126.png',
    'pokefoot_00000127.png',
    'pokefoot_00000128.png',
    'pokefoot_00000129.png',
    'pokefoot_00000130.png',
    'pokefoot_00000131.png',
    'pokefoot_00000132.png',
    'pokefoot_00000133.png',
    'pokefoot_00000134.png',
    'pokefoot_00000135.png',
    'pokefoot_00000136.png',
    'pokefoot_00000137.png',
    'pokefoot_00000138.png',
    'pokefoot_00000139.png',
    'pokefoot_00000140.png',
    'pokefoot_00000141.png',
    'pokefoot_00000142.png',
    'pokefoot_00000143.png',
    'pokefoot_00000144.png',
    'pokefoot_00000145.png',
    'pokefoot_00000146.png',
    'pokefoot_00000147.png',
    'pokefoot_00000148.png',
    'pokefoot_00000149.png',
    'pokefoot_00000150.png',
    'pokefoot_00000151.png',
    'pokefoot_00000152.png',
    'pokefoot_00000153.png',
    'pokefoot_00000154.png',
    'pokefoot_00000155.png',
    'pokefoot_00000156.png',
    'pokefoot_00000157.png',
    'pokefoot_00000158.png',
    'pokefoot_00000159.png',
    'pokefoot_00000160.png',
    'pokefoot_00000161.png',
    'pokefoot_00000162.png',
    'pokefoot_00000163.png',
    'pokefoot_00000164.png',
    'pokefoot_00000165.png',
    'pokefoot_00000166.png',
    'pokefoot_00000167.png',
    'pokefoot_00000168.png',
    'pokefoot_00000169.png',
    'pokefoot_00000170.png',
    'pokefoot_00000171.png',
    'pokefoot_00000172.png',
    'pokefoot_00000173.png',
    'pokefoot_00000174.png',
    'pokefoot_00000175.png',
    'pokefoot_00000176.png',
    'pokefoot_00000177.png',
    'pokefoot_00000178.png',
    'pokefoot_00000179.png',
    'pokefoot_00000180.png',
    'pokefoot_00000181.png',
    'pokefoot_00000182.png',
    'pokefoot_00000183.png',
    'pokefoot_00000184.png',
    'pokefoot_00000185.png',
    'pokefoot_00000186.png',
    'pokefoot_00000187.png',
    'pokefoot_00000188.png',
    'pokefoot_00000189.png',
    'pokefoot_00000190.png',
    'pokefoot_00000191.png',
    'pokefoot_00000192.png',
    'pokefoot_00000193.png',
    'pokefoot_00000194.png',
    'pokefoot_00000195.png',
    'pokefoot_00000196.png',
    'pokefoot_00000197.png',
    'pokefoot_00000198.png',
    'pokefoot_00000199.png',
    'pokefoot_00000200.png',
    'pokefoot_00000201.png',
    'pokefoot_00000202.png',
    'pokefoot_00000203.png',
    'pokefoot_00000204.png',
    'pokefoot_00000205.png',
    'pokefoot_00000206.png',
    'pokefoot_00000207.png',
    'pokefoot_00000208.png',
    'pokefoot_00000209.png',
    'pokefoot_00000210.png',
    'pokefoot_00000211.png',
    'pokefoot_00000212.png',
    'pokefoot_00000213.png',
    'pokefoot_00000214.png',
    'pokefoot_00000215.png',
    'pokefoot_00000216.png',
    'pokefoot_00000217.png',
    'pokefoot_00000218.png',
    'pokefoot_00000219.png',
    'pokefoot_00000220.png',
    'pokefoot_00000221.png',
    'pokefoot_00000222.png',
    'pokefoot_00000223.png',
    'pokefoot_00000224.png',
    'pokefoot_00000225.png',
    'pokefoot_00000226.png',
    'pokefoot_00000227.png',
    'pokefoot_00000228.png',
    'pokefoot_00000229.png',
    'pokefoot_00000230.png',
    'pokefoot_00000231.png',
    'pokefoot_00000232.png',
    'pokefoot_00000233.png',
    'pokefoot_00000234.png',
    'pokefoot_00000235.png',
    'pokefoot_00000236.png',
    'pokefoot_00000237.png',
    'pokefoot_00000238.png',
    'pokefoot_00000239.png',
    'pokefoot_00000240.png',
    'pokefoot_00000241.png',
    'pokefoot_00000242.png',
    'pokefoot_00000243.png',
    'pokefoot_00000244.png',
    'pokefoot_00000245.png',
    'pokefoot_00000246.png',
    'pokefoot_00000247.png',
    'pokefoot_00000248.png',
    'pokefoot_00000249.png',
    'pokefoot_00000250.png',
    'pokefoot_00000251.png',
    'pokefoot_00000252.png',
    'pokefoot_00000253.png',
    'pokefoot_00000254.png',
    'pokefoot_00000255.png',
    'pokefoot_00000256.png',
    'pokefoot_00000257.png',
    'pokefoot_00000258.png',
    'pokefoot_00000259.png',
    'pokefoot_00000260.png',
    'pokefoot_00000261.png',
    'pokefoot_00000262.png',
    'pokefoot_00000263.png',
    'pokefoot_00000264.png',
    'pokefoot_00000265.png',
    'pokefoot_00000266.png',
    'pokefoot_00000267.png',
    'pokefoot_00000268.png',
    'pokefoot_00000269.png',
    'pokefoot_00000270.png',
    'pokefoot_00000271.png',
    'pokefoot_00000272.png',
    'pokefoot_00000273.png',
    'pokefoot_00000274.png',
    'pokefoot_00000275.png',
    'pokefoot_00000276.png',
    'pokefoot_00000277.png',
    'pokefoot_00000278.png',
    'pokefoot_00000279.png',
    'pokefoot_00000280.png',
    'pokefoot_00000281.png',
    'pokefoot_00000282.png',
    'pokefoot_00000283.png',
    'pokefoot_00000284.png',
    'pokefoot_00000285.png',
    'pokefoot_00000286.png',
    'pokefoot_00000287.png',
    'pokefoot_00000288.png',
    'pokefoot_00000289.png',
    'pokefoot_00000290.png',
    'pokefoot_00000291.png',
    'pokefoot_00000292.png',
    'pokefoot_00000293.png',
    'pokefoot_00000294.png',
    'pokefoot_00000295.png',
    'pokefoot_00000296.png',
    'pokefoot_00000297.png',
    'pokefoot_00000298.png',
    'pokefoot_00000299.png',
    'pokefoot_00000300.png',
    'pokefoot_00000301.png',
    'pokefoot_00000302.png',
    'pokefoot_00000303.png',
    'pokefoot_00000304.png',
    'pokefoot_00000305.png',
    'pokefoot_00000306.png',
    'pokefoot_00000307.png',
    'pokefoot_00000308.png',
    'pokefoot_00000309.png',
    'pokefoot_00000310.png',
    'pokefoot_00000311.png',
    'pokefoot_00000312.png',
    'pokefoot_00000313.png',
    'pokefoot_00000314.png',
    'pokefoot_00000315.png',
    'pokefoot_00000316.png',
    'pokefoot_00000317.png',
    'pokefoot_00000318.png',
    'pokefoot_00000319.png',
    'pokefoot_00000320.png',
    'pokefoot_00000321.png',
    'pokefoot_00000322.png',
    'pokefoot_00000323.png',
    'pokefoot_00000324.png',
    'pokefoot_00000325.png',
    'pokefoot_00000326.png',
    'pokefoot_00000327.png',
    'pokefoot_00000328.png',
    'pokefoot_00000329.png',
    'pokefoot_00000330.png',
    'pokefoot_00000331.png',
    'pokefoot_00000332.png',
    'pokefoot_00000333.png',
    'pokefoot_00000334.png',
    'pokefoot_00000335.png',
    'pokefoot_00000336.png',
    'pokefoot_00000337.png',
    'pokefoot_00000338.png',
    'pokefoot_00000339.png',
    'pokefoot_00000340.png',
    'pokefoot_00000341.png',
    'pokefoot_00000342.png',
    'pokefoot_00000343.png',
    'pokefoot_00000344.png',
    'pokefoot_00000345.png',
    'pokefoot_00000346.png',
    'pokefoot_00000347.png',
    'pokefoot_00000348.png',
    'pokefoot_00000349.png',
    'pokefoot_00000350.png',
    'pokefoot_00000351.png',
    'pokefoot_00000352.png',
    'pokefoot_00000353.png',
    'pokefoot_00000354.png',
    'pokefoot_00000355.png',
    'pokefoot_00000356.png',
    'pokefoot_00000357.png',
    'pokefoot_00000358.png',
    'pokefoot_00000359.png',
    'pokefoot_00000360.png',
    'pokefoot_00000361.png',
    'pokefoot_00000362.png',
    'pokefoot_00000363.png',
    'pokefoot_00000364.png',
    'pokefoot_00000365.png',
    'pokefoot_00000366.png',
    'pokefoot_00000367.png',
    'pokefoot_00000368.png',
    'pokefoot_00000369.png',
    'pokefoot_00000370.png',
    'pokefoot_00000371.png',
    'pokefoot_00000372.png',
    'pokefoot_00000373.png',
    'pokefoot_00000374.png',
    'pokefoot_00000375.png',
    'pokefoot_00000376.png',
    'pokefoot_00000377.png',
    'pokefoot_00000378.png',
    'pokefoot_00000379.png',
    'pokefoot_00000380.png',
    'pokefoot_00000381.png',
    'pokefoot_00000382.png',
    'pokefoot_00000383.png',
    'pokefoot_00000384.png',
    'pokefoot_00000385.png',
    'pokefoot_00000386.png',
    'pokefoot_00000387.png',
    'pokefoot_00000388.png',
    'pokefoot_00000389.png',
    'pokefoot_00000390.png',
    'pokefoot_00000391.png',
    'pokefoot_00000392.png',
    'pokefoot_00000393.png',
    'pokefoot_00000394.png',
    'pokefoot_00000395.png',
    'pokefoot_00000396.png',
    'pokefoot_00000397.png',
    'pokefoot_00000398.png',
    'pokefoot_00000399.png',
    'pokefoot_00000400.png',
    'pokefoot_00000401.png',
    'pokefoot_00000402.png',
    'pokefoot_00000403.png',
    'pokefoot_00000404.png',
    'pokefoot_00000405.png',
    'pokefoot_00000406.png',
    'pokefoot_00000407.png',
    'pokefoot_00000408.png',
    'pokefoot_00000409.png',
    'pokefoot_00000410.png',
    'pokefoot_00000411.png',
    'pokefoot_00000412.png',
    'pokefoot_00000413.png',
    'pokefoot_00000414.png',
    'pokefoot_00000415.png',
    'pokefoot_00000416.png',
    'pokefoot_00000417.png',
    'pokefoot_00000418.png',
    'pokefoot_00000419.png',
    'pokefoot_00000420.png',
    'pokefoot_00000421.png',
    'pokefoot_00000422.png',
    'pokefoot_00000423.png',
    'pokefoot_00000424.png',
    'pokefoot_00000425.png',
    'pokefoot_00000426.png',
    'pokefoot_00000427.png',
    'pokefoot_00000428.png',
    'pokefoot_00000429.png',
    'pokefoot_00000430.png',
    'pokefoot_00000431.png',
    'pokefoot_00000432.png',
    'pokefoot_00000433.png',
    'pokefoot_00000434.png',
    'pokefoot_00000435.png',
    'pokefoot_00000436.png',
    'pokefoot_00000437.png',
    'pokefoot_00000438.png',
    'pokefoot_00000439.png',
    'pokefoot_00000440.png',
    'pokefoot_00000441.png',
    'pokefoot_00000442.png',
    'pokefoot_00000443.png',
    'pokefoot_00000444.png',
    'pokefoot_00000445.png',
    'pokefoot_00000446.png',
    'pokefoot_00000447.png',
    'pokefoot_00000448.png',
    'pokefoot_00000449.png',
    'pokefoot_00000450.png',
    'pokefoot_00000451.png',
    'pokefoot_00000452.png',
    'pokefoot_00000453.png',
    'pokefoot_00000454.png',
    'pokefoot_00000455.png',
    'pokefoot_00000456.png',
    'pokefoot_00000457.png',
    'pokefoot_00000458.png',
    'pokefoot_00000459.png',
    'pokefoot_00000460.png',
    'pokefoot_00000461.png',
    'pokefoot_00000462.png',
    'pokefoot_00000463.png',
    'pokefoot_00000464.png',
    'pokefoot_00000465.png',
    'pokefoot_00000466.png',
    'pokefoot_00000467.png',
    'pokefoot_00000468.png',
    'pokefoot_00000469.png',
    'pokefoot_00000470.png',
    'pokefoot_00000471.png',
    'pokefoot_00000472.png',
    'pokefoot_00000473.png',
    'pokefoot_00000474.png',
    'pokefoot_00000475.png',
    'pokefoot_00000476.png',
    'pokefoot_00000477.png',
    'pokefoot_00000478.png',
    'pokefoot_00000479.png',
    'pokefoot_00000480.png',
    'pokefoot_00000481.png',
    'pokefoot_00000482.png',
    'pokefoot_00000483.png',
    'pokefoot_00000484.png',
    'pokefoot_00000485.png',
    'pokefoot_00000486.png',
    'pokefoot_00000487.png',
    'pokefoot_00000488.png',
    'pokefoot_00000489.png',
    'pokefoot_00000490.png',
    'pokefoot_00000491.png',
    'pokefoot_00000492.png',
    'pokefoot_00000493.png',
    'pokefoot_00000494.png',
    'pokefoot_00000495.png',
    'pokefoot_00000496.png',
    ),
    extra_args : CLOBBER_SIZE_VERSION101_128K_NCGR_FLAGS
)