otherpoke_index_ncgr += {
    '0154' : files('normal/back.png'),
    '0155' : files('normal/front.png'),
    '0156' : files('spiky/back.png'),
    '0157' : files('spiky/front.png'),
}

otherpoke_index_nclr += {
    '252' : files('normal/front.png'),
    '253' : files('normal/back.png'),
    '254' : files('spiky/front.png'),
    '255' : files('spiky/back.png'),
}