#include "application/pokegear/phone/phone_internal.h"
#include "msgdata/msg/msg_0641.h"
#include "msgdata/msg/msg_0642.h"
#include "msgdata/msg/msg_0643.h"
#include "msgdata/msg/msg_0644.h"
#include "msgdata/msg/msg_0645.h"
#include "msgdata/msg/msg_0646.h"
#include "msgdata/msg/msg_0647.h"
#include "msgdata/msg/msg_0648.h"
#include "msgdata/msg/msg_0649.h"
#include "msgdata/msg/msg_0650.h"
#include "msgdata/msg/msg_0651.h"
#include "msgdata/msg/msg_0652.h"
#include "msgdata/msg/msg_0653.h"
#include "msgdata/msg/msg_0654.h"
#include "msgdata/msg/msg_0655.h"
#include "msgdata/msg/msg_0656.h"
#include "msgdata/msg/msg_0657.h"
#include "msgdata/msg/msg_0658.h"
#include "msgdata/msg/msg_0659.h"
#include "msgdata/msg/msg_0660.h"
#include "msgdata/msg/msg_0661.h"
#include "msgdata/msg/msg_0662.h"
#include "msgdata/msg/msg_0663.h"
#include "msgdata/msg/msg_0664.h"
#include "msgdata/msg/msg_0665.h"
#include "msgdata/msg/msg_0666.h"
#include "msgdata/msg/msg_0667.h"
#include "msgdata/msg/msg_0669.h"
#include "msgdata/msg/msg_0670.h"
#include "msgdata/msg/msg_0671.h"
#include "msgdata/msg/msg_0672.h"
#include "msgdata/msg/msg_0673.h"
#include "msgdata/msg/msg_0674.h"
#include "msgdata/msg/msg_0675.h"
#include "msgdata/msg/msg_0676.h"
#include "msgdata/msg/msg_0677.h"
#include "msgdata/msg/msg_0678.h"
#include "msgdata/msg/msg_0679.h"
#include "msgdata/msg/msg_0680.h"
#include "msgdata/msg/msg_0681.h"
#include "msgdata/msg/msg_0682.h"
#include "msgdata/msg/msg_0683.h"
#include "msgdata/msg/msg_0684.h"
#include "msgdata/msg/msg_0685.h"
#include "msgdata/msg/msg_0686.h"
#include "msgdata/msg/msg_0687.h"
#include "msgdata/msg/msg_0688.h"
#include "msgdata/msg/msg_0689.h"
#include "msgdata/msg/msg_0690.h"
#include "msgdata/msg/msg_0691.h"
#include "msgdata/msg/msg_0692.h"
#include "msgdata/msg/msg_0693.h"
#include "msgdata/msg/msg_0694.h"
#include "msgdata/msg/msg_0695.h"
#include "msgdata/msg/msg_0696.h"
#include "msgdata/msg/msg_0697.h"
#include "msgdata/msg/msg_0698.h"
#include "msgdata/msg/msg_0699.h"
#include "msgdata/msg/msg_0700.h"
#include "msgdata/msg/msg_0701.h"
#include "msgdata/msg/msg_0702.h"
#include "msgdata/msg/msg_0703.h"
#include "msgdata/msg/msg_0704.h"
#include "msgdata/msg/msg_0705.h"
#include "msgdata/msg/msg_0706.h"
#include "msgdata/msg/msg_0707.h"
#include "msgdata/msg/msg_0708.h"
#include "msgdata/msg/msg_0709.h"
#include "msgdata/msg/msg_0710.h"
#include "msgdata/msg/msg_0711.h"
#include "msgdata/msg/msg_0712.h"
#include "msgdata/msg/msg_0713.h"
#include "msgdata/msg/msg_0714.h"
#include "msgdata/msg/msg_0715.h"
#include "msgdata/msg/msg_0716.h"

// This table contains all 455 phone scripts in the game
// Not all of them are sensible at the same time as each caller has its own gmm bank
// It is unclear why GameFreak designed it this way
// x00: u8 Male player GMM
// x01: u8 Female player GMM
// x02: u16
//    bits 0-3: kind
//    bits 4-15: param0
// x04: u16 param1
//        0: nil
//        1: flag action: param0=1 set param0=1 clear, param1=flagId
//        2: same as 1
//        3: rematch
//        4: gift item, param1=itemSetId
//        5: random word, param0=numChoices, param1=baseMsgId
const PhoneCallScriptDef gPhoneCallScriptDef[] = {
    {
     .msgIds = { 0, 0 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { msg_0716_00001, msg_0716_00002 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { msg_0716_00033, msg_0716_00034 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { msg_0716_00035, msg_0716_00036 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { msg_0716_00037, msg_0716_00038 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { msg_0716_00039, msg_0716_00040 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { msg_0716_00041, msg_0716_00042 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { msg_0716_00043, msg_0716_00044 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { msg_0716_00003, msg_0716_00004 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { msg_0716_00005, msg_0716_00006 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { msg_0716_00007, msg_0716_00008 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { msg_0716_00009, msg_0716_00010 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { msg_0716_00011, msg_0716_00012 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { msg_0716_00013, msg_0716_00014 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { msg_0716_00015, msg_0716_00016 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { msg_0716_00017, msg_0716_00018 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { msg_0716_00019, msg_0716_00020 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { msg_0716_00021, msg_0716_00022 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { msg_0716_00023, msg_0716_00024 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { msg_0716_00025, msg_0716_00026 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { msg_0716_00027, msg_0716_00028 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { msg_0716_00029, msg_0716_00030 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { msg_0716_00031, msg_0716_00032 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { msg_0664_00001, msg_0664_00002 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { msg_0664_00003, msg_0664_00003 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { msg_0664_00005, msg_0664_00005 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { msg_0664_00006, msg_0664_00006 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 29, 29 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 22, 22 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 6, 6 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 7, 7 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 8, 8 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 9, 9 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 10, 10 },
     .kind = 3,
     .param0 = 1,
     .param1 = 0,
     },
    {
     .msgIds = { 11, 11 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 12, 12 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 6, 6 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 7, 7 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 8, 8 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 9, 9 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 10, 10 },
     .kind = 3,
     .param0 = 1,
     .param1 = 0,
     },
    {
     .msgIds = { 11, 11 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 12, 12 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 13, 13 },
     .kind = 4,
     .param0 = 1,
     .param1 = 149,
     },
    {
     .msgIds = { 14, 14 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 15, 16 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 5, 5 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 6, 6 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 7, 7 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 8, 8 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 9, 9 },
     .kind = 3,
     .param0 = 1,
     .param1 = 0,
     },
    {
     .msgIds = { 10, 10 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 11, 11 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 5, 5 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 6, 6 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 7, 7 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 21, 21 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 19, 19 },
     .kind = 3,
     .param0 = 1,
     .param1 = 0,
     },
    {
     .msgIds = { 20, 20 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 8, 8 },
     .kind = 5,
     .param0 = 9,
     .param1 = 23,
     },
    {
     .msgIds = { 22, 22 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 5, 5 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 6, 6 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 7, 7 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 8, 8 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 9, 9 },
     .kind = 3,
     .param0 = 1,
     .param1 = 0,
     },
    {
     .msgIds = { 10, 10 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 11, 11 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 1, 2 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 3, 3 },
     .kind = 2,
     .param0 = 1,
     .param1 = 2441,
     },
    {
     .msgIds = { 4, 4 },
     .kind = 2,
     .param0 = 1,
     .param1 = 2442,
     },
    {
     .msgIds = { 5, 5 },
     .kind = 2,
     .param0 = 1,
     .param1 = 2443,
     },
    {
     .msgIds = { 6, 6 },
     .kind = 2,
     .param0 = 1,
     .param1 = 2444,
     },
    {
     .msgIds = { 7, 7 },
     .kind = 2,
     .param0 = 1,
     .param1 = 2445,
     },
    {
     .msgIds = { 8, 8 },
     .kind = 2,
     .param0 = 1,
     .param1 = 2446,
     },
    {
     .msgIds = { 9, 9 },
     .kind = 2,
     .param0 = 1,
     .param1 = 2447,
     },
    {
     .msgIds = { 10, 10 },
     .kind = 2,
     .param0 = 1,
     .param1 = 2448,
     },
    {
     .msgIds = { 11, 11 },
     .kind = 2,
     .param0 = 1,
     .param1 = 2449,
     },
    {
     .msgIds = { 22, 23 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 24, 25 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 26, 26 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 27, 27 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 12, 12 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 1, 1 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 1, 2 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 3, 3 },
     .kind = 2,
     .param0 = 1,
     .param1 = 2436,
     },
    {
     .msgIds = { 7, 7 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 8, 8 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 9, 9 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 10, 10 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 11, 11 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 12, 12 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 1, 2 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 10, 11 },
     .kind = 2,
     .param0 = 1,
     .param1 = 2437,
     },
    {
     .msgIds = { 1, 1 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 12, 12 },
     .kind = 2,
     .param0 = 1,
     .param1 = 2450,
     },
    {
     .msgIds = { 13, 13 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 1, 2 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 1, 2 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 13, 14 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 9, 9 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 3, 3 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 3, 3 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 1, 1 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 6, 6 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 7, 7 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 8, 8 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 9, 9 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 10, 10 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 21, 21 },
     .kind = 3,
     .param0 = 1,
     .param1 = 0,
     },
    {
     .msgIds = { 22, 23 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 24, 24 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 5, 5 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 6, 6 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 7, 7 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 8, 8 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 20, 20 },
     .kind = 3,
     .param0 = 1,
     .param1 = 0,
     },
    {
     .msgIds = { 9, 9 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 21, 21 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 22, 22 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 6, 6 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 7, 7 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 8, 8 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 9, 9 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 10, 10 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 21, 21 },
     .kind = 3,
     .param0 = 1,
     .param1 = 0,
     },
    {
     .msgIds = { 22, 22 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 23, 23 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 5, 5 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 6, 6 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 7, 7 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 8, 8 },
     .kind = 3,
     .param0 = 1,
     .param1 = 0,
     },
    {
     .msgIds = { 9, 9 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 10, 10 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 5, 5 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 6, 6 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 7, 7 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 8, 8 },
     .kind = 3,
     .param0 = 1,
     .param1 = 0,
     },
    {
     .msgIds = { 9, 9 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 10, 10 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 1, 1 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 2, 3 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 4, 5 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 6, 7 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 8, 9 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 10, 11 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 12, 13 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 26, 27 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 28, 29 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 30, 31 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 32, 33 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 34, 35 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 36, 37 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 38, 39 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 40, 41 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 5, 5 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 6, 7 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 8, 9 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 10, 11 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 12, 13 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 14, 15 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 16, 17 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 18, 19 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 20, 21 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 22, 23 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 24, 25 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 26, 27 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 28, 29 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 30, 31 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 32, 33 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 34, 35 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 36, 37 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 38, 38 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 39, 39 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 40, 40 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 1, 1 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 1, 1 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 1, 1 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 1, 1 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 1, 1 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 1, 1 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 1, 1 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 1, 1 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 1, 1 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 1, 1 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 1, 1 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 1, 1 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 1, 1 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 1, 1 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 1, 1 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 6, 6 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 7, 7 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 8, 8 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 9, 9 },
     .kind = 3,
     .param0 = 1,
     .param1 = 0,
     },
    {
     .msgIds = { 10, 10 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 11, 11 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 6, 6 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 7, 7 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 8, 8 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 9, 9 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 10, 10 },
     .kind = 3,
     .param0 = 1,
     .param1 = 0,
     },
    {
     .msgIds = { 11, 12 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 13, 13 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 6, 6 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 7, 7 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 8, 8 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 9, 9 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 10, 10 },
     .kind = 3,
     .param0 = 1,
     .param1 = 0,
     },
    {
     .msgIds = { 11, 12 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 13, 13 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 6, 6 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 7, 7 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 8, 8 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 9, 9 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 10, 10 },
     .kind = 3,
     .param0 = 1,
     .param1 = 0,
     },
    {
     .msgIds = { 11, 11 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 12, 12 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 6, 6 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 7, 7 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 8, 8 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 9, 9 },
     .kind = 3,
     .param0 = 1,
     .param1 = 0,
     },
    {
     .msgIds = { 10, 11 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 12, 12 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 6, 6 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 7, 7 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 8, 8 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 9, 9 },
     .kind = 3,
     .param0 = 1,
     .param1 = 0,
     },
    {
     .msgIds = { 10, 10 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 11, 11 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 6, 6 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 7, 7 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 8, 8 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 9, 9 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 10, 10 },
     .kind = 3,
     .param0 = 1,
     .param1 = 0,
     },
    {
     .msgIds = { 11, 11 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 12, 12 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 6, 6 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 7, 7 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 8, 8 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 11, 11 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 9, 9 },
     .kind = 4,
     .param0 = 1,
     .param1 = 92,
     },
    {
     .msgIds = { 10, 10 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 6, 6 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 7, 7 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 8, 8 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 9, 9 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 10, 10 },
     .kind = 3,
     .param0 = 1,
     .param1 = 0,
     },
    {
     .msgIds = { 11, 12 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 13, 13 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 14, 14 },
     .kind = 4,
     .param0 = 1,
     .param1 = 91,
     },
    {
     .msgIds = { 15, 15 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 6, 6 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 7, 7 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 8, 8 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 9, 9 },
     .kind = 3,
     .param0 = 1,
     .param1 = 0,
     },
    {
     .msgIds = { 10, 11 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 12, 12 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 13, 13 },
     .kind = 4,
     .param0 = 1,
     .param1 = 85,
     },
    {
     .msgIds = { 14, 14 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 15, 15 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 6, 6 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 7, 7 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 8, 8 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 9, 9 },
     .kind = 3,
     .param0 = 1,
     .param1 = 0,
     },
    {
     .msgIds = { 10, 10 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 11, 11 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 12, 12 },
     .kind = 4,
     .param0 = 1,
     .param1 = 82,
     },
    {
     .msgIds = { 13, 13 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 6, 6 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 7, 7 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 8, 8 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 9, 9 },
     .kind = 3,
     .param0 = 1,
     .param1 = 0,
     },
    {
     .msgIds = { 10, 10 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 11, 11 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 12, 12 },
     .kind = 4,
     .param0 = 1,
     .param1 = 83,
     },
    {
     .msgIds = { 13, 13 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 6, 6 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 7, 7 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 8, 8 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 9, 9 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 10, 10 },
     .kind = 4,
     .param0 = 1,
     .param1 = 92,
     },
    {
     .msgIds = { 11, 11 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 12, 12 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 6, 6 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 7, 7 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 8, 8 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 9, 9 },
     .kind = 3,
     .param0 = 1,
     .param1 = 0,
     },
    {
     .msgIds = { 10, 10 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 11, 11 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 12, 12 },
     .kind = 4,
     .param0 = 1,
     .param1 = 84,
     },
    {
     .msgIds = { 13, 13 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 6, 6 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 9, 9 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 10, 10 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 11, 11 },
     .kind = 3,
     .param0 = 1,
     .param1 = 0,
     },
    {
     .msgIds = { 12, 12 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 7, 8 },
     .kind = 5,
     .param0 = 6,
     .param1 = 16,
     },
    {
     .msgIds = { 13, 13 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 14, 14 },
     .kind = 4,
     .param0 = 1,
     .param1 = 63,
     },
    {
     .msgIds = { 15, 15 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 6, 6 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 7, 7 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 8, 8 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 9, 9 },
     .kind = 3,
     .param0 = 1,
     .param1 = 0,
     },
    {
     .msgIds = { 10, 10 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 11, 11 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 12, 12 },
     .kind = 4,
     .param0 = 1,
     .param1 = 4,
     },
    {
     .msgIds = { 13, 13 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 5, 5 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 6, 6 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 7, 7 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 8, 8 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 9, 9 },
     .kind = 3,
     .param0 = 1,
     .param1 = 0,
     },
    {
     .msgIds = { 10, 10 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 11, 11 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 6, 6 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 7, 7 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 8, 8 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 9, 9 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 10, 10 },
     .kind = 3,
     .param0 = 1,
     .param1 = 0,
     },
    {
     .msgIds = { 11, 11 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 12, 12 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 5, 5 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 6, 6 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 7, 7 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 8, 8 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 9, 9 },
     .kind = 3,
     .param0 = 1,
     .param1 = 0,
     },
    {
     .msgIds = { 10, 10 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 11, 11 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 12, 12 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 5, 5 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 6, 6 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 7, 7 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 8, 8 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 9, 9 },
     .kind = 3,
     .param0 = 1,
     .param1 = 0,
     },
    {
     .msgIds = { 10, 10 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 11, 11 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 6, 6 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 7, 7 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 8, 8 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 9, 9 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 10, 10 },
     .kind = 3,
     .param0 = 1,
     .param1 = 0,
     },
    {
     .msgIds = { 11, 11 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 12, 12 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 13, 13 },
     .kind = 4,
     .param0 = 1,
     .param1 = 149,
     },
    {
     .msgIds = { 14, 14 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 6, 6 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 7, 7 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 8, 8 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 9, 9 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 10, 10 },
     .kind = 3,
     .param0 = 1,
     .param1 = 0,
     },
    {
     .msgIds = { 11, 11 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 12, 12 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 13, 13 },
     .kind = 4,
     .param0 = 1,
     .param1 = 149,
     },
    {
     .msgIds = { 14, 14 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 5, 5 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 6, 6 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 7, 7 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 8, 8 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 9, 9 },
     .kind = 3,
     .param0 = 1,
     .param1 = 0,
     },
    {
     .msgIds = { 10, 10 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 11, 11 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 5, 5 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 6, 6 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 7, 7 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 8, 8 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 9, 9 },
     .kind = 3,
     .param0 = 1,
     .param1 = 0,
     },
    {
     .msgIds = { 10, 10 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 11, 11 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 5, 5 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 6, 6 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 7, 7 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 8, 8 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 9, 9 },
     .kind = 3,
     .param0 = 1,
     .param1 = 0,
     },
    {
     .msgIds = { 10, 10 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 11, 11 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 5, 5 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 6, 6 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 7, 7 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 8, 8 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 9, 9 },
     .kind = 3,
     .param0 = 1,
     .param1 = 0,
     },
    {
     .msgIds = { 10, 10 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 11, 11 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 6, 6 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 7, 7 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 8, 8 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 9, 9 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 10, 10 },
     .kind = 3,
     .param0 = 1,
     .param1 = 0,
     },
    {
     .msgIds = { 11, 11 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 12, 12 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 13, 13 },
     .kind = 4,
     .param0 = 1,
     .param1 = 80,
     },
    {
     .msgIds = { 14, 14 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 6, 6 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 7, 7 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 8, 8 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 9, 9 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 10, 10 },
     .kind = 3,
     .param0 = 1,
     .param1 = 0,
     },
    {
     .msgIds = { 11, 11 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 12, 12 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 13, 13 },
     .kind = 4,
     .param0 = 1,
     .param1 = 107,
     },
    {
     .msgIds = { 14, 14 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 5, 5 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 6, 6 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 7, 7 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 8, 8 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 9, 9 },
     .kind = 3,
     .param0 = 1,
     .param1 = 0,
     },
    {
     .msgIds = { 10, 10 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 11, 11 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 5, 5 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 6, 6 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 7, 7 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 8, 8 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 9, 9 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 10, 10 },
     .kind = 3,
     .param0 = 1,
     .param1 = 0,
     },
    {
     .msgIds = { 11, 11 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 12, 12 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 5, 5 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 6, 6 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 17, 17 },
     .kind = 3,
     .param0 = 1,
     .param1 = 0,
     },
    {
     .msgIds = { 18, 18 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 19, 19 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 6, 6 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 7, 7 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 8, 8 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 9, 9 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 10, 10 },
     .kind = 3,
     .param0 = 1,
     .param1 = 0,
     },
    {
     .msgIds = { 11, 11 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 12, 12 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 13, 13 },
     .kind = 4,
     .param0 = 1,
     .param1 = 110,
     },
    {
     .msgIds = { 14, 14 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 6, 6 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 7, 7 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 8, 8 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 9, 9 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 10, 10 },
     .kind = 3,
     .param0 = 1,
     .param1 = 0,
     },
    {
     .msgIds = { 11, 11 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 12, 12 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 13, 13 },
     .kind = 4,
     .param0 = 1,
     .param1 = 108,
     },
    {
     .msgIds = { 14, 14 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 6, 6 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 7, 7 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 8, 8 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 9, 9 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 10, 10 },
     .kind = 3,
     .param0 = 1,
     .param1 = 0,
     },
    {
     .msgIds = { 11, 11 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 12, 12 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 13, 13 },
     .kind = 4,
     .param0 = 1,
     .param1 = 109,
     },
    {
     .msgIds = { 14, 14 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 5, 5 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 6, 6 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 7, 7 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 8, 8 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 9, 9 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 10, 10 },
     .kind = 3,
     .param0 = 1,
     .param1 = 0,
     },
    {
     .msgIds = { 11, 11 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
    {
     .msgIds = { 12, 12 },
     .kind = 0,
     .param0 = 0,
     .param1 = 0,
     },
};
