otherpoke_index_ncgr += {
    '0150' : files('altered/back.png'),
    '0151' : files('altered/front.png'),
    '0152' : files('origin/back.png'),
    '0153' : files('origin/front.png'),
}

otherpoke_index_nclr += {
    '248' : files('altered/front.png'),
    '249' : files('altered/back.png'),
    '250' : files('origin/front.png'),
    '251' : files('origin/back.png'),
}