mmodel_json = files(
    'mmodel_00000280.json',
    'mmodel_00000281.json',
    'mmodel_00000282.json',
    'mmodel_00000283.json',
    'mmodel_00000284.json',
    'mmodel_00000285.json',
    'mmodel_00000286.json',
    'mmodel_00000287.json',
    'mmodel_00000288.json',
    'mmodel_00000289.json',
    'mmodel_00000290.json',
    'mmodel_00000291.json',
    'mmodel_00000292.json',
    'mmodel_00000293.json',
    'mmodel_00000294.json',
    'mmodel_00000295.json',
    'mmodel_00000296.json',
)

mmodel_nsbtx = copy_gen.process(files(
    'mmodel_00000000.NSBTX',
    'mmodel_00000001.NSBTX',
    'mmodel_00000002.NSBTX',
    'mmodel_00000003.NSBTX',
    'mmodel_00000004.NSBTX',
    'mmodel_00000005.NSBTX',
    'mmodel_00000006.NSBTX',
    'mmodel_00000007.NSBTX',
    'mmodel_00000008.NSBTX',
    'mmodel_00000009.NSBTX',
    'mmodel_00000010.NSBTX',
    'mmodel_00000011.NSBTX',
    'mmodel_00000012.NSBTX',
    'mmodel_00000013.NSBTX',
    'mmodel_00000014.NSBTX',
    'mmodel_00000015.NSBTX',
    'mmodel_00000016.NSBTX',
    'mmodel_00000017.NSBTX',
    'mmodel_00000018.NSBTX',
    'mmodel_00000019.NSBTX',
    'mmodel_00000020.NSBTX',
    'mmodel_00000021.NSBTX',
    'mmodel_00000022.NSBTX',
    'mmodel_00000023.NSBTX',
    'mmodel_00000024.NSBTX',
    'mmodel_00000025.NSBTX',
    'mmodel_00000026.NSBTX',
    'mmodel_00000027.NSBTX',
    'mmodel_00000028.NSBTX',
    'mmodel_00000029.NSBTX',
    'mmodel_00000030.NSBTX',
    'mmodel_00000031.NSBTX',
    'mmodel_00000032.NSBTX',
    'mmodel_00000033.NSBTX',
    'mmodel_00000034.NSBTX',
    'mmodel_00000035.NSBTX',
    'mmodel_00000036.NSBTX',
    'mmodel_00000037.NSBTX',
    'mmodel_00000038.NSBTX',
    'mmodel_00000039.NSBTX',
    'mmodel_00000040.NSBTX',
    'mmodel_00000041.NSBTX',
    'mmodel_00000042.NSBTX',
    'mmodel_00000043.NSBTX',
    'mmodel_00000044.NSBTX',
    'mmodel_00000045.NSBTX',
    'mmodel_00000046.NSBTX',
    'mmodel_00000047.NSBTX',
    'mmodel_00000048.NSBTX',
    'mmodel_00000049.NSBTX',
    'mmodel_00000050.NSBTX',
    'mmodel_00000051.NSBTX',
    'mmodel_00000052.NSBTX',
    'mmodel_00000053.NSBTX',
    'mmodel_00000054.NSBTX',
    'mmodel_00000055.NSBTX',
    'mmodel_00000056.NSBTX',
    'mmodel_00000057.NSBTX',
    'mmodel_00000058.NSBTX',
    'mmodel_00000059.NSBTX',
    'mmodel_00000060.NSBTX',
    'mmodel_00000061.NSBTX',
    'mmodel_00000062.NSBTX',
    'mmodel_00000063.NSBTX',
    'mmodel_00000064.NSBTX',
    'mmodel_00000065.NSBTX',
    'mmodel_00000066.NSBTX',
    'mmodel_00000067.NSBTX',
    'mmodel_00000068.NSBTX',
    'mmodel_00000069.NSBTX',
    'mmodel_00000070.NSBTX',
    'mmodel_00000071.NSBTX',
    'mmodel_00000072.NSBTX',
    'mmodel_00000073.NSBTX',
    'mmodel_00000074.NSBTX',
    'mmodel_00000075.NSBTX',
    'mmodel_00000076.NSBTX',
    'mmodel_00000077.NSBTX',
    'mmodel_00000078.NSBTX',
    'mmodel_00000079.NSBTX',
    'mmodel_00000080.NSBTX',
    'mmodel_00000081.NSBTX',
    'mmodel_00000082.NSBTX',
    'mmodel_00000083.NSBTX',
    'mmodel_00000084.NSBTX',
    'mmodel_00000085.NSBTX',
    'mmodel_00000086.NSBTX',
    'mmodel_00000087.NSBTX',
    'mmodel_00000088.NSBTX',
    'mmodel_00000089.NSBTX',
    'mmodel_00000090.NSBTX',
    'mmodel_00000091.NSBTX',
    'mmodel_00000092.NSBTX',
    'mmodel_00000093.NSBTX',
    'mmodel_00000094.NSBTX',
    'mmodel_00000095.NSBTX',
    'mmodel_00000096.NSBTX',
    'mmodel_00000097.NSBTX',
    'mmodel_00000098.NSBTX',
    'mmodel_00000099.NSBTX',
    'mmodel_00000100.NSBTX',
    'mmodel_00000101.NSBTX',
    'mmodel_00000102.NSBTX',
    'mmodel_00000103.NSBTX',
    'mmodel_00000104.NSBTX',
    'mmodel_00000105.NSBTX',
    'mmodel_00000106.NSBTX',
    'mmodel_00000107.NSBTX',
    'mmodel_00000108.NSBTX',
    'mmodel_00000109.NSBTX',
    'mmodel_00000110.NSBTX',
    'mmodel_00000111.NSBTX',
    'mmodel_00000112.NSBTX',
    'mmodel_00000113.NSBTX',
    'mmodel_00000114.NSBTX',
    'mmodel_00000115.NSBTX',
    'mmodel_00000116.NSBTX',
    'mmodel_00000117.NSBTX',
    'mmodel_00000118.NSBTX',
    'mmodel_00000119.NSBTX',
    'mmodel_00000120.NSBTX',
    'mmodel_00000121.NSBTX',
    'mmodel_00000122.NSBTX',
    'mmodel_00000123.NSBTX',
    'mmodel_00000124.NSBTX',
    'mmodel_00000125.NSBTX',
    'mmodel_00000126.NSBTX',
    'mmodel_00000127.NSBTX',
    'mmodel_00000128.NSBTX',
    'mmodel_00000129.NSBTX',
    'mmodel_00000130.NSBTX',
    'mmodel_00000131.NSBTX',
    'mmodel_00000132.NSBTX',
    'mmodel_00000133.NSBTX',
    'mmodel_00000134.NSBTX',
    'mmodel_00000135.NSBTX',
    'mmodel_00000136.NSBTX',
    'mmodel_00000137.NSBTX',
    'mmodel_00000138.NSBTX',
    'mmodel_00000139.NSBTX',
    'mmodel_00000140.NSBTX',
    'mmodel_00000141.NSBTX',
    'mmodel_00000142.NSBTX',
    'mmodel_00000143.NSBTX',
    'mmodel_00000144.NSBTX',
    'mmodel_00000145.NSBTX',
    'mmodel_00000146.NSBTX',
    'mmodel_00000147.NSBTX',
    'mmodel_00000148.NSBTX',
    'mmodel_00000149.NSBTX',
    'mmodel_00000150.NSBTX',
    'mmodel_00000151.NSBTX',
    'mmodel_00000152.NSBTX',
    'mmodel_00000153.NSBTX',
    'mmodel_00000154.NSBTX',
    'mmodel_00000155.NSBTX',
    'mmodel_00000156.NSBTX',
    'mmodel_00000157.NSBTX',
    'mmodel_00000158.NSBTX',
    'mmodel_00000159.NSBTX',
    'mmodel_00000160.NSBTX',
    'mmodel_00000161.NSBTX',
    'mmodel_00000162.NSBTX',
    'mmodel_00000163.NSBTX',
    'mmodel_00000164.NSBTX',
    'mmodel_00000165.NSBTX',
    'mmodel_00000166.NSBTX',
    'mmodel_00000167.NSBTX',
    'mmodel_00000168.NSBTX',
    'mmodel_00000169.NSBTX',
    'mmodel_00000170.NSBTX',
    'mmodel_00000171.NSBTX',
    'mmodel_00000172.NSBTX',
    'mmodel_00000173.NSBTX',
    'mmodel_00000174.NSBTX',
    'mmodel_00000175.NSBTX',
    'mmodel_00000176.NSBTX',
    'mmodel_00000177.NSBTX',
    'mmodel_00000178.NSBTX',
    'mmodel_00000179.NSBTX',
    'mmodel_00000180.NSBTX',
    'mmodel_00000181.NSBTX',
    'mmodel_00000182.NSBTX',
    'mmodel_00000183.NSBTX',
    'mmodel_00000184.NSBTX',
    'mmodel_00000185.NSBTX',
    'mmodel_00000186.NSBTX',
    'mmodel_00000187.NSBTX',
    'mmodel_00000188.NSBTX',
    'mmodel_00000189.NSBTX',
    'mmodel_00000190.NSBTX',
    'mmodel_00000191.NSBTX',
    'mmodel_00000192.NSBTX',
    'mmodel_00000193.NSBTX',
    'mmodel_00000194.NSBTX',
    'mmodel_00000195.NSBTX',
    'mmodel_00000196.NSBTX',
    'mmodel_00000197.NSBTX',
    'mmodel_00000198.NSBTX',
    'mmodel_00000199.NSBTX',
    'mmodel_00000200.NSBTX',
    'mmodel_00000201.NSBTX',
    'mmodel_00000202.NSBTX',
    'mmodel_00000203.NSBTX',
    'mmodel_00000204.NSBTX',
    'mmodel_00000205.NSBTX',
    'mmodel_00000206.NSBTX',
    'mmodel_00000207.NSBTX',
    'mmodel_00000208.NSBTX',
    'mmodel_00000209.NSBTX',
    'mmodel_00000210.NSBTX',
    'mmodel_00000211.NSBTX',
    'mmodel_00000212.NSBTX',
    'mmodel_00000213.NSBTX',
    'mmodel_00000214.NSBTX',
    'mmodel_00000215.NSBTX',
    'mmodel_00000216.NSBTX',
    'mmodel_00000217.NSBTX',
    'mmodel_00000218.NSBTX',
    'mmodel_00000219.NSBTX',
    'mmodel_00000220.NSBTX',
    'mmodel_00000221.NSBTX',
    'mmodel_00000222.NSBTX',
    'mmodel_00000223.NSBTX',
    'mmodel_00000224.NSBTX',
    'mmodel_00000225.NSBTX',
    'mmodel_00000226.NSBTX',
    'mmodel_00000227.NSBTX',
    'mmodel_00000228.NSBTX',
    'mmodel_00000229.NSBTX',
    'mmodel_00000230.NSBTX',
    'mmodel_00000231.NSBTX',
    'mmodel_00000232.NSBTX',
    'mmodel_00000233.NSBTX',
    'mmodel_00000234.NSBTX',
    'mmodel_00000235.NSBTX',
    'mmodel_00000236.NSBTX',
    'mmodel_00000237.NSBTX',
    'mmodel_00000238.NSBTX',
    'mmodel_00000239.NSBTX',
    'mmodel_00000240.NSBTX',
    'mmodel_00000241.NSBTX',
    'mmodel_00000242.NSBTX',
    'mmodel_00000243.NSBTX',
    'mmodel_00000244.NSBTX',
    'mmodel_00000245.NSBTX',
    'mmodel_00000246.NSBTX',
    'mmodel_00000247.NSBTX',
    'mmodel_00000248.NSBTX',
    'mmodel_00000249.NSBTX',
    'mmodel_00000250.NSBTX',
    'mmodel_00000251.NSBTX',
    'mmodel_00000252.NSBTX',
    'mmodel_00000253.NSBTX',
    'mmodel_00000254.NSBTX',
    'mmodel_00000255.NSBTX',
    'mmodel_00000256.NSBTX',
    'mmodel_00000257.NSBTX',
    'mmodel_00000258.NSBTX',
    'mmodel_00000259.NSBTX',
    'mmodel_00000260.NSBTX',
    'mmodel_00000261.NSBTX',
    'mmodel_00000262.NSBTX',
    'mmodel_00000263.NSBTX',
    'mmodel_00000264.NSBTX',
    'mmodel_00000265.NSBTX',
    'mmodel_00000297.NSBTX',
    'mmodel_00000298.NSBTX',
    'mmodel_00000299.NSBTX',
    'mmodel_00000300.NSBTX',
    'mmodel_00000301.NSBTX',
    'mmodel_00000302.NSBTX',
    'mmodel_00000303.NSBTX',
    'mmodel_00000304.NSBTX',
    'mmodel_00000305.NSBTX',
    'mmodel_00000306.NSBTX',
    'mmodel_00000307.NSBTX',
    'mmodel_00000308.NSBTX',
    'mmodel_00000309.NSBTX',
    'mmodel_00000310.NSBTX',
    'mmodel_00000311.NSBTX',
    'mmodel_00000312.NSBTX',
    'mmodel_00000313.NSBTX',
    'mmodel_00000314.NSBTX',
    'mmodel_00000315.NSBTX',
    'mmodel_00000316.NSBTX',
    'mmodel_00000317.NSBTX',
    'mmodel_00000318.NSBTX',
    'mmodel_00000319.NSBTX',
    'mmodel_00000320.NSBTX',
    'mmodel_00000321.NSBTX',
    'mmodel_00000322.NSBTX',
    'mmodel_00000323.NSBTX',
    'mmodel_00000324.NSBTX',
    'mmodel_00000325.NSBTX',
    'mmodel_00000326.NSBTX',
    'mmodel_00000327.NSBTX',
    'mmodel_00000328.NSBTX',
    'mmodel_00000329.NSBTX',
    'mmodel_00000330.NSBTX',
    'mmodel_00000331.NSBTX',
    'mmodel_00000332.NSBTX',
    'mmodel_00000333.NSBTX',
    'mmodel_00000334.NSBTX',
    'mmodel_00000335.NSBTX',
    'mmodel_00000336.NSBTX',
    'mmodel_00000337.NSBTX',
    'mmodel_00000338.NSBTX',
    'mmodel_00000339.NSBTX',
    'mmodel_00000340.NSBTX',
    'mmodel_00000341.NSBTX',
    'mmodel_00000342.NSBTX',
    'mmodel_00000343.NSBTX',
    'mmodel_00000344.NSBTX',
    'mmodel_00000345.NSBTX',
    'mmodel_00000346.NSBTX',
    'mmodel_00000347.NSBTX',
    'mmodel_00000348.NSBTX',
    'mmodel_00000349.NSBTX',
    'mmodel_00000350.NSBTX',
    'mmodel_00000351.NSBTX',
    'mmodel_00000352.NSBTX',
    'mmodel_00000353.NSBTX',
    'mmodel_00000354.NSBTX',
    'mmodel_00000355.NSBTX',
    'mmodel_00000356.NSBTX',
    'mmodel_00000357.NSBTX',
    'mmodel_00000358.NSBTX',
    'mmodel_00000359.NSBTX',
    'mmodel_00000360.NSBTX',
    'mmodel_00000361.NSBTX',
    'mmodel_00000362.NSBTX',
    'mmodel_00000363.NSBTX',
    'mmodel_00000364.NSBTX',
    'mmodel_00000365.NSBTX',
    'mmodel_00000366.NSBTX',
    'mmodel_00000367.NSBTX',
    'mmodel_00000368.NSBTX',
    'mmodel_00000369.NSBTX',
    'mmodel_00000370.NSBTX',
    'mmodel_00000371.NSBTX',
    'mmodel_00000372.NSBTX',
    'mmodel_00000373.NSBTX',
    'mmodel_00000374.NSBTX',
    'mmodel_00000375.NSBTX',
    'mmodel_00000376.NSBTX',
    'mmodel_00000377.NSBTX',
    'mmodel_00000378.NSBTX',
    'mmodel_00000379.NSBTX',
    'mmodel_00000380.NSBTX',
    'mmodel_00000381.NSBTX',
    'mmodel_00000382.NSBTX',
    'mmodel_00000383.NSBTX',
    'mmodel_00000384.NSBTX',
    'mmodel_00000385.NSBTX',
    'mmodel_00000386.NSBTX',
    'mmodel_00000387.NSBTX',
    'mmodel_00000388.NSBTX',
    'mmodel_00000389.NSBTX',
    'mmodel_00000390.NSBTX',
    'mmodel_00000391.NSBTX',
    'mmodel_00000392.NSBTX',
    'mmodel_00000393.NSBTX',
    'mmodel_00000394.NSBTX',
    'mmodel_00000395.NSBTX',
    'mmodel_00000396.NSBTX',
    'mmodel_00000397.NSBTX',
    'mmodel_00000398.NSBTX',
    'mmodel_00000399.NSBTX',
    'mmodel_00000400.NSBTX',
    'mmodel_00000401.NSBTX',
    'mmodel_00000402.NSBTX',
    'mmodel_00000403.NSBTX',
    'mmodel_00000404.NSBTX',
    'mmodel_00000405.NSBTX',
    'mmodel_00000406.NSBTX',
    'mmodel_00000407.NSBTX',
    'mmodel_00000408.NSBTX',
    'mmodel_00000409.NSBTX',
    'mmodel_00000410.NSBTX',
    'mmodel_00000411.NSBTX',
    'mmodel_00000412.NSBTX',
    'mmodel_00000413.NSBTX',
    'mmodel_00000414.NSBTX',
    'mmodel_00000415.NSBTX',
    'mmodel_00000416.NSBTX',
    'mmodel_00000417.NSBTX',
    'mmodel_00000418.NSBTX',
    'mmodel_00000419.NSBTX',
    'mmodel_00000420.NSBTX',
    'mmodel_00000421.NSBTX',
    'mmodel_00000422.NSBTX',
    'mmodel_00000423.NSBTX',
    'mmodel_00000424.NSBTX',
    'mmodel_00000425.NSBTX',
    'mmodel_00000426.NSBTX',
    'mmodel_00000427.NSBTX',
    'mmodel_00000428.NSBTX',
    'mmodel_00000429.NSBTX',
    'mmodel_00000430.NSBTX',
    'mmodel_00000431.NSBTX',
    'mmodel_00000432.NSBTX',
    'mmodel_00000433.NSBTX',
    'mmodel_00000434.NSBTX',
    'mmodel_00000435.NSBTX',
    'mmodel_00000436.NSBTX',
    'mmodel_00000437.NSBTX',
    'mmodel_00000438.NSBTX',
    'mmodel_00000439.NSBTX',
    'mmodel_00000440.NSBTX',
    'mmodel_00000441.NSBTX',
    'mmodel_00000442.NSBTX',
    'mmodel_00000443.NSBTX',
    'mmodel_00000444.NSBTX',
    'mmodel_00000445.NSBTX',
    'mmodel_00000446.NSBTX',
    'mmodel_00000447.NSBTX',
    'mmodel_00000448.NSBTX',
    'mmodel_00000449.NSBTX',
    'mmodel_00000450.NSBTX',
    'mmodel_00000451.NSBTX',
    'mmodel_00000452.NSBTX',
    'mmodel_00000453.NSBTX',
    'mmodel_00000454.NSBTX',
    'mmodel_00000455.NSBTX',
    'mmodel_00000456.NSBTX',
    'mmodel_00000457.NSBTX',
    'mmodel_00000458.NSBTX',
    'mmodel_00000459.NSBTX',
    'mmodel_00000460.NSBTX',
    'mmodel_00000461.NSBTX',
    'mmodel_00000462.NSBTX',
    'mmodel_00000463.NSBTX',
    'mmodel_00000464.NSBTX',
    'mmodel_00000465.NSBTX',
    'mmodel_00000466.NSBTX',
    'mmodel_00000467.NSBTX',
    'mmodel_00000468.NSBTX',
    'mmodel_00000469.NSBTX',
    'mmodel_00000470.NSBTX',
    'mmodel_00000471.NSBTX',
    'mmodel_00000472.NSBTX',
    'mmodel_00000473.NSBTX',
    'mmodel_00000474.NSBTX',
    'mmodel_00000475.NSBTX',
    'mmodel_00000476.NSBTX',
    'mmodel_00000477.NSBTX',
    'mmodel_00000478.NSBTX',
    'mmodel_00000479.NSBTX',
    'mmodel_00000480.NSBTX',
    'mmodel_00000481.NSBTX',
    'mmodel_00000482.NSBTX',
    'mmodel_00000483.NSBTX',
    'mmodel_00000484.NSBTX',
    'mmodel_00000485.NSBTX',
    'mmodel_00000486.NSBTX',
    'mmodel_00000487.NSBTX',
    'mmodel_00000488.NSBTX',
    'mmodel_00000489.NSBTX',
    'mmodel_00000490.NSBTX',
    'mmodel_00000491.NSBTX',
    'mmodel_00000492.NSBTX',
    'mmodel_00000493.NSBTX',
    'mmodel_00000494.NSBTX',
    'mmodel_00000495.NSBTX',
    'mmodel_00000496.NSBTX',
    'mmodel_00000497.NSBTX',
    'mmodel_00000498.NSBTX',
    'mmodel_00000499.NSBTX',
    'mmodel_00000500.NSBTX',
    'mmodel_00000501.NSBTX',
    'mmodel_00000502.NSBTX',
    'mmodel_00000503.NSBTX',
    'mmodel_00000504.NSBTX',
    'mmodel_00000505.NSBTX',
    'mmodel_00000506.NSBTX',
    'mmodel_00000507.NSBTX',
    'mmodel_00000508.NSBTX',
    'mmodel_00000509.NSBTX',
    'mmodel_00000510.NSBTX',
    'mmodel_00000511.NSBTX',
    'mmodel_00000512.NSBTX',
    'mmodel_00000513.NSBTX',
    'mmodel_00000514.NSBTX',
    'mmodel_00000515.NSBTX',
    'mmodel_00000516.NSBTX',
    'mmodel_00000517.NSBTX',
    'mmodel_00000518.NSBTX',
    'mmodel_00000519.NSBTX',
    'mmodel_00000520.NSBTX',
    'mmodel_00000521.NSBTX',
    'mmodel_00000522.NSBTX',
    'mmodel_00000523.NSBTX',
    'mmodel_00000524.NSBTX',
    'mmodel_00000525.NSBTX',
    'mmodel_00000526.NSBTX',
    'mmodel_00000527.NSBTX',
    'mmodel_00000528.NSBTX',
    'mmodel_00000529.NSBTX',
    'mmodel_00000530.NSBTX',
    'mmodel_00000531.NSBTX',
    'mmodel_00000532.NSBTX',
    'mmodel_00000533.NSBTX',
    'mmodel_00000534.NSBTX',
    'mmodel_00000535.NSBTX',
    'mmodel_00000536.NSBTX',
    'mmodel_00000537.NSBTX',
    'mmodel_00000538.NSBTX',
    'mmodel_00000539.NSBTX',
    'mmodel_00000540.NSBTX',
    'mmodel_00000541.NSBTX',
    'mmodel_00000542.NSBTX',
    'mmodel_00000543.NSBTX',
    'mmodel_00000544.NSBTX',
    'mmodel_00000545.NSBTX',
    'mmodel_00000546.NSBTX',
    'mmodel_00000547.NSBTX',
    'mmodel_00000548.NSBTX',
    'mmodel_00000549.NSBTX',
    'mmodel_00000550.NSBTX',
    'mmodel_00000551.NSBTX',
    'mmodel_00000552.NSBTX',
    'mmodel_00000553.NSBTX',
    'mmodel_00000554.NSBTX',
    'mmodel_00000555.NSBTX',
    'mmodel_00000556.NSBTX',
    'mmodel_00000557.NSBTX',
    'mmodel_00000558.NSBTX',
    'mmodel_00000559.NSBTX',
    'mmodel_00000560.NSBTX',
    'mmodel_00000561.NSBTX',
    'mmodel_00000562.NSBTX',
    'mmodel_00000563.NSBTX',
    'mmodel_00000564.NSBTX',
    'mmodel_00000565.NSBTX',
    'mmodel_00000566.NSBTX',
    'mmodel_00000567.NSBTX',
    'mmodel_00000568.NSBTX',
    'mmodel_00000569.NSBTX',
    'mmodel_00000570.NSBTX',
    'mmodel_00000571.NSBTX',
    'mmodel_00000572.NSBTX',
    'mmodel_00000573.NSBTX',
    'mmodel_00000574.NSBTX',
    'mmodel_00000575.NSBTX',
    'mmodel_00000576.NSBTX',
    'mmodel_00000577.NSBTX',
    'mmodel_00000578.NSBTX',
    'mmodel_00000579.NSBTX',
    'mmodel_00000580.NSBTX',
    'mmodel_00000581.NSBTX',
    'mmodel_00000582.NSBTX',
    'mmodel_00000583.NSBTX',
    'mmodel_00000584.NSBTX',
    'mmodel_00000585.NSBTX',
    'mmodel_00000586.NSBTX',
    'mmodel_00000587.NSBTX',
    'mmodel_00000588.NSBTX',
    'mmodel_00000589.NSBTX',
    'mmodel_00000590.NSBTX',
    'mmodel_00000591.NSBTX',
    'mmodel_00000592.NSBTX',
    'mmodel_00000593.NSBTX',
    'mmodel_00000594.NSBTX',
    'mmodel_00000595.NSBTX',
    'mmodel_00000596.NSBTX',
    'mmodel_00000597.NSBTX',
    'mmodel_00000598.NSBTX',
    'mmodel_00000599.NSBTX',
    'mmodel_00000600.NSBTX',
    'mmodel_00000601.NSBTX',
    'mmodel_00000602.NSBTX',
    'mmodel_00000603.NSBTX',
    'mmodel_00000604.NSBTX',
    'mmodel_00000605.NSBTX',
    'mmodel_00000606.NSBTX',
    'mmodel_00000607.NSBTX',
    'mmodel_00000608.NSBTX',
    'mmodel_00000609.NSBTX',
    'mmodel_00000610.NSBTX',
    'mmodel_00000611.NSBTX',
    'mmodel_00000612.NSBTX',
    'mmodel_00000613.NSBTX',
    'mmodel_00000614.NSBTX',
    'mmodel_00000615.NSBTX',
    'mmodel_00000616.NSBTX',
    'mmodel_00000617.NSBTX',
    'mmodel_00000618.NSBTX',
    'mmodel_00000619.NSBTX',
    'mmodel_00000620.NSBTX',
    'mmodel_00000621.NSBTX',
    'mmodel_00000622.NSBTX',
    'mmodel_00000623.NSBTX',
    'mmodel_00000624.NSBTX',
    'mmodel_00000625.NSBTX',
    'mmodel_00000626.NSBTX',
    'mmodel_00000627.NSBTX',
    'mmodel_00000628.NSBTX',
    'mmodel_00000629.NSBTX',
    'mmodel_00000630.NSBTX',
    'mmodel_00000631.NSBTX',
    'mmodel_00000632.NSBTX',
    'mmodel_00000633.NSBTX',
    'mmodel_00000634.NSBTX',
    'mmodel_00000635.NSBTX',
    'mmodel_00000636.NSBTX',
    'mmodel_00000637.NSBTX',
    'mmodel_00000638.NSBTX',
    'mmodel_00000639.NSBTX',
    'mmodel_00000640.NSBTX',
    'mmodel_00000641.NSBTX',
    'mmodel_00000642.NSBTX',
    'mmodel_00000643.NSBTX',
    'mmodel_00000644.NSBTX',
    'mmodel_00000645.NSBTX',
    'mmodel_00000646.NSBTX',
    'mmodel_00000647.NSBTX',
    'mmodel_00000648.NSBTX',
    'mmodel_00000649.NSBTX',
    'mmodel_00000650.NSBTX',
    'mmodel_00000651.NSBTX',
    'mmodel_00000652.NSBTX',
    'mmodel_00000653.NSBTX',
    'mmodel_00000654.NSBTX',
    'mmodel_00000655.NSBTX',
    'mmodel_00000656.NSBTX',
    'mmodel_00000657.NSBTX',
    'mmodel_00000658.NSBTX',
    'mmodel_00000659.NSBTX',
    'mmodel_00000660.NSBTX',
    'mmodel_00000661.NSBTX',
    'mmodel_00000662.NSBTX',
    'mmodel_00000663.NSBTX',
    'mmodel_00000664.NSBTX',
    'mmodel_00000665.NSBTX',
    'mmodel_00000666.NSBTX',
    'mmodel_00000667.NSBTX',
    'mmodel_00000668.NSBTX',
    'mmodel_00000669.NSBTX',
    'mmodel_00000670.NSBTX',
    'mmodel_00000671.NSBTX',
    'mmodel_00000672.NSBTX',
    'mmodel_00000673.NSBTX',
    'mmodel_00000674.NSBTX',
    'mmodel_00000675.NSBTX',
    'mmodel_00000676.NSBTX',
    'mmodel_00000677.NSBTX',
    'mmodel_00000678.NSBTX',
    'mmodel_00000679.NSBTX',
    'mmodel_00000680.NSBTX',
    'mmodel_00000681.NSBTX',
    'mmodel_00000682.NSBTX',
    'mmodel_00000683.NSBTX',
    'mmodel_00000684.NSBTX',
    'mmodel_00000685.NSBTX',
    'mmodel_00000686.NSBTX',
    'mmodel_00000687.NSBTX',
    'mmodel_00000688.NSBTX',
    'mmodel_00000689.NSBTX',
    'mmodel_00000690.NSBTX',
    'mmodel_00000691.NSBTX',
    'mmodel_00000692.NSBTX',
    'mmodel_00000693.NSBTX',
    'mmodel_00000694.NSBTX',
    'mmodel_00000695.NSBTX',
    'mmodel_00000696.NSBTX',
    'mmodel_00000697.NSBTX',
    'mmodel_00000698.NSBTX',
    'mmodel_00000699.NSBTX',
    'mmodel_00000700.NSBTX',
    'mmodel_00000701.NSBTX',
    'mmodel_00000702.NSBTX',
    'mmodel_00000703.NSBTX',
    'mmodel_00000704.NSBTX',
    'mmodel_00000705.NSBTX',
    'mmodel_00000706.NSBTX',
    'mmodel_00000707.NSBTX',
    'mmodel_00000708.NSBTX',
    'mmodel_00000709.NSBTX',
    'mmodel_00000710.NSBTX',
    'mmodel_00000711.NSBTX',
    'mmodel_00000712.NSBTX',
    'mmodel_00000713.NSBTX',
    'mmodel_00000714.NSBTX',
    'mmodel_00000715.NSBTX',
    'mmodel_00000716.NSBTX',
    'mmodel_00000717.NSBTX',
    'mmodel_00000718.NSBTX',
    'mmodel_00000719.NSBTX',
    'mmodel_00000720.NSBTX',
    'mmodel_00000721.NSBTX',
    'mmodel_00000722.NSBTX',
    'mmodel_00000723.NSBTX',
    'mmodel_00000724.NSBTX',
    'mmodel_00000725.NSBTX',
    'mmodel_00000726.NSBTX',
    'mmodel_00000727.NSBTX',
    'mmodel_00000728.NSBTX',
    'mmodel_00000729.NSBTX',
    'mmodel_00000730.NSBTX',
    'mmodel_00000731.NSBTX',
    'mmodel_00000732.NSBTX',
    'mmodel_00000733.NSBTX',
    'mmodel_00000734.NSBTX',
    'mmodel_00000735.NSBTX',
    'mmodel_00000736.NSBTX',
    'mmodel_00000737.NSBTX',
    'mmodel_00000738.NSBTX',
    'mmodel_00000739.NSBTX',
    'mmodel_00000740.NSBTX',
    'mmodel_00000741.NSBTX',
    'mmodel_00000742.NSBTX',
    'mmodel_00000743.NSBTX',
    'mmodel_00000744.NSBTX',
    'mmodel_00000745.NSBTX',
    'mmodel_00000746.NSBTX',
    'mmodel_00000747.NSBTX',
    'mmodel_00000748.NSBTX',
    'mmodel_00000749.NSBTX',
    'mmodel_00000750.NSBTX',
    'mmodel_00000751.NSBTX',
    'mmodel_00000752.NSBTX',
    'mmodel_00000753.NSBTX',
    'mmodel_00000754.NSBTX',
    'mmodel_00000755.NSBTX',
    'mmodel_00000756.NSBTX',
    'mmodel_00000757.NSBTX',
    'mmodel_00000758.NSBTX',
    'mmodel_00000759.NSBTX',
    'mmodel_00000760.NSBTX',
    'mmodel_00000761.NSBTX',
    'mmodel_00000762.NSBTX',
    'mmodel_00000763.NSBTX',
    'mmodel_00000764.NSBTX',
    'mmodel_00000765.NSBTX',
    'mmodel_00000766.NSBTX',
    'mmodel_00000767.NSBTX',
    'mmodel_00000768.NSBTX',
    'mmodel_00000769.NSBTX',
    'mmodel_00000770.NSBTX',
    'mmodel_00000771.NSBTX',
    'mmodel_00000772.NSBTX',
    'mmodel_00000773.NSBTX',
    'mmodel_00000774.NSBTX',
    'mmodel_00000775.NSBTX',
    'mmodel_00000776.NSBTX',
    'mmodel_00000777.NSBTX',
    'mmodel_00000778.NSBTX',
    'mmodel_00000779.NSBTX',
    'mmodel_00000780.NSBTX',
    'mmodel_00000781.NSBTX',
    'mmodel_00000782.NSBTX',
    'mmodel_00000783.NSBTX',
    'mmodel_00000784.NSBTX',
    'mmodel_00000785.NSBTX',
    'mmodel_00000786.NSBTX',
    'mmodel_00000787.NSBTX',
    'mmodel_00000788.NSBTX',
    'mmodel_00000789.NSBTX',
    'mmodel_00000790.NSBTX',
    'mmodel_00000791.NSBTX',
    'mmodel_00000792.NSBTX',
    'mmodel_00000793.NSBTX',
    'mmodel_00000794.NSBTX',
    'mmodel_00000795.NSBTX',
    'mmodel_00000796.NSBTX',
    'mmodel_00000797.NSBTX',
    'mmodel_00000798.NSBTX',
    'mmodel_00000799.NSBTX',
    'mmodel_00000800.NSBTX',
    'mmodel_00000801.NSBTX',
    'mmodel_00000802.NSBTX',
    'mmodel_00000803.NSBTX',
    'mmodel_00000804.NSBTX',
    'mmodel_00000805.NSBTX',
    'mmodel_00000806.NSBTX',
    'mmodel_00000807.NSBTX',
    'mmodel_00000808.NSBTX',
    'mmodel_00000809.NSBTX',
    'mmodel_00000810.NSBTX',
    'mmodel_00000811.NSBTX',
    'mmodel_00000812.NSBTX',
    'mmodel_00000813.NSBTX',
    'mmodel_00000814.NSBTX',
    'mmodel_00000815.NSBTX',
    'mmodel_00000816.NSBTX',
    'mmodel_00000817.NSBTX',
    'mmodel_00000818.NSBTX',
    'mmodel_00000819.NSBTX',
    'mmodel_00000820.NSBTX',
    'mmodel_00000821.NSBTX',
    'mmodel_00000822.NSBTX',
    'mmodel_00000823.NSBTX',
    'mmodel_00000824.NSBTX',
    'mmodel_00000825.NSBTX',
    'mmodel_00000826.NSBTX',
    'mmodel_00000827.NSBTX',
    'mmodel_00000828.NSBTX',
    'mmodel_00000829.NSBTX',
    'mmodel_00000830.NSBTX',
    'mmodel_00000831.NSBTX',
    'mmodel_00000832.NSBTX',
    'mmodel_00000833.NSBTX',
    'mmodel_00000834.NSBTX',
    'mmodel_00000835.NSBTX',
    'mmodel_00000836.NSBTX',
    'mmodel_00000837.NSBTX',
    'mmodel_00000838.NSBTX',
    'mmodel_00000839.NSBTX',
    'mmodel_00000840.NSBTX',
    'mmodel_00000841.NSBTX',
    'mmodel_00000842.NSBTX',
    'mmodel_00000843.NSBTX',
    'mmodel_00000844.NSBTX',
    'mmodel_00000845.NSBTX',
    'mmodel_00000846.NSBTX',
    'mmodel_00000847.NSBTX',
    'mmodel_00000848.NSBTX',
    'mmodel_00000849.NSBTX',
    'mmodel_00000850.NSBTX',
    'mmodel_00000851.NSBTX',
    'mmodel_00000852.NSBTX',
    'mmodel_00000853.NSBTX',
    'mmodel_00000854.NSBTX',
    'mmodel_00000855.NSBTX',
    'mmodel_00000856.NSBTX',
    'mmodel_00000857.NSBTX',
    'mmodel_00000858.NSBTX',
    'mmodel_00000859.NSBTX',
    'mmodel_00000860.NSBTX',
    'mmodel_00000861.NSBTX',
    'mmodel_00000862.NSBTX',
))

mmodel_nsbmd = copy_gen.process(files(
    'mmodel_00000266.NSBMD',
    'mmodel_00000267.NSBMD',
    'mmodel_00000268.NSBMD',
    'mmodel_00000269.NSBMD',
    'mmodel_00000270.NSBMD',
    'mmodel_00000271.NSBMD',
    'mmodel_00000272.NSBMD',
    'mmodel_00000273.NSBMD',
    'mmodel_00000274.NSBMD',
    'mmodel_00000275.NSBMD',
    'mmodel_00000276.NSBMD',
    'mmodel_00000277.NSBMD',
    'mmodel_00000278.NSBMD',
    'mmodel_00000279.NSBMD',
))