otherpoke_index_ncgr += {
    '0078' : files('plant/back.png'),
    '0079' : files('plant/front.png'),
    '0080' : files('sandy/back.png'),
    '0081' : files('sandy/front.png'),
    '0082' : files('trash/back.png'),
    '0083' : files('trash/front.png'),
}

otherpoke_index_nclr += {
    '176' : files('plant/front.png'),
    '177' : files('plant/back.png'),
    '178' : files('sandy/front.png'),
    '179' : files('sandy/back.png'),
    '180' : files('trash/front.png'),
    '181' : files('trash/back.png'),
}