#ifndef POKEHEARTGOLD_CONSTANTS_FIELD_FIELD_EFFECT_RENDERER_H
#define POKEHEARTGOLD_CONSTANTS_FIELD_FIELD_EFFECT_RENDERER_H

enum FieldEffectRendererType {
    FIELD_EFFECT_RENDERER_0 = 0,
    FIELD_EFFECT_RENDERER_1,
    FIELD_EFFECT_RENDERER_2,
    FIELD_EFFECT_RENDERER_3,
    FIELD_EFFECT_RENDERER_4,
    FIELD_EFFECT_RENDERER_5,
    FIELD_EFFECT_RENDERER_6,
    FIELD_EFFECT_RENDERER_7,
    FIELD_EFFECT_RENDERER_8,
    FIELD_EFFECT_RENDERER_9,
    FIELD_EFFECT_RENDERER_10,
    FIELD_EFFECT_RENDERER_11,
    FIELD_EFFECT_RENDERER_12,
    FIELD_EFFECT_RENDERER_13,
    FIELD_EFFECT_RENDERER_14,
    FIELD_EFFECT_RENDERER_15,
    FIELD_EFFECT_RENDERER_16,
    FIELD_EFFECT_RENDERER_17,
    FIELD_EFFECT_RENDERER_18,
    FIELD_EFFECT_RENDERER_19,
    FIELD_EFFECT_RENDERER_20,
    FIELD_EFFECT_RENDERER_21,
    FIELD_EFFECT_RENDERER_22,
    FIELD_EFFECT_RENDERER_COUNT, // 23
    FIELD_EFFECT_RENDERER_INVALID = FIELD_EFFECT_RENDERER_COUNT,
};

#endif // POKEHEARTGOLD_CONSTANTS_FIELD_FIELD_EFFECT_RENDERER_H
