#ifndef POKEHEARTGOLD_CONSTANTS_FIELD_MAP_LOAD_H
#define POKEHEARTGOLD_CONSTANTS_FIELD_MAP_LOAD_H

enum MapLoadType {
    MAP_LOAD_TYPE_OVERWORLD = 0,
    MAP_LOAD_TYPE_SAFARI,
    MAP_LOAD_TYPE_UNION,
    MAP_LOAD_TYPE_COLOSSEUM,
    MAP_LOAD_TYPE_BATTLE_TOWER,
    MAP_LOAD_TYPE_5,
    MAP_LOAD_TYPE_MAX
};

#endif // POKEHEARTGOLD_CONSTANTS_FIELD_MAP_LOAD_H
