otherpoke_index_ncgr += {
    '0092' : files('normal/back.png'),
    '0093' : files('sunshine/back.png'),
    '0094' : files('normal/front.png'),
    '0095' : files('sunshine/front.png'),
}

otherpoke_index_nclr += {
    '190' : files('normal/front.png'),
    '191' : files('sunshine/front.png'),
    '192' : files('normal/back.png'),
    '193' : files('sunshine/back.png'),
}