shop_gra_ncgr = copy_gen.process(files(
    'shop_gra_00000.NCGR',
    'shop_gra_00004.NCGR',
    'shop_gra_00007.NCGR',
    'shop_gra_00012.NCGR',
    'shop_gra_00016.NCGR',
    'shop_gra_00023.NCGR',
))
shop_gra_nclr = copy_gen.process(files(
    'shop_gra_00001.NCLR',
    'shop_gra_00010.NCLR',
    'shop_gra_00011.NCLR',
    'shop_gra_00015.NCLR',
    'shop_gra_00022.NCLR',
))
shop_gra_ncer = copy_gen.process(files(
    'shop_gra_00005.NCER',
    'shop_gra_00008.NCER',
    'shop_gra_00024.NCER',
))
shop_gra_nanr = copy_gen.process(files(
    'shop_gra_00006.NANR',
    'shop_gra_00009.NANR',
    'shop_gra_00025.NANR',
))
shop_gra_nscr = copy_gen.process(files(
    'shop_gra_00002.NSCR',
    'shop_gra_00003.NSCR',
    'shop_gra_00013.NSCR',
    'shop_gra_00014.NSCR',
    'shop_gra_00017.NSCR',
    'shop_gra_00018.NSCR',
    'shop_gra_00019.NSCR',
    'shop_gra_00020.NSCR',
    'shop_gra_00021.NSCR',
))
