PREVIEW_GRAPHIC_DIR  := files/fielddata/graphic/preview_graphic/preview_graphic
PREVIEW_GRAPHIC_NARC := $(PREVIEW_GRAPHIC_DIR).narc

PREVIEW_GRAPHIC_PNG  := $(wildcard $(PREVIEW_GRAPHIC_DIR)/*.png)
PREVIEW_GRAPHIC_NSCR := $(wildcard $(PREVIEW_GRAPHIC_DIR)/*.NSCR)

PREVIEW_GRAPHIC_NCGR 	:= $(PREVIEW_GRAPHIC_PNG:%.png=%.NCGR)
PREVIEW_GRAPHIC_NCLR	:= $(PREVIEW_GRAPHIC_PNG:%.png=%.NCLR)
PREVIEW_GRAPHIC_NCGR_LZ := $(PREVIEW_GRAPHIC_NCGR:%.NCGR=%.NCGR.lz)
PREVIEW_GRAPHIC_NSCR_LZ := $(PREVIEW_GRAPHIC_NSCR:%.NSCR=%.NSCR.lz)

8BPP_NOPAD_NCLR_PNG_FILES += $(PREVIEW_GRAPHIC_NCLR)
VERSION101_SOPC_8BPP_NCGR_FILES += $(PREVIEW_GRAPHIC_NCGR)

$(PREVIEW_GRAPHIC_NARC): $(PREVIEW_GRAPHIC_NCGR_LZ) $(PREVIEW_GRAPHIC_NSCR_LZ) $(PREVIEW_GRAPHIC_NCLR)
	$(KNARC) -p $(PREVIEW_GRAPHIC_NARC) -d $(PREVIEW_GRAPHIC_DIR) -i

FS_CLEAN_TARGETS += $(PREVIEW_GRAPHIC_NCGR_LZ) $(PREVIEW_GRAPHIC_NSCR_LZ) $(PREVIEW_GRAPHIC_NCLR) $(PREVIEW_GRAPHIC_NARC)
