item_icon_nanr = copy_gen.process(files(
    'item_icon_000.NANR'
))

item_icon_ncer = copy_gen.process(files(
    'item_icon_001.NCER'
))

item_icon_nclr = copy_gen.process(files(
    'item_icon_003.NCLR',
    'item_icon_005.NCLR',
    'item_icon_007.NCLR',
    'item_icon_009.NCLR',
    'item_icon_011.NCLR',
    'item_icon_013.NCLR',
    'item_icon_015.NCLR',
    'item_icon_017.NCLR',
    'item_icon_019.NCLR',
    'item_icon_022.NCLR',
    'item_icon_025.NCLR',
    'item_icon_027.NCLR',
    'item_icon_028.NCLR',
    'item_icon_029.NCLR',
    'item_icon_031.NCLR',
    'item_icon_032.NCLR',
    'item_icon_034.NCLR',
    'item_icon_035.NCLR',
    'item_icon_036.NCLR',
    'item_icon_037.NCLR',
    'item_icon_039.NCLR',
    'item_icon_042.NCLR',
    'item_icon_044.NCLR',
    'item_icon_046.NCLR',
    'item_icon_048.NCLR',
    'item_icon_050.NCLR',
    'item_icon_052.NCLR',
    'item_icon_054.NCLR',
    'item_icon_055.NCLR',
    'item_icon_057.NCLR',
    'item_icon_059.NCLR',
    'item_icon_060.NCLR',
    'item_icon_061.NCLR',
    'item_icon_062.NCLR',
    'item_icon_064.NCLR',
    'item_icon_066.NCLR',
    'item_icon_067.NCLR',
    'item_icon_068.NCLR',
    'item_icon_069.NCLR',
    'item_icon_070.NCLR',
    'item_icon_072.NCLR',
    'item_icon_074.NCLR',
    'item_icon_075.NCLR',
    'item_icon_077.NCLR',
    'item_icon_079.NCLR',
    'item_icon_080.NCLR',
    'item_icon_081.NCLR',
    'item_icon_082.NCLR',
    'item_icon_084.NCLR',
    'item_icon_086.NCLR',
    'item_icon_087.NCLR',
    'item_icon_088.NCLR',
    'item_icon_089.NCLR',
    'item_icon_091.NCLR',
    'item_icon_093.NCLR',
    'item_icon_094.NCLR',
    'item_icon_096.NCLR',
    'item_icon_097.NCLR',
    'item_icon_098.NCLR',
    'item_icon_099.NCLR',
    'item_icon_101.NCLR',
    'item_icon_102.NCLR',
    'item_icon_103.NCLR',
    'item_icon_104.NCLR',
    'item_icon_106.NCLR',
    'item_icon_108.NCLR',
    'item_icon_110.NCLR',
    'item_icon_111.NCLR',
    'item_icon_113.NCLR',
    'item_icon_114.NCLR',
    'item_icon_116.NCLR',
    'item_icon_118.NCLR',
    'item_icon_120.NCLR',
    'item_icon_122.NCLR',
    'item_icon_124.NCLR',
    'item_icon_126.NCLR',
    'item_icon_129.NCLR',
    'item_icon_131.NCLR',
    'item_icon_134.NCLR',
    'item_icon_137.NCLR',
    'item_icon_139.NCLR',
    'item_icon_141.NCLR',
    'item_icon_143.NCLR',
    'item_icon_145.NCLR',
    'item_icon_147.NCLR',
    'item_icon_149.NCLR',
    'item_icon_151.NCLR',
    'item_icon_153.NCLR',
    'item_icon_155.NCLR',
    'item_icon_157.NCLR',
    'item_icon_159.NCLR',
    'item_icon_161.NCLR',
    'item_icon_163.NCLR',
    'item_icon_165.NCLR',
    'item_icon_167.NCLR',
    'item_icon_169.NCLR',
    'item_icon_171.NCLR',
    'item_icon_173.NCLR',
    'item_icon_175.NCLR',
    'item_icon_177.NCLR',
    'item_icon_179.NCLR',
    'item_icon_181.NCLR',
    'item_icon_183.NCLR',
    'item_icon_185.NCLR',
    'item_icon_187.NCLR',
    'item_icon_189.NCLR',
    'item_icon_191.NCLR',
    'item_icon_193.NCLR',
    'item_icon_195.NCLR',
    'item_icon_197.NCLR',
    'item_icon_199.NCLR',
    'item_icon_201.NCLR',
    'item_icon_203.NCLR',
    'item_icon_205.NCLR',
    'item_icon_207.NCLR',
    'item_icon_209.NCLR',
    'item_icon_211.NCLR',
    'item_icon_213.NCLR',
    'item_icon_215.NCLR',
    'item_icon_217.NCLR',
    'item_icon_219.NCLR',
    'item_icon_221.NCLR',
    'item_icon_223.NCLR',
    'item_icon_225.NCLR',
    'item_icon_227.NCLR',
    'item_icon_229.NCLR',
    'item_icon_231.NCLR',
    'item_icon_233.NCLR',
    'item_icon_235.NCLR',
    'item_icon_237.NCLR',
    'item_icon_239.NCLR',
    'item_icon_241.NCLR',
    'item_icon_243.NCLR',
    'item_icon_245.NCLR',
    'item_icon_247.NCLR',
    'item_icon_249.NCLR',
    'item_icon_251.NCLR',
    'item_icon_253.NCLR',
    'item_icon_255.NCLR',
    'item_icon_257.NCLR',
    'item_icon_259.NCLR',
    'item_icon_261.NCLR',
    'item_icon_262.NCLR',
    'item_icon_264.NCLR',
    'item_icon_266.NCLR',
    'item_icon_268.NCLR',
    'item_icon_270.NCLR',
    'item_icon_272.NCLR',
    'item_icon_274.NCLR',
    'item_icon_276.NCLR',
    'item_icon_278.NCLR',
    'item_icon_280.NCLR',
    'item_icon_282.NCLR',
    'item_icon_284.NCLR',
    'item_icon_286.NCLR',
    'item_icon_288.NCLR',
    'item_icon_290.NCLR',
    'item_icon_292.NCLR',
    'item_icon_294.NCLR',
    'item_icon_296.NCLR',
    'item_icon_298.NCLR',
    'item_icon_300.NCLR',
    'item_icon_302.NCLR',
    'item_icon_304.NCLR',
    'item_icon_307.NCLR',
    'item_icon_309.NCLR',
    'item_icon_311.NCLR',
    'item_icon_313.NCLR',
    'item_icon_315.NCLR',
    'item_icon_317.NCLR',
    'item_icon_319.NCLR',
    'item_icon_321.NCLR',
    'item_icon_323.NCLR',
    'item_icon_325.NCLR',
    'item_icon_327.NCLR',
    'item_icon_330.NCLR',
    'item_icon_332.NCLR',
    'item_icon_334.NCLR',
    'item_icon_336.NCLR',
    'item_icon_338.NCLR',
    'item_icon_340.NCLR',
    'item_icon_342.NCLR',
    'item_icon_343.NCLR',
    'item_icon_344.NCLR',
    'item_icon_345.NCLR',
    'item_icon_346.NCLR',
    'item_icon_348.NCLR',
    'item_icon_350.NCLR',
    'item_icon_352.NCLR',
    'item_icon_354.NCLR',
    'item_icon_356.NCLR',
    'item_icon_358.NCLR',
    'item_icon_360.NCLR',
    'item_icon_362.NCLR',
    'item_icon_364.NCLR',
    'item_icon_366.NCLR',
    'item_icon_368.NCLR',
    'item_icon_370.NCLR',
    'item_icon_372.NCLR',
    'item_icon_374.NCLR',
    'item_icon_377.NCLR',
    'item_icon_379.NCLR',
    'item_icon_380.NCLR',
    'item_icon_382.NCLR',
    'item_icon_384.NCLR',
    'item_icon_386.NCLR',
    'item_icon_393.NCLR',
    'item_icon_396.NCLR',
    'item_icon_398.NCLR',
    'item_icon_399.NCLR',
    'item_icon_400.NCLR',
    'item_icon_401.NCLR',
    'item_icon_402.NCLR',
    'item_icon_403.NCLR',
    'item_icon_404.NCLR',
    'item_icon_405.NCLR',
    'item_icon_406.NCLR',
    'item_icon_407.NCLR',
    'item_icon_408.NCLR',
    'item_icon_409.NCLR',
    'item_icon_410.NCLR',
    'item_icon_411.NCLR',
    'item_icon_412.NCLR',
    'item_icon_413.NCLR',
    'item_icon_416.NCLR',
    'item_icon_418.NCLR',
    'item_icon_420.NCLR',
    'item_icon_422.NCLR',
    'item_icon_424.NCLR',
    'item_icon_426.NCLR',
    'item_icon_428.NCLR',
    'item_icon_430.NCLR',
    'item_icon_432.NCLR',
    'item_icon_434.NCLR',
    'item_icon_436.NCLR',
    'item_icon_438.NCLR',
    'item_icon_440.NCLR',
    'item_icon_442.NCLR',
    'item_icon_444.NCLR',
    'item_icon_446.NCLR',
    'item_icon_448.NCLR',
    'item_icon_450.NCLR',
    'item_icon_452.NCLR',
    'item_icon_454.NCLR',
    'item_icon_456.NCLR',
    'item_icon_458.NCLR',
    'item_icon_460.NCLR',
    'item_icon_462.NCLR',
    'item_icon_463.NCLR',
    'item_icon_465.NCLR',
    'item_icon_467.NCLR',
    'item_icon_469.NCLR',
    'item_icon_471.NCLR',
    'item_icon_473.NCLR',
    'item_icon_475.NCLR',
    'item_icon_477.NCLR',
    'item_icon_479.NCLR',
    'item_icon_481.NCLR',
    'item_icon_483.NCLR',
    'item_icon_485.NCLR',
    'item_icon_487.NCLR',
    'item_icon_489.NCLR',
    'item_icon_491.NCLR',
    'item_icon_493.NCLR',
    'item_icon_495.NCLR',
    'item_icon_497.NCLR',
    'item_icon_499.NCLR',
    'item_icon_501.NCLR',
    'item_icon_503.NCLR',
    'item_icon_505.NCLR',
    'item_icon_507.NCLR',
    'item_icon_509.NCLR',
    'item_icon_511.NCLR',
    'item_icon_513.NCLR',
    'item_icon_515.NCLR',
    'item_icon_517.NCLR',
    'item_icon_519.NCLR',
    'item_icon_521.NCLR',
    'item_icon_523.NCLR',
    'item_icon_525.NCLR',
    'item_icon_527.NCLR',
    'item_icon_529.NCLR',
    'item_icon_531.NCLR',
    'item_icon_533.NCLR',
    'item_icon_535.NCLR',
    'item_icon_537.NCLR',
    'item_icon_539.NCLR',
    'item_icon_541.NCLR',
    'item_icon_543.NCLR',
    'item_icon_545.NCLR',
    'item_icon_547.NCLR',
    'item_icon_549.NCLR',
    'item_icon_551.NCLR',
    'item_icon_553.NCLR',
    'item_icon_555.NCLR',
    'item_icon_557.NCLR',
    'item_icon_559.NCLR',
    'item_icon_561.NCLR',
    'item_icon_563.NCLR',
    'item_icon_565.NCLR',
    'item_icon_567.NCLR',
    'item_icon_569.NCLR',
    'item_icon_571.NCLR',
    'item_icon_573.NCLR',
    'item_icon_575.NCLR',
    'item_icon_577.NCLR',
    'item_icon_579.NCLR',
    'item_icon_581.NCLR',
    'item_icon_583.NCLR',
    'item_icon_585.NCLR',
    'item_icon_587.NCLR',
    'item_icon_589.NCLR',
    'item_icon_591.NCLR',
    'item_icon_593.NCLR',
    'item_icon_595.NCLR',
    'item_icon_597.NCLR',
    'item_icon_599.NCLR',
    'item_icon_601.NCLR',
    'item_icon_603.NCLR',
    'item_icon_605.NCLR',
    'item_icon_607.NCLR',
    'item_icon_609.NCLR',
    'item_icon_610.NCLR',
    'item_icon_612.NCLR',
    'item_icon_614.NCLR',
    'item_icon_616.NCLR',
    'item_icon_618.NCLR',
    'item_icon_620.NCLR',
    'item_icon_621.NCLR',
    'item_icon_622.NCLR',
    'item_icon_623.NCLR',
    'item_icon_624.NCLR',
    'item_icon_625.NCLR',
    'item_icon_626.NCLR',
    'item_icon_627.NCLR',
    'item_icon_628.NCLR',
    'item_icon_629.NCLR',
    'item_icon_630.NCLR',
    'item_icon_631.NCLR',
    'item_icon_632.NCLR',
    'item_icon_633.NCLR',
    'item_icon_634.NCLR',
    'item_icon_635.NCLR',
    'item_icon_637.NCLR',
    'item_icon_639.NCLR',
    'item_icon_641.NCLR',
    'item_icon_643.NCLR',
    'item_icon_645.NCLR',
    'item_icon_647.NCLR',
    'item_icon_649.NCLR',
    'item_icon_651.NCLR',
    'item_icon_653.NCLR',
    'item_icon_655.NCLR',
    'item_icon_657.NCLR',
    'item_icon_658.NCLR',
    'item_icon_660.NCLR',
    'item_icon_662.NCLR',
    'item_icon_664.NCLR',
    'item_icon_666.NCLR',
    'item_icon_668.NCLR',
    'item_icon_670.NCLR',
    'item_icon_672.NCLR',
    'item_icon_674.NCLR',
    'item_icon_676.NCLR',
    'item_icon_678.NCLR',
    'item_icon_680.NCLR',
    'item_icon_682.NCLR',
    'item_icon_684.NCLR',
    'item_icon_686.NCLR',
    'item_icon_688.NCLR',
    'item_icon_690.NCLR',
    'item_icon_692.NCLR',
    'item_icon_694.NCLR',
    'item_icon_696.NCLR',
    'item_icon_698.NCLR',
    'item_icon_700.NCLR',
    'item_icon_702.NCLR',
    'item_icon_704.NCLR',
    'item_icon_706.NCLR',
    'item_icon_708.NCLR',
    'item_icon_710.NCLR',
    'item_icon_712.NCLR',
    'item_icon_714.NCLR',
    'item_icon_716.NCLR',
    'item_icon_718.NCLR',
    'item_icon_720.NCLR',
    'item_icon_722.NCLR',
    'item_icon_724.NCLR',
    'item_icon_726.NCLR',
    'item_icon_728.NCLR',
    'item_icon_730.NCLR',
    'item_icon_732.NCLR',
    'item_icon_734.NCLR',
    'item_icon_736.NCLR',
    'item_icon_738.NCLR',
    'item_icon_740.NCLR',
    'item_icon_742.NCLR',
    'item_icon_744.NCLR',
    'item_icon_746.NCLR',
    'item_icon_748.NCLR',
    'item_icon_750.NCLR',
    'item_icon_752.NCLR',
    'item_icon_754.NCLR',
    'item_icon_756.NCLR',
    'item_icon_758.NCLR',
    'item_icon_760.NCLR',
    'item_icon_762.NCLR',
    'item_icon_764.NCLR',
    'item_icon_766.NCLR',
    'item_icon_768.NCLR',
    'item_icon_770.NCLR',
    'item_icon_772.NCLR',
    'item_icon_774.NCLR',
    'item_icon_776.NCLR',
    'item_icon_778.NCLR',
    'item_icon_780.NCLR',
    'item_icon_782.NCLR',
    'item_icon_784.NCLR',
    'item_icon_786.NCLR',
    'item_icon_788.NCLR',
    'item_icon_790.NCLR',
    'item_icon_792.NCLR',
    'item_icon_794.NCLR',
    'item_icon_796.NCLR',
))

item_icon_ncgr = copy_gen.process(files(
    'item_icon_002.NCGR',
    'item_icon_004.NCGR',
    'item_icon_006.NCGR',
    'item_icon_008.NCGR',
    'item_icon_010.NCGR',
    'item_icon_012.NCGR',
    'item_icon_014.NCGR',
    'item_icon_016.NCGR',
    'item_icon_018.NCGR',
    'item_icon_020.NCGR',
    'item_icon_021.NCGR',
    'item_icon_023.NCGR',
    'item_icon_024.NCGR',
    'item_icon_026.NCGR',
    'item_icon_030.NCGR',
    'item_icon_033.NCGR',
    'item_icon_038.NCGR',
    'item_icon_040.NCGR',
    'item_icon_041.NCGR',
    'item_icon_043.NCGR',
    'item_icon_045.NCGR',
    'item_icon_047.NCGR',
    'item_icon_049.NCGR',
    'item_icon_051.NCGR',
    'item_icon_053.NCGR',
    'item_icon_056.NCGR',
    'item_icon_058.NCGR',
    'item_icon_063.NCGR',
    'item_icon_065.NCGR',
    'item_icon_071.NCGR',
    'item_icon_073.NCGR',
    'item_icon_076.NCGR',
    'item_icon_078.NCGR',
    'item_icon_083.NCGR',
    'item_icon_085.NCGR',
    'item_icon_090.NCGR',
    'item_icon_092.NCGR',
    'item_icon_095.NCGR',
    'item_icon_100.NCGR',
    'item_icon_105.NCGR',
    'item_icon_107.NCGR',
    'item_icon_109.NCGR',
    'item_icon_112.NCGR',
    'item_icon_115.NCGR',
    'item_icon_117.NCGR',
    'item_icon_119.NCGR',
    'item_icon_121.NCGR',
    'item_icon_123.NCGR',
    'item_icon_125.NCGR',
    'item_icon_127.NCGR',
    'item_icon_128.NCGR',
    'item_icon_130.NCGR',
    'item_icon_132.NCGR',
    'item_icon_133.NCGR',
    'item_icon_135.NCGR',
    'item_icon_136.NCGR',
    'item_icon_138.NCGR',
    'item_icon_140.NCGR',
    'item_icon_142.NCGR',
    'item_icon_144.NCGR',
    'item_icon_146.NCGR',
    'item_icon_148.NCGR',
    'item_icon_150.NCGR',
    'item_icon_152.NCGR',
    'item_icon_154.NCGR',
    'item_icon_156.NCGR',
    'item_icon_158.NCGR',
    'item_icon_160.NCGR',
    'item_icon_162.NCGR',
    'item_icon_164.NCGR',
    'item_icon_166.NCGR',
    'item_icon_168.NCGR',
    'item_icon_170.NCGR',
    'item_icon_172.NCGR',
    'item_icon_174.NCGR',
    'item_icon_176.NCGR',
    'item_icon_178.NCGR',
    'item_icon_180.NCGR',
    'item_icon_182.NCGR',
    'item_icon_184.NCGR',
    'item_icon_186.NCGR',
    'item_icon_188.NCGR',
    'item_icon_190.NCGR',
    'item_icon_192.NCGR',
    'item_icon_194.NCGR',
    'item_icon_196.NCGR',
    'item_icon_198.NCGR',
    'item_icon_200.NCGR',
    'item_icon_202.NCGR',
    'item_icon_204.NCGR',
    'item_icon_206.NCGR',
    'item_icon_208.NCGR',
    'item_icon_210.NCGR',
    'item_icon_212.NCGR',
    'item_icon_214.NCGR',
    'item_icon_216.NCGR',
    'item_icon_218.NCGR',
    'item_icon_220.NCGR',
    'item_icon_222.NCGR',
    'item_icon_224.NCGR',
    'item_icon_226.NCGR',
    'item_icon_228.NCGR',
    'item_icon_230.NCGR',
    'item_icon_232.NCGR',
    'item_icon_234.NCGR',
    'item_icon_236.NCGR',
    'item_icon_238.NCGR',
    'item_icon_240.NCGR',
    'item_icon_242.NCGR',
    'item_icon_244.NCGR',
    'item_icon_246.NCGR',
    'item_icon_248.NCGR',
    'item_icon_250.NCGR',
    'item_icon_252.NCGR',
    'item_icon_254.NCGR',
    'item_icon_256.NCGR',
    'item_icon_258.NCGR',
    'item_icon_260.NCGR',
    'item_icon_263.NCGR',
    'item_icon_265.NCGR',
    'item_icon_267.NCGR',
    'item_icon_269.NCGR',
    'item_icon_271.NCGR',
    'item_icon_273.NCGR',
    'item_icon_275.NCGR',
    'item_icon_277.NCGR',
    'item_icon_279.NCGR',
    'item_icon_281.NCGR',
    'item_icon_283.NCGR',
    'item_icon_285.NCGR',
    'item_icon_287.NCGR',
    'item_icon_289.NCGR',
    'item_icon_291.NCGR',
    'item_icon_293.NCGR',
    'item_icon_295.NCGR',
    'item_icon_297.NCGR',
    'item_icon_299.NCGR',
    'item_icon_301.NCGR',
    'item_icon_303.NCGR',
    'item_icon_305.NCGR',
    'item_icon_306.NCGR',
    'item_icon_308.NCGR',
    'item_icon_310.NCGR',
    'item_icon_312.NCGR',
    'item_icon_314.NCGR',
    'item_icon_316.NCGR',
    'item_icon_318.NCGR',
    'item_icon_320.NCGR',
    'item_icon_322.NCGR',
    'item_icon_324.NCGR',
    'item_icon_326.NCGR',
    'item_icon_328.NCGR',
    'item_icon_329.NCGR',
    'item_icon_331.NCGR',
    'item_icon_333.NCGR',
    'item_icon_335.NCGR',
    'item_icon_337.NCGR',
    'item_icon_339.NCGR',
    'item_icon_341.NCGR',
    'item_icon_347.NCGR',
    'item_icon_349.NCGR',
    'item_icon_351.NCGR',
    'item_icon_353.NCGR',
    'item_icon_355.NCGR',
    'item_icon_357.NCGR',
    'item_icon_359.NCGR',
    'item_icon_361.NCGR',
    'item_icon_363.NCGR',
    'item_icon_365.NCGR',
    'item_icon_367.NCGR',
    'item_icon_369.NCGR',
    'item_icon_371.NCGR',
    'item_icon_373.NCGR',
    'item_icon_375.NCGR',
    'item_icon_376.NCGR',
    'item_icon_378.NCGR',
    'item_icon_381.NCGR',
    'item_icon_383.NCGR',
    'item_icon_385.NCGR',
    'item_icon_387.NCGR',
    'item_icon_388.NCGR',
    'item_icon_389.NCGR',
    'item_icon_390.NCGR',
    'item_icon_391.NCGR',
    'item_icon_392.NCGR',
    'item_icon_394.NCGR',
    'item_icon_395.NCGR',
    'item_icon_397.NCGR',
    'item_icon_414.NCGR',
    'item_icon_415.NCGR',
    'item_icon_417.NCGR',
    'item_icon_419.NCGR',
    'item_icon_421.NCGR',
    'item_icon_423.NCGR',
    'item_icon_425.NCGR',
    'item_icon_427.NCGR',
    'item_icon_429.NCGR',
    'item_icon_431.NCGR',
    'item_icon_433.NCGR',
    'item_icon_435.NCGR',
    'item_icon_437.NCGR',
    'item_icon_439.NCGR',
    'item_icon_441.NCGR',
    'item_icon_443.NCGR',
    'item_icon_445.NCGR',
    'item_icon_447.NCGR',
    'item_icon_449.NCGR',
    'item_icon_451.NCGR',
    'item_icon_453.NCGR',
    'item_icon_455.NCGR',
    'item_icon_457.NCGR',
    'item_icon_459.NCGR',
    'item_icon_461.NCGR',
    'item_icon_464.NCGR',
    'item_icon_466.NCGR',
    'item_icon_468.NCGR',
    'item_icon_470.NCGR',
    'item_icon_472.NCGR',
    'item_icon_474.NCGR',
    'item_icon_476.NCGR',
    'item_icon_478.NCGR',
    'item_icon_480.NCGR',
    'item_icon_482.NCGR',
    'item_icon_484.NCGR',
    'item_icon_486.NCGR',
    'item_icon_488.NCGR',
    'item_icon_490.NCGR',
    'item_icon_492.NCGR',
    'item_icon_494.NCGR',
    'item_icon_496.NCGR',
    'item_icon_498.NCGR',
    'item_icon_500.NCGR',
    'item_icon_502.NCGR',
    'item_icon_504.NCGR',
    'item_icon_506.NCGR',
    'item_icon_508.NCGR',
    'item_icon_510.NCGR',
    'item_icon_512.NCGR',
    'item_icon_514.NCGR',
    'item_icon_516.NCGR',
    'item_icon_518.NCGR',
    'item_icon_520.NCGR',
    'item_icon_522.NCGR',
    'item_icon_524.NCGR',
    'item_icon_526.NCGR',
    'item_icon_528.NCGR',
    'item_icon_530.NCGR',
    'item_icon_532.NCGR',
    'item_icon_534.NCGR',
    'item_icon_536.NCGR',
    'item_icon_538.NCGR',
    'item_icon_540.NCGR',
    'item_icon_542.NCGR',
    'item_icon_544.NCGR',
    'item_icon_546.NCGR',
    'item_icon_548.NCGR',
    'item_icon_550.NCGR',
    'item_icon_552.NCGR',
    'item_icon_554.NCGR',
    'item_icon_556.NCGR',
    'item_icon_558.NCGR',
    'item_icon_560.NCGR',
    'item_icon_562.NCGR',
    'item_icon_564.NCGR',
    'item_icon_566.NCGR',
    'item_icon_568.NCGR',
    'item_icon_570.NCGR',
    'item_icon_572.NCGR',
    'item_icon_574.NCGR',
    'item_icon_576.NCGR',
    'item_icon_578.NCGR',
    'item_icon_580.NCGR',
    'item_icon_582.NCGR',
    'item_icon_584.NCGR',
    'item_icon_586.NCGR',
    'item_icon_588.NCGR',
    'item_icon_590.NCGR',
    'item_icon_592.NCGR',
    'item_icon_594.NCGR',
    'item_icon_596.NCGR',
    'item_icon_598.NCGR',
    'item_icon_600.NCGR',
    'item_icon_602.NCGR',
    'item_icon_604.NCGR',
    'item_icon_606.NCGR',
    'item_icon_608.NCGR',
    'item_icon_611.NCGR',
    'item_icon_613.NCGR',
    'item_icon_615.NCGR',
    'item_icon_617.NCGR',
    'item_icon_619.NCGR',
    'item_icon_636.NCGR',
    'item_icon_638.NCGR',
    'item_icon_640.NCGR',
    'item_icon_642.NCGR',
    'item_icon_644.NCGR',
    'item_icon_646.NCGR',
    'item_icon_648.NCGR',
    'item_icon_650.NCGR',
    'item_icon_652.NCGR',
    'item_icon_654.NCGR',
    'item_icon_656.NCGR',
    'item_icon_659.NCGR',
    'item_icon_661.NCGR',
    'item_icon_663.NCGR',
    'item_icon_665.NCGR',
    'item_icon_667.NCGR',
    'item_icon_669.NCGR',
    'item_icon_671.NCGR',
    'item_icon_673.NCGR',
    'item_icon_675.NCGR',
    'item_icon_677.NCGR',
    'item_icon_679.NCGR',
    'item_icon_681.NCGR',
    'item_icon_683.NCGR',
    'item_icon_685.NCGR',
    'item_icon_687.NCGR',
    'item_icon_689.NCGR',
    'item_icon_691.NCGR',
    'item_icon_693.NCGR',
    'item_icon_695.NCGR',
    'item_icon_697.NCGR',
    'item_icon_699.NCGR',
    'item_icon_701.NCGR',
    'item_icon_703.NCGR',
    'item_icon_705.NCGR',
    'item_icon_707.NCGR',
    'item_icon_709.NCGR',
    'item_icon_711.NCGR',
    'item_icon_713.NCGR',
    'item_icon_715.NCGR',
    'item_icon_717.NCGR',
    'item_icon_719.NCGR',
    'item_icon_721.NCGR',
    'item_icon_723.NCGR',
    'item_icon_725.NCGR',
    'item_icon_727.NCGR',
    'item_icon_729.NCGR',
    'item_icon_731.NCGR',
    'item_icon_733.NCGR',
    'item_icon_735.NCGR',
    'item_icon_737.NCGR',
    'item_icon_739.NCGR',
    'item_icon_741.NCGR',
    'item_icon_743.NCGR',
    'item_icon_745.NCGR',
    'item_icon_747.NCGR',
    'item_icon_749.NCGR',
    'item_icon_751.NCGR',
    'item_icon_753.NCGR',
    'item_icon_755.NCGR',
    'item_icon_757.NCGR',
    'item_icon_759.NCGR',
    'item_icon_761.NCGR',
    'item_icon_763.NCGR',
    'item_icon_765.NCGR',
    'item_icon_767.NCGR',
    'item_icon_769.NCGR',
    'item_icon_771.NCGR',
    'item_icon_773.NCGR',
    'item_icon_775.NCGR',
    'item_icon_777.NCGR',
    'item_icon_779.NCGR',
    'item_icon_781.NCGR',
    'item_icon_783.NCGR',
    'item_icon_785.NCGR',
    'item_icon_787.NCGR',
    'item_icon_789.NCGR',
    'item_icon_791.NCGR',
    'item_icon_793.NCGR',
    'item_icon_795.NCGR',
))