map_matrix_bin = copy_gen.process(files(
    'map_matrix_0000_EVERYWHERE.bin',
    'map_matrix_0001.bin',
    'map_matrix_0002_D01R0101.bin',
    'map_matrix_0003_D02R0101.bin',
    'map_matrix_0004_D02R0102.bin',
    'map_matrix_0005_D02R0103.bin',
    'map_matrix_0006_D05R0101.bin',
    'map_matrix_0007_D05R0102.bin',
    'map_matrix_0008_D10R0101.bin',
    'map_matrix_0009.bin',
    'map_matrix_0010.bin',
    'map_matrix_0011.bin',
    'map_matrix_0012_D15R0101.bin',
    'map_matrix_0013_D15R0102.bin',
    'map_matrix_0014_D15R0103.bin',
    'map_matrix_0015_D17R0101.bin',
    'map_matrix_0016_D17R0102.bin',
    'map_matrix_0017_D17R0103.bin',
    'map_matrix_0018_D17R0104.bin',
    'map_matrix_0019_D17R0105.bin',
    'map_matrix_0020_D17R0106.bin',
    'map_matrix_0021_D17R0107.bin',
    'map_matrix_0022_D17R0108.bin',
    'map_matrix_0023_D17R0109.bin',
    'map_matrix_0024_D17R0110.bin',
    'map_matrix_0025_D18R0101.bin',
    'map_matrix_0026_D18R0102.bin',
    'map_matrix_0027_D22R0101.bin',
    'map_matrix_0028_D23R0101.bin',
    'map_matrix_0029_D23R0102.bin',
    'map_matrix_0030_D23R0103.bin',
    'map_matrix_0031_D23R0104.bin',
    'map_matrix_0032_D23R0105.bin',
    'map_matrix_0033.bin',
    'map_matrix_0034_D24R0202.bin',
    'map_matrix_0035_D24R0203.bin',
    'map_matrix_0036.bin',
    'map_matrix_0037_D24R0205.bin',
    'map_matrix_0038.bin',
    'map_matrix_0039_D24R0207.bin',
    'map_matrix_0040.bin',
    'map_matrix_0041_D24R0209.bin',
    'map_matrix_0042_D25R0101.bin',
    'map_matrix_0043_D25R0102.bin',
    'map_matrix_0044_D25R0103.bin',
    'map_matrix_0045_D26R0101.bin',
    'map_matrix_0046_D26R0102.bin',
    'map_matrix_0047_D27R0101.bin',
    'map_matrix_0048_D27R0102.bin',
    'map_matrix_0049_D27R0103.bin',
    'map_matrix_0050_D27R0104.bin',
    'map_matrix_0051_D27R0105.bin',
    'map_matrix_0052_D27R0106.bin',
    'map_matrix_0053_D35R0102.bin',
    'map_matrix_0054_D35R0103.bin',
    'map_matrix_0055_D35R0104.bin',
    'map_matrix_0056_D36R0101.bin',
    'map_matrix_0057_D37R0101.bin',
    'map_matrix_0058_D37R0102.bin',
    'map_matrix_0059_D37R0103.bin',
    'map_matrix_0060_D37R0104.bin',
    'map_matrix_0061_D37R0105.bin',
    'map_matrix_0062_D38R0101.bin',
    'map_matrix_0063_D38R0102.bin',
    'map_matrix_0064_D38R0103.bin',
    'map_matrix_0065_D38R0104.bin',
    'map_matrix_0066_T20R0301.bin',
    'map_matrix_0067_D17R1101.bin',
    'map_matrix_0068_T27R0201.bin',
    'map_matrix_0069_R35R0101.bin',
    'map_matrix_0070_R31R0101.bin',
    'map_matrix_0071_T20R0201.bin',
    'map_matrix_0072_T20R0202.bin',
    'map_matrix_0073_T21PC0101.bin',
    'map_matrix_0074_UNION.bin',
    'map_matrix_0075_DIRECT2.bin',
    'map_matrix_0076_DIRECT4.bin',
    'map_matrix_0077_T27PC0105.bin',
    'map_matrix_0078_D03R0101.bin',
    'map_matrix_0079_D03R0102.bin',
    'map_matrix_0080_D03R0103.bin',
    'map_matrix_0081_D11R0101.bin',
    'map_matrix_0082_D11R0102.bin',
    'map_matrix_0083_D11R0103.bin',
    'map_matrix_0084_D11R0104.bin',
    'map_matrix_0085_D11R0105.bin',
    'map_matrix_0086_D46R0101.bin',
    'map_matrix_0087_T22GYM0101.bin',
    'map_matrix_0088_T23GYM0101.bin',
    'map_matrix_0089_T25GYM0101.bin',
    'map_matrix_0090_T27GYM0101.bin',
    'map_matrix_0091_T26GYM0101.bin',
    'map_matrix_0092_T24GYM0101.bin',
    'map_matrix_0093_T28GYM0103.bin',
    'map_matrix_0094_T30GYM0101.bin',
    'map_matrix_0095_T28R0201.bin',
    'map_matrix_0096_T21R0401.bin',
    'map_matrix_0097_T21R0301.bin',
    'map_matrix_0098_D42R0101.bin',
    'map_matrix_0099_D42R0102.bin',
    'map_matrix_0100_T20R0101.bin',
    'map_matrix_0101_T20R0102.bin',
    'map_matrix_0102_T22R0301.bin',
    'map_matrix_0103_R30R0201.bin',
    'map_matrix_0104_T21FS0101.bin',
    'map_matrix_0105_T23GYM0102.bin',
    'map_matrix_0106_D26R0103.bin',
    'map_matrix_0107_T25R0201.bin',
    'map_matrix_0108_T25R0601.bin',
    'map_matrix_0109_T25R1101.bin',
    'map_matrix_0110_D23R0106.bin',
    'map_matrix_0111_T25R0501.bin',
    'map_matrix_0112_T25R0502.bin',
    'map_matrix_0113_T25R1001.bin',
    'map_matrix_0114_T25R1002.bin',
    'map_matrix_0115_T25R1003.bin',
    'map_matrix_0116_T25R1004.bin',
    'map_matrix_0117_T25R1005.bin',
    'map_matrix_0118_T25R1006.bin',
    'map_matrix_0119_T25R1301.bin',
    'map_matrix_0120_T25R1302.bin',
    'map_matrix_0121_T25R1303.bin',
    'map_matrix_0122_T25R1304.bin',
    'map_matrix_0123_T25R1305.bin',
    'map_matrix_0124_T25R1306.bin',
    'map_matrix_0125_T23R0201.bin',
    'map_matrix_0126_T27R0501.bin',
    'map_matrix_0127_T23R0501.bin',
    'map_matrix_0128_R39R0101.bin',
    'map_matrix_0129_R39R0201.bin',
    'map_matrix_0130_T27R0202.bin',
    'map_matrix_0131_D27R0107.bin',
    'map_matrix_0132_D39R0101.bin',
    'map_matrix_0133_D39R0102.bin',
    'map_matrix_0134_D39R0103.bin',
    'map_matrix_0135_D39R0104.bin',
    'map_matrix_0136_T26R0701.bin',
    'map_matrix_0137_P01R0101.bin',
    'map_matrix_0138_D35R0101.bin',
    'map_matrix_0139_T24R0501.bin',
    'map_matrix_0140_T25R0901.bin',
    'map_matrix_0141_D40R0101.bin',
    'map_matrix_0142_D40R0102.bin',
    'map_matrix_0143_D40R0104.bin',
    'map_matrix_0144_D40R0107.bin',
    'map_matrix_0145_D44R0101.bin',
    'map_matrix_0146_D44R0102.bin',
    'map_matrix_0147_R26R0201.bin',
    'map_matrix_0148_T10R0101.bin',
    'map_matrix_0149_D44R0103.bin',
    'map_matrix_0150_R22R0101.bin',
    'map_matrix_0151_D45R0101.bin',
    'map_matrix_0152_D48R0101.bin',
    'map_matrix_0153_D49.bin',
    'map_matrix_0154_D49R0101.bin',
    'map_matrix_0155_D49R0102.bin',
    'map_matrix_0156_D49R0103.bin',
    'map_matrix_0157_D49R0104.bin',
    'map_matrix_0158_D49R0105.bin',
    'map_matrix_0159_D49R0106.bin',
    'map_matrix_0160_D49R0107.bin',
    'map_matrix_0161_D43R0101.bin',
    'map_matrix_0162_D43R0102.bin',
    'map_matrix_0163_D43R0103.bin',
    'map_matrix_0164_D45R0102.bin',
    'map_matrix_0165_T10R0201.bin',
    'map_matrix_0166_T10R0301.bin',
    'map_matrix_0167_T10R0401.bin',
    'map_matrix_0168_T10R0501.bin',
    'map_matrix_0169_T10R0601.bin',
    'map_matrix_0170_T10R0701.bin',
    'map_matrix_0171_P01R0301.bin',
    'map_matrix_0172_P01R0302.bin',
    'map_matrix_0173_P01R0303.bin',
    'map_matrix_0174_P01R0304.bin',
    'map_matrix_0175_P01R0305.bin',
    'map_matrix_0176_P01R0306.bin',
    'map_matrix_0177_P01R0307.bin',
    'map_matrix_0178_P01R0102.bin',
    'map_matrix_0179_R34R0101.bin',
    'map_matrix_0180_D24R0210.bin',
    'map_matrix_0181_D24R0211.bin',
    'map_matrix_0182_D24R0212.bin',
    'map_matrix_0183_D17R0112.bin',
    'map_matrix_0184_D50R0101.bin',
    'map_matrix_0185_T06R0301.bin',
    'map_matrix_0186_P01R0103.bin',
    'map_matrix_0187_T11R0601.bin',
    'map_matrix_0188_T11R0602.bin',
    'map_matrix_0189_T11R0701.bin',
    'map_matrix_0190_T11R0801.bin',
    'map_matrix_0191_T11R0802.bin',
    'map_matrix_0192_T11R0101.bin',
    'map_matrix_0193_T05R0201.bin',
    'map_matrix_0194_T05R0601.bin',
    'map_matrix_0195_T05R0701.bin',
    'map_matrix_0196_R35R0201.bin',
    'map_matrix_0197_SAF01.bin',
    'map_matrix_0198_SAF02.bin',
    'map_matrix_0199_SAF03.bin',
    'map_matrix_0200_SAF04.bin',
    'map_matrix_0201_SAF05.bin',
    'map_matrix_0202_SAF06.bin',
    'map_matrix_0203_SAF07.bin',
    'map_matrix_0204_SAF08.bin',
    'map_matrix_0205_SAF09.bin',
    'map_matrix_0206_SAF10.bin',
    'map_matrix_0207_SAF11.bin',
    'map_matrix_0208_SAF12.bin',
    'map_matrix_0209_SAF13.bin',
    'map_matrix_0210_SAF14.bin',
    'map_matrix_0211_P01R0104.bin',
    'map_matrix_0212_D47R0102.bin',
    'map_matrix_0213_T07R0401.bin',
    'map_matrix_0214_T07R0501.bin',
    'map_matrix_0215_T07R0101.bin',
    'map_matrix_0216_T07R0102.bin',
    'map_matrix_0217_T07R0103.bin',
    'map_matrix_0218_T07R0104.bin',
    'map_matrix_0219_T07R0105.bin',
    'map_matrix_0220_T07R0106.bin',
    'map_matrix_0221_T07R0201.bin',
    'map_matrix_0222_T07R0202.bin',
    'map_matrix_0223_T07R0203.bin',
    'map_matrix_0224_T07R0204.bin',
    'map_matrix_0225_T07R0205.bin',
    'map_matrix_0226_T07R0701.bin',
    'map_matrix_0227_D47R0101.bin',
    'map_matrix_0228_T28GYM0102.bin',
    'map_matrix_0229_T28GYM0101.bin',
    'map_matrix_0230_D32.bin',
    'map_matrix_0231_D32R0101.bin',
    'map_matrix_0232_D31R0201.bin',
    'map_matrix_0233_D32R0301.bin',
    'map_matrix_0234_D32R0401.bin',
    'map_matrix_0235_D32R0501.bin',
    'map_matrix_0236_D32R0601.bin',
    'map_matrix_0237_T25R1201.bin',
    'map_matrix_0238_T25R1202.bin',
    'map_matrix_0239_T25R1203.bin',
    'map_matrix_0240_D32R0102.bin',
    'map_matrix_0241_T11R0702.bin',
    'map_matrix_0242_T03R0101.bin',
    'map_matrix_0243_T08R0201.bin',
    'map_matrix_0244_T02R0301.bin',
    'map_matrix_0245_T02R0302.bin',
    'map_matrix_0246_T01R0101.bin',
    'map_matrix_0247_T01R0102.bin',
    'map_matrix_0248_T01R0201.bin',
    'map_matrix_0249_T01R0202.bin',
    'map_matrix_0250_T01R0301.bin',
    'map_matrix_0251_R10R0201.bin',
    'map_matrix_0252_R05R0101.bin',
    'map_matrix_0253_R05R0201.bin',
    'map_matrix_0254_R25R0101.bin',
    'map_matrix_0255_T06GYM0101.bin',
    'map_matrix_0256_T11GYM0101.bin',
    'map_matrix_0257_T04GYM0101.bin',
    'map_matrix_0258_T07GYM0101.bin',
    'map_matrix_0259_T08GYM0101.bin',
    'map_matrix_0260_T03GYM0101.bin',
    'map_matrix_0261_T02GYM0101.bin',
    'map_matrix_0262_D31R0202.bin',
    'map_matrix_0263_D31R0207.bin',
    'map_matrix_0264_D11R0106.bin',
    'map_matrix_0265_D41R0101.bin',
    'map_matrix_0266_D41R0102.bin',
    'map_matrix_0267_D41R0103.bin',
    'map_matrix_0268_D41R0104.bin',
    'map_matrix_0269_D41R0105.bin',
    'map_matrix_0270_D41R0106.bin',
    'map_matrix_0271_D41R0107.bin',
    'map_matrix_0272_D41R0108.bin',
    'map_matrix_0273_D24R0102.bin',
    'map_matrix_0274_T04R0401.bin',
    'map_matrix_0275_D40R0106.bin',
    'map_matrix_0276_R10R0202.bin',
    'map_matrix_0277_D51R0101.bin',
    'map_matrix_0278_D51R0201.bin',
    'map_matrix_0279_D52R0101.bin',
    'map_matrix_0280_HIROBA.bin',
    'map_matrix_0281_D02R0104.bin',
    'map_matrix_0282_T25R0503.bin',
    'map_matrix_0283_T11R0603.bin',
    'map_matrix_0284_D52R0102.bin',
    'map_matrix_0285_D52R0103.bin',
    'map_matrix_0286_T25SP0101.bin',
    'map_matrix_0287_D51R0301.bin',
))