prebuilt_files = [    'b_plist_gra.narc',    'bag_gra.narc',    'batt_bg.narc',    'batt_obj.narc',    'dp_height.narc',    'dp_height_o.narc',    'font.narc',    'growtbl.narc',    'item_data.narc',    'msg.narc',    'otherpoke.narc',    'personal.narc',    'plist_gra.narc',    'poke_anm.narc',    'poke_icon.narc',    'pokeanm.narc',    'pokegra.narc',    'poketch.narc',    'pokezukan.narc',    'pst_gra.narc',    'waza_tbl.narc',    'winframe.narc',    'zukan.narc',    'pbr_file.inc',    'sound_data.sdat',
]

foreach f : prebuilt_files
    nitrofs_files += fs.copyfile(f)
endforeach