PBR_FILES = pbr/b_plist_gra.narc \
		pbr/bag_gra.narc \
		pbr/batt_bg.narc \
		pbr/batt_obj.narc \
		pbr/font.narc \
		pbr/growtbl.narc \
		pbr/item_data.narc \
		pbr/msg.narc \
		pbr/pbr_file.inc \
		pbr/personal.narc \
		pbr/plist_gra.narc \
		pbr/poke_anm.narc \
		pbr/poke_icon.narc \
		pbr/pokeanm.narc \
		pbr/pokezukan.narc \
		pbr/pst_gra.narc \
		pbr/sound_data.sdat \
		pbr/waza_tbl.narc \
		pbr/winframe.narc \
		pbr/poketch.narc \
		pbr/zukan.narc

