subscript_asm = files(
    'subscript_0000_StartEncounter.s',
    'subscript_0001_UseMove.s',
    'subscript_0002_UpdateHp.s',
    'subscript_0003_RunAway.s',
    'subscript_0004_BattleWin.s',
    'subscript_0005_BattleLose.s',
    'subscript_0006_FaintMon.s',
    'subscript_0007_Miss.s',
    'subscript_0008_RunAwayFail.s',
    'subscript_0009_SwitchMon.s',
    'subscript_0010_ShowParty.s',
    'subscript_0011_ThrowBall.s',
    'subscript_0012_UpdateStatStage.s',
    'subscript_0013_ChargedTurnVanish.s',
    'subscript_0014_FlinchMon.s',
    'subscript_0015_Flinched.s',
    'subscript_0016_CriticalHit.s',
    'subscript_0017_MultiHit.s',
    'subscript_0018_FallAsleep.s',
    'subscript_0019_WakeUp.s',
    'subscript_0020_Sleeping.s',
    'subscript_0021_MoveFollowupMessage.s',
    'subscript_0022_Poison.s',
    'subscript_0023_PoisonDamage.s',
    'subscript_0024_DrainHalfDamageDealt.s',
    'subscript_0025_Burn.s',
    'subscript_0026_BurnDamage.s',
    'subscript_0027_Freeze.s',
    'subscript_0028_Frozen.s',
    'subscript_0029_ThawOut.s',
    'subscript_0030_DefrostedByMove.s',
    'subscript_0031_Paralyze.s',
    'subscript_0032_FullyParalyzed.s',
    'subscript_0033_DreamEater.s',
    'subscript_0034_ResetStatChanges.s',
    'subscript_0035_BideStart.s',
    'subscript_0036_BideEnd.s',
    'subscript_0037_Confuse.s',
    'subscript_0038_Confused.s',
    'subscript_0039_HurtSelfInConfusion.s',
    'subscript_0040_SnapOutOfConfusion.s',
    'subscript_0041_TrainerMessage.s',
    'subscript_0042_NoPP.s',
    'subscript_0043_Struggle.s',
    'subscript_0044_Rampage.s',
    'subscript_0045_Conversion.s',
    'subscript_0046_RecoverHalf.s',
    'subscript_0047_BadPoison.s',
    'subscript_0048_PayDay.s',
    'subscript_0049_LightScreen.s',
    'subscript_0050_MoveEffectEnd.s',
    'subscript_0051_RampageEnd.s',
    'subscript_0052_Reflect.s',
    'subscript_0053_AnimationPreparedMessage.s',
    'subscript_0054_Mist.s',
    'subscript_0055_Rest.s',
    'subscript_0056_Uproar.s',
    'subscript_0057_ShowPreparedMessage.s',
    'subscript_0058_BindStart.s',
    'subscript_0059_Bind.s',
    'subscript_0060_BindEnd.s',
    'subscript_0061_CrashOnMiss.s',
    'subscript_0062_FocusEnergy.s',
    'subscript_0063_Recoil_1_4.s',
    'subscript_0064_Recharge.s',
    'subscript_0065_Recharging.s',
    'subscript_0066_SetRage.s',
    'subscript_0067_Mimic.s',
    'subscript_0068_LeechSeedStart.s',
    'subscript_0069_LeechSeed.s',
    'subscript_0070_DisableStart.s',
    'subscript_0071_Disabled.s',
    'subscript_0072_DisableEnd.s',
    'subscript_0073_EncoreStart.s',
    'subscript_0074_EncoreEnd.s',
    'subscript_0075_ButItFailed.s',
    'subscript_0076_AttackMessageAndAnimation.s',
    'subscript_0077_PainSplit.s',
    'subscript_0078_Conversion2.s',
    'subscript_0079_LockOn.s',
    'subscript_0080_Sketch.s',
    'subscript_0081_Feint.s',
    'subscript_0082_DestinyBond.s',
    'subscript_0083_CheckDestinyBondGrudge.s',
    'subscript_0084_Spite.s',
    'subscript_0085_StealItem.s',
    'subscript_0086_MeanLook.s',
    'subscript_0087_Protect.s',
    'subscript_0088_HealBell.s',
    'subscript_0089_TrySubstitute.s',
    'subscript_0090_HitSubstitute.s',
    'subscript_0091_ForceSwitchOrFlee.s',
    'subscript_0092_Transform.s',
    'subscript_0093_NightmareStart.s',
    'subscript_0094_Nightmare.s',
    'subscript_0095_Minimize.s',
    'subscript_0096_CurseNormal.s',
    'subscript_0097_CurseGhost.s',
    'subscript_0098_CurseDamage.s',
    'subscript_0099_HazardsCheck.s',
    'subscript_0100_Foresight.s',
    'subscript_0101_PerrishSongStart.s',
    'subscript_0102_PerishSongContinue.s',
    'subscript_0103_WeatherStart.s',
    'subscript_0104_WeatherContinue.s',
    'subscript_0105_Swagger.s',
    'subscript_0106_Infatuate.s',
    'subscript_0107_Infatuated.s',
    'subscript_0108_ImmobilizedByLove.s',
    'subscript_0109_SafeguardStart.s',
    'subscript_0110_SafeguardEnd.s',
    'subscript_0111_RecoverHp.s',
    'subscript_0112_PresentHeal.s',
    'subscript_0113_Magnitude.s',
    'subscript_0114_BatonPass.s',
    'subscript_0115_RapidSpin.s',
    'subscript_0116_BreakBind.s',
    'subscript_0117_BlowAwayHazards.s',
    'subscript_0118_PsychoShift.s',
    'subscript_0119_Omniboost.s',
    'subscript_0120_BellyDrum.s',
    'subscript_0121_FutureSightDamage.s',
    'subscript_0122_Teleport.s',
    'subscript_0123_FutureSightStart.s',
    'subscript_0124_Stockpile.s',
    'subscript_0125_Swallow.s',
    'subscript_0126_PrintMessagePlayAnimation.s',
    'subscript_0127_TormentStart.s',
    'subscript_0128_Flatter.s',
    'subscript_0129_Memento.s',
    'subscript_0130_HealTargetParalysis.s',
    'subscript_0131_Charge.s',
    'subscript_0132_TauntStart.s',
    'subscript_0133_MoveFailTaunted.s',
    'subscript_0134_ExchangeItems.s',
    'subscript_0135_CopyAbility.s',
    'subscript_0136_WishHeal.s',
    'subscript_0137_IngrainHeal.s',
    'subscript_0138_SuperpowerDebuff.s',
    'subscript_0139_MagicCoat.s',
    'subscript_0140_BreakScreens.s',
    'subscript_0141_Yawn.s',
    'subscript_0142_KnockOfff.s',
    'subscript_0143_SwapAbility.s',
    'subscript_0144_Imprisoned.s',
    'subscript_0145_CurePoisonParalysisBurn.s',
    'subscript_0146_Snatch.s',
    'subscript_0147_Recoil_1_3.s',
    'subscript_0148_Tickle.s',
    'subscript_0149_CosmicPower.s',
    'subscript_0150_BulkUp.s',
    'subscript_0151_CalmMind.s',
    'subscript_0152_DragonDance.s',
    'subscript_0153_Pursuit.s',
    'subscript_0154_Roost.s',
    'subscript_0155_WakeUpTarget.s',
    'subscript_0156_GravityStart.s',
    'subscript_0157_MoveFailGravity.s',
    'subscript_0158_MiracleEye.s',
    'subscript_0159_HealingWish.s',
    'subscript_0160_TailwindStart.s',
    'subscript_0161_CloseCombatDebuff.s',
    'subscript_0162_PowerTrick.s',
    'subscript_0163_GastroAcid.s',
    'subscript_0164_LuckyChantStart.s',
    'subscript_0165_PowerSwap.s',
    'subscript_0166_GuardSwap.s',
    'subscript_0167_WorrySeed.s',
    'subscript_0168_HeartSwap.s',
    'subscript_0169_AquaRingHeal.s',
    'subscript_0170_Recoil_1_3_BurnChance.s',
    'subscript_0171_Defog.s',
    'subscript_0172_DefogMessage.s',
    'subscript_0173_HealBlockStart.s',
    'subscript_0174_MoveHealBlocked.s',
    'subscript_0175_PivotMove.s',
    'subscript_0176_MoveFailMissed.s',
    'subscript_0177_MoldBreaker.s',
    'subscript_0178_ResoreHpAbility.s',
    'subscript_0179_FlashFire.s',
    'subscript_0180_LightningRod.s',
    'subscript_0181_Soundproof.s',
    'subscript_0182_MotorDrive.s',
    'subscript_0183_Drizzle.s',
    'subscript_0184_SandStream.s',
    'subscript_0185_Drought.s',
    'subscript_0186_Intimidate.s',
    'subscript_0187_Trace.s',
    'subscript_0188_ColorChange.s',
    'subscript_0189_RoughSkin.s',
    'subscript_0190_RestoreStatusAbility.s',
    'subscript_0191_LoafingAround.s',
    'subscript_0192_HPRestoreGradual.s',
    'subscript_0193_Aftermath.s',
    'subscript_0194_Anticipation.s',
    'subscript_0195_Forewarn.s',
    'subscript_0196_SlowStart.s',
    'subscript_0197_SlowStartEnd.s',
    'subscript_0198_HeldItemHeal.s',
    'subscript_0199_HeldItemCureParalysis.s',
    'subscript_0200_HeldItemWakeUp.s',
    'subscript_0201_HeldItemCurePoison.s',
    'subscript_0202_HeldItemCureBurn.s',
    'subscript_0203_HeldItemThawOut.s',
    'subscript_0204_HeldItemRestorePP.s',
    'subscript_0205_HeldItemCureConfusion.s',
    'subscript_0206_HeldItemCureAll.s',
    'subscript_0207_DislikeBerryFlavor.s',
    'subscript_0208_HeldItemRaiseStat.s',
    'subscript_0209_HeldItemRaiseCritrate.s',
    'subscript_0210_HeldItemSharplyRaiseStat.s',
    'subscript_0211_HeldItemRestoreStatdown.s',
    'subscript_0212_HeldItemCureInfatuation.s',
    'subscript_0213_HeldItemGradualRestoreHP.s',
    'subscript_0214_HeldItemLoseHP.s',
    'subscript_0215_HeldItemLoseHPMessage.s',
    'subscript_0216_TransferStickyBarb.s',
    'subscript_0217_PowerHerb.s',
    'subscript_0218_EmbargoStart.s',
    'subscript_0219_Pluck.s',
    'subscript_0220_Fling.s',
    'subscript_0221_NoStatusAbility.s',
    'subscript_0222_RunAwayItem.s',
    'subscript_0223_BattleItem.s',
    'subscript_0224_BagItemRestoreHp.s',
    'subscript_0225_BagItemRestorePP.s',
    'subscript_0226_Recoil_1_3_ChanceToParalyz.s',
    'subscript_0227_SafariThrowBait.s',
    'subscript_0228_SafariThrowBall.s',
    'subscript_0229_RunAwaySafari.s',
    'subscript_0230_RunAwayWildMon.s',
    'subscript_0231_ReplaceFainted.s',
    'subscript_0232_TightenFocus.s',
    'subscript_0233_TailwindEnd.s',
    'subscript_0234_RainingEnd.s',
    'subscript_0235_SandstormEnd.s',
    'subscript_0236_SunEnd.s',
    'subscript_0237_HailEnd.s',
    'subscript_0238_GravityEnd.s',
    'subscript_0239_CannotHeal.s',
    'subscript_0240_UproarContinue.s',
    'subscript_0241_UproarEnd.s',
    'subscript_0242_MagnetRiseEnd.s',
    'subscript_0243_HealBlockEnd.s',
    'subscript_0244_EmbargoEnd.s',
    'subscript_0245_RageBuilding.s',
    'subscript_0246_Recoil_1_2.s',
    'subscript_0247_BurnOrFlinch.s',
    'subscript_0248_FreezeOrFlinch.s',
    'subscript_0249_ParalyzeOrFlinch.s',
    'subscript_0250_LuckyChantEnd.s',
    'subscript_0251_TrickRoomEnd.s',
    'subscript_0252_SnowWarning.s',
    'subscript_0253_Frisk.s',
    'subscript_0254_DisobeyWhileSleep.s',
    'subscript_0255_DisobeyNothing.s',
    'subscript_0256_DisobeyOrders.s',
    'subscript_0257_DisobeySleep.s',
    'subscript_0258_DisobeyHitSelf.s',
    'subscript_0259_ChargeMoveCleanup.s',
    'subscript_0260_Chater.s',
    'subscript_0261_LunarDance.s',
    'subscript_0262_FormChange.s',
    'subscript_0263_BadDreams.s',
    'subscript_0264_SuperEffectiveBerries.s',
    'subscript_0265_HeldItemAccuracyUp.s',
    'subscript_0266_HeldItemRecoilWhenHit.s',
    'subscript_0267_PotionItem.s',
    'subscript_0268_StatusHealItem.s',
    'subscript_0269_XItem.s',
    'subscript_0270_GuardSpec.s',
    'subscript_0271_OverworldRain.s',
    'subscript_0272_OverworldHail.s',
    'subscript_0273_OverworldSand.s',
    'subscript_0274_OverworldFog.s',
    'subscript_0275_ThrowSafariBall.s',
    'subscript_0276_GrantExp.s',
    'subscript_0277_AfterSelfdestruct.s',
    'subscript_0278_CheckQuickClaw.s',
    'subscript_0279_PushAttackerAndTarget.s',
    'subscript_0280_PopAttackerAndTarget.s',
    'subscript_0281_NoTarget.s',
    'subscript_0282_BideNoTarget.s',
    'subscript_0283_LinkWinLose.s',
    'subscript_0284_RunAwaySafely.s',
    'subscript_0285_Pressure.s',
    'subscript_0286_RunAwayOpponentFail.s',
    'subscript_0287_VanishOff.s',
    'subscript_0288_TauntEnd.s',
    'subscript_0289_UseFullRestore.s',
    'subscript_0290_Pluck.s',
    'subscript_0291_WaitMoveAnimation.s',
    'subscript_0292_PowerHerbSkullBash.s',
    'subscript_0293_CheckShayminForm.s',
    'subscript_0294_OverworldSun.s',
    'subscript_0295_OverworldTrickRoom.s',
    'subscript_0296_GiratinaFormChange.s',
)