gs_areawindow_pngs = files(
    'areawindow_0.png',
    'areawindow_1.png',
    'areawindow_2.png',
    'areawindow_3.png',
    'areawindow_4.png',
    'areawindow_5.png',
    'areawindow_6.png',
    'areawindow_7.png',
    'areawindow_8.png',
)

gs_areawindow_ncgr = ncgr_gen.process(gs_areawindow_pngs, extra_args : VERSION101_SOPC_NCGR_FLAGS)
gs_areawindow_nclr = nclr_gen.process(gs_areawindow_pngs)