preview_graphic_png = files(
    'preview_graphic_bell_tower_day.png',
    'preview_graphic_bell_tower_evening.png',
    'preview_graphic_bell_tower_morning.png',
    'preview_graphic_bell_tower_night.png',
    'preview_graphic_burned_tower_day.png',
    'preview_graphic_burned_tower_evening.png',
    'preview_graphic_burned_tower_morning.png',
    'preview_graphic_burned_tower_night.png',
    'preview_graphic_cerulean_cave_day.png',
    'preview_graphic_cerulean_cave_morning.png',
    'preview_graphic_cerulean_cave_night.png',
    'preview_graphic_dark_cave_r31_day.png',
    'preview_graphic_dark_cave_r31_morning.png',
    'preview_graphic_dark_cave_r31_night.png',
    'preview_graphic_dark_cave_r45_day.png',
    'preview_graphic_dark_cave_r45_morning.png',
    'preview_graphic_dark_cave_r45_night.png',
    'preview_graphic_diglett_cave_day.png',
    'preview_graphic_diglett_cave_morning.png',
    'preview_graphic_diglett_cave_night.png',
    'preview_graphic_dragons_den_day.png',
    'preview_graphic_dragons_den_morning.png',
    'preview_graphic_dragons_den_night.png',
    'preview_graphic_ice_path_day.png',
    'preview_graphic_ice_path_morning.png',
    'preview_graphic_ice_path_night.png',
    'preview_graphic_ilex_forest_day.png',
    'preview_graphic_ilex_forest_evening.png',
    'preview_graphic_ilex_forest_morning.png',
    'preview_graphic_ilex_forest_night.png',
    'preview_graphic_mt_moon_day.png',
    'preview_graphic_mt_moon_evening.png',
    'preview_graphic_mt_moon_morning.png',
    'preview_graphic_mt_moon_night.png',
    'preview_graphic_mt_mortar_day.png',
    'preview_graphic_mt_mortar_evening.png',
    'preview_graphic_mt_mortar_morning.png',
    'preview_graphic_mt_mortar_night.png',
    'preview_graphic_mt_silver_day.png',
    'preview_graphic_mt_silver_morning.png',
    'preview_graphic_mt_silver_night.png',
    'preview_graphic_national_park_day.png',
    'preview_graphic_national_park_evening.png',
    'preview_graphic_national_park_morning.png',
    'preview_graphic_national_park_night.png',
    'preview_graphic_rock_tunnel_day.png',
    'preview_graphic_rock_tunnel_morning.png',
    'preview_graphic_rock_tunnel_night.png',
    'preview_graphic_ruins_of_alph_day.png',
    'preview_graphic_ruins_of_alph_morning.png',
    'preview_graphic_ruins_of_alph_night.png',
    'preview_graphic_seafoam_islands_day.png',
    'preview_graphic_seafoam_islands_morning.png',
    'preview_graphic_seafoam_islands_night.png',
    'preview_graphic_slowpoke_well_day.png',
    'preview_graphic_slowpoke_well_morning.png',
    'preview_graphic_slowpoke_well_night.png',
    'preview_graphic_sprout_tower_day.png',
    'preview_graphic_sprout_tower_morning.png',
    'preview_graphic_sprout_tower_night.png',
    'preview_graphic_tohjo_falls_day.png',
    'preview_graphic_tohjo_falls_morning.png',
    'preview_graphic_tohjo_falls_night.png',
    'preview_graphic_union_cave_day.png',
    'preview_graphic_union_cave_morning.png',
    'preview_graphic_union_cave_night.png',
    'preview_graphic_victory_road_day.png',
    'preview_graphic_victory_road_morning.png',
    'preview_graphic_victory_road_night.png',
    'preview_graphic_viridian_forest_day.png',
    'preview_graphic_viridian_forest_evening.png',
    'preview_graphic_viridian_forest_morning.png',
    'preview_graphic_viridian_forest_night.png',
    'preview_graphic_whirl_islands_day.png',
    'preview_graphic_whirl_islands_morning.png',
    'preview_graphic_whirl_islands_night.png',
)

preview_graphic_nscr_lz = lz_gen.process(files(
    'preview_graphic_bell_tower_day.NSCR',
    'preview_graphic_bell_tower_evening.NSCR',
    'preview_graphic_bell_tower_morning.NSCR',
    'preview_graphic_bell_tower_night.NSCR',
    'preview_graphic_burned_tower_day.NSCR',
    'preview_graphic_burned_tower_evening.NSCR',
    'preview_graphic_burned_tower_morning.NSCR',
    'preview_graphic_burned_tower_night.NSCR',
    'preview_graphic_cerulean_cave_day.NSCR',
    'preview_graphic_cerulean_cave_morning.NSCR',
    'preview_graphic_cerulean_cave_night.NSCR',
    'preview_graphic_dark_cave_r31_day.NSCR',
    'preview_graphic_dark_cave_r31_morning.NSCR',
    'preview_graphic_dark_cave_r31_night.NSCR',
    'preview_graphic_dark_cave_r45_day.NSCR',
    'preview_graphic_dark_cave_r45_morning.NSCR',
    'preview_graphic_dark_cave_r45_night.NSCR',
    'preview_graphic_diglett_cave_day.NSCR',
    'preview_graphic_diglett_cave_morning.NSCR',
    'preview_graphic_diglett_cave_night.NSCR',
    'preview_graphic_dragons_den_day.NSCR',
    'preview_graphic_dragons_den_morning.NSCR',
    'preview_graphic_dragons_den_night.NSCR',
    'preview_graphic_ice_path_day.NSCR',
    'preview_graphic_ice_path_morning.NSCR',
    'preview_graphic_ice_path_night.NSCR',
    'preview_graphic_ilex_forest_day.NSCR',
    'preview_graphic_ilex_forest_evening.NSCR',
    'preview_graphic_ilex_forest_morning.NSCR',
    'preview_graphic_ilex_forest_night.NSCR',
    'preview_graphic_mt_moon_day.NSCR',
    'preview_graphic_mt_moon_evening.NSCR',
    'preview_graphic_mt_moon_morning.NSCR',
    'preview_graphic_mt_moon_night.NSCR',
    'preview_graphic_mt_mortar_day.NSCR',
    'preview_graphic_mt_mortar_evening.NSCR',
    'preview_graphic_mt_mortar_morning.NSCR',
    'preview_graphic_mt_mortar_night.NSCR',
    'preview_graphic_mt_silver_day.NSCR',
    'preview_graphic_mt_silver_morning.NSCR',
    'preview_graphic_mt_silver_night.NSCR',
    'preview_graphic_national_park_day.NSCR',
    'preview_graphic_national_park_evening.NSCR',
    'preview_graphic_national_park_morning.NSCR',
    'preview_graphic_national_park_night.NSCR',
    'preview_graphic_rock_tunnel_day.NSCR',
    'preview_graphic_rock_tunnel_morning.NSCR',
    'preview_graphic_rock_tunnel_night.NSCR',
    'preview_graphic_ruins_of_alph_day.NSCR',
    'preview_graphic_ruins_of_alph_morning.NSCR',
    'preview_graphic_ruins_of_alph_night.NSCR',
    'preview_graphic_seafoam_islands_day.NSCR',
    'preview_graphic_seafoam_islands_morning.NSCR',
    'preview_graphic_seafoam_islands_night.NSCR',
    'preview_graphic_slowpoke_well_day.NSCR',
    'preview_graphic_slowpoke_well_morning.NSCR',
    'preview_graphic_slowpoke_well_night.NSCR',
    'preview_graphic_sprout_tower_day.NSCR',
    'preview_graphic_sprout_tower_morning.NSCR',
    'preview_graphic_sprout_tower_night.NSCR',
    'preview_graphic_tohjo_falls_day.NSCR',
    'preview_graphic_tohjo_falls_morning.NSCR',
    'preview_graphic_tohjo_falls_night.NSCR',
    'preview_graphic_union_cave_day.NSCR',
    'preview_graphic_union_cave_morning.NSCR',
    'preview_graphic_union_cave_night.NSCR',
    'preview_graphic_victory_road_day.NSCR',
    'preview_graphic_victory_road_morning.NSCR',
    'preview_graphic_victory_road_night.NSCR',
    'preview_graphic_viridian_forest_day.NSCR',
    'preview_graphic_viridian_forest_evening.NSCR',
    'preview_graphic_viridian_forest_morning.NSCR',
    'preview_graphic_viridian_forest_night.NSCR',
    'preview_graphic_whirl_islands_day.NSCR',
    'preview_graphic_whirl_islands_morning.NSCR',
    'preview_graphic_whirl_islands_night.NSCR',
))

preview_graphic_ncgr_lz = ncgr_lz_gen.process(preview_graphic_png,
        extra_args : VERSION101_SOPC_8BPP_NCGR_FLAGS
)
preview_graphic_nclr = nclr_gen.process(preview_graphic_png,
        extra_args : BPP8_NOPAD_NCLR_PNG_FLAGS
)
