namein_nclr = copy_gen.process(files(
    'namein_00000000.NCLR',
    'namein_00000001.NCLR',
))

namein_ncgr_lz = lz_gen.process(files(
    'namein_00000002.NCGR',
    'namein_00000003.NCGR',
    'namein_00000010.NCGR',
    'namein_00000011.NCGR',
    'namein_00000016.NCGR',
))

namein_nscr_lz = lz_gen.process(files(
    'namein_00000004.NSCR',
    'namein_00000005.NSCR',
    'namein_00000006.NSCR',
    'namein_00000007.NSCR',
    'namein_00000008.NSCR',
    'namein_00000009.NSCR',
    'namein_00000017.NSCR',
    'namein_00000018.NSCR',
))

namein_ncer_lz = lz_gen.process(files(
    'namein_00000012.NCER',
    'namein_00000013.NCER',
))

namein_nanr_lz = lz_gen.process(files(
    'namein_00000014.NANR',
    'namein_00000015.NANR',
))