#ifndef POKEHEARTGOLD_CONFIG_H
#define POKEHEARTGOLD_CONFIG_H

#define VERSION_HEARTGOLD 7
#define VERSION_SOULSILVER 8

#define LANGUAGE_ENGLISH 2

#undef GAME_VERSION
#ifdef HEARTGOLD
#define GAME_VERSION VERSION_HEARTGOLD
#else // SOULSILVER
#define GAME_VERSION VERSION_SOULSILVER
#endif

#undef GAME_LANGUAGE
#ifdef ENGLISH
#define GAME_LANGUAGE LANGUAGE_ENGLISH
#endif

#endif //POKEHEARTGOLD_CONFIG_H
