#ifndef GUARD_POKEHEARTGOLD_OVERLAY_36_H
#define GUARD_POKEHEARTGOLD_OVERLAY_36_H

#include "overlay_manager.h"

FS_EXTERN_OVERLAY(OVY_36);
extern const OverlayManagerTemplate ov36_App_MainMenu_SelectOption_Continue;
extern const OverlayManagerTemplate ov36_App_MainMenu_SelectOption_NewGame;
extern const OverlayManagerTemplate ov36_App_InitGameState_AfterOakSpeech;

#endif // GUARD_POKEHEARTGOLD_OVERLAY_36_H
