#ifndef POKEHEARTGOLD_SAVE_DATA_READ_ERROR_H
#define POKEHEARTGOLD_SAVE_DATA_READ_ERROR_H

#include "heap.h"

void ShowSaveDataReadError(HeapID heapId);

#endif //POKEHEARTGOLD_SAVE_DATA_READ_ERROR_H
