#ifndef POKEHEARTGOLD_SAVE_POKEATHLON_H
#define POKEHEARTGOLD_SAVE_POKEATHLON_H

#include "save.h"

typedef struct POKEATHLON_SAV POKEATHLON_SAV;

POKEATHLON_SAV *Save_Pokeathlon_get(SAVEDATA *saveData);
BOOL sub_02031A78(POKEATHLON_SAV *pokeathlon, int idx);

#endif //POKEHEARTGOLD_SAVE_POKEATHLON_H
