#ifndef POKEHEARTGOLD_UNK_02091278_H
#define POKEHEARTGOLD_UNK_02091278_H

#include "global.h"

#include "config.h"

#define DEX_LANGUAGE_FLAG_JAPANESE 0
#define DEX_LANGUAGE_FLAG_ENGLISH  1
#define DEX_LANGUAGE_FLAG_FRENCH   2
#define DEX_LANGUAGE_FLAG_GERMAN   3
#define DEX_LANGUAGE_FLAG_ITALIAN  4
#define DEX_LANGUAGE_FLAG_SPANISH  5
#define DEX_LANGUAGE_FLAG_MAX      6

#if GAME_LANGUAGE == LANGUAGE_JAPANESSE
#define DEX_LANGUAGE_FLAG_NATIVE DEX_LANGUAGE_FLAG_JAPANESE
#elif GAME_LANGUAGE == LANGUAGE_ENGLISH
#define DEX_LANGUAGE_FLAG_NATIVE DEX_LANGUAGE_FLAG_ENGLISH
#elif GAME_LANGUAGE == LANGUAGE_FRENCH
#define DEX_LANGUAGE_FLAG_NATIVE DEX_LANGUAGE_FLAG_FRENCH
#elif GAME_LANGUAGE == LANGUAGE_GERMAN
#define DEX_LANGUAGE_FLAG_NATIVE DEX_LANGUAGE_FLAG_GERMAN
#elif GAME_LANGUAGE == LANGUAGE_ITALIAN
#define DEX_LANGUAGE_FLAG_NATIVE DEX_LANGUAGE_FLAG_ITALIAN
#elif GAME_LANGUAGE == LANGUAGE_SPANISH
#define DEX_LANGUAGE_FLAG_NATIVE DEX_LANGUAGE_FLAG_SPANISH
#else
#error "Unsupported language"
#endif

int LanguageToDexFlag(u32 language);
int sub_02091294(int index);

#endif // POKEHEARTGOLD_UNK_02091278_H
