#ifndef POKEHEARTGOLD_WFC_USER_INFO_WARNING_H
#define POKEHEARTGOLD_WFC_USER_INFO_WARNING_H

#include "heap.h"

void ShowWFCUserInfoWarning(HeapID heapId, int a1);

#endif // POKEHEARTGOLD_WFC_USER_INFO_WARNING_H
