#ifndef POKEHEARTGOLD_CONSTANTS_BATTLE_TRAINER_AI_H
#define POKEHEARTGOLD_CONSTANTS_BATTLE_TRAINER_AI_H

#define AI_INIT_SCORE_MOVE_1 (1 << 0)
#define AI_INIT_SCORE_MOVE_2 (1 << 1)
#define AI_INIT_SCORE_MOVE_3 (1 << 2)
#define AI_INIT_SCORE_MOVE_4 (1 << 3)

#define AI_INIT_SCORE_ALL_MOVES (AI_INIT_SCORE_MOVE_1 | AI_INIT_SCORE_MOVE_2 | AI_INIT_SCORE_MOVE_3 | AI_INIT_SCORE_MOVE_4)

#define AI_STATUS_FLAG_DONE     (1 << 0)
#define AI_STATUS_FLAG_ESCAPE   (1 << 1)
#define AI_STATUS_FLAG_SAFARI   (1 << 2)
#define AI_STATUS_FLAG_BREAK    (1 << 3)
#define AI_STATUS_FLAG_CONTINUE (1 << 4)

#define AI_STATUS_FLAG_DONE_OFF     (AI_STATUS_FLAG_DONE ^ 0xFF)
#define AI_STATUS_FLAG_ESCAPE_OFF   (AI_STATUS_FLAG_ESCAPE ^ 0xFF)
#define AI_STATUS_FLAG_SAFARI_OFF   (AI_STATUS_FLAG_SAFARI ^ 0xFF)
#define AI_STATUS_FLAG_BREAK_OFF    (AI_STATUS_FLAG_BREAK ^ 0xFF)
#define AI_STATUS_FLAG_CONTINUE_OFF (AI_STATUS_FLAG_CONTINUE ^ 0xFF)

#endif // POKEHEARTGOLD_CONSTANTS_BATTLE_TRAINER_AI_H
