#ifndef POKEHEARTGOLD_CONSTANTS_BATTLE_TRAINER_AI_H
#define POKEHEARTGOLD_CONSTANTS_BATTLE_TRAINER_AI_H

#define AI_INIT_SCORE_MOVE_1 (1 << 0)
#define AI_INIT_SCORE_MOVE_2 (1 << 1)
#define AI_INIT_SCORE_MOVE_3 (1 << 2)
#define AI_INIT_SCORE_MOVE_4 (1 << 3)

#define AI_INIT_SCORE_ALL_MOVES (AI_INIT_SCORE_MOVE_1 | AI_INIT_SCORE_MOVE_2 | AI_INIT_SCORE_MOVE_3 | AI_INIT_SCORE_MOVE_4)

#define AI_STATUS_FLAG_DONE     (1 << 0)
#define AI_STATUS_FLAG_ESCAPE   (1 << 1)
#define AI_STATUS_FLAG_SAFARI   (1 << 2)
#define AI_STATUS_FLAG_BREAK    (1 << 3)
#define AI_STATUS_FLAG_CONTINUE (1 << 4)

#define AI_STATUS_FLAG_DONE_OFF     (AI_STATUS_FLAG_DONE ^ 0xFF)
#define AI_STATUS_FLAG_ESCAPE_OFF   (AI_STATUS_FLAG_ESCAPE ^ 0xFF)
#define AI_STATUS_FLAG_SAFARI_OFF   (AI_STATUS_FLAG_SAFARI ^ 0xFF)
#define AI_STATUS_FLAG_BREAK_OFF    (AI_STATUS_FLAG_BREAK ^ 0xFF)
#define AI_STATUS_FLAG_CONTINUE_OFF (AI_STATUS_FLAG_CONTINUE ^ 0xFF)

#define AI_BATTLER_DEFENDER         0
#define AI_BATTLER_ATTACKER         1
#define AI_BATTLER_DEFENDER_PARTNER (AI_BATTLER_DEFENDER ^ 2)
#define AI_BATTLER_ATTACKER_PARTNER (AI_BATTLER_ATTACKER ^ 2)

#define AI_MAX_STACK_SIZE 8

#define AI_NO_COMPARISON_MADE     0
#define AI_NOT_HIGHEST_DAMAGE     1
#define AI_MOVE_IS_HIGHEST_DAMAGE 2

#define AI_NOT_HAVE 0
#define AI_HAVE     1
#define AI_UNKNOWN  2

#define USE_MAX_DAMAGE  0
#define ROLL_FOR_DAMAGE 1

#define CHECK_DISABLE 0
#define CHECK_ENCORE  1

#define CHECK_LEVEL_HIGHER_THAN_TARGET 0
#define CHECK_LEVEL_LOWER_THAN_TARGET  1
#define CHECK_LEVEL_EQUAL_TO_TARGET    2

#define LOAD_DEFENDER_TYPE_1         0
#define LOAD_ATTACKER_TYPE_1         1
#define LOAD_DEFENDER_TYPE_2         2
#define LOAD_ATTACKER_TYPE_2         3     
#define LOAD_MOVE_TYPE               4
#define LOAD_DEFENDER_PARTNER_TYPE_1 5
#define LOAD_ATTACKER_PARTNER_TYPE_1 6
#define LOAD_DEFENDER_PARTNER_TYPE_2 7
#define LOAD_ATTACKER_PARTNER_TYPE_2 8

#define AI_WEATHER_CLEAR     0
#define AI_WEATHER_SUNNY     1
#define AI_WEATHER_RAINING   2
#define AI_WEATHER_SANDSTORM 3
#define AI_WEATHER_HAILING   4
#define AI_WEATHER_DEEP_FOG  5

#endif // POKEHEARTGOLD_CONSTANTS_BATTLE_TRAINER_AI_H
