#ifndef POKEHEARTGOLD_CONSTANTS_BATTLE_TRAINER_AI_H
#define POKEHEARTGOLD_CONSTANTS_BATTLE_TRAINER_AI_H

#define AI_INIT_SCORE_MOVE_1 (1 << 0)
#define AI_INIT_SCORE_MOVE_2 (1 << 1)
#define AI_INIT_SCORE_MOVE_3 (1 << 2)
#define AI_INIT_SCORE_MOVE_4 (1 << 3)

#define AI_INIT_SCORE_ALL_MOVES (AI_INIT_SCORE_MOVE_1 | AI_INIT_SCORE_MOVE_2 | AI_INIT_SCORE_MOVE_3 | AI_INIT_SCORE_MOVE_4)

#define AI_STATUS_FLAG_0        (1 << 0)
#define AI_STATUS_FLAG_ESCAPE   (1 << 1)
#define AI_STATUS_FLAG_SAFARI   (1 << 2)
#define AI_STATUS_FLAG_3        (1 << 3)
#define AI_STATUS_FLAG_CONTINUE (1 << 4)

#endif // POKEHEARTGOLD_CONSTANTS_BATTLE_TRAINER_AI_H
