otherpoke_index_ncgr += {
    '0134' : files('land/back.png'),
    '0135' : files('land/front.png'),
    '0136' : files('sky/back.png'),
    '0137' : files('sky/front.png'),
}

otherpoke_index_nclr += {
    '232' : files('land/front.png'),
    '233' : files('land/back.png'),
    '234' : files('sky/front.png'),
    '235' : files('sky/back.png'),
}