resdat_json = files(
    'resdat_00000000.json',
    'resdat_00000001.json',
    'resdat_00000002.json',
    'resdat_00000003.json',
    'resdat_00000004.json',
    'resdat_00000005.json',
    'resdat_00000006.json',
    'resdat_00000007.json',
    'resdat_00000008.json',
    'resdat_00000009.json',
    'resdat_00000010.json',
    'resdat_00000011.json',
    'resdat_00000012.json',
    'resdat_00000013.json',
    'resdat_00000014.json',
    'resdat_00000015.json',
    'resdat_00000016.json',
    'resdat_00000017.json',
    'resdat_00000018.json',
    'resdat_00000019.json',
    'resdat_00000020.json',
    'resdat_00000021.json',
    'resdat_00000022.json',
    'resdat_00000023.json',
    'resdat_00000024.json',
    'resdat_00000025.json',
    'resdat_00000026.json',
    'resdat_00000027.json',
    'resdat_00000028.json',
    'resdat_00000029.json',
    'resdat_00000030.json',
    'resdat_00000031.json',
    'resdat_00000032.json',
    'resdat_00000033.json',
    'resdat_00000034.json',
    'resdat_00000035.json',
    'resdat_00000036.json',
    'resdat_00000037.json',
    'resdat_00000038.json',
    'resdat_00000039.json',
    'resdat_00000040.json',
    'resdat_00000041.json',
    'resdat_00000042.json',
    'resdat_00000043.json',
    'resdat_00000044.json',
    'resdat_00000045.json',
    'resdat_00000046.json',
    'resdat_00000047.json',
    'resdat_00000048.json',
    'resdat_00000049.json',
    'resdat_00000050.json',
    'resdat_00000051.json',
    'resdat_00000052.json',
    'resdat_00000053.json',
    'resdat_00000054.json',
    'resdat_00000055.json',
    'resdat_00000056.json',
    'resdat_00000057.json',
    'resdat_00000058.json',
    'resdat_00000059.json',
    'resdat_00000060.json',
    'resdat_00000061.json',
    'resdat_00000062.json',
    'resdat_00000063.json',
    'resdat_00000064.json',
    'resdat_00000065.json',
    'resdat_00000066.json',
    'resdat_00000067.json',
    'resdat_00000068.json',
    'resdat_00000069.json',
    'resdat_00000070.json',
    'resdat_00000071.json',
    'resdat_00000072.json',
    'resdat_00000073.json',
    'resdat_00000074.json',
    'resdat_00000075.json',
    'resdat_00000076.json',
    'resdat_00000077.json',
    'resdat_00000078.json',
    'resdat_00000079.json',
    'resdat_00000080.json',
    'resdat_00000081.json',
    'resdat_00000082.json',
    'resdat_00000083.json',
    'resdat_00000084.json',
    'resdat_00000085.json',
    'resdat_00000086.json',
    'resdat_00000087.json',
    'resdat_00000088.json',
    'resdat_00000089.json',
)