# Collect ROM inputs and SHA-sums
icon_png_ss = files('icon.png')

rom_header_template_ss = files('rom_header_template.sbin')

main_sha1_ss = files('main.sha1')
filesystem_sha1_ss = files('filesystem.sha1')
rom_sha1_ss = files('rom.sha1')

rom_ini_ss = files('rom.ini')
filesys_csv_ss = files('filesystem.csv')
