nitrorom_exe = find_program('bin/makerom.exe') #this will eventually be nitrorom.exe like in plat

subdir('compstatic')
subdir('csv2bin')
subdir('jsonproc')
subdir('msgenc')
subdir('nitrogfx')
subdir('o2narc')
subdir('ordergen')
subdir('postconf')
subdir('scripts')

# Tools from the subprojects
makelcf_exe = find_program('makelcf', native: true)
