#include "script.h"
#include "map_object_manager.h"
#include "save_follow_poke.h"
#include "script_pokemon_util.h"
#include "field_map_object.h"
#include "map_header.h"
#include "field_follow_poke.h"
#include "constants/scrcmd.h"
#include "constants/follow_poke_idx.h"

static void FieldSystemFollowMonClear(FollowMon *followMon);
static void FollowingPoke_SetObjectShinyFlag(LocalMapObject *mapObject, BOOL enable);
static BOOL FollowPokePermissionDiglettCheck(int mapno);
static void FollowingPoke_SetObjectFormParam(LocalMapObject *mapObject, int species, u8 form);
static LocalMapObject *CreateFollowingSpriteFieldObject(MapObjectManager *mapObjectMan, int species, u16 form, int gender, int direction, int x, int y, int shiny);

static const u16 sModelIndexLUT[] = {
    FOLLOWER_MON_NONE,
    FOLLOWER_MON_BULBASAUR,
    FOLLOWER_MON_IVYSAUR,
    FOLLOWER_MON_VENUSAUR,
    FOLLOWER_MON_CHARMANDER,
    FOLLOWER_MON_CHARMELEON,
    FOLLOWER_MON_CHARIZARD,
    FOLLOWER_MON_SQUIRTLE,
    FOLLOWER_MON_WARTORTLE,
    FOLLOWER_MON_BLASTOISE,
    FOLLOWER_MON_CATERPIE,
    FOLLOWER_MON_METAPOD,
    FOLLOWER_MON_BUTTERFREE,
    FOLLOWER_MON_WEEDLE,
    FOLLOWER_MON_KAKUNA,
    FOLLOWER_MON_BEEDRILL,
    FOLLOWER_MON_PIDGEY,
    FOLLOWER_MON_PIDGEOTTO,
    FOLLOWER_MON_PIDGEOT,
    FOLLOWER_MON_RATTATA,
    FOLLOWER_MON_RATICATE,
    FOLLOWER_MON_SPEAROW,
    FOLLOWER_MON_FEAROW,
    FOLLOWER_MON_EKANS,
    FOLLOWER_MON_ARBOK,
    FOLLOWER_MON_PIKACHU,
    FOLLOWER_MON_RAICHU,
    FOLLOWER_MON_SANDSHREW,
    FOLLOWER_MON_SANDSLASH,
    FOLLOWER_MON_NIDORAN_F,
    FOLLOWER_MON_NIDORINA,
    FOLLOWER_MON_NIDOQUEEN,
    FOLLOWER_MON_NIDORAN_M,
    FOLLOWER_MON_NIDORINO,
    FOLLOWER_MON_NIDOKING,
    FOLLOWER_MON_CLEFAIRY,
    FOLLOWER_MON_CLEFABLE,
    FOLLOWER_MON_VULPIX,
    FOLLOWER_MON_NINETALES,
    FOLLOWER_MON_JIGGLYPUFF,
    FOLLOWER_MON_WIGGLYTUFF,
    FOLLOWER_MON_ZUBAT,
    FOLLOWER_MON_GOLBAT,
    FOLLOWER_MON_ODDISH,
    FOLLOWER_MON_GLOOM,
    FOLLOWER_MON_VILEPLUME,
    FOLLOWER_MON_PARAS,
    FOLLOWER_MON_PARASECT,
    FOLLOWER_MON_VENONAT,
    FOLLOWER_MON_VENOMOTH,
    FOLLOWER_MON_DIGLETT,
    FOLLOWER_MON_DUGTRIO,
    FOLLOWER_MON_MEOWTH,
    FOLLOWER_MON_PERSIAN,
    FOLLOWER_MON_PSYDUCK,
    FOLLOWER_MON_GOLDUCK,
    FOLLOWER_MON_MANKEY,
    FOLLOWER_MON_PRIMEAPE,
    FOLLOWER_MON_GROWLITHE,
    FOLLOWER_MON_ARCANINE,
    FOLLOWER_MON_POLIWAG,
    FOLLOWER_MON_POLIWHIRL,
    FOLLOWER_MON_POLIWRATH,
    FOLLOWER_MON_ABRA,
    FOLLOWER_MON_KADABRA,
    FOLLOWER_MON_ALAKAZAM,
    FOLLOWER_MON_MACHOP,
    FOLLOWER_MON_MACHOKE,
    FOLLOWER_MON_MACHAMP,
    FOLLOWER_MON_BELLSPROUT,
    FOLLOWER_MON_WEEPINBELL,
    FOLLOWER_MON_VICTREEBEL,
    FOLLOWER_MON_TENTACOOL,
    FOLLOWER_MON_TENTACRUEL,
    FOLLOWER_MON_GEODUDE,
    FOLLOWER_MON_GRAVELER,
    FOLLOWER_MON_GOLEM,
    FOLLOWER_MON_PONYTA,
    FOLLOWER_MON_RAPIDASH,
    FOLLOWER_MON_SLOWPOKE,
    FOLLOWER_MON_SLOWBRO,
    FOLLOWER_MON_MAGNEMITE,
    FOLLOWER_MON_MAGNETON,
    FOLLOWER_MON_FARFETCHD,
    FOLLOWER_MON_DODUO,
    FOLLOWER_MON_DODRIO,
    FOLLOWER_MON_SEEL,
    FOLLOWER_MON_DEWGONG,
    FOLLOWER_MON_GRIMER,
    FOLLOWER_MON_MUK,
    FOLLOWER_MON_SHELLDER,
    FOLLOWER_MON_CLOYSTER,
    FOLLOWER_MON_GASTLY,
    FOLLOWER_MON_HAUNTER,
    FOLLOWER_MON_GENGAR,
    FOLLOWER_MON_ONIX,
    FOLLOWER_MON_DROWZEE,
    FOLLOWER_MON_HYPNO,
    FOLLOWER_MON_KRABBY,
    FOLLOWER_MON_KINGLER,
    FOLLOWER_MON_VOLTORB,
    FOLLOWER_MON_ELECTRODE,
    FOLLOWER_MON_EXEGGCUTE,
    FOLLOWER_MON_EXEGGUTOR,
    FOLLOWER_MON_CUBONE,
    FOLLOWER_MON_MAROWAK,
    FOLLOWER_MON_HITMONLEE,
    FOLLOWER_MON_HITMONCHAN,
    FOLLOWER_MON_LICKITUNG,
    FOLLOWER_MON_KOFFING,
    FOLLOWER_MON_WEEZING,
    FOLLOWER_MON_RHYHORN,
    FOLLOWER_MON_RHYDON,
    FOLLOWER_MON_CHANSEY,
    FOLLOWER_MON_TANGELA,
    FOLLOWER_MON_KANGASKHAN,
    FOLLOWER_MON_HORSEA,
    FOLLOWER_MON_SEADRA,
    FOLLOWER_MON_GOLDEEN,
    FOLLOWER_MON_SEAKING,
    FOLLOWER_MON_STARYU,
    FOLLOWER_MON_STARMIE,
    FOLLOWER_MON_MR_MIME,
    FOLLOWER_MON_SCYTHER,
    FOLLOWER_MON_JYNX,
    FOLLOWER_MON_ELECTABUZZ,
    FOLLOWER_MON_MAGMAR,
    FOLLOWER_MON_PINSIR,
    FOLLOWER_MON_TAUROS,
    FOLLOWER_MON_MAGIKARP,
    FOLLOWER_MON_GYARADOS,
    FOLLOWER_MON_LAPRAS,
    FOLLOWER_MON_DITTO,
    FOLLOWER_MON_EEVEE,
    FOLLOWER_MON_VAPOREON,
    FOLLOWER_MON_JOLTEON,
    FOLLOWER_MON_FLAREON,
    FOLLOWER_MON_PORYGON,
    FOLLOWER_MON_OMANYTE,
    FOLLOWER_MON_OMASTAR,
    FOLLOWER_MON_KABUTO,
    FOLLOWER_MON_KABUTOPS,
    FOLLOWER_MON_AERODACTYL,
    FOLLOWER_MON_SNORLAX,
    FOLLOWER_MON_ARTICUNO,
    FOLLOWER_MON_ZAPDOS,
    FOLLOWER_MON_MOLTRES,
    FOLLOWER_MON_DRATINI,
    FOLLOWER_MON_DRAGONAIR,
    FOLLOWER_MON_DRAGONITE,
    FOLLOWER_MON_MEWTWO,
    FOLLOWER_MON_MEW,
    FOLLOWER_MON_CHIKORITA,
    FOLLOWER_MON_BAYLEEF,
    FOLLOWER_MON_MEGANIUM,
    FOLLOWER_MON_CYNDAQUIL,
    FOLLOWER_MON_QUILAVA,
    FOLLOWER_MON_TYPHLOSION,
    FOLLOWER_MON_TOTODILE,
    FOLLOWER_MON_CROCONAW,
    FOLLOWER_MON_FERALIGATR,
    FOLLOWER_MON_SENTRET,
    FOLLOWER_MON_FURRET,
    FOLLOWER_MON_HOOTHOOT,
    FOLLOWER_MON_NOCTOWL,
    FOLLOWER_MON_LEDYBA,
    FOLLOWER_MON_LEDIAN,
    FOLLOWER_MON_SPINARAK,
    FOLLOWER_MON_ARIADOS,
    FOLLOWER_MON_CROBAT,
    FOLLOWER_MON_CHINCHOU,
    FOLLOWER_MON_LANTURN,
    FOLLOWER_MON_PICHU,
    FOLLOWER_MON_CLEFFA,
    FOLLOWER_MON_IGGLYBUFF,
    FOLLOWER_MON_TOGEPI,
    FOLLOWER_MON_TOGETIC,
    FOLLOWER_MON_NATU,
    FOLLOWER_MON_XATU,
    FOLLOWER_MON_MAREEP,
    FOLLOWER_MON_FLAAFFY,
    FOLLOWER_MON_AMPHAROS,
    FOLLOWER_MON_BELLOSSOM,
    FOLLOWER_MON_MARILL,
    FOLLOWER_MON_AZUMARILL,
    FOLLOWER_MON_SUDOWOODO,
    FOLLOWER_MON_POLITOED,
    FOLLOWER_MON_HOPPIP,
    FOLLOWER_MON_SKIPLOOM,
    FOLLOWER_MON_JUMPLUFF,
    FOLLOWER_MON_AIPOM,
    FOLLOWER_MON_SUNKERN,
    FOLLOWER_MON_SUNFLORA,
    FOLLOWER_MON_YANMA,
    FOLLOWER_MON_WOOPER,
    FOLLOWER_MON_QUAGSIRE,
    FOLLOWER_MON_ESPEON,
    FOLLOWER_MON_UMBREON,
    FOLLOWER_MON_MURKROW,
    FOLLOWER_MON_SLOWKING,
    FOLLOWER_MON_MISDREAVUS,
    FOLLOWER_MON_UNOWN_A,
    FOLLOWER_MON_WOBBUFFET,
    FOLLOWER_MON_GIRAFARIG,
    FOLLOWER_MON_PINECO,
    FOLLOWER_MON_FORRETRESS,
    FOLLOWER_MON_DUNSPARCE,
    FOLLOWER_MON_GLIGAR,
    FOLLOWER_MON_STEELIX,
    FOLLOWER_MON_SNUBBULL,
    FOLLOWER_MON_GRANBULL,
    FOLLOWER_MON_QWILFISH,
    FOLLOWER_MON_SCIZOR,
    FOLLOWER_MON_SHUCKLE,
    FOLLOWER_MON_HERACROSS,
    FOLLOWER_MON_SNEASEL,
    FOLLOWER_MON_TEDDIURSA,
    FOLLOWER_MON_URSARING,
    FOLLOWER_MON_SLUGMA,
    FOLLOWER_MON_MAGCARGO,
    FOLLOWER_MON_SWINUB,
    FOLLOWER_MON_PILOSWINE,
    FOLLOWER_MON_CORSOLA,
    FOLLOWER_MON_REMORAID,
    FOLLOWER_MON_OCTILLERY,
    FOLLOWER_MON_DELIBIRD,
    FOLLOWER_MON_MANTINE,
    FOLLOWER_MON_SKARMORY,
    FOLLOWER_MON_HOUNDOUR,
    FOLLOWER_MON_HOUNDOOM,
    FOLLOWER_MON_KINGDRA,
    FOLLOWER_MON_PHANPY,
    FOLLOWER_MON_DONPHAN,
    FOLLOWER_MON_PORYGON2,
    FOLLOWER_MON_STANTLER,
    FOLLOWER_MON_SMEARGLE,
    FOLLOWER_MON_TYROGUE,
    FOLLOWER_MON_HITMONTOP,
    FOLLOWER_MON_SMOOCHUM,
    FOLLOWER_MON_ELEKID,
    FOLLOWER_MON_MAGBY,
    FOLLOWER_MON_MILTANK,
    FOLLOWER_MON_BLISSEY,
    FOLLOWER_MON_RAIKOU,
    FOLLOWER_MON_ENTEI,
    FOLLOWER_MON_SUICUNE,
    FOLLOWER_MON_LARVITAR,
    FOLLOWER_MON_PUPITAR,
    FOLLOWER_MON_TYRANITAR,
    FOLLOWER_MON_LUGIA,
    FOLLOWER_MON_HO_OH,
    FOLLOWER_MON_CELEBI,
    FOLLOWER_MON_TREECKO,
    FOLLOWER_MON_GROVYLE,
    FOLLOWER_MON_SCEPTILE,
    FOLLOWER_MON_TORCHIC,
    FOLLOWER_MON_COMBUSKEN,
    FOLLOWER_MON_BLAZIKEN,
    FOLLOWER_MON_MUDKIP,
    FOLLOWER_MON_MARSHTOMP,
    FOLLOWER_MON_SWAMPERT,
    FOLLOWER_MON_POOCHYENA,
    FOLLOWER_MON_MIGHTYENA,
    FOLLOWER_MON_ZIGZAGOON,
    FOLLOWER_MON_LINOONE,
    FOLLOWER_MON_WURMPLE,
    FOLLOWER_MON_SILCOON,
    FOLLOWER_MON_BEAUTIFLY,
    FOLLOWER_MON_CASCOON,
    FOLLOWER_MON_DUSTOX,
    FOLLOWER_MON_LOTAD,
    FOLLOWER_MON_LOMBRE,
    FOLLOWER_MON_LUDICOLO,
    FOLLOWER_MON_SEEDOT,
    FOLLOWER_MON_NUZLEAF,
    FOLLOWER_MON_SHIFTRY,
    FOLLOWER_MON_TAILLOW,
    FOLLOWER_MON_SWELLOW,
    FOLLOWER_MON_WINGULL,
    FOLLOWER_MON_PELIPPER,
    FOLLOWER_MON_RALTS,
    FOLLOWER_MON_KIRLIA,
    FOLLOWER_MON_GARDEVOIR,
    FOLLOWER_MON_SURSKIT,
    FOLLOWER_MON_MASQUERAIN,
    FOLLOWER_MON_SHROOMISH,
    FOLLOWER_MON_BRELOOM,
    FOLLOWER_MON_SLAKOTH,
    FOLLOWER_MON_VIGOROTH,
    FOLLOWER_MON_SLAKING,
    FOLLOWER_MON_NINCADA,
    FOLLOWER_MON_NINJASK,
    FOLLOWER_MON_SHEDINJA,
    FOLLOWER_MON_WHISMUR,
    FOLLOWER_MON_LOUDRED,
    FOLLOWER_MON_EXPLOUD,
    FOLLOWER_MON_MAKUHITA,
    FOLLOWER_MON_HARIYAMA,
    FOLLOWER_MON_AZURILL,
    FOLLOWER_MON_NOSEPASS,
    FOLLOWER_MON_SKITTY,
    FOLLOWER_MON_DELCATTY,
    FOLLOWER_MON_SABLEYE,
    FOLLOWER_MON_MAWILE,
    FOLLOWER_MON_ARON,
    FOLLOWER_MON_LAIRON,
    FOLLOWER_MON_AGGRON,
    FOLLOWER_MON_MEDITITE,
    FOLLOWER_MON_MEDICHAM,
    FOLLOWER_MON_ELECTRIKE,
    FOLLOWER_MON_MANECTRIC,
    FOLLOWER_MON_PLUSLE,
    FOLLOWER_MON_MINUN,
    FOLLOWER_MON_VOLBEAT,
    FOLLOWER_MON_ILLUMISE,
    FOLLOWER_MON_ROSELIA,
    FOLLOWER_MON_GULPIN,
    FOLLOWER_MON_SWALOT,
    FOLLOWER_MON_CARVANHA,
    FOLLOWER_MON_SHARPEDO,
    FOLLOWER_MON_WAILMER,
    FOLLOWER_MON_WAILORD,
    FOLLOWER_MON_NUMEL,
    FOLLOWER_MON_CAMERUPT,
    FOLLOWER_MON_TORKOAL,
    FOLLOWER_MON_SPOINK,
    FOLLOWER_MON_GRUMPIG,
    FOLLOWER_MON_SPINDA,
    FOLLOWER_MON_TRAPINCH,
    FOLLOWER_MON_VIBRAVA,
    FOLLOWER_MON_FLYGON,
    FOLLOWER_MON_CACNEA,
    FOLLOWER_MON_CACTURNE,
    FOLLOWER_MON_SWABLU,
    FOLLOWER_MON_ALTARIA,
    FOLLOWER_MON_ZANGOOSE,
    FOLLOWER_MON_SEVIPER,
    FOLLOWER_MON_LUNATONE,
    FOLLOWER_MON_SOLROCK,
    FOLLOWER_MON_BARBOACH,
    FOLLOWER_MON_WHISCASH,
    FOLLOWER_MON_CORPHISH,
    FOLLOWER_MON_CRAWDAUNT,
    FOLLOWER_MON_BALTOY,
    FOLLOWER_MON_CLAYDOL,
    FOLLOWER_MON_LILEEP,
    FOLLOWER_MON_CRADILY,
    FOLLOWER_MON_ANORITH,
    FOLLOWER_MON_ARMALDO,
    FOLLOWER_MON_FEEBAS,
    FOLLOWER_MON_MILOTIC,
    FOLLOWER_MON_CASTFORM,
    FOLLOWER_MON_KECLEON,
    FOLLOWER_MON_SHUPPET,
    FOLLOWER_MON_BANETTE,
    FOLLOWER_MON_DUSKULL,
    FOLLOWER_MON_DUSCLOPS,
    FOLLOWER_MON_TROPIUS,
    FOLLOWER_MON_CHIMECHO,
    FOLLOWER_MON_ABSOL,
    FOLLOWER_MON_WYNAUT,
    FOLLOWER_MON_SNORUNT,
    FOLLOWER_MON_GLALIE,
    FOLLOWER_MON_SPHEAL,
    FOLLOWER_MON_SEALEO,
    FOLLOWER_MON_WALREIN,
    FOLLOWER_MON_CLAMPERL,
    FOLLOWER_MON_HUNTAIL,
    FOLLOWER_MON_GOREBYSS,
    FOLLOWER_MON_RELICANTH,
    FOLLOWER_MON_LUVDISC,
    FOLLOWER_MON_BAGON,
    FOLLOWER_MON_SHELGON,
    FOLLOWER_MON_SALAMENCE,
    FOLLOWER_MON_BELDUM,
    FOLLOWER_MON_METANG,
    FOLLOWER_MON_METAGROSS,
    FOLLOWER_MON_REGIROCK,
    FOLLOWER_MON_REGICE,
    FOLLOWER_MON_REGISTEEL,
    FOLLOWER_MON_LATIAS,
    FOLLOWER_MON_LATIOS,
    FOLLOWER_MON_KYOGRE,
    FOLLOWER_MON_GROUDON,
    FOLLOWER_MON_RAYQUAZA,
    FOLLOWER_MON_JIRACHI,
    FOLLOWER_MON_DEOXYS,
    FOLLOWER_MON_TURTWIG,
    FOLLOWER_MON_GROTLE,
    FOLLOWER_MON_TORTERRA,
    FOLLOWER_MON_CHIMCHAR,
    FOLLOWER_MON_MONFERNO,
    FOLLOWER_MON_INFERNAPE,
    FOLLOWER_MON_PIPLUP,
    FOLLOWER_MON_PRINPLUP,
    FOLLOWER_MON_EMPOLEON,
    FOLLOWER_MON_STARLY,
    FOLLOWER_MON_STARAVIA,
    FOLLOWER_MON_STARAPTOR,
    FOLLOWER_MON_BIDOOF,
    FOLLOWER_MON_BIBAREL,
    FOLLOWER_MON_KRICKETOT,
    FOLLOWER_MON_KRICKETUNE,
    FOLLOWER_MON_SHINX,
    FOLLOWER_MON_LUXIO,
    FOLLOWER_MON_LUXRAY,
    FOLLOWER_MON_BUDEW,
    FOLLOWER_MON_ROSERADE,
    FOLLOWER_MON_CRANIDOS,
    FOLLOWER_MON_RAMPARDOS,
    FOLLOWER_MON_SHIELDON,
    FOLLOWER_MON_BASTIODON,
    FOLLOWER_MON_BURMY,
    FOLLOWER_MON_WORMADAM,
    FOLLOWER_MON_MOTHIM,
    FOLLOWER_MON_COMBEE,
    FOLLOWER_MON_VESPIQUEN,
    FOLLOWER_MON_PACHIRISU,
    FOLLOWER_MON_BUIZEL,
    FOLLOWER_MON_FLOATZEL,
    FOLLOWER_MON_CHERUBI,
    FOLLOWER_MON_CHERRIM,
    FOLLOWER_MON_SHELLOS_WEST,
    FOLLOWER_MON_GASTRODON_WEST,
    FOLLOWER_MON_AMBIPOM,
    FOLLOWER_MON_DRIFLOON,
    FOLLOWER_MON_DRIFBLIM,
    FOLLOWER_MON_BUNEARY,
    FOLLOWER_MON_LOPUNNY,
    FOLLOWER_MON_MISMAGIUS,
    FOLLOWER_MON_HONCHKROW,
    FOLLOWER_MON_GLAMEOW,
    FOLLOWER_MON_PURUGLY,
    FOLLOWER_MON_CHINGLING,
    FOLLOWER_MON_STUNKY,
    FOLLOWER_MON_SKUNTANK,
    FOLLOWER_MON_BRONZOR,
    FOLLOWER_MON_BRONZONG,
    FOLLOWER_MON_BONSLY,
    FOLLOWER_MON_MIME_JR,
    FOLLOWER_MON_HAPPINY,
    FOLLOWER_MON_CHATOT,
    FOLLOWER_MON_SPIRITOMB,
    FOLLOWER_MON_GIBLE,
    FOLLOWER_MON_GABITE,
    FOLLOWER_MON_GARCHOMP,
    FOLLOWER_MON_MUNCHLAX,
    FOLLOWER_MON_RIOLU,
    FOLLOWER_MON_LUCARIO,
    FOLLOWER_MON_HIPPOPOTAS,
    FOLLOWER_MON_HIPPOWDON,
    FOLLOWER_MON_SKORUPI,
    FOLLOWER_MON_DRAPION,
    FOLLOWER_MON_CROAGUNK,
    FOLLOWER_MON_TOXICROAK,
    FOLLOWER_MON_CARNIVINE,
    FOLLOWER_MON_FINNEON,
    FOLLOWER_MON_LUMINEON,
    FOLLOWER_MON_MANTYKE,
    FOLLOWER_MON_SNOVER,
    FOLLOWER_MON_ABOMASNOW,
    FOLLOWER_MON_WEAVILE,
    FOLLOWER_MON_MAGNEZONE,
    FOLLOWER_MON_LICKILICKY,
    FOLLOWER_MON_RHYPERIOR,
    FOLLOWER_MON_TANGROWTH,
    FOLLOWER_MON_ELECTIVIRE,
    FOLLOWER_MON_MAGMORTAR,
    FOLLOWER_MON_TOGEKISS,
    FOLLOWER_MON_YANMEGA,
    FOLLOWER_MON_LEAFEON,
    FOLLOWER_MON_GLACEON,
    FOLLOWER_MON_GLISCOR,
    FOLLOWER_MON_MAMOSWINE,
    FOLLOWER_MON_PORYGON_Z,
    FOLLOWER_MON_GALLADE,
    FOLLOWER_MON_PROBOPASS,
    FOLLOWER_MON_DUSKNOIR,
    FOLLOWER_MON_FROSLASS,
    FOLLOWER_MON_ROTOM,
    FOLLOWER_MON_UXIE,
    FOLLOWER_MON_MESPRIT,
    FOLLOWER_MON_AZELF,
    FOLLOWER_MON_DIALGA,
    FOLLOWER_MON_PALKIA,
    FOLLOWER_MON_HEATRAN,
    FOLLOWER_MON_REGIGIGAS,
    FOLLOWER_MON_GIRATINA,
    FOLLOWER_MON_CRESSELIA,
    FOLLOWER_MON_PHIONE,
    FOLLOWER_MON_MANAPHY,
    FOLLOWER_MON_DARKRAI,
    FOLLOWER_MON_SHAYMIN,
    FOLLOWER_MON_ARCEUS_NORMAL,
};

static const u16 sFormMaxLUT[] = {
    0,          // SPECIES_BULBASAUR
    0,          // SPECIES_IVYSAUR
    0,          // SPECIES_VENUSAUR
    0,          // SPECIES_CHARMANDER
    0,          // SPECIES_CHARMELEON
    0,          // SPECIES_CHARIZARD
    0,          // SPECIES_SQUIRTLE
    0,          // SPECIES_WARTORTLE
    0,          // SPECIES_BLASTOISE
    0,          // SPECIES_CATERPIE
    0,          // SPECIES_METAPOD
    0,          // SPECIES_BUTTERFREE
    0,          // SPECIES_WEEDLE
    0,          // SPECIES_KAKUNA
    0,          // SPECIES_BEEDRILL
    0,          // SPECIES_PIDGEY
    0,          // SPECIES_PIDGEOTTO
    0,          // SPECIES_PIDGEOT
    0,          // SPECIES_RATTATA
    0,          // SPECIES_RATICATE
    0,          // SPECIES_SPEAROW
    0,          // SPECIES_FEAROW
    0,          // SPECIES_EKANS
    0,          // SPECIES_ARBOK
    0,          // SPECIES_PIKACHU
    0,          // SPECIES_RAICHU
    0,          // SPECIES_SANDSHREW
    0,          // SPECIES_SANDSLASH
    0,          // SPECIES_NIDORAN_F
    0,          // SPECIES_NIDORINA
    0,          // SPECIES_NIDOQUEEN
    0,          // SPECIES_NIDORAN_M
    0,          // SPECIES_NIDORINO
    0,          // SPECIES_NIDOKING
    0,          // SPECIES_CLEFAIRY
    0,          // SPECIES_CLEFABLE
    0,          // SPECIES_VULPIX
    0,          // SPECIES_NINETALES
    0,          // SPECIES_JIGGLYPUFF
    0,          // SPECIES_WIGGLYTUFF
    0,          // SPECIES_ZUBAT
    0,          // SPECIES_GOLBAT
    0,          // SPECIES_ODDISH
    0,          // SPECIES_GLOOM
    0,          // SPECIES_VILEPLUME
    0,          // SPECIES_PARAS
    0,          // SPECIES_PARASECT
    0,          // SPECIES_VENONAT
    0,          // SPECIES_VENOMOTH
    0,          // SPECIES_DIGLETT
    0,          // SPECIES_DUGTRIO
    0,          // SPECIES_MEOWTH
    0,          // SPECIES_PERSIAN
    0,          // SPECIES_PSYDUCK
    0,          // SPECIES_GOLDUCK
    0,          // SPECIES_MANKEY
    0,          // SPECIES_PRIMEAPE
    0,          // SPECIES_GROWLITHE
    0,          // SPECIES_ARCANINE
    0,          // SPECIES_POLIWAG
    0,          // SPECIES_POLIWHIRL
    0,          // SPECIES_POLIWRATH
    0,          // SPECIES_ABRA
    0,          // SPECIES_KADABRA
    0,          // SPECIES_ALAKAZAM
    0,          // SPECIES_MACHOP
    0,          // SPECIES_MACHOKE
    0,          // SPECIES_MACHAMP
    0,          // SPECIES_BELLSPROUT
    0,          // SPECIES_WEEPINBELL
    0,          // SPECIES_VICTREEBEL
    0,          // SPECIES_TENTACOOL
    0,          // SPECIES_TENTACRUEL
    0,          // SPECIES_GEODUDE
    0,          // SPECIES_GRAVELER
    0,          // SPECIES_GOLEM
    0,          // SPECIES_PONYTA
    0,          // SPECIES_RAPIDASH
    0,          // SPECIES_SLOWPOKE
    0,          // SPECIES_SLOWBRO
    0,          // SPECIES_MAGNEMITE
    0,          // SPECIES_MAGNETON
    0,          // SPECIES_FARFETCHD
    0,          // SPECIES_DODUO
    0,          // SPECIES_DODRIO
    0,          // SPECIES_SEEL
    0,          // SPECIES_DEWGONG
    0,          // SPECIES_GRIMER
    0,          // SPECIES_MUK
    0,          // SPECIES_SHELLDER
    0,          // SPECIES_CLOYSTER
    0,          // SPECIES_GASTLY
    0,          // SPECIES_HAUNTER
    0,          // SPECIES_GENGAR
    0,          // SPECIES_ONIX
    0,          // SPECIES_DROWZEE
    0,          // SPECIES_HYPNO
    0,          // SPECIES_KRABBY
    0,          // SPECIES_KINGLER
    0,          // SPECIES_VOLTORB
    0,          // SPECIES_ELECTRODE
    0,          // SPECIES_EXEGGCUTE
    0,          // SPECIES_EXEGGUTOR
    0,          // SPECIES_CUBONE
    0,          // SPECIES_MAROWAK
    0,          // SPECIES_HITMONLEE
    0,          // SPECIES_HITMONCHAN
    0,          // SPECIES_LICKITUNG
    0,          // SPECIES_KOFFING
    0,          // SPECIES_WEEZING
    0,          // SPECIES_RHYHORN
    0,          // SPECIES_RHYDON
    0,          // SPECIES_CHANSEY
    0,          // SPECIES_TANGELA
    0,          // SPECIES_KANGASKHAN
    0,          // SPECIES_HORSEA
    0,          // SPECIES_SEADRA
    0,          // SPECIES_GOLDEEN
    0,          // SPECIES_SEAKING
    0,          // SPECIES_STARYU
    0,          // SPECIES_STARMIE
    0,          // SPECIES_MR_MIME
    0,          // SPECIES_SCYTHER
    0,          // SPECIES_JYNX
    0,          // SPECIES_ELECTABUZZ
    0,          // SPECIES_MAGMAR
    0,          // SPECIES_PINSIR
    0,          // SPECIES_TAUROS
    0,          // SPECIES_MAGIKARP
    0,          // SPECIES_GYARADOS
    0,          // SPECIES_LAPRAS
    0,          // SPECIES_DITTO
    0,          // SPECIES_EEVEE
    0,          // SPECIES_VAPOREON
    0,          // SPECIES_JOLTEON
    0,          // SPECIES_FLAREON
    0,          // SPECIES_PORYGON
    0,          // SPECIES_OMANYTE
    0,          // SPECIES_OMASTAR
    0,          // SPECIES_KABUTO
    0,          // SPECIES_KABUTOPS
    0,          // SPECIES_AERODACTYL
    0,          // SPECIES_SNORLAX
    0,          // SPECIES_ARTICUNO
    0,          // SPECIES_ZAPDOS
    0,          // SPECIES_MOLTRES
    0,          // SPECIES_DRATINI
    0,          // SPECIES_DRAGONAIR
    0,          // SPECIES_DRAGONITE
    0,          // SPECIES_MEWTWO
    0,          // SPECIES_MEW
    0,          // SPECIES_CHIKORITA
    0,          // SPECIES_BAYLEEF
    0,          // SPECIES_MEGANIUM
    0,          // SPECIES_CYNDAQUIL
    0,          // SPECIES_QUILAVA
    0,          // SPECIES_TYPHLOSION
    0,          // SPECIES_TOTODILE
    0,          // SPECIES_CROCONAW
    0,          // SPECIES_FERALIGATR
    0,          // SPECIES_SENTRET
    0,          // SPECIES_FURRET
    0,          // SPECIES_HOOTHOOT
    0,          // SPECIES_NOCTOWL
    0,          // SPECIES_LEDYBA
    0,          // SPECIES_LEDIAN
    0,          // SPECIES_SPINARAK
    0,          // SPECIES_ARIADOS
    0,          // SPECIES_CROBAT
    0,          // SPECIES_CHINCHOU
    0,          // SPECIES_LANTURN
    1,          // SPECIES_PICHU
    0,          // SPECIES_CLEFFA
    0,          // SPECIES_IGGLYBUFF
    0,          // SPECIES_TOGEPI
    0,          // SPECIES_TOGETIC
    0,          // SPECIES_NATU
    0,          // SPECIES_XATU
    0,          // SPECIES_MAREEP
    0,          // SPECIES_FLAAFFY
    0,          // SPECIES_AMPHAROS
    0,          // SPECIES_BELLOSSOM
    0,          // SPECIES_MARILL
    0,          // SPECIES_AZUMARILL
    0,          // SPECIES_SUDOWOODO
    0,          // SPECIES_POLITOED
    0,          // SPECIES_HOPPIP
    0,          // SPECIES_SKIPLOOM
    0,          // SPECIES_JUMPLUFF
    0,          // SPECIES_AIPOM
    0,          // SPECIES_SUNKERN
    0,          // SPECIES_SUNFLORA
    0,          // SPECIES_YANMA
    0,          // SPECIES_WOOPER
    0,          // SPECIES_QUAGSIRE
    0,          // SPECIES_ESPEON
    0,          // SPECIES_UMBREON
    0,          // SPECIES_MURKROW
    0,          // SPECIES_SLOWKING
    0,          // SPECIES_MISDREAVUS
    27,         // SPECIES_UNOWN
    0,          // SPECIES_WOBBUFFET
    0,          // SPECIES_GIRAFARIG
    0,          // SPECIES_PINECO
    0,          // SPECIES_FORRETRESS
    0,          // SPECIES_DUNSPARCE
    0,          // SPECIES_GLIGAR
    0,          // SPECIES_STEELIX
    0,          // SPECIES_SNUBBULL
    0,          // SPECIES_GRANBULL
    0,          // SPECIES_QWILFISH
    0,          // SPECIES_SCIZOR
    0,          // SPECIES_SHUCKLE
    0,          // SPECIES_HERACROSS
    0,          // SPECIES_SNEASEL
    0,          // SPECIES_TEDDIURSA
    0,          // SPECIES_URSARING
    0,          // SPECIES_SLUGMA
    0,          // SPECIES_MAGCARGO
    0,          // SPECIES_SWINUB
    0,          // SPECIES_PILOSWINE
    0,          // SPECIES_CORSOLA
    0,          // SPECIES_REMORAID
    0,          // SPECIES_OCTILLERY
    0,          // SPECIES_DELIBIRD
    0,          // SPECIES_MANTINE
    0,          // SPECIES_SKARMORY
    0,          // SPECIES_HOUNDOUR
    0,          // SPECIES_HOUNDOOM
    0,          // SPECIES_KINGDRA
    0,          // SPECIES_PHANPY
    0,          // SPECIES_DONPHAN
    0,          // SPECIES_PORYGON2
    0,          // SPECIES_STANTLER
    0,          // SPECIES_SMEARGLE
    0,          // SPECIES_TYROGUE
    0,          // SPECIES_HITMONTOP
    0,          // SPECIES_SMOOCHUM
    0,          // SPECIES_ELEKID
    0,          // SPECIES_MAGBY
    0,          // SPECIES_MILTANK
    0,          // SPECIES_BLISSEY
    0,          // SPECIES_RAIKOU
    0,          // SPECIES_ENTEI
    0,          // SPECIES_SUICUNE
    0,          // SPECIES_LARVITAR
    0,          // SPECIES_PUPITAR
    0,          // SPECIES_TYRANITAR
    0,          // SPECIES_LUGIA
    0,          // SPECIES_HO_OH
    0,          // SPECIES_CELEBI
    0,          // SPECIES_TREECKO
    0,          // SPECIES_GROVYLE
    0,          // SPECIES_SCEPTILE
    0,          // SPECIES_TORCHIC
    0,          // SPECIES_COMBUSKEN
    0,          // SPECIES_BLAZIKEN
    0,          // SPECIES_MUDKIP
    0,          // SPECIES_MARSHTOMP
    0,          // SPECIES_SWAMPERT
    0,          // SPECIES_POOCHYENA
    0,          // SPECIES_MIGHTYENA
    0,          // SPECIES_ZIGZAGOON
    0,          // SPECIES_LINOONE
    0,          // SPECIES_WURMPLE
    0,          // SPECIES_SILCOON
    0,          // SPECIES_BEAUTIFLY
    0,          // SPECIES_CASCOON
    0,          // SPECIES_DUSTOX
    0,          // SPECIES_LOTAD
    0,          // SPECIES_LOMBRE
    0,          // SPECIES_LUDICOLO
    0,          // SPECIES_SEEDOT
    0,          // SPECIES_NUZLEAF
    0,          // SPECIES_SHIFTRY
    0,          // SPECIES_TAILLOW
    0,          // SPECIES_SWELLOW
    0,          // SPECIES_WINGULL
    0,          // SPECIES_PELIPPER
    0,          // SPECIES_RALTS
    0,          // SPECIES_KIRLIA
    0,          // SPECIES_GARDEVOIR
    0,          // SPECIES_SURSKIT
    0,          // SPECIES_MASQUERAIN
    0,          // SPECIES_SHROOMISH
    0,          // SPECIES_BRELOOM
    0,          // SPECIES_SLAKOTH
    0,          // SPECIES_VIGOROTH
    0,          // SPECIES_SLAKING
    0,          // SPECIES_NINCADA
    0,          // SPECIES_NINJASK
    0,          // SPECIES_SHEDINJA
    0,          // SPECIES_WHISMUR
    0,          // SPECIES_LOUDRED
    0,          // SPECIES_EXPLOUD
    0,          // SPECIES_MAKUHITA
    0,          // SPECIES_HARIYAMA
    0,          // SPECIES_AZURILL
    0,          // SPECIES_NOSEPASS
    0,          // SPECIES_SKITTY
    0,          // SPECIES_DELCATTY
    0,          // SPECIES_SABLEYE
    0,          // SPECIES_MAWILE
    0,          // SPECIES_ARON
    0,          // SPECIES_LAIRON
    0,          // SPECIES_AGGRON
    0,          // SPECIES_MEDITITE
    0,          // SPECIES_MEDICHAM
    0,          // SPECIES_ELECTRIKE
    0,          // SPECIES_MANECTRIC
    0,          // SPECIES_PLUSLE
    0,          // SPECIES_MINUN
    0,          // SPECIES_VOLBEAT
    0,          // SPECIES_ILLUMISE
    0,          // SPECIES_ROSELIA
    0,          // SPECIES_GULPIN
    0,          // SPECIES_SWALOT
    0,          // SPECIES_CARVANHA
    0,          // SPECIES_SHARPEDO
    0,          // SPECIES_WAILMER
    0,          // SPECIES_WAILORD
    0,          // SPECIES_NUMEL
    0,          // SPECIES_CAMERUPT
    0,          // SPECIES_TORKOAL
    0,          // SPECIES_SPOINK
    0,          // SPECIES_GRUMPIG
    0,          // SPECIES_SPINDA
    0,          // SPECIES_TRAPINCH
    0,          // SPECIES_VIBRAVA
    0,          // SPECIES_FLYGON
    0,          // SPECIES_CACNEA
    0,          // SPECIES_CACTURNE
    0,          // SPECIES_SWABLU
    0,          // SPECIES_ALTARIA
    0,          // SPECIES_ZANGOOSE
    0,          // SPECIES_SEVIPER
    0,          // SPECIES_LUNATONE
    0,          // SPECIES_SOLROCK
    0,          // SPECIES_BARBOACH
    0,          // SPECIES_WHISCASH
    0,          // SPECIES_CORPHISH
    0,          // SPECIES_CRAWDAUNT
    0,          // SPECIES_BALTOY
    0,          // SPECIES_CLAYDOL
    0,          // SPECIES_LILEEP
    0,          // SPECIES_CRADILY
    0,          // SPECIES_ANORITH
    0,          // SPECIES_ARMALDO
    0,          // SPECIES_FEEBAS
    0,          // SPECIES_MILOTIC
    0,          // SPECIES_CASTFORM
    0,          // SPECIES_KECLEON
    0,          // SPECIES_SHUPPET
    0,          // SPECIES_BANETTE
    0,          // SPECIES_DUSKULL
    0,          // SPECIES_DUSCLOPS
    0,          // SPECIES_TROPIUS
    0,          // SPECIES_CHIMECHO
    0,          // SPECIES_ABSOL
    0,          // SPECIES_WYNAUT
    0,          // SPECIES_SNORUNT
    0,          // SPECIES_GLALIE
    0,          // SPECIES_SPHEAL
    0,          // SPECIES_SEALEO
    0,          // SPECIES_WALREIN
    0,          // SPECIES_CLAMPERL
    0,          // SPECIES_HUNTAIL
    0,          // SPECIES_GOREBYSS
    0,          // SPECIES_RELICANTH
    0,          // SPECIES_LUVDISC
    0,          // SPECIES_BAGON
    0,          // SPECIES_SHELGON
    0,          // SPECIES_SALAMENCE
    0,          // SPECIES_BELDUM
    0,          // SPECIES_METANG
    0,          // SPECIES_METAGROSS
    0,          // SPECIES_REGIROCK
    0,          // SPECIES_REGICE
    0,          // SPECIES_REGISTEEL
    0,          // SPECIES_LATIAS
    0,          // SPECIES_LATIOS
    0,          // SPECIES_KYOGRE
    0,          // SPECIES_GROUDON
    0,          // SPECIES_RAYQUAZA
    0,          // SPECIES_JIRACHI
    3,          // SPECIES_DEOXYS
    0,          // SPECIES_TURTWIG
    0,          // SPECIES_GROTLE
    0,          // SPECIES_TORTERRA
    0,          // SPECIES_CHIMCHAR
    0,          // SPECIES_MONFERNO
    0,          // SPECIES_INFERNAPE
    0,          // SPECIES_PIPLUP
    0,          // SPECIES_PRINPLUP
    0,          // SPECIES_EMPOLEON
    0,          // SPECIES_STARLY
    0,          // SPECIES_STARAVIA
    0,          // SPECIES_STARAPTOR
    0,          // SPECIES_BIDOOF
    0,          // SPECIES_BIBAREL
    0,          // SPECIES_KRICKETOT
    0,          // SPECIES_KRICKETUNE
    0,          // SPECIES_SHINX
    0,          // SPECIES_LUXIO
    0,          // SPECIES_LUXRAY
    0,          // SPECIES_BUDEW
    0,          // SPECIES_ROSERADE
    0,          // SPECIES_CRANIDOS
    0,          // SPECIES_RAMPARDOS
    0,          // SPECIES_SHIELDON
    0,          // SPECIES_BASTIODON
    2,          // SPECIES_BURMY
    2,          // SPECIES_WORMADAM
    0,          // SPECIES_MOTHIM
    0,          // SPECIES_COMBEE
    0,          // SPECIES_VESPIQUEN
    0,          // SPECIES_PACHIRISU
    0,          // SPECIES_BUIZEL
    0,          // SPECIES_FLOATZEL
    0,          // SPECIES_CHERUBI
    0,          // SPECIES_CHERRIM
    1,          // SPECIES_SHELLOS
    1,          // SPECIES_GASTRODON
    0,          // SPECIES_AMBIPOM
    0,          // SPECIES_DRIFLOON
    0,          // SPECIES_DRIFBLIM
    0,          // SPECIES_BUNEARY
    0,          // SPECIES_LOPUNNY
    0,          // SPECIES_MISMAGIUS
    0,          // SPECIES_HONCHKROW
    0,          // SPECIES_GLAMEOW
    0,          // SPECIES_PURUGLY
    0,          // SPECIES_CHINGLING
    0,          // SPECIES_STUNKY
    0,          // SPECIES_SKUNTANK
    0,          // SPECIES_BRONZOR
    0,          // SPECIES_BRONZONG
    0,          // SPECIES_BONSLY
    0,          // SPECIES_MIME_JR
    0,          // SPECIES_HAPPINY
    0,          // SPECIES_CHATOT
    0,          // SPECIES_SPIRITOMB
    0,          // SPECIES_GIBLE
    0,          // SPECIES_GABITE
    0,          // SPECIES_GARCHOMP
    0,          // SPECIES_MUNCHLAX
    0,          // SPECIES_RIOLU
    0,          // SPECIES_LUCARIO
    0,          // SPECIES_HIPPOPOTAS
    0,          // SPECIES_HIPPOWDON
    0,          // SPECIES_SKORUPI
    0,          // SPECIES_DRAPION
    0,          // SPECIES_CROAGUNK
    0,          // SPECIES_TOXICROAK
    0,          // SPECIES_CARNIVINE
    0,          // SPECIES_FINNEON
    0,          // SPECIES_LUMINEON
    0,          // SPECIES_MANTYKE
    0,          // SPECIES_SNOVER
    0,          // SPECIES_ABOMASNOW
    0,          // SPECIES_WEAVILE
    0,          // SPECIES_MAGNEZONE
    0,          // SPECIES_LICKILICKY
    0,          // SPECIES_RHYPERIOR
    0,          // SPECIES_TANGROWTH
    0,          // SPECIES_ELECTIVIRE
    0,          // SPECIES_MAGMORTAR
    0,          // SPECIES_TOGEKISS
    0,          // SPECIES_YANMEGA
    0,          // SPECIES_LEAFEON
    0,          // SPECIES_GLACEON
    0,          // SPECIES_GLISCOR
    0,          // SPECIES_MAMOSWINE
    0,          // SPECIES_PORYGON_Z
    0,          // SPECIES_GALLADE
    0,          // SPECIES_PROBOPASS
    0,          // SPECIES_DUSKNOIR
    0,          // SPECIES_FROSLASS
    5,          // SPECIES_ROTOM
    0,          // SPECIES_UXIE
    0,          // SPECIES_MESPRIT
    0,          // SPECIES_AZELF
    0,          // SPECIES_DIALGA
    0,          // SPECIES_PALKIA
    0,          // SPECIES_HEATRAN
    0,          // SPECIES_REGIGIGAS
    1,          // SPECIES_GIRATINA
    0,          // SPECIES_CRESSELIA
    0,          // SPECIES_PHIONE
    0,          // SPECIES_MANAPHY
    0,          // SPECIES_DARKRAI
    1,          // SPECIES_SHAYMIN
    17,         // SPECIES_ARCEUS
};

static const u16 sFemaleFlagLUT[] = {
    FALSE,      // SPECIES_BULBASAUR
    FALSE,      // SPECIES_IVYSAUR
    TRUE,       // SPECIES_VENUSAUR
    FALSE,      // SPECIES_CHARMANDER
    FALSE,      // SPECIES_CHARMELEON
    FALSE,      // SPECIES_CHARIZARD
    FALSE,      // SPECIES_SQUIRTLE
    FALSE,      // SPECIES_WARTORTLE
    FALSE,      // SPECIES_BLASTOISE
    FALSE,      // SPECIES_CATERPIE
    FALSE,      // SPECIES_METAPOD
    FALSE,      // SPECIES_BUTTERFREE
    FALSE,      // SPECIES_WEEDLE
    FALSE,      // SPECIES_KAKUNA
    FALSE,      // SPECIES_BEEDRILL
    FALSE,      // SPECIES_PIDGEY
    FALSE,      // SPECIES_PIDGEOTTO
    FALSE,      // SPECIES_PIDGEOT
    FALSE,      // SPECIES_RATTATA
    FALSE,      // SPECIES_RATICATE
    FALSE,      // SPECIES_SPEAROW
    FALSE,      // SPECIES_FEAROW
    FALSE,      // SPECIES_EKANS
    FALSE,      // SPECIES_ARBOK
    TRUE,       // SPECIES_PIKACHU
    FALSE,      // SPECIES_RAICHU
    FALSE,      // SPECIES_SANDSHREW
    FALSE,      // SPECIES_SANDSLASH
    FALSE,      // SPECIES_NIDORAN_F
    FALSE,      // SPECIES_NIDORINA
    FALSE,      // SPECIES_NIDOQUEEN
    FALSE,      // SPECIES_NIDORAN_M
    FALSE,      // SPECIES_NIDORINO
    FALSE,      // SPECIES_NIDOKING
    FALSE,      // SPECIES_CLEFAIRY
    FALSE,      // SPECIES_CLEFABLE
    FALSE,      // SPECIES_VULPIX
    FALSE,      // SPECIES_NINETALES
    FALSE,      // SPECIES_JIGGLYPUFF
    FALSE,      // SPECIES_WIGGLYTUFF
    FALSE,      // SPECIES_ZUBAT
    FALSE,      // SPECIES_GOLBAT
    FALSE,      // SPECIES_ODDISH
    FALSE,      // SPECIES_GLOOM
    FALSE,      // SPECIES_VILEPLUME
    FALSE,      // SPECIES_PARAS
    FALSE,      // SPECIES_PARASECT
    FALSE,      // SPECIES_VENONAT
    FALSE,      // SPECIES_VENOMOTH
    FALSE,      // SPECIES_DIGLETT
    FALSE,      // SPECIES_DUGTRIO
    FALSE,      // SPECIES_MEOWTH
    FALSE,      // SPECIES_PERSIAN
    FALSE,      // SPECIES_PSYDUCK
    FALSE,      // SPECIES_GOLDUCK
    FALSE,      // SPECIES_MANKEY
    FALSE,      // SPECIES_PRIMEAPE
    FALSE,      // SPECIES_GROWLITHE
    FALSE,      // SPECIES_ARCANINE
    FALSE,      // SPECIES_POLIWAG
    FALSE,      // SPECIES_POLIWHIRL
    FALSE,      // SPECIES_POLIWRATH
    FALSE,      // SPECIES_ABRA
    FALSE,      // SPECIES_KADABRA
    FALSE,      // SPECIES_ALAKAZAM
    FALSE,      // SPECIES_MACHOP
    FALSE,      // SPECIES_MACHOKE
    FALSE,      // SPECIES_MACHAMP
    FALSE,      // SPECIES_BELLSPROUT
    FALSE,      // SPECIES_WEEPINBELL
    FALSE,      // SPECIES_VICTREEBEL
    FALSE,      // SPECIES_TENTACOOL
    FALSE,      // SPECIES_TENTACRUEL
    FALSE,      // SPECIES_GEODUDE
    FALSE,      // SPECIES_GRAVELER
    FALSE,      // SPECIES_GOLEM
    FALSE,      // SPECIES_PONYTA
    FALSE,      // SPECIES_RAPIDASH
    FALSE,      // SPECIES_SLOWPOKE
    FALSE,      // SPECIES_SLOWBRO
    FALSE,      // SPECIES_MAGNEMITE
    FALSE,      // SPECIES_MAGNETON
    FALSE,      // SPECIES_FARFETCHD
    FALSE,      // SPECIES_DODUO
    FALSE,      // SPECIES_DODRIO
    FALSE,      // SPECIES_SEEL
    FALSE,      // SPECIES_DEWGONG
    FALSE,      // SPECIES_GRIMER
    FALSE,      // SPECIES_MUK
    FALSE,      // SPECIES_SHELLDER
    FALSE,      // SPECIES_CLOYSTER
    FALSE,      // SPECIES_GASTLY
    FALSE,      // SPECIES_HAUNTER
    FALSE,      // SPECIES_GENGAR
    FALSE,      // SPECIES_ONIX
    FALSE,      // SPECIES_DROWZEE
    FALSE,      // SPECIES_HYPNO
    FALSE,      // SPECIES_KRABBY
    FALSE,      // SPECIES_KINGLER
    FALSE,      // SPECIES_VOLTORB
    FALSE,      // SPECIES_ELECTRODE
    FALSE,      // SPECIES_EXEGGCUTE
    FALSE,      // SPECIES_EXEGGUTOR
    FALSE,      // SPECIES_CUBONE
    FALSE,      // SPECIES_MAROWAK
    FALSE,      // SPECIES_HITMONLEE
    FALSE,      // SPECIES_HITMONCHAN
    FALSE,      // SPECIES_LICKITUNG
    FALSE,      // SPECIES_KOFFING
    FALSE,      // SPECIES_WEEZING
    FALSE,      // SPECIES_RHYHORN
    FALSE,      // SPECIES_RHYDON
    FALSE,      // SPECIES_CHANSEY
    FALSE,      // SPECIES_TANGELA
    FALSE,      // SPECIES_KANGASKHAN
    FALSE,      // SPECIES_HORSEA
    FALSE,      // SPECIES_SEADRA
    FALSE,      // SPECIES_GOLDEEN
    FALSE,      // SPECIES_SEAKING
    FALSE,      // SPECIES_STARYU
    FALSE,      // SPECIES_STARMIE
    FALSE,      // SPECIES_MR_MIME
    FALSE,      // SPECIES_SCYTHER
    FALSE,      // SPECIES_JYNX
    FALSE,      // SPECIES_ELECTABUZZ
    FALSE,      // SPECIES_MAGMAR
    FALSE,      // SPECIES_PINSIR
    FALSE,      // SPECIES_TAUROS
    FALSE,      // SPECIES_MAGIKARP
    FALSE,      // SPECIES_GYARADOS
    FALSE,      // SPECIES_LAPRAS
    FALSE,      // SPECIES_DITTO
    FALSE,      // SPECIES_EEVEE
    FALSE,      // SPECIES_VAPOREON
    FALSE,      // SPECIES_JOLTEON
    FALSE,      // SPECIES_FLAREON
    FALSE,      // SPECIES_PORYGON
    FALSE,      // SPECIES_OMANYTE
    FALSE,      // SPECIES_OMASTAR
    FALSE,      // SPECIES_KABUTO
    FALSE,      // SPECIES_KABUTOPS
    FALSE,      // SPECIES_AERODACTYL
    FALSE,      // SPECIES_SNORLAX
    FALSE,      // SPECIES_ARTICUNO
    FALSE,      // SPECIES_ZAPDOS
    FALSE,      // SPECIES_MOLTRES
    FALSE,      // SPECIES_DRATINI
    FALSE,      // SPECIES_DRAGONAIR
    FALSE,      // SPECIES_DRAGONITE
    FALSE,      // SPECIES_MEWTWO
    FALSE,      // SPECIES_MEW
    FALSE,      // SPECIES_CHIKORITA
    FALSE,      // SPECIES_BAYLEEF
    TRUE,       // SPECIES_MEGANIUM
    FALSE,      // SPECIES_CYNDAQUIL
    FALSE,      // SPECIES_QUILAVA
    FALSE,      // SPECIES_TYPHLOSION
    FALSE,      // SPECIES_TOTODILE
    FALSE,      // SPECIES_CROCONAW
    FALSE,      // SPECIES_FERALIGATR
    FALSE,      // SPECIES_SENTRET
    FALSE,      // SPECIES_FURRET
    FALSE,      // SPECIES_HOOTHOOT
    FALSE,      // SPECIES_NOCTOWL
    FALSE,      // SPECIES_LEDYBA
    FALSE,      // SPECIES_LEDIAN
    FALSE,      // SPECIES_SPINARAK
    FALSE,      // SPECIES_ARIADOS
    FALSE,      // SPECIES_CROBAT
    FALSE,      // SPECIES_CHINCHOU
    FALSE,      // SPECIES_LANTURN
    FALSE,      // SPECIES_PICHU
    FALSE,      // SPECIES_CLEFFA
    FALSE,      // SPECIES_IGGLYBUFF
    FALSE,      // SPECIES_TOGEPI
    FALSE,      // SPECIES_TOGETIC
    FALSE,      // SPECIES_NATU
    FALSE,      // SPECIES_XATU
    FALSE,      // SPECIES_MAREEP
    FALSE,      // SPECIES_FLAAFFY
    FALSE,      // SPECIES_AMPHAROS
    FALSE,      // SPECIES_BELLOSSOM
    FALSE,      // SPECIES_MARILL
    FALSE,      // SPECIES_AZUMARILL
    FALSE,      // SPECIES_SUDOWOODO
    FALSE,      // SPECIES_POLITOED
    FALSE,      // SPECIES_HOPPIP
    FALSE,      // SPECIES_SKIPLOOM
    FALSE,      // SPECIES_JUMPLUFF
    FALSE,      // SPECIES_AIPOM
    FALSE,      // SPECIES_SUNKERN
    FALSE,      // SPECIES_SUNFLORA
    FALSE,      // SPECIES_YANMA
    FALSE,      // SPECIES_WOOPER
    FALSE,      // SPECIES_QUAGSIRE
    FALSE,      // SPECIES_ESPEON
    FALSE,      // SPECIES_UMBREON
    FALSE,      // SPECIES_MURKROW
    FALSE,      // SPECIES_SLOWKING
    FALSE,      // SPECIES_MISDREAVUS
    FALSE,      // SPECIES_UNOWN
    TRUE,       // SPECIES_WOBBUFFET
    FALSE,      // SPECIES_GIRAFARIG
    FALSE,      // SPECIES_PINECO
    FALSE,      // SPECIES_FORRETRESS
    FALSE,      // SPECIES_DUNSPARCE
    FALSE,      // SPECIES_GLIGAR
    TRUE,       // SPECIES_STEELIX
    FALSE,      // SPECIES_SNUBBULL
    FALSE,      // SPECIES_GRANBULL
    FALSE,      // SPECIES_QWILFISH
    FALSE,      // SPECIES_SCIZOR
    FALSE,      // SPECIES_SHUCKLE
    TRUE,       // SPECIES_HERACROSS
    FALSE,      // SPECIES_SNEASEL
    FALSE,      // SPECIES_TEDDIURSA
    FALSE,      // SPECIES_URSARING
    FALSE,      // SPECIES_SLUGMA
    FALSE,      // SPECIES_MAGCARGO
    FALSE,      // SPECIES_SWINUB
    FALSE,      // SPECIES_PILOSWINE
    FALSE,      // SPECIES_CORSOLA
    FALSE,      // SPECIES_REMORAID
    FALSE,      // SPECIES_OCTILLERY
    FALSE,      // SPECIES_DELIBIRD
    FALSE,      // SPECIES_MANTINE
    FALSE,      // SPECIES_SKARMORY
    FALSE,      // SPECIES_HOUNDOUR
    FALSE,      // SPECIES_HOUNDOOM
    FALSE,      // SPECIES_KINGDRA
    FALSE,      // SPECIES_PHANPY
    FALSE,      // SPECIES_DONPHAN
    FALSE,      // SPECIES_PORYGON2
    FALSE,      // SPECIES_STANTLER
    FALSE,      // SPECIES_SMEARGLE
    FALSE,      // SPECIES_TYROGUE
    FALSE,      // SPECIES_HITMONTOP
    FALSE,      // SPECIES_SMOOCHUM
    FALSE,      // SPECIES_ELEKID
    FALSE,      // SPECIES_MAGBY
    FALSE,      // SPECIES_MILTANK
    FALSE,      // SPECIES_BLISSEY
    FALSE,      // SPECIES_RAIKOU
    FALSE,      // SPECIES_ENTEI
    FALSE,      // SPECIES_SUICUNE
    FALSE,      // SPECIES_LARVITAR
    FALSE,      // SPECIES_PUPITAR
    FALSE,      // SPECIES_TYRANITAR
    FALSE,      // SPECIES_LUGIA
    FALSE,      // SPECIES_HO_OH
    FALSE,      // SPECIES_CELEBI
    FALSE,      // SPECIES_TREECKO
    FALSE,      // SPECIES_GROVYLE
    FALSE,      // SPECIES_SCEPTILE
    FALSE,      // SPECIES_TORCHIC
    FALSE,      // SPECIES_COMBUSKEN
    FALSE,      // SPECIES_BLAZIKEN
    FALSE,      // SPECIES_MUDKIP
    FALSE,      // SPECIES_MARSHTOMP
    FALSE,      // SPECIES_SWAMPERT
    FALSE,      // SPECIES_POOCHYENA
    FALSE,      // SPECIES_MIGHTYENA
    FALSE,      // SPECIES_ZIGZAGOON
    FALSE,      // SPECIES_LINOONE
    FALSE,      // SPECIES_WURMPLE
    FALSE,      // SPECIES_SILCOON
    FALSE,      // SPECIES_BEAUTIFLY
    FALSE,      // SPECIES_CASCOON
    FALSE,      // SPECIES_DUSTOX
    FALSE,      // SPECIES_LOTAD
    FALSE,      // SPECIES_LOMBRE
    FALSE,      // SPECIES_LUDICOLO
    FALSE,      // SPECIES_SEEDOT
    FALSE,      // SPECIES_NUZLEAF
    FALSE,      // SPECIES_SHIFTRY
    FALSE,      // SPECIES_TAILLOW
    FALSE,      // SPECIES_SWELLOW
    FALSE,      // SPECIES_WINGULL
    FALSE,      // SPECIES_PELIPPER
    FALSE,      // SPECIES_RALTS
    FALSE,      // SPECIES_KIRLIA
    FALSE,      // SPECIES_GARDEVOIR
    FALSE,      // SPECIES_SURSKIT
    FALSE,      // SPECIES_MASQUERAIN
    FALSE,      // SPECIES_SHROOMISH
    FALSE,      // SPECIES_BRELOOM
    FALSE,      // SPECIES_SLAKOTH
    FALSE,      // SPECIES_VIGOROTH
    FALSE,      // SPECIES_SLAKING
    FALSE,      // SPECIES_NINCADA
    FALSE,      // SPECIES_NINJASK
    FALSE,      // SPECIES_SHEDINJA
    FALSE,      // SPECIES_WHISMUR
    FALSE,      // SPECIES_LOUDRED
    FALSE,      // SPECIES_EXPLOUD
    FALSE,      // SPECIES_MAKUHITA
    FALSE,      // SPECIES_HARIYAMA
    FALSE,      // SPECIES_AZURILL
    FALSE,      // SPECIES_NOSEPASS
    FALSE,      // SPECIES_SKITTY
    FALSE,      // SPECIES_DELCATTY
    FALSE,      // SPECIES_SABLEYE
    FALSE,      // SPECIES_MAWILE
    FALSE,      // SPECIES_ARON
    FALSE,      // SPECIES_LAIRON
    FALSE,      // SPECIES_AGGRON
    FALSE,      // SPECIES_MEDITITE
    FALSE,      // SPECIES_MEDICHAM
    FALSE,      // SPECIES_ELECTRIKE
    FALSE,      // SPECIES_MANECTRIC
    FALSE,      // SPECIES_PLUSLE
    FALSE,      // SPECIES_MINUN
    FALSE,      // SPECIES_VOLBEAT
    FALSE,      // SPECIES_ILLUMISE
    FALSE,      // SPECIES_ROSELIA
    FALSE,      // SPECIES_GULPIN
    FALSE,      // SPECIES_SWALOT
    FALSE,      // SPECIES_CARVANHA
    FALSE,      // SPECIES_SHARPEDO
    FALSE,      // SPECIES_WAILMER
    FALSE,      // SPECIES_WAILORD
    FALSE,      // SPECIES_NUMEL
    FALSE,      // SPECIES_CAMERUPT
    FALSE,      // SPECIES_TORKOAL
    FALSE,      // SPECIES_SPOINK
    FALSE,      // SPECIES_GRUMPIG
    FALSE,      // SPECIES_SPINDA
    FALSE,      // SPECIES_TRAPINCH
    FALSE,      // SPECIES_VIBRAVA
    FALSE,      // SPECIES_FLYGON
    FALSE,      // SPECIES_CACNEA
    FALSE,      // SPECIES_CACTURNE
    FALSE,      // SPECIES_SWABLU
    FALSE,      // SPECIES_ALTARIA
    FALSE,      // SPECIES_ZANGOOSE
    FALSE,      // SPECIES_SEVIPER
    FALSE,      // SPECIES_LUNATONE
    FALSE,      // SPECIES_SOLROCK
    FALSE,      // SPECIES_BARBOACH
    FALSE,      // SPECIES_WHISCASH
    FALSE,      // SPECIES_CORPHISH
    FALSE,      // SPECIES_CRAWDAUNT
    FALSE,      // SPECIES_BALTOY
    FALSE,      // SPECIES_CLAYDOL
    FALSE,      // SPECIES_LILEEP
    FALSE,      // SPECIES_CRADILY
    FALSE,      // SPECIES_ANORITH
    FALSE,      // SPECIES_ARMALDO
    FALSE,      // SPECIES_FEEBAS
    FALSE,      // SPECIES_MILOTIC
    FALSE,      // SPECIES_CASTFORM
    FALSE,      // SPECIES_KECLEON
    FALSE,      // SPECIES_SHUPPET
    FALSE,      // SPECIES_BANETTE
    FALSE,      // SPECIES_DUSKULL
    FALSE,      // SPECIES_DUSCLOPS
    FALSE,      // SPECIES_TROPIUS
    FALSE,      // SPECIES_CHIMECHO
    FALSE,      // SPECIES_ABSOL
    FALSE,      // SPECIES_WYNAUT
    FALSE,      // SPECIES_SNORUNT
    FALSE,      // SPECIES_GLALIE
    FALSE,      // SPECIES_SPHEAL
    FALSE,      // SPECIES_SEALEO
    FALSE,      // SPECIES_WALREIN
    FALSE,      // SPECIES_CLAMPERL
    FALSE,      // SPECIES_HUNTAIL
    FALSE,      // SPECIES_GOREBYSS
    FALSE,      // SPECIES_RELICANTH
    FALSE,      // SPECIES_LUVDISC
    FALSE,      // SPECIES_BAGON
    FALSE,      // SPECIES_SHELGON
    FALSE,      // SPECIES_SALAMENCE
    FALSE,      // SPECIES_BELDUM
    FALSE,      // SPECIES_METANG
    FALSE,      // SPECIES_METAGROSS
    FALSE,      // SPECIES_REGIROCK
    FALSE,      // SPECIES_REGICE
    FALSE,      // SPECIES_REGISTEEL
    FALSE,      // SPECIES_LATIAS
    FALSE,      // SPECIES_LATIOS
    FALSE,      // SPECIES_KYOGRE
    FALSE,      // SPECIES_GROUDON
    FALSE,      // SPECIES_RAYQUAZA
    FALSE,      // SPECIES_JIRACHI
    FALSE,      // SPECIES_DEOXYS
    FALSE,      // SPECIES_TURTWIG
    FALSE,      // SPECIES_GROTLE
    FALSE,      // SPECIES_TORTERRA
    FALSE,      // SPECIES_CHIMCHAR
    FALSE,      // SPECIES_MONFERNO
    FALSE,      // SPECIES_INFERNAPE
    FALSE,      // SPECIES_PIPLUP
    FALSE,      // SPECIES_PRINPLUP
    FALSE,      // SPECIES_EMPOLEON
    FALSE,      // SPECIES_STARLY
    FALSE,      // SPECIES_STARAVIA
    FALSE,      // SPECIES_STARAPTOR
    FALSE,      // SPECIES_BIDOOF
    FALSE,      // SPECIES_BIBAREL
    FALSE,      // SPECIES_KRICKETOT
    FALSE,      // SPECIES_KRICKETUNE
    FALSE,      // SPECIES_SHINX
    FALSE,      // SPECIES_LUXIO
    FALSE,      // SPECIES_LUXRAY
    FALSE,      // SPECIES_BUDEW
    FALSE,      // SPECIES_ROSERADE
    FALSE,      // SPECIES_CRANIDOS
    FALSE,      // SPECIES_RAMPARDOS
    FALSE,      // SPECIES_SHIELDON
    FALSE,      // SPECIES_BASTIODON
    FALSE,      // SPECIES_BURMY
    FALSE,      // SPECIES_WORMADAM
    FALSE,      // SPECIES_MOTHIM
    TRUE,       // SPECIES_COMBEE
    FALSE,      // SPECIES_VESPIQUEN
    FALSE,      // SPECIES_PACHIRISU
    FALSE,      // SPECIES_BUIZEL
    FALSE,      // SPECIES_FLOATZEL
    FALSE,      // SPECIES_CHERUBI
    FALSE,      // SPECIES_CHERRIM
    FALSE,      // SPECIES_SHELLOS
    FALSE,      // SPECIES_GASTRODON
    FALSE,      // SPECIES_AMBIPOM
    FALSE,      // SPECIES_DRIFLOON
    FALSE,      // SPECIES_DRIFBLIM
    FALSE,      // SPECIES_BUNEARY
    FALSE,      // SPECIES_LOPUNNY
    FALSE,      // SPECIES_MISMAGIUS
    FALSE,      // SPECIES_HONCHKROW
    FALSE,      // SPECIES_GLAMEOW
    FALSE,      // SPECIES_PURUGLY
    FALSE,      // SPECIES_CHINGLING
    FALSE,      // SPECIES_STUNKY
    FALSE,      // SPECIES_SKUNTANK
    FALSE,      // SPECIES_BRONZOR
    FALSE,      // SPECIES_BRONZONG
    FALSE,      // SPECIES_BONSLY
    FALSE,      // SPECIES_MIME_JR
    FALSE,      // SPECIES_HAPPINY
    FALSE,      // SPECIES_CHATOT
    FALSE,      // SPECIES_SPIRITOMB
    TRUE,       // SPECIES_GIBLE
    TRUE,       // SPECIES_GABITE
    TRUE,       // SPECIES_GARCHOMP
    FALSE,      // SPECIES_MUNCHLAX
    FALSE,      // SPECIES_RIOLU
    FALSE,      // SPECIES_LUCARIO
    TRUE,       // SPECIES_HIPPOPOTAS
    TRUE,       // SPECIES_HIPPOWDON
    FALSE,      // SPECIES_SKORUPI
    FALSE,      // SPECIES_DRAPION
    FALSE,      // SPECIES_CROAGUNK
    FALSE,      // SPECIES_TOXICROAK
    FALSE,      // SPECIES_CARNIVINE
    FALSE,      // SPECIES_FINNEON
    FALSE,      // SPECIES_LUMINEON
    FALSE,      // SPECIES_MANTYKE
    FALSE,      // SPECIES_SNOVER
    FALSE,      // SPECIES_ABOMASNOW
    FALSE,      // SPECIES_WEAVILE
    FALSE,      // SPECIES_MAGNEZONE
    FALSE,      // SPECIES_LICKILICKY
    FALSE,      // SPECIES_RHYPERIOR
    FALSE,      // SPECIES_TANGROWTH
    FALSE,      // SPECIES_ELECTIVIRE
    FALSE,      // SPECIES_MAGMORTAR
    FALSE,      // SPECIES_TOGEKISS
    FALSE,      // SPECIES_YANMEGA
    FALSE,      // SPECIES_LEAFEON
    FALSE,      // SPECIES_GLACEON
    FALSE,      // SPECIES_GLISCOR
    FALSE,      // SPECIES_MAMOSWINE
    FALSE,      // SPECIES_PORYGON_Z
    FALSE,      // SPECIES_GALLADE
    FALSE,      // SPECIES_PROBOPASS
    FALSE,      // SPECIES_DUSKNOIR
    FALSE,      // SPECIES_FROSLASS
    FALSE,      // SPECIES_ROTOM
    FALSE,      // SPECIES_UXIE
    FALSE,      // SPECIES_MESPRIT
    FALSE,      // SPECIES_AZELF
    FALSE,      // SPECIES_DIALGA
    FALSE,      // SPECIES_PALKIA
    FALSE,      // SPECIES_HEATRAN
    FALSE,      // SPECIES_REGIGIGAS
    FALSE,      // SPECIES_GIRATINA
    FALSE,      // SPECIES_CRESSELIA
    FALSE,      // SPECIES_PHIONE
    FALSE,      // SPECIES_MANAPHY
    FALSE,      // SPECIES_DARKRAI
    FALSE,      // SPECIES_SHAYMIN
    FALSE,      // SPECIES_ARCEUS
};

LocalMapObject *sub_020699F8(MapObjectManager *mapObjectMan, int x, int y, int direction, u32 mapno) {
    FieldSystem *fieldSystem;
    Party *party;
    int partyCount;
    Pokemon *mon;
    int species;
    int form;
    int gender;
    int shiny;
    int player_unk;

    fieldSystem = MapObjectManager_GetFieldSysPtr(mapObjectMan);
    party = SaveArray_Party_Get(fieldSystem->saveData);
    partyCount = Party_GetCount(party);
    FieldSystemFollowMonClear(&fieldSystem->followMon);
    SavFollowPoke_SetUnused2bitField(0, Save_FollowPoke_Get(fieldSystem->saveData));
    if (partyCount != 0) {
        if (CountAlivePokemon(party) == 0) {
            mon = GetFirstNonEggInParty(party);
        } else {
            mon = GetFirstAliveMonInParty_CrashIfNone(party);
        }
        species = GetMonData(mon, MON_DATA_SPECIES, NULL);
        fieldSystem->followMon.mapObject = NULL;
        if (GetFollowPokePermissionBySpeciesAndMap(species, mapno)) {
            form = GetMonData(mon, MON_DATA_FORM, NULL);
            gender = GetMonData(mon, MON_DATA_GENDER, NULL);
            shiny = MonIsShiny(mon);
            fieldSystem->followMon.mapObject = CreateFollowingSpriteFieldObject(mapObjectMan, species, form, gender, direction, x, y, shiny);
            fieldSystem->followMon.active = TRUE;
            FieldSystem_SetFollowPokeParam(fieldSystem, species, form, shiny, gender);
            FieldSystemUnkSub108_Set(fieldSystem->unk108, mon, species, GetMonData(mon, MON_DATA_PERSONALITY, NULL));
            player_unk = PlayerAvatar_GetState(fieldSystem->playerAvatar);
            if (player_unk == 0 || player_unk == 3) {
                SavFollowPoke_SetUnused2bitField(1, Save_FollowPoke_Get(fieldSystem->saveData));
            } else if (player_unk == 1) {
                SavFollowPoke_SetUnused2bitField(2, Save_FollowPoke_Get(fieldSystem->saveData));
                sub_0206A054(fieldSystem);
                sub_0205FC94(FollowingPokemon_GetMapObject(fieldSystem), 56);
            } else if (player_unk == 2) {
                SavFollowPoke_SetUnused2bitField(2, Save_FollowPoke_Get(fieldSystem->saveData));
                sub_0206A054(fieldSystem);
                sub_0205FC94(FollowingPokemon_GetMapObject(fieldSystem), 56);
            } else {
                GF_ASSERT(0);
            }
            if (SavFollowPoke_GetInhibitFlagState(Save_FollowPoke_Get(fieldSystem->saveData))) {
                sub_0206A054(fieldSystem);
            }
        }
    }

    return fieldSystem->followMon.mapObject;
}

void sub_02069B74(MapObjectManager *mapObjectMan, u32 mapno) {
    FieldSystem *fieldSystem;
    Party *party;
    int partyCount;
    Pokemon *mon;
    int species;
    int form;
    u8 gender;
    int shiny;
    int player_unk;
    LocalMapObject *followPokeObj;

    fieldSystem = MapObjectManager_GetFieldSysPtr(mapObjectMan);
    party = SaveArray_Party_Get(fieldSystem->saveData);
    partyCount = Party_GetCount(party);
    FieldSystemFollowMonClear(&fieldSystem->followMon);
    if (partyCount != 0) {
        mon = GetFirstAliveMonInParty_CrashIfNone(party);
        species = GetMonData(mon, MON_DATA_SPECIES, NULL);
        FieldSystemUnkSub108_Set(fieldSystem->unk108, mon, species, GetMonData(mon, MON_DATA_PERSONALITY, NULL));
        if (GetFollowPokePermissionBySpeciesAndMap(species, mapno)) {
            followPokeObj = GetMapObjectByID(fieldSystem->mapObjectMan, obj_partner_poke);
            if (followPokeObj == NULL) {
                fieldSystem->followMon.unk15 = 1;
            } else {
                form = GetMonData(mon, MON_DATA_FORM, NULL);
                gender = GetMonGender(mon);
                shiny = MonIsShiny(mon);
                fieldSystem->followMon.mapObject = followPokeObj;
                fieldSystem->followMon.active = TRUE;
                FieldSystem_SetFollowPokeParam(fieldSystem, species, form, shiny, gender);
                FollowPokeMapObjectSetParams(followPokeObj, species, form, shiny);
                MapObject_SetGfxID(fieldSystem->followMon.mapObject, FollowingPokemon_GetSpriteID(species, form, gender));
                player_unk = PlayerAvatar_GetState(fieldSystem->playerAvatar);
                if (player_unk == 0 || player_unk == 3) {
                    SavFollowPoke_SetUnused2bitField(1, Save_FollowPoke_Get(fieldSystem->saveData));
                } else if (player_unk == 1) {
                    SavFollowPoke_SetUnused2bitField(2, Save_FollowPoke_Get(fieldSystem->saveData));
                    sub_0206A040(fieldSystem->followMon.mapObject, TRUE);
                } else if (player_unk == 2) {
                    SavFollowPoke_SetUnused2bitField(2, Save_FollowPoke_Get(fieldSystem->saveData));
                    sub_0206A040(fieldSystem->followMon.mapObject, TRUE);
                } else {
                    GF_ASSERT(0);
                }
                if (sub_02069E14(fieldSystem->followMon.mapObject)) {
                    sub_0206A040(fieldSystem->followMon.mapObject, TRUE);
                }
                if (SavFollowPoke_GetInhibitFlagState(Save_FollowPoke_Get(fieldSystem->saveData))) {
                    sub_0206A054(fieldSystem);
                }
                MapObject_ClearFlag18(fieldSystem->followMon.mapObject, FALSE);
            }
        } else {
            followPokeObj = GetMapObjectByID(fieldSystem->mapObjectMan, obj_partner_poke);
            if (followPokeObj != NULL) {
                form = GetMonData(mon, MON_DATA_FORM, NULL);
                gender = GetMonGender(mon);
                shiny = MonIsShiny(mon);
                FieldSystem_SetFollowPokeParam(fieldSystem, species, form, shiny, gender);
                FollowPokeMapObjectSetParams(followPokeObj, species, form, shiny);
                MapObject_SetGfxID(followPokeObj, FollowingPokemon_GetSpriteID(species, form, gender));
                fieldSystem->followMon.mapObject = followPokeObj;
                fieldSystem->followMon.active = TRUE;
                fieldSystem->followMon.unk15 = 1;
            }
        }
    }
}

LocalMapObject *FollowingPokemon_GetMapObject(FieldSystem *fieldSystem) {
    return fieldSystem->followMon.mapObject;
}

u32 FollowingPokemon_GetSpriteID(int species, u16 form, u32 gender) {
    int ret;

    if (species <= 0 || species > NATIONAL_DEX_COUNT) {
        ret = SPRITE_FOLLOWER_MON_BULBASAUR;
    } else {
        ret = SPRITE_FOLLOWER_MON_BULBASAUR + SpeciesToOverworldModelIndexOffset(species);
        if (OverworldModelLookupHasFemaleForm(species)) {
            if (gender == MON_FEMALE) {
                ret++;
            }
        } else {
            if (form > OverworldModelLookupFormCount(species)) {
                form = 0;
            }
            ret += form;
        }
        if (ret > SPRITE_FOLLOWER_MON_ARCEUS_DARK) {
            ret = SPRITE_FOLLOWER_MON_BULBASAUR;
        }
    }
    return ret;
}

void sub_02069DC8(LocalMapObject *mapObject, BOOL enable_bit) {
    sub_0206A040(mapObject, enable_bit);
    if (enable_bit) {
        sub_02069DEC(mapObject, TRUE);
    } else {
        sub_02069DEC(mapObject, FALSE);
    }
}

void sub_02069DEC(LocalMapObject *mapObject, BOOL enable_bit) {
    int value;
    u8 flag0;
    u32 flag1;
    u32 flag2;

    value = MapObject_GetParam(mapObject, 2);
    flag0 = value & 1;
    flag1 = enable_bit;
    flag2 = value >> 2;
    value = flag2 << 2;
    value |= flag1 << 1;
    value |= flag0 << 0;
    MapObject_SetParam(mapObject, value, 2);
}

u8 sub_02069E14(LocalMapObject *mapObject) {
    return (MapObject_GetParam(mapObject, 2) >> 1) & 1;
}

void sub_02069E28(LocalMapObject *mapObject, u32 a1) {
    int param;
    u16 r2;
    u16 b;

    param = MapObject_GetParam(mapObject, 2);

    r2 = param >> 10;
    b = r2 << 10;
    param = (u8) param;
    param |= b | (a1 << 8);

    MapObject_SetParam(mapObject, param, 2);
}

void sub_02069E50(LocalMapObject *mapObject, u8 a1) {
    int param;
    u32 b;

    GF_ASSERT(a1 <= 23);

    param = MapObject_GetParam(mapObject, 2);

    b = param & 0x3FF;
    param = (a1 << 10) | (u8)b;

    MapObject_SetParam(mapObject, param, 2);
}

void sub_02069E84(LocalMapObject *mapObject, u8 a1) {
    int param;
    u8 a;
    u32 b;

    param = MapObject_GetParam(mapObject, 2);

    a = param & 3;
    b = param >> 3;

    param = (b << 3) | (a1 << 2);
    param |= a;

    MapObject_SetParam(mapObject, param, 2);
}

u8 sub_02069EAC(LocalMapObject *mapObject) {
    return (MapObject_GetParam(mapObject, 2) >> 2) & 1;
}

u8 sub_02069EC0(LocalMapObject *mapObject) {
    return (MapObject_GetParam(mapObject, 2) >> 8) & 3;
}

u8 sub_02069ED4(LocalMapObject *mapObject) {
    return (MapObject_GetParam(mapObject, 2) >> 10) & 0x3F;
}

void FollowPokeMapObjectSetParams(LocalMapObject *mapObject, int species, u8 form, BOOL shiny) {
    FollowingPoke_SetObjectShinyFlag(mapObject, shiny);
    FollowingPoke_SetObjectFormParam(mapObject, species, form);
    MapObject_SetParam(mapObject, species, 0);
}

void sub_02069F0C(LocalMapObject *mapObject, int species, u8 form, BOOL shiny, int a4) {
    MapObject_SetParam(mapObject, a4, 2);
    FollowingPoke_SetObjectShinyFlag(mapObject, shiny);
    FollowingPoke_SetObjectFormParam(mapObject, species, form);
    MapObject_SetParam(mapObject, species, 0);
}

void FieldSystem_SetFollowPokeParam(FieldSystem *fieldSystem, int species, u8 form, BOOL shiny, u8 gender) {
    fieldSystem->followMon.species = species;
    fieldSystem->followMon.shiny = shiny;
    fieldSystem->followMon.form = form;
    fieldSystem->followMon.gender = gender;
}

u8 GetFollowPokeSizeParamBySpecies(int species) {
    u8 data[4];

    ReadWholeNarcMemberByIdPair(data, NARC_fielddata_tsurepoke_tp_param, SpeciesToOverworldModelIndexOffset(species));
    return data[1];
}

int FollowPokeObj_GetSpecies(LocalMapObject *mapObject) {
    return MapObject_GetParam(mapObject, 0);
}

BOOL FollowingPokemon_IsActive(FieldSystem *fieldSystem) {
    if (fieldSystem->followMon.active == 0) {
        return FALSE;
    }

    if (CountAlivePokemon(SaveArray_Party_Get(fieldSystem->saveData)) != 0) {
        return TRUE;
    } else {
        return FALSE;
    }
}

BOOL sub_02069FB0(FieldSystem *fieldSystem) {
    if (FollowingPokemon_IsActive(fieldSystem)) {
        if (!MapObject_CheckVisible(fieldSystem->followMon.mapObject)) {
            return TRUE;
        } else {
            return FALSE;
        }
    } else {
        return FALSE;
    }
}

BOOL GetFollowPokePermission(FieldSystem *fieldSystem) {
    u32 mapno;

    mapno = SavFollowPoke_GetMapId(Save_FollowPoke_Get(fieldSystem->saveData));
    return GetFollowPokePermissionBySpeciesAndMap(FollowPokeObj_GetSpecies(fieldSystem->followMon.mapObject), mapno);
}

BOOL GetFollowPokePermissionBySpeciesAndMap(int species, u32 mapno) {
    BOOL ret;
    if ((species == SPECIES_DIGLETT || species == SPECIES_DUGTRIO) && !FollowPokePermissionDiglettCheck(mapno)) {
        return FALSE;
    }

    switch (MapHeader_GetFollowMode(mapno)) {
    case MAP_FOLLOWMODE_PREVENT:
        ret = FALSE;
        break;
    case MAP_FOLLOWMODE_HEIGHT_RESTRICT:
        if (GetFollowPokeSizeParamBySpecies(species)) {
            ret = FALSE;
        } else {
            ret = TRUE;
        }
        break;
    case MAP_FOLLOWMODE_ALLOW:
        ret = TRUE;
        break;
    }

    return ret;
}

void sub_0206A040(LocalMapObject *mapObject, BOOL enable_bit) {
    MapObject_SetVisible(mapObject, enable_bit);
    MapObject_SetFlag19(mapObject, enable_bit);
}

void sub_0206A054(FieldSystem *fieldSystem) {
    LocalMapObject *obj = fieldSystem->followMon.mapObject;
    sub_02069DC8(obj, TRUE);
    sub_02069DEC(obj, FALSE);
}

static void FieldSystemFollowMonClear(FollowMon *followMon) {
    followMon->active = FALSE;
    followMon->mapObject = NULL;
    followMon->unk4 = 0;
    followMon->unk1C = 0;
    followMon->unk8 = 0;
    followMon->unkC = 0;
    followMon->unk15 = 0;
}

static void FollowingPoke_SetObjectShinyFlag(LocalMapObject *mapObject, BOOL enable) {
    int param;
    u32 val;

    param = MapObject_GetParam(mapObject, 2);
    val = param >> 1;

    param = val << 1;
    if (enable) {
        param |= 1;
    }

    MapObject_SetParam(mapObject, param, 2);
}

static BOOL FollowPokePermissionDiglettCheck(int mapno) {
    switch (mapno) {
    case MAP_D17R0101:
    case MAP_D17R0102:
    case MAP_D17R0103:
    case MAP_D17R0104:
    case MAP_D17R0105:
    case MAP_D17R0106:
    case MAP_D17R0107:
    case MAP_D17R0108:
    case MAP_D17R0109:
    case MAP_D17R0110:
    case MAP_D17R0112:
        return FALSE;
    default:
        return TRUE;
    }
}

static void FollowingPoke_SetObjectFormParam(LocalMapObject *mapObject, int species, u8 form) {
    u8 data[4];
    int offset;
    int formct;
    u16 param;

    offset = SpeciesToOverworldModelIndexOffset(species);
    formct = OverworldModelLookupFormCount(species);
    if (formct > 0) {
        if (form <= formct) {
            offset += form;
        } else {
            GF_ASSERT(0);
        }
    }
    ReadWholeNarcMemberByIdPair(data, NARC_fielddata_tsurepoke_tp_param, offset);
    param = (data[1] << 8) | data[2];
    MapObject_SetParam(mapObject, param, 1);
}

static LocalMapObject *CreateFollowingSpriteFieldObject(MapObjectManager *mapObjectMan, int species, u16 form, int gender, int direction, int x, int y, int shiny) {
    LocalMapObject *ret;

    ret = CreateSpecialFieldObject(
        mapObjectMan,
        x,
        y,
        direction,
        FollowingPokemon_GetSpriteID(species, form, gender),
        0x30,
        MAP_NOTHING
    );
    GF_ASSERT(ret != NULL);
    MapObject_SetID(ret, obj_partner_poke);
    MapObject_SetType(ret, 0);
    MapObject_SetFlagID(ret, 0);
    MapObject_SetScript(ret, std_following_mon);
    MapObject_SetParam(ret, 0, 2);
    FollowPokeMapObjectSetParams(ret, species, form, shiny);
    MapObject_SetXRange(ret, -1);
    MapObject_SetYRange(ret, -1);
    MapObject_SetFlagsBits(ret, MAPOBJECTFLAG_UNK13 | MAPOBJECTFLAG_UNK10);
    MapObject_ClearFlagsBits(ret, MAPOBJECTFLAG_UNK8 | MAPOBJECTFLAG_UNK7);
    MapObject_SetFlag29(ret, TRUE);
    sub_02069DC8(ret, TRUE);
    return ret;
}

struct FieldSystemUnk108 *FieldSystemUnkSub108_Alloc(HeapID heapId) {
    struct FieldSystemUnk108 *ret;

    ret = AllocFromHeap(heapId, sizeof(struct FieldSystemUnk108));
    MI_CpuClear8(ret, sizeof(struct FieldSystemUnk108));
    ret->species = 0;
    ret->personality = 0;
    ret->isRegistered = 0;
    ret->mon = 0;
    return ret;
}

void FieldSystemUnkSub108_AddMonMood(struct FieldSystemUnk108 *unk, s8 by) {
    s8 mood;

    if (unk->mon == NULL) {
        GF_ASSERT(0);
        return;
    }

    mood = GetMonData(unk->mon, MON_DATA_MOOD, NULL);
    if (mood + by > 127) {
        mood = 127;
    } else if (mood + by < -127) {
        mood = -127;
    } else {
        mood += by;
    }
    SetMonData(unk->mon, MON_DATA_MOOD, &mood);
}

void FieldSystemUnkSub108_SetMonMood(struct FieldSystemUnk108 *unk, s8 mood) {
    if (unk->mon == NULL) {
        GF_ASSERT(0);
        return;
    }

    SetMonData(unk->mon, MON_DATA_MOOD, &mood);
}

s8 FieldSystemUnkSub108_GetMonMood(struct FieldSystemUnk108 *unk) {
    if (unk->mon == NULL) {
        GF_ASSERT(0);
        return 0;
    }

    return GetMonData(unk->mon, MON_DATA_MOOD, NULL);
}

void FieldSystemUnkSub108_Set(struct FieldSystemUnk108 *a0, Pokemon *mon, u16 species, u32 personality) {
    s8 mood;
    if (species != SPECIES_NONE && (a0->isRegistered == 0 || a0->species != species || a0->personality != personality)) {
        a0->species = species;
        a0->personality = personality;
        mood = 0;
        a0->isRegistered = 1;
        a0->mon = mon;
        SetMonData(mon, MON_DATA_MOOD, &mood);
    }
}

void FieldSystemUnkSub108_MoveMoodTowardsNeutral(struct FieldSystemUnk108 *a0) {
    s8 mood;
    if (a0->mon == NULL) {
        GF_ASSERT(0);
        return;
    }
    mood = GetMonData(a0->mon, MON_DATA_MOOD, NULL);
    if (mood < 0) {
        mood++;
    } else if (mood > 0) {
        mood--;
    }
    SetMonData(a0->mon, MON_DATA_MOOD, &mood);
}

int SpeciesToOverworldModelIndexOffset(int species) {
    return sModelIndexLUT[species];
}

int OverworldModelLookupFormCount(int species) {
    if (!(species > 0 && species <= NATIONAL_DEX_COUNT)) {
        GF_ASSERT(0);
        species = 0;
    } else {
        species--;
    }
    return sFormMaxLUT[species];
}

BOOL OverworldModelLookupHasFemaleForm(int species) {
    if (!(species > 0 && species <= NATIONAL_DEX_COUNT)) {
        GF_ASSERT(0);
        species = 0;
    } else {
        species--;
    }
    return sFemaleFlagLUT[species];
}
