TOOLSDIR  := ../tools
BUILD_DIR := build
NEFNAME   := sub
MWCCVER   := 2.0/sp2p3
PROC      := arm7tdmi
PROC_S    := arm4t
PROC_LD   := v4t

include ../common.mk

.SECONDARY:
.SECONDEXPANSION:
.DELETE_ON_ERROR:
.PHONY: all tidy clean

