Static sub
{
	Address 0x02380000
	StackSize 1024 1024
}

Autoload ext
{
	Address 0x027E0000
	Object sub.ext.o
}

Autoload wram
{
	Address 0x037F8000
	Object sub.wram.o
	Object OS_interrupt.o
	Object OS_irqTable.o
	Object OS_spinLock.o
	Object OS_thread.o
	Object OS_context.o
	Object OS_message.o
	Object OS_mutex.o
	Object OS_init.o
	Object OS_arena.o
	Object sub.wram_1.o
	Object libsyscall.o
	Object sub.wram_2.o
}

Autoload ext_wram
{
	Address 0x06000000
	Object sub.ext_wram.o
}
