zukan_gra_png_clobber = files(
    'zukan_gra_00000012.png',
	'zukan_gra_00000023.png',
	'zukan_gra_00000026.png',
	'zukan_gra_00000029.png',
	'zukan_gra_00000036.png',
	'zukan_gra_00000037.png',
	'zukan_gra_00000038.png',
	'zukan_gra_00000039.png',
	'zukan_gra_00000040.png',
	'zukan_gra_00000041.png',
	'zukan_gra_00000042.png',
	'zukan_gra_00000043.png',
	'zukan_gra_00000044.png',
	'zukan_gra_00000045.png',
	'zukan_gra_00000046.png',
	'zukan_gra_00000047.png',
	'zukan_gra_00000048.png',
	'zukan_gra_00000049.png',
	'zukan_gra_00000050.png',
	'zukan_gra_00000051.png',
	'zukan_gra_00000052.png',
	'zukan_gra_00000053.png',
	'zukan_gra_00000072.png',
	'zukan_gra_00000076.png',
	'zukan_gra_00000077.png',
	'zukan_gra_00000105.png',
	'zukan_gra_00000109.png',
	'zukan_gra_00000111.png',
	'zukan_gra_00000114.png',
	'zukan_gra_00000115.png',
	'zukan_gra_00000119.png'
)

zukan_gra_ncgr_lz_clobber = ncgr_lz_gen.process(zukan_gra_png_clobber,
    extra_args : CLOBBER_SIZE_VERSION101_64K_NCGR_FLAGS
)

zukan_gra_png_sopc = files(
    'zukan_gra_00000001.png',
	'zukan_gra_00000003.png',
	'zukan_gra_00000004.png',
	'zukan_gra_00000017.png',
	'zukan_gra_00000019.png',
	'zukan_gra_00000058.png',
	'zukan_gra_00000083.png',
	'zukan_gra_00000085.png',
	'zukan_gra_00000087.png',
	'zukan_gra_00000090.png',
	'zukan_gra_00000092.png',
	'zukan_gra_00000093.png',
	'zukan_gra_00000094.png',
	'zukan_gra_00000102.png',
	'zukan_gra_00000104.png'
)

zukan_gra_ncgr_lz_sopc = ncgr_lz_gen.process(zukan_gra_png_sopc,
    extra_args : VERSION101_SOPC_NCGR_FLAGS
)

zukan_gra_nclr = copy_gen.process(files(
    'zukan_gra_00000002.NCLR',
    'zukan_gra_00000015.NCLR',
    'zukan_gra_00000018.NCLR',
    'zukan_gra_00000032.NCLR',
    'zukan_gra_00000035.NCLR',
    'zukan_gra_00000056.NCLR',
    'zukan_gra_00000075.NCLR',
    'zukan_gra_00000108.NCLR',
    'zukan_gra_00000110.NCLR',
    'zukan_gra_00000118.NCLR',
    'zukan_gra_00000122.NCLR',
))

zukan_gra_nscr_lz = lz_gen.process(files(
    'zukan_gra_00000000.NSCR',
    'zukan_gra_00000005.NSCR',
    'zukan_gra_00000006.NSCR',
    'zukan_gra_00000007.NSCR',
    'zukan_gra_00000008.NSCR',
    'zukan_gra_00000009.NSCR',
    'zukan_gra_00000010.NSCR',
    'zukan_gra_00000011.NSCR',
    'zukan_gra_00000016.NSCR',
    'zukan_gra_00000020.NSCR',
    'zukan_gra_00000021.NSCR',
    'zukan_gra_00000022.NSCR',
    'zukan_gra_00000057.NSCR',
    'zukan_gra_00000059.NSCR',
    'zukan_gra_00000060.NSCR',
    'zukan_gra_00000061.NSCR',
    'zukan_gra_00000062.NSCR',
    'zukan_gra_00000063.NSCR',
    'zukan_gra_00000064.NSCR',
    'zukan_gra_00000065.NSCR',
    'zukan_gra_00000066.NSCR',
    'zukan_gra_00000067.NSCR',
    'zukan_gra_00000068.NSCR',
    'zukan_gra_00000069.NSCR',
    'zukan_gra_00000070.NSCR',
    'zukan_gra_00000071.NSCR',
    'zukan_gra_00000080.NSCR',
    'zukan_gra_00000081.NSCR',
    'zukan_gra_00000082.NSCR',
    'zukan_gra_00000084.NSCR',
    'zukan_gra_00000086.NSCR',
    'zukan_gra_00000088.NSCR',
    'zukan_gra_00000089.NSCR',
    'zukan_gra_00000091.NSCR',
    'zukan_gra_00000095.NSCR',
    'zukan_gra_00000096.NSCR',
    'zukan_gra_00000097.NSCR',
    'zukan_gra_00000098.NSCR',
    'zukan_gra_00000099.NSCR',
    'zukan_gra_00000100.NSCR',
    'zukan_gra_00000101.NSCR',
    'zukan_gra_00000103.NSCR',
))

zukan_gra_ncer_lz = lz_gen.process(files(
    'zukan_gra_00000013.NCER',
    'zukan_gra_00000024.NCER',
    'zukan_gra_00000027.NCER',
    'zukan_gra_00000030.NCER',
    'zukan_gra_00000033.NCER',
    'zukan_gra_00000054.NCER',
    'zukan_gra_00000073.NCER',
    'zukan_gra_00000078.NCER',
    'zukan_gra_00000106.NCER',
    'zukan_gra_00000112.NCER',
    'zukan_gra_00000116.NCER',
    'zukan_gra_00000120.NCER',
))

zukan_gra_nanr_lz = lz_gen.process(files(
    'zukan_gra_00000014.NANR',
    'zukan_gra_00000025.NANR',
    'zukan_gra_00000028.NANR',
    'zukan_gra_00000031.NANR',
    'zukan_gra_00000034.NANR',
    'zukan_gra_00000055.NANR',
    'zukan_gra_00000074.NANR',
    'zukan_gra_00000079.NANR',
    'zukan_gra_00000107.NANR',
    'zukan_gra_00000113.NANR',
    'zukan_gra_00000117.NANR',
    'zukan_gra_00000121.NANR',

))