otherpoke_index_ncgr += {
    '0064' : files('normal/back.png'),
    '0065' : files('sun/back.png'),
    '0066' : files('rain/back.png'),
    '0067' : files('ice/back.png'),
    '0068' : files('normal/front.png'),
    '0069' : files('sun/front.png'),
    '0070' : files('rain/front.png'),
    '0071' : files('ice/front.png'),
}

otherpoke_index_nclr += {
    '162' : files('normal/front.png'),
    '163' : files('sun/front.png'),
    '164' : files('rain/front.png'),
    '165' : files('ice/front.png'),
    '166' : files('normal/back.png'),
    '167' : files('sun/back.png'),
    '168' : files('rain/back.png'),
    '169' : files('ice/back.png'),
}