foreach i : range(0, 493)
    dir = i.to_string(fill : 4)
    pokegra_female_back += files(dir / 'female/back.png')
    pokegra_male_back += files(dir / 'male/back.png')
    pokegra_female_front += files(dir / 'female/front.png')
    pokegra_male_front += files(dir / 'male/front.png')
    #pokegra_normal_pal += files(dir / 'male/front.png')
    #pokegra_shiny_pal += files(dir / 'male/back.png')
endforeach
