otherpoke_index_ncgr += {
    '0088' : files('west/back.png'),
    '0089' : files('east/back.png'),
    '0090' : files('west/front.png'),
    '0091' : files('east/front.png'),
}

otherpoke_index_nclr += {
    '186' : files('west/front.png'),
    '187' : files('west/back.png'),
    '188' : files('east/front.png'),
    '189' : files('east/back.png'),
}