otherpoke_index_ncgr += {
    '0138' : files('normal/back.png'),
    '0139' : files('normal/front.png'),
    '0140' : files('oven/back.png'),
    '0141' : files('oven/front.png'),
    '0142' : files('washer/back.png'),
    '0143' : files('washer/front.png'),
    '0144' : files('fridge/back.png'),
    '0145' : files('fridge/front.png'),
    '0146' : files('fan/back.png'),
    '0147' : files('fan/front.png'),
    '0148' : files('lawnmower/back.png'),
    '0149' : files('lawnmower/front.png'),
}

otherpoke_index_nclr += {
    '236' : files('normal/front.png'),
    '237' : files('normal/back.png'),
    '238' : files('oven/front.png'),
    '239' : files('oven/back.png'),
    '240' : files('washer/front.png'),
    '241' : files('washer/back.png'),
    '242' : files('fridge/front.png'),
    '243' : files('fridge/back.png'),
    '244' : files('fan/front.png'),
    '245' : files('fan/back.png'),
    '246' : files('lawnmower/front.png'),
    '247' : files('lawnmower/back.png'),
}