poke_icon_png = files(
    'poke_icon_00000007.png',
    'poke_icon_00000008.png',
    'poke_icon_00000009.png',
    'poke_icon_00000010.png',
    'poke_icon_00000011.png',
    'poke_icon_00000012.png',
    'poke_icon_00000013.png',
    'poke_icon_00000014.png',
    'poke_icon_00000015.png',
    'poke_icon_00000016.png',
    'poke_icon_00000017.png',
    'poke_icon_00000018.png',
    'poke_icon_00000019.png',
    'poke_icon_00000020.png',
    'poke_icon_00000021.png',
    'poke_icon_00000022.png',
    'poke_icon_00000023.png',
    'poke_icon_00000024.png',
    'poke_icon_00000025.png',
    'poke_icon_00000026.png',
    'poke_icon_00000027.png',
    'poke_icon_00000028.png',
    'poke_icon_00000029.png',
    'poke_icon_00000030.png',
    'poke_icon_00000031.png',
    'poke_icon_00000032.png',
    'poke_icon_00000033.png',
    'poke_icon_00000034.png',
    'poke_icon_00000035.png',
    'poke_icon_00000036.png',
    'poke_icon_00000037.png',
    'poke_icon_00000038.png',
    'poke_icon_00000039.png',
    'poke_icon_00000040.png',
    'poke_icon_00000041.png',
    'poke_icon_00000042.png',
    'poke_icon_00000043.png',
    'poke_icon_00000044.png',
    'poke_icon_00000045.png',
    'poke_icon_00000046.png',
    'poke_icon_00000047.png',
    'poke_icon_00000048.png',
    'poke_icon_00000049.png',
    'poke_icon_00000050.png',
    'poke_icon_00000051.png',
    'poke_icon_00000052.png',
    'poke_icon_00000053.png',
    'poke_icon_00000054.png',
    'poke_icon_00000055.png',
    'poke_icon_00000056.png',
    'poke_icon_00000057.png',
    'poke_icon_00000058.png',
    'poke_icon_00000059.png',
    'poke_icon_00000060.png',
    'poke_icon_00000061.png',
    'poke_icon_00000062.png',
    'poke_icon_00000063.png',
    'poke_icon_00000064.png',
    'poke_icon_00000065.png',
    'poke_icon_00000066.png',
    'poke_icon_00000067.png',
    'poke_icon_00000068.png',
    'poke_icon_00000069.png',
    'poke_icon_00000070.png',
    'poke_icon_00000071.png',
    'poke_icon_00000072.png',
    'poke_icon_00000073.png',
    'poke_icon_00000074.png',
    'poke_icon_00000075.png',
    'poke_icon_00000076.png',
    'poke_icon_00000077.png',
    'poke_icon_00000078.png',
    'poke_icon_00000079.png',
    'poke_icon_00000080.png',
    'poke_icon_00000081.png',
    'poke_icon_00000082.png',
    'poke_icon_00000083.png',
    'poke_icon_00000084.png',
    'poke_icon_00000085.png',
    'poke_icon_00000086.png',
    'poke_icon_00000087.png',
    'poke_icon_00000088.png',
    'poke_icon_00000089.png',
    'poke_icon_00000090.png',
    'poke_icon_00000091.png',
    'poke_icon_00000092.png',
    'poke_icon_00000093.png',
    'poke_icon_00000094.png',
    'poke_icon_00000095.png',
    'poke_icon_00000096.png',
    'poke_icon_00000097.png',
    'poke_icon_00000098.png',
    'poke_icon_00000099.png',
    'poke_icon_00000100.png',
    'poke_icon_00000101.png',
    'poke_icon_00000102.png',
    'poke_icon_00000103.png',
    'poke_icon_00000104.png',
    'poke_icon_00000105.png',
    'poke_icon_00000106.png',
    'poke_icon_00000107.png',
    'poke_icon_00000108.png',
    'poke_icon_00000109.png',
    'poke_icon_00000110.png',
    'poke_icon_00000111.png',
    'poke_icon_00000112.png',
    'poke_icon_00000113.png',
    'poke_icon_00000114.png',
    'poke_icon_00000115.png',
    'poke_icon_00000116.png',
    'poke_icon_00000117.png',
    'poke_icon_00000118.png',
    'poke_icon_00000119.png',
    'poke_icon_00000120.png',
    'poke_icon_00000121.png',
    'poke_icon_00000122.png',
    'poke_icon_00000123.png',
    'poke_icon_00000124.png',
    'poke_icon_00000125.png',
    'poke_icon_00000126.png',
    'poke_icon_00000127.png',
    'poke_icon_00000128.png',
    'poke_icon_00000129.png',
    'poke_icon_00000130.png',
    'poke_icon_00000131.png',
    'poke_icon_00000132.png',
    'poke_icon_00000133.png',
    'poke_icon_00000134.png',
    'poke_icon_00000135.png',
    'poke_icon_00000136.png',
    'poke_icon_00000137.png',
    'poke_icon_00000138.png',
    'poke_icon_00000139.png',
    'poke_icon_00000140.png',
    'poke_icon_00000141.png',
    'poke_icon_00000142.png',
    'poke_icon_00000143.png',
    'poke_icon_00000144.png',
    'poke_icon_00000145.png',
    'poke_icon_00000146.png',
    'poke_icon_00000147.png',
    'poke_icon_00000148.png',
    'poke_icon_00000149.png',
    'poke_icon_00000150.png',
    'poke_icon_00000151.png',
    'poke_icon_00000152.png',
    'poke_icon_00000153.png',
    'poke_icon_00000154.png',
    'poke_icon_00000155.png',
    'poke_icon_00000156.png',
    'poke_icon_00000157.png',
    'poke_icon_00000158.png',
    'poke_icon_00000159.png',
    'poke_icon_00000160.png',
    'poke_icon_00000161.png',
    'poke_icon_00000162.png',
    'poke_icon_00000163.png',
    'poke_icon_00000164.png',
    'poke_icon_00000165.png',
    'poke_icon_00000166.png',
    'poke_icon_00000167.png',
    'poke_icon_00000168.png',
    'poke_icon_00000169.png',
    'poke_icon_00000170.png',
    'poke_icon_00000171.png',
    'poke_icon_00000172.png',
    'poke_icon_00000173.png',
    'poke_icon_00000174.png',
    'poke_icon_00000175.png',
    'poke_icon_00000176.png',
    'poke_icon_00000177.png',
    'poke_icon_00000178.png',
    'poke_icon_00000179.png',
    'poke_icon_00000180.png',
    'poke_icon_00000181.png',
    'poke_icon_00000182.png',
    'poke_icon_00000183.png',
    'poke_icon_00000184.png',
    'poke_icon_00000185.png',
    'poke_icon_00000186.png',
    'poke_icon_00000187.png',
    'poke_icon_00000188.png',
    'poke_icon_00000189.png',
    'poke_icon_00000190.png',
    'poke_icon_00000191.png',
    'poke_icon_00000192.png',
    'poke_icon_00000193.png',
    'poke_icon_00000194.png',
    'poke_icon_00000195.png',
    'poke_icon_00000196.png',
    'poke_icon_00000197.png',
    'poke_icon_00000198.png',
    'poke_icon_00000199.png',
    'poke_icon_00000200.png',
    'poke_icon_00000201.png',
    'poke_icon_00000202.png',
    'poke_icon_00000203.png',
    'poke_icon_00000204.png',
    'poke_icon_00000205.png',
    'poke_icon_00000206.png',
    'poke_icon_00000207.png',
    'poke_icon_00000208.png',
    'poke_icon_00000209.png',
    'poke_icon_00000210.png',
    'poke_icon_00000211.png',
    'poke_icon_00000212.png',
    'poke_icon_00000213.png',
    'poke_icon_00000214.png',
    'poke_icon_00000215.png',
    'poke_icon_00000216.png',
    'poke_icon_00000217.png',
    'poke_icon_00000218.png',
    'poke_icon_00000219.png',
    'poke_icon_00000220.png',
    'poke_icon_00000221.png',
    'poke_icon_00000222.png',
    'poke_icon_00000223.png',
    'poke_icon_00000224.png',
    'poke_icon_00000225.png',
    'poke_icon_00000226.png',
    'poke_icon_00000227.png',
    'poke_icon_00000228.png',
    'poke_icon_00000229.png',
    'poke_icon_00000230.png',
    'poke_icon_00000231.png',
    'poke_icon_00000232.png',
    'poke_icon_00000233.png',
    'poke_icon_00000234.png',
    'poke_icon_00000235.png',
    'poke_icon_00000236.png',
    'poke_icon_00000237.png',
    'poke_icon_00000238.png',
    'poke_icon_00000239.png',
    'poke_icon_00000240.png',
    'poke_icon_00000241.png',
    'poke_icon_00000242.png',
    'poke_icon_00000243.png',
    'poke_icon_00000244.png',
    'poke_icon_00000245.png',
    'poke_icon_00000246.png',
    'poke_icon_00000247.png',
    'poke_icon_00000248.png',
    'poke_icon_00000249.png',
    'poke_icon_00000250.png',
    'poke_icon_00000251.png',
    'poke_icon_00000252.png',
    'poke_icon_00000253.png',
    'poke_icon_00000254.png',
    'poke_icon_00000255.png',
    'poke_icon_00000256.png',
    'poke_icon_00000257.png',
    'poke_icon_00000258.png',
    'poke_icon_00000259.png',
    'poke_icon_00000260.png',
    'poke_icon_00000261.png',
    'poke_icon_00000262.png',
    'poke_icon_00000263.png',
    'poke_icon_00000264.png',
    'poke_icon_00000265.png',
    'poke_icon_00000266.png',
    'poke_icon_00000267.png',
    'poke_icon_00000268.png',
    'poke_icon_00000269.png',
    'poke_icon_00000270.png',
    'poke_icon_00000271.png',
    'poke_icon_00000272.png',
    'poke_icon_00000273.png',
    'poke_icon_00000274.png',
    'poke_icon_00000275.png',
    'poke_icon_00000276.png',
    'poke_icon_00000277.png',
    'poke_icon_00000278.png',
    'poke_icon_00000279.png',
    'poke_icon_00000280.png',
    'poke_icon_00000281.png',
    'poke_icon_00000282.png',
    'poke_icon_00000283.png',
    'poke_icon_00000284.png',
    'poke_icon_00000285.png',
    'poke_icon_00000286.png',
    'poke_icon_00000287.png',
    'poke_icon_00000288.png',
    'poke_icon_00000289.png',
    'poke_icon_00000290.png',
    'poke_icon_00000291.png',
    'poke_icon_00000292.png',
    'poke_icon_00000293.png',
    'poke_icon_00000294.png',
    'poke_icon_00000295.png',
    'poke_icon_00000296.png',
    'poke_icon_00000297.png',
    'poke_icon_00000298.png',
    'poke_icon_00000299.png',
    'poke_icon_00000300.png',
    'poke_icon_00000301.png',
    'poke_icon_00000302.png',
    'poke_icon_00000303.png',
    'poke_icon_00000304.png',
    'poke_icon_00000305.png',
    'poke_icon_00000306.png',
    'poke_icon_00000307.png',
    'poke_icon_00000308.png',
    'poke_icon_00000309.png',
    'poke_icon_00000310.png',
    'poke_icon_00000311.png',
    'poke_icon_00000312.png',
    'poke_icon_00000313.png',
    'poke_icon_00000314.png',
    'poke_icon_00000315.png',
    'poke_icon_00000316.png',
    'poke_icon_00000317.png',
    'poke_icon_00000318.png',
    'poke_icon_00000319.png',
    'poke_icon_00000320.png',
    'poke_icon_00000321.png',
    'poke_icon_00000322.png',
    'poke_icon_00000323.png',
    'poke_icon_00000324.png',
    'poke_icon_00000325.png',
    'poke_icon_00000326.png',
    'poke_icon_00000327.png',
    'poke_icon_00000328.png',
    'poke_icon_00000329.png',
    'poke_icon_00000330.png',
    'poke_icon_00000331.png',
    'poke_icon_00000332.png',
    'poke_icon_00000333.png',
    'poke_icon_00000334.png',
    'poke_icon_00000335.png',
    'poke_icon_00000336.png',
    'poke_icon_00000337.png',
    'poke_icon_00000338.png',
    'poke_icon_00000339.png',
    'poke_icon_00000340.png',
    'poke_icon_00000341.png',
    'poke_icon_00000342.png',
    'poke_icon_00000343.png',
    'poke_icon_00000344.png',
    'poke_icon_00000345.png',
    'poke_icon_00000346.png',
    'poke_icon_00000347.png',
    'poke_icon_00000348.png',
    'poke_icon_00000349.png',
    'poke_icon_00000350.png',
    'poke_icon_00000351.png',
    'poke_icon_00000352.png',
    'poke_icon_00000353.png',
    'poke_icon_00000354.png',
    'poke_icon_00000355.png',
    'poke_icon_00000356.png',
    'poke_icon_00000357.png',
    'poke_icon_00000358.png',
    'poke_icon_00000359.png',
    'poke_icon_00000360.png',
    'poke_icon_00000361.png',
    'poke_icon_00000362.png',
    'poke_icon_00000363.png',
    'poke_icon_00000364.png',
    'poke_icon_00000365.png',
    'poke_icon_00000366.png',
    'poke_icon_00000367.png',
    'poke_icon_00000368.png',
    'poke_icon_00000369.png',
    'poke_icon_00000370.png',
    'poke_icon_00000371.png',
    'poke_icon_00000372.png',
    'poke_icon_00000373.png',
    'poke_icon_00000374.png',
    'poke_icon_00000375.png',
    'poke_icon_00000376.png',
    'poke_icon_00000377.png',
    'poke_icon_00000378.png',
    'poke_icon_00000379.png',
    'poke_icon_00000380.png',
    'poke_icon_00000381.png',
    'poke_icon_00000382.png',
    'poke_icon_00000383.png',
    'poke_icon_00000384.png',
    'poke_icon_00000385.png',
    'poke_icon_00000386.png',
    'poke_icon_00000387.png',
    'poke_icon_00000388.png',
    'poke_icon_00000389.png',
    'poke_icon_00000390.png',
    'poke_icon_00000391.png',
    'poke_icon_00000392.png',
    'poke_icon_00000393.png',
    'poke_icon_00000394.png',
    'poke_icon_00000395.png',
    'poke_icon_00000396.png',
    'poke_icon_00000397.png',
    'poke_icon_00000398.png',
    'poke_icon_00000399.png',
    'poke_icon_00000400.png',
    'poke_icon_00000401.png',
    'poke_icon_00000402.png',
    'poke_icon_00000403.png',
    'poke_icon_00000404.png',
    'poke_icon_00000405.png',
    'poke_icon_00000406.png',
    'poke_icon_00000407.png',
    'poke_icon_00000408.png',
    'poke_icon_00000409.png',
    'poke_icon_00000410.png',
    'poke_icon_00000411.png',
    'poke_icon_00000412.png',
    'poke_icon_00000413.png',
    'poke_icon_00000414.png',
    'poke_icon_00000415.png',
    'poke_icon_00000416.png',
    'poke_icon_00000417.png',
    'poke_icon_00000418.png',
    'poke_icon_00000419.png',
    'poke_icon_00000420.png',
    'poke_icon_00000421.png',
    'poke_icon_00000422.png',
    'poke_icon_00000423.png',
    'poke_icon_00000424.png',
    'poke_icon_00000425.png',
    'poke_icon_00000426.png',
    'poke_icon_00000427.png',
    'poke_icon_00000428.png',
    'poke_icon_00000429.png',
    'poke_icon_00000430.png',
    'poke_icon_00000431.png',
    'poke_icon_00000432.png',
    'poke_icon_00000433.png',
    'poke_icon_00000434.png',
    'poke_icon_00000435.png',
    'poke_icon_00000436.png',
    'poke_icon_00000437.png',
    'poke_icon_00000438.png',
    'poke_icon_00000439.png',
    'poke_icon_00000440.png',
    'poke_icon_00000441.png',
    'poke_icon_00000442.png',
    'poke_icon_00000443.png',
    'poke_icon_00000444.png',
    'poke_icon_00000445.png',
    'poke_icon_00000446.png',
    'poke_icon_00000447.png',
    'poke_icon_00000448.png',
    'poke_icon_00000449.png',
    'poke_icon_00000450.png',
    'poke_icon_00000451.png',
    'poke_icon_00000452.png',
    'poke_icon_00000453.png',
    'poke_icon_00000454.png',
    'poke_icon_00000455.png',
    'poke_icon_00000456.png',
    'poke_icon_00000457.png',
    'poke_icon_00000458.png',
    'poke_icon_00000459.png',
    'poke_icon_00000460.png',
    'poke_icon_00000461.png',
    'poke_icon_00000462.png',
    'poke_icon_00000463.png',
    'poke_icon_00000464.png',
    'poke_icon_00000465.png',
    'poke_icon_00000466.png',
    'poke_icon_00000467.png',
    'poke_icon_00000468.png',
    'poke_icon_00000469.png',
    'poke_icon_00000470.png',
    'poke_icon_00000471.png',
    'poke_icon_00000472.png',
    'poke_icon_00000473.png',
    'poke_icon_00000474.png',
    'poke_icon_00000475.png',
    'poke_icon_00000476.png',
    'poke_icon_00000477.png',
    'poke_icon_00000478.png',
    'poke_icon_00000479.png',
    'poke_icon_00000480.png',
    'poke_icon_00000481.png',
    'poke_icon_00000482.png',
    'poke_icon_00000483.png',
    'poke_icon_00000484.png',
    'poke_icon_00000485.png',
    'poke_icon_00000486.png',
    'poke_icon_00000487.png',
    'poke_icon_00000488.png',
    'poke_icon_00000489.png',
    'poke_icon_00000490.png',
    'poke_icon_00000491.png',
    'poke_icon_00000492.png',
    'poke_icon_00000493.png',
    'poke_icon_00000494.png',
    'poke_icon_00000495.png',
    'poke_icon_00000496.png',
    'poke_icon_00000497.png',
    'poke_icon_00000498.png',
    'poke_icon_00000499.png',
    'poke_icon_00000500.png',
    'poke_icon_00000501.png',
    'poke_icon_00000502.png',
    'poke_icon_00000503.png',
    'poke_icon_00000504.png',
    'poke_icon_00000505.png',
    'poke_icon_00000506.png',
    'poke_icon_00000507.png',
    'poke_icon_00000508.png',
    'poke_icon_00000509.png',
    'poke_icon_00000510.png',
    'poke_icon_00000511.png',
    'poke_icon_00000512.png',
    'poke_icon_00000513.png',
    'poke_icon_00000514.png',
    'poke_icon_00000515.png',
    'poke_icon_00000516.png',
    'poke_icon_00000517.png',
    'poke_icon_00000518.png',
    'poke_icon_00000519.png',
    'poke_icon_00000520.png',
    'poke_icon_00000521.png',
    'poke_icon_00000522.png',
    'poke_icon_00000523.png',
    'poke_icon_00000524.png',
    'poke_icon_00000525.png',
    'poke_icon_00000526.png',
    'poke_icon_00000527.png',
    'poke_icon_00000528.png',
    'poke_icon_00000529.png',
    'poke_icon_00000530.png',
    'poke_icon_00000531.png',
    'poke_icon_00000532.png',
    'poke_icon_00000533.png',
    'poke_icon_00000534.png',
    'poke_icon_00000535.png',
    'poke_icon_00000536.png',
    'poke_icon_00000537.png',
    'poke_icon_00000538.png',
    'poke_icon_00000539.png',
    'poke_icon_00000540.png',
    'poke_icon_00000541.png',
    'poke_icon_00000542.png',
    'poke_icon_00000543.png',
    'poke_icon_00000544.png',
    'poke_icon_00000545.png',
    'poke_icon_00000546.png',
    'poke_icon_00000547.png',
    'poke_icon_00000548.png',
    'poke_icon_00000549.png',
    'poke_icon_00000550.png',
)

poke_icon_pal = files('poke_icon_00000000.pal')

poke_icon_json_ncer = files(
    'poke_icon_00000002.json',
    'poke_icon_00000004.json',
    'poke_icon_00000006.json',
)

poke_icon_json_nanr = files(
    'poke_icon_00000001.json',
    'poke_icon_00000003.json',
    'poke_icon_00000005.json',
)

poke_icon_nclr = nclr_gen.process(poke_icon_pal, extra_args : ['-bitdepth', '4'])
poke_icon_ncer = ncer_gen.process(poke_icon_json_ncer)
poke_icon_nanr = nanr_gen.process(poke_icon_json_nanr)
poke_icon_ncgr = ncgr_gen.process(poke_icon_png, extra_args : CLOBBER_SIZE_VERSION101_NCGR_FLAGS )

poke_icon_narc = custom_target('poke_icon.narc',
    output : [
        'poke_icon.narc',
        'poke_icon.naix',
    ],
    input : [
        poke_icon_nclr,
        poke_icon_ncer,
        poke_icon_nanr,
        poke_icon_ncgr
    ],
    command : [
        nitroarc_exe,
        '--create',
        '--index',
        '--file', '@OUTPUT0@',
        '@PRIVATE_DIR@'
    ],
    build_by_default : true
)

nitrofs_files += poke_icon_narc
naix_headers += poke_icon_narc[1]
