POKE_ICON_DIR := files/poketool/icongra/poke_icon
POKE_ICON_NARC := $(POKE_ICON_DIR)/poke_icon.narc
POKE_ICON_BUILD_DIR := $(POKE_ICON_DIR)/build-poke_icon

POKE_ICON_GFX_FLAGS_ICON := -clobbersize -version101
POKE_ICON_GFX_FLAGS_PAL := -bitdepth 4

POKE_ICON_PAL_FILES := $(wildcard $(POKE_ICON_DIR)/*.pal)
POKE_ICON_PAL_OBJS := $(patsubst $(POKE_ICON_DIR)/%.pal,$(POKE_ICON_BUILD_DIR)/%.NCLR,$(POKE_ICON_PAL_FILES))
POKE_ICON_ANIM_FILES := $(POKE_ICON_DIR)/0_00000001.json $(POKE_ICON_DIR)/0_00000003.json $(POKE_ICON_DIR)/0_00000005.json
POKE_ICON_ANIM_OBJS := $(patsubst $(POKE_ICON_DIR)/%.json,$(POKE_ICON_BUILD_DIR)/%.NANR,$(POKE_ICON_ANIM_FILES))
POKE_ICON_CELL_FILES := $(POKE_ICON_DIR)/0_00000002.json $(POKE_ICON_DIR)/0_00000004.json $(POKE_ICON_DIR)/0_00000006.json
POKE_ICON_CELL_OBJS := $(patsubst $(POKE_ICON_DIR)/%.json,$(POKE_ICON_BUILD_DIR)/%.NCER,$(POKE_ICON_CELL_FILES))
POKE_ICON_ICON_FILES := $(wildcard $(POKE_ICON_DIR)/*.png)
POKE_ICON_ICON_OBJS := $(patsubst $(POKE_ICON_DIR)/%.png,$(POKE_ICON_BUILD_DIR)/%.NCGR,$(POKE_ICON_ICON_FILES))

$(POKE_ICON_BUILD_DIR)/%.NCLR: $(POKE_ICON_DIR)/%.pal
	@mkdir -p $(POKE_ICON_BUILD_DIR)
	$(GFX) $< $@ $(POKE_ICON_GFX_FLAGS_PAL)

$(POKE_ICON_BUILD_DIR)/%.NCER: $(POKE_ICON_DIR)/%.json
	@mkdir -p $(POKE_ICON_BUILD_DIR)
	$(GFX) $< $@

$(POKE_ICON_BUILD_DIR)/%.NANR: $(POKE_ICON_DIR)/%.json
	@mkdir -p $(POKE_ICON_BUILD_DIR)
	$(GFX) $< $@

$(POKE_ICON_BUILD_DIR)/%.NCGR: $(POKE_ICON_DIR)/%.png
	@mkdir -p $(POKE_ICON_BUILD_DIR)
	$(GFX) $< $@ $(POKE_ICON_GFX_FLAGS_ICON)

$(POKE_ICON_NARC): %.narc: $(POKE_ICON_PAL_OBJS) $(POKE_ICON_ANIM_OBJS) $(POKE_ICON_CELL_OBJS) $(POKE_ICON_ICON_OBJS)
	$(KNARC) -d $(POKE_ICON_BUILD_DIR) -p $@ -i

FS_CLEAN_TARGETS += $(POKE_ICON_NARC) $(POKE_ICON_BUILD_DIR)
